-- Procurement is opt-in. Supplier terms and payable posting start disabled.
CREATE TABLE cohamy_crm.supplier_profiles (
 organization_id uuid PRIMARY KEY REFERENCES cohamy_crm.organizations(id),contact_name text NOT NULL DEFAULT '',contact_email text NOT NULL DEFAULT '',contact_phone text NOT NULL DEFAULT '',
 terms_days integer NOT NULL DEFAULT 0 CHECK(terms_days>=0),payable_enabled boolean NOT NULL DEFAULT false,active boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE cohamy_crm.supplier_products (
 organization_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),product_id uuid NOT NULL REFERENCES cohamy_crm.products(id),supplier_sku text NOT NULL,
 lead_days integer NOT NULL DEFAULT 0 CHECK(lead_days>=0),active boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,PRIMARY KEY(organization_id,product_id)
);
CREATE TABLE cohamy_crm.purchase_requests (
 id uuid PRIMARY KEY,code text NOT NULL UNIQUE,status text NOT NULL DEFAULT 'REQUESTED' CHECK(status IN('REQUESTED','APPROVED','REJECTED','CONVERTED')),
 needed_on date NOT NULL,requester_id uuid NOT NULL REFERENCES cohamy_crm.users(id),approver_id uuid REFERENCES cohamy_crm.users(id),reason text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE cohamy_crm.purchase_request_lines (id uuid PRIMARY KEY,request_id uuid NOT NULL REFERENCES cohamy_crm.purchase_requests(id),product_id uuid NOT NULL REFERENCES cohamy_crm.products(id),quantity numeric(30,6) NOT NULL CHECK(quantity>0),note text NOT NULL);
CREATE TABLE cohamy_crm.purchase_request_events (id uuid PRIMARY KEY,request_id uuid NOT NULL REFERENCES cohamy_crm.purchase_requests(id),action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER purchase_request_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.purchase_request_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.supplier_rfqs (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,request_id uuid NOT NULL REFERENCES cohamy_crm.purchase_requests(id),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','OPEN','SELECTED','CANCELLED')),deadline timestamptz NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.supplier_rfq_versions (id uuid PRIMARY KEY,rfq_id uuid NOT NULL REFERENCES cohamy_crm.supplier_rfqs(id),number integer NOT NULL,snapshot jsonb NOT NULL,checksum text NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(rfq_id,number));
CREATE TRIGGER supplier_rfq_versions_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.supplier_rfq_versions FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE TABLE cohamy_crm.supplier_quotes (id uuid PRIMARY KEY,rfq_id uuid NOT NULL REFERENCES cohamy_crm.supplier_rfqs(id),supplier_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),number integer NOT NULL,snapshot jsonb NOT NULL,checksum text NOT NULL,status text NOT NULL DEFAULT 'RECEIVED' CHECK(status IN('RECEIVED','SELECTED','REJECTED')),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(rfq_id,supplier_id,number));

CREATE TABLE cohamy_crm.purchase_orders (
 id uuid PRIMARY KEY,code text NOT NULL UNIQUE,request_id uuid NOT NULL REFERENCES cohamy_crm.purchase_requests(id),rfq_id uuid REFERENCES cohamy_crm.supplier_rfqs(id),supplier_quote_id uuid REFERENCES cohamy_crm.supplier_quotes(id),supplier_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),
 status text NOT NULL DEFAULT 'PENDING_APPROVAL' CHECK(status IN('PENDING_APPROVAL','APPROVED','PARTIAL','RECEIVED','CANCELLED')),expected_on date NOT NULL,late_reason text NOT NULL DEFAULT '',total_amount numeric(30,0) NOT NULL CHECK(total_amount>=0),terms_snapshot jsonb NOT NULL,
 requester_id uuid NOT NULL REFERENCES cohamy_crm.users(id),approver_id uuid REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE cohamy_crm.purchase_order_lines (id uuid PRIMARY KEY,order_id uuid NOT NULL REFERENCES cohamy_crm.purchase_orders(id),product_id uuid NOT NULL REFERENCES cohamy_crm.products(id),quantity numeric(30,6) NOT NULL CHECK(quantity>0),unit_price numeric(30,0) NOT NULL CHECK(unit_price>=0),received numeric(30,6) NOT NULL DEFAULT 0 CHECK(received>=0),rejected numeric(30,6) NOT NULL DEFAULT 0 CHECK(rejected>=0),CHECK(received+rejected<=quantity));
CREATE TABLE cohamy_crm.purchase_order_events (id uuid PRIMARY KEY,order_id uuid NOT NULL REFERENCES cohamy_crm.purchase_orders(id),action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER purchase_order_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.purchase_order_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.goods_receipts (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,order_id uuid NOT NULL REFERENCES cohamy_crm.purchase_orders(id),inventory_document_id uuid NOT NULL REFERENCES cohamy_crm.inventory_documents(id),received_at timestamptz NOT NULL,status text NOT NULL CHECK(status IN('ACCEPTED','PARTIAL','REJECTED')),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.goods_receipt_lines (id uuid PRIMARY KEY,receipt_id uuid NOT NULL REFERENCES cohamy_crm.goods_receipts(id),order_line_id uuid NOT NULL REFERENCES cohamy_crm.purchase_order_lines(id),lot_id uuid REFERENCES cohamy_crm.inventory_lots(id),accepted numeric(30,6) NOT NULL CHECK(accepted>=0),rejected numeric(30,6) NOT NULL CHECK(rejected>=0),rejection_reason text NOT NULL,CHECK(accepted+rejected>0));
CREATE TABLE cohamy_crm.supplier_claims (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,receipt_line_id uuid NOT NULL REFERENCES cohamy_crm.goods_receipt_lines(id),quantity numeric(30,6) NOT NULL CHECK(quantity>0),reason text NOT NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','ACKNOWLEDGED','RESOLVED','REJECTED')),document_version_id uuid REFERENCES cohamy_crm.document_versions(id),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.supplier_claim_events (id uuid PRIMARY KEY,claim_id uuid NOT NULL REFERENCES cohamy_crm.supplier_claims(id),action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER supplier_claim_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.supplier_claim_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.payables (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,supplier_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),receipt_id uuid NOT NULL UNIQUE REFERENCES cohamy_crm.goods_receipts(id),original_amount numeric(30,0) NOT NULL CHECK(original_amount>0),remaining_amount numeric(30,0) NOT NULL CHECK(remaining_amount>=0),due_on date NOT NULL,terms_snapshot jsonb NOT NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','PARTIAL','PAID','DISPUTED','VOID')),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.payable_events (id uuid PRIMARY KEY,payable_id uuid NOT NULL REFERENCES cohamy_crm.payables(id),action text NOT NULL,amount numeric(30,0) NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER payable_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.payable_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE TABLE cohamy_crm.supplier_payments (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,supplier_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),amount numeric(30,0) NOT NULL CHECK(amount>0),allocated_amount numeric(30,0) NOT NULL DEFAULT 0 CHECK(allocated_amount>=0),status text NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','EXECUTED','REVERSED')),requester_id uuid NOT NULL REFERENCES cohamy_crm.users(id),approver_id uuid REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(allocated_amount<=amount));
CREATE TABLE cohamy_crm.supplier_payment_allocations (id uuid PRIMARY KEY,payment_id uuid NOT NULL REFERENCES cohamy_crm.supplier_payments(id),payable_id uuid NOT NULL REFERENCES cohamy_crm.payables(id),amount numeric(30,0) NOT NULL CHECK(amount>0),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TRIGGER supplier_payment_allocations_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.supplier_payment_allocations FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE TABLE cohamy_crm.procurement_actions (id uuid PRIMARY KEY,action text NOT NULL,resource_id text NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER procurement_actions_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.procurement_actions FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE INDEX purchase_orders_supplier ON cohamy_crm.purchase_orders(supplier_id,status,expected_on);
CREATE INDEX payables_supplier_due ON cohamy_crm.payables(supplier_id,status,due_on);
