-- Consignment starts empty and inactive. It never reclassifies sold inventory automatically.
CREATE TABLE cohamy_crm.consignment_agreements (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,organization_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_ACCEPTANCE','ACTIVE','ENDED')),current_version_id uuid,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.consignment_agreement_versions (id uuid PRIMARY KEY,agreement_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreements(id),number integer NOT NULL,snapshot jsonb NOT NULL,checksum text NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(agreement_id,number));
ALTER TABLE cohamy_crm.consignment_agreements ADD CONSTRAINT consignment_current_version_fk FOREIGN KEY(current_version_id) REFERENCES cohamy_crm.consignment_agreement_versions(id);
CREATE TRIGGER consignment_agreement_versions_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_agreement_versions FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE TABLE cohamy_crm.consignment_acceptances (id uuid PRIMARY KEY,version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),party text NOT NULL CHECK(party IN('COHAMY','PARTNER')),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),idempotency_key uuid NOT NULL,request_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(version_id,party),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_acceptances_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_acceptances FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.consignment_shipments (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,agreement_version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),status text NOT NULL DEFAULT 'IN_TRANSIT' CHECK(status IN('IN_TRANSIT','PARTIAL','RECEIVED','SHORT','RETURNED')),source_document_id uuid NOT NULL REFERENCES cohamy_crm.inventory_documents(id),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.consignment_batches (id uuid PRIMARY KEY,shipment_id uuid NOT NULL REFERENCES cohamy_crm.consignment_shipments(id),organization_id uuid NOT NULL REFERENCES cohamy_crm.organizations(id),product_id uuid NOT NULL REFERENCES cohamy_crm.products(id),lot_id uuid NOT NULL REFERENCES cohamy_crm.inventory_lots(id),source_location_id uuid NOT NULL REFERENCES cohamy_crm.warehouse_locations(id),custodian_warehouse_id uuid NOT NULL REFERENCES cohamy_crm.warehouses(id),sent numeric(30,6) NOT NULL CHECK(sent>0),received numeric(30,6) NOT NULL DEFAULT 0 CHECK(received>=0),damaged numeric(30,6) NOT NULL DEFAULT 0 CHECK(damaged>=0),short numeric(30,6) NOT NULL DEFAULT 0 CHECK(short>=0),sold numeric(30,6) NOT NULL DEFAULT 0 CHECK(sold>=0),returned numeric(30,6) NOT NULL DEFAULT 0 CHECK(returned>=0),adjusted numeric(30,6) NOT NULL DEFAULT 0,version integer NOT NULL DEFAULT 1,CHECK(received+damaged+short<=sent),CHECK(sold+returned<=received+adjusted));
CREATE TABLE cohamy_crm.consignment_receipts (id uuid PRIMARY KEY,shipment_id uuid NOT NULL REFERENCES cohamy_crm.consignment_shipments(id),number integer NOT NULL,lines jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(shipment_id,number),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_receipts_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_receipts FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.consignment_sale_reports (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,agreement_version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),period_start date NOT NULL,period_end date NOT NULL,status text NOT NULL DEFAULT 'SUBMITTED' CHECK(status IN('PREVIEW','SUBMITTED','ACCEPTED','REJECTED')),source text NOT NULL CHECK(source IN('MANUAL','FILE')),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(agreement_version_id,period_start,period_end));
CREATE TABLE cohamy_crm.consignment_sale_lines (id uuid PRIMARY KEY,report_id uuid NOT NULL REFERENCES cohamy_crm.consignment_sale_reports(id),batch_id uuid NOT NULL REFERENCES cohamy_crm.consignment_batches(id),quantity numeric(30,6) NOT NULL CHECK(quantity>0),gross_amount numeric(30,0) NOT NULL CHECK(gross_amount>=0));
CREATE TABLE cohamy_crm.consignment_sale_events (id uuid PRIMARY KEY,report_id uuid NOT NULL REFERENCES cohamy_crm.consignment_sale_reports(id),action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_sale_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_sale_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.consignment_settlements (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,agreement_version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),period_start date NOT NULL,period_end date NOT NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','PARTNER_ACCEPTED','COHAMY_ACCEPTED','DISPUTED','LOCKED','ADJUSTMENT')),gross_amount numeric(30,0) NOT NULL,partner_amount numeric(30,0) NOT NULL,cohamy_amount numeric(30,0) NOT NULL,calculation jsonb NOT NULL,original_settlement_id uuid REFERENCES cohamy_crm.consignment_settlements(id),actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX consignment_settlement_period_once ON cohamy_crm.consignment_settlements(agreement_version_id,period_start,period_end) WHERE original_settlement_id IS NULL;
CREATE TABLE cohamy_crm.consignment_settlement_reports (settlement_id uuid NOT NULL REFERENCES cohamy_crm.consignment_settlements(id),report_id uuid NOT NULL UNIQUE REFERENCES cohamy_crm.consignment_sale_reports(id),PRIMARY KEY(settlement_id,report_id));
CREATE TABLE cohamy_crm.consignment_settlement_events (id uuid PRIMARY KEY,settlement_id uuid NOT NULL REFERENCES cohamy_crm.consignment_settlements(id),action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_settlement_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_settlement_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();

CREATE TABLE cohamy_crm.consignment_replenishments (id uuid PRIMARY KEY,agreement_version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),product_id uuid NOT NULL REFERENCES cohamy_crm.products(id),suggested numeric(30,6) NOT NULL CHECK(suggested>0),explanation jsonb NOT NULL,status text NOT NULL DEFAULT 'REQUESTED' CHECK(status IN('REQUESTED','APPROVED','REJECTED','FULFILLED')),requester_id uuid NOT NULL REFERENCES cohamy_crm.users(id),approver_id uuid REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.consignment_returns (id uuid PRIMARY KEY,code text NOT NULL UNIQUE,agreement_version_id uuid NOT NULL REFERENCES cohamy_crm.consignment_agreement_versions(id),status text NOT NULL DEFAULT 'REQUESTED' CHECK(status IN('REQUESTED','APPROVED','IN_TRANSIT','RECEIVED','SHORT','REJECTED')),reason text NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cohamy_crm.consignment_return_lines (id uuid PRIMARY KEY,return_id uuid NOT NULL REFERENCES cohamy_crm.consignment_returns(id),batch_id uuid NOT NULL REFERENCES cohamy_crm.consignment_batches(id),requested numeric(30,6) NOT NULL CHECK(requested>0),shipped numeric(30,6) NOT NULL DEFAULT 0 CHECK(shipped>=0),received numeric(30,6) NOT NULL DEFAULT 0 CHECK(received>=0),CHECK(shipped<=requested),CHECK(received<=shipped));
CREATE TABLE cohamy_crm.consignment_events (id uuid PRIMARY KEY,entity_type text NOT NULL,entity_id uuid NOT NULL,action text NOT NULL,payload jsonb NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),reason text NOT NULL,idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_events_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_events FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE TABLE cohamy_crm.consignment_actions (id uuid PRIMARY KEY,action text NOT NULL,resource_id text NOT NULL,actor_id uuid NOT NULL REFERENCES cohamy_crm.users(id),idempotency_key uuid NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,idempotency_key));
CREATE TRIGGER consignment_actions_immutable BEFORE UPDATE OR DELETE ON cohamy_crm.consignment_actions FOR EACH ROW EXECUTE FUNCTION cohamy_crm.deny_audit_mutation();
CREATE INDEX consignment_batches_partner_product ON cohamy_crm.consignment_batches(organization_id,product_id);
