import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const postgres=process.env.CRM_DATABASE_MODE==='postgres';if(!postgres){process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-pricing-'+randomUUID();}
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),auth=await import('../../lib/crm/auth'),p=await import('../../lib/crm/pricing'),repo=await import('../../lib/crm/repository'),{installQaRuntime}=await import('./qa-runtime'),fixture=await import('./pricing-fixture');
 const ids=await createQaFixture(),owner=await database(),admin=(await auth.login('admin@crm-qa.invalid',qaPassword)).user,sales=(await auth.login('sales@crm-qa.invalid',qaPassword)).user,a=(await auth.login('a@crm-qa.invalid',qaPassword)).user,b=(await auth.login('b@crm-qa.invalid',qaPassword)).user,close=await installQaRuntime(owner),db=await database(),cases:{name:string;status:string}[]=[];
 const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 const draft=(definition=fixture.qaPriceDefinition,name='QA fictitious price')=>p.savePriceBook(admin,{version:0,name,definition,idempotencyKey:randomUUID()});
 const publish=(head:{id:string;version:number;versionId:string})=>p.publishPriceBook(admin,{id:head.id,version:head.version,versionId:head.versionId,action:'PUBLISH',reason:'QA fictitious published policy',idempotencyKey:randomUUID()});
 let productIds:string[]=[],all:{id:string;version:number;versionId:string;number:number},tierId='',tierBook:{id:string;version:number;versionId:string;number:number},ownBook:{id:string;version:number;versionId:string;number:number};
 try{
 await test('F031 no published eligible policy reports unavailable; public retail price never substitutes',async()=>{await assert.rejects(p.previewPrice(a,{organizationId:ids.dealerA,basket:fixture.qaBasket}),/PRICE_UNAVAILABLE/);await assert.rejects(draft(),/SKU_UNCONFIGURED/);productIds=await fixture.createPriceProducts(admin);await assert.rejects(p.savePriceUnit(admin,{productId:productIds[0],productVersion:1,code:'BAD',label:'QA',numerator:'1',denominator:'1',isCase:false,allowFractional:false,active:true,version:0,reason:'QA stale'}),/VERSION_CONFLICT/);});
 await test('F031 tier assignment uses active partners/current versions; Sales/dealers cannot publish or change tiers',async()=>{tierId=(await p.savePriceTier(admin,{version:0,code:'QA_GOLD',name:'QA fictitious gold',active:true})).id;await p.assignPriceTier(admin,{organizationId:ids.dealerA,tierId,version:0,reason:'QA assigned tier'});await assert.rejects(p.assignPriceTier(admin,{organizationId:ids.dealerA,tierId,version:0,reason:'QA stale'}),/VERSION_CONFLICT/);await assert.rejects(p.savePriceTier(sales,{version:0}),/FORBIDDEN/);await assert.rejects(p.savePriceBook(a,{}),/FORBIDDEN/);});
 await test('F031 priority then organization/tier/all specificity applies; scoped preview hides full internal policy',async()=>{all=await draft();await publish(all);tierBook=await draft({...fixture.qaPriceDefinition,audience:'TIER',tierId,lines:[{sku:'QA_PRICE_A',unitPrice:'700',thresholds:[]}]});await publish(tierBook);ownBook=await draft({...fixture.qaPriceDefinition,audience:'ORGANIZATION',organizationId:ids.dealerA,lines:[{sku:'QA_PRICE_A',unitPrice:'600',thresholds:[]}]});await publish(ownBook);const r=await p.previewPrice(a,{organizationId:ids.dealerA,basket:fixture.qaBasket});assert.equal(r.priceVersionId,ownBook.versionId);assert.equal(r.calculation.subtotal,'14400');assert.equal('priceVersion' in r,false);assert.equal('definition' in r,false);assert.equal((await p.previewPrice(b,{organizationId:ids.dealerB,basket:fixture.qaBasket})).priceVersionId,all.versionId);await assert.rejects(p.previewPrice(a,{organizationId:ids.dealerB,basket:fixture.qaBasket}),/NOT_FOUND/);await assert.rejects(p.previewPrice(sales,{organizationId:ids.dealerB,basket:fixture.qaBasket}),/NOT_FOUND/);});
 await test('F032 half-open Vietnam boundaries preserve adjacent windows and reject equal-precedence overlap',async()=>{const first=await draft({...fixture.qaPriceDefinition,priority:50,startsAt:'2030-01-01T00:00:00+07:00',endsAt:'2030-02-01T00:00:00+07:00'});await publish(first);const overlap=await draft({...fixture.qaPriceDefinition,priority:50,startsAt:'2030-01-15T00:00:00+07:00',endsAt:null});await assert.rejects(publish(overlap),/PRICE_WINDOW_CONFLICT/);const adjacent=await draft({...fixture.qaPriceDefinition,priority:50,startsAt:'2030-02-01T00:00:00+07:00',endsAt:'2030-03-01T00:00:00+07:00'});await publish(adjacent);for(const [at,expected]of [['2030-01-31T23:59:59+07:00',first.versionId],['2030-02-01T00:00:00+07:00',adjacent.versionId],['2030-03-01T00:00:00+07:00',ownBook!.versionId]])assert.equal((await db.transaction(tx=>p.eligiblePriceBook(tx,a,ids.dealerA,new Date(at)))).priceVersion.id,expected);});
 await test('F032 saved drafts and exact retry cannot alter a published immutable version; reused keys reject other content',async()=>{const current=(await p.listPriceBooks(admin)).find(x=>x.id===ownBook!.id)!,key=randomUUID(),request={id:current.id,version:current.version,name:'QA revised draft',definition:{...fixture.qaPriceDefinition,audience:'ORGANIZATION' as const,organizationId:ids.dealerA,lines:[{sku:'QA_PRICE_A',unitPrice:'500',thresholds:[]}]},idempotencyKey:key};const saved=await p.savePriceBook(admin,request);assert.deepEqual(await p.savePriceBook(admin,request),saved);await assert.rejects(p.savePriceBook(admin,{...request,name:'QA altered retry'}),/IDEMPOTENCY_CONFLICT/);assert.equal((await p.previewPrice(a,{organizationId:ids.dealerA,basket:fixture.qaBasket})).priceVersionId,ownBook!.versionId);assert.equal((await p.priceBookVersions(admin,current.id)).length,2);await assert.rejects(db.query('UPDATE cohamy_crm.price_book_versions SET checksum=$1 WHERE id=$2',['qa',saved.versionId]),postgres?/permission denied/:/AUDIT_APPEND_ONLY/);});
 await test('F032 publish/withdraw retries return original result; withdrawn scope falls back only to another eligible policy',async()=>{const head=(await p.listPriceBooks(admin)).find(x=>x.id===ownBook!.id)!,request={id:head.id,version:head.version,versionId:head.latest_version_id!,action:'PUBLISH',reason:'QA publish revised draft',idempotencyKey:randomUUID()} as const,result=await p.publishPriceBook(admin,request);assert.deepEqual(await p.publishPriceBook(admin,request),result);assert.equal((await p.previewPrice(a,{organizationId:ids.dealerA,basket:fixture.qaBasket})).calculation.subtotal,'12000');await p.publishPriceBook(admin,{...request,version:result.version,action:'WITHDRAW',idempotencyKey:randomUUID()});assert.equal((await p.previewPrice(a,{organizationId:ids.dealerA,basket:fixture.qaBasket})).priceVersionId,tierBook!.versionId);await assert.rejects(db.query('DELETE FROM cohamy_crm.price_events'),postgres?/permission denied/:/AUDIT_APPEND_ONLY/);});
 await test('F033 exact unit configuration versions are audited; base ratio and fractional gifts cannot bypass validation',async()=>{await assert.rejects(p.savePriceUnit(admin,{productId:productIds[0],productVersion:3,code:'BASE',label:'QA',numerator:'12',denominator:'1',isCase:false,allowFractional:true,active:true,version:1,reason:'QA invalid base'}),/INVALID_UNIT_RATIO/);assert.equal((await p.productPriceUnits(a,productIds[0])).length,2);const work=await import('../../lib/crm/work'),product=await work.getCatalogItem(admin,productIds[0]);await assert.rejects(work.updateCatalogItem(admin,product.id,{version:product.version,sku:product.sku,name:product.name,stockUnit:'Kg',unitsPerCase:product.units_per_case,active:true}),/UNIT_IN_USE/);assert.equal((await work.getCatalogItem(admin,product.id)).stock_unit,'Gói');await assert.rejects(db.query('DELETE FROM cohamy_crm.commercial_unit_versions'),postgres?/permission denied/:/AUDIT_APPEND_ONLY/);});
 await test('F136 stale identity after lock/unlock remains blocked while fresh authentication works',async()=>{await repo.setAccountActive(admin,ids.membershipB,{active:false});await repo.setAccountActive(admin,ids.membershipB,{active:true});await assert.rejects(p.previewPrice(b,{organizationId:ids.dealerB,basket:fixture.qaBasket}),/FORBIDDEN/);const fresh=(await auth.login('b@crm-qa.invalid',qaPassword)).user;assert.ok(fresh.membershipVersion>b.membershipVersion);assert.equal((await p.previewPrice(fresh,{organizationId:ids.dealerB,basket:fixture.qaBasket})).priceVersionId,all!.versionId);});
 if(postgres)await test('F032 concurrent equal-precedence publication allows exactly one complete policy/event',async()=>{const definition={...fixture.qaPriceDefinition,priority:500,startsAt:'2035-01-01T00:00:00+07:00',endsAt:null},one=await draft(definition),two=await draft(definition),results=await Promise.allSettled([publish(one),publish(two)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);for(const r of results)if(r.status==='rejected')assert.match(String(r.reason),/PRICE_WINDOW_CONFLICT/);assert.equal((await db.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.price_events WHERE book_id=ANY($1::uuid[])',[[one.id,two.id]])).rows[0].n,'1');});
 }finally{await fs.mkdir('docs/crm/test-results',{recursive:true});await fs.writeFile('docs/crm/test-results/pricing-'+(postgres?'postgres':'local')+'.json',JSON.stringify({testedAt:new Date().toISOString(),environment:postgres?'STAGING isolated PostgreSQL DML-only service role; fictitious published policies only':'LOCAL isolated PGlite; fictitious published policies only',status:cases.length===(postgres?9:8)&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await close();await owner.close();}}
main().catch(e=>{console.error(e instanceof Error?e.message:'PRICING_QA_FAILED');process.exitCode=1;});
