import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_REGISTRATION_MODE='OPEN';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-library-'+randomUUID();
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),{login,authenticate}=await import('../../lib/crm/auth'),repo=await import('../../lib/crm/repository'),l=await import('../../lib/crm/partner-library'),w=await import('../../lib/crm/workspace'),o=await import('../../lib/crm/onboarding'),m=await import('../../lib/crm/dealer-members');const ids=await createQaFixture(),db=await database(),cases:{name:string;status:string}[]=[];const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
try{const admin=(await login('admin@crm-qa.invalid',qaPassword)).user,a=(await login('a@crm-qa.invalid',qaPassword)).user,b=(await login('b@crm-qa.invalid',qaPassword)).user,sales=(await login('sales@crm-qa.invalid',qaPassword)).user;await repo.createAccount(admin,{email:'library-staff@crm-qa.invalid',password:qaPassword,displayName:'LOCAL QA Library Staff',organizationId:ids.dealerA,role:'DEALER_STAFF'});const staffSession=await login('library-staff@crm-qa.invalid',qaPassword),staff=staffSession.user;let itemId='',fileId='',documentId='';const draft={version:0,title:'LOCAL QA Policy - synthetic',category:'POLICY',audience:'DEALER_OWNER',organizationId:ids.dealerA,requiredRead:true,status:'DRAFT',effectiveAt:'2026-01-01T00:00:00Z'};
await test('F019 unpublished policy has no portal access and publication requires a real stored file',async()=>{const item=await l.saveLibraryItem(admin,draft);itemId=item.id;await assert.rejects(l.getLibraryItem(a,itemId),/NOT_FOUND/);assert.equal((await l.library(a)).length,0);await assert.rejects(l.saveLibraryItem(sales,draft),/FORBIDDEN/);await assert.rejects(l.saveLibraryItem(admin,{...draft,id:itemId,version:1,status:'PUBLISHED'}),/LIBRARY_FILE_REQUIRED/);const f=await w.uploadDocument(admin,{entityType:'library',entityId:itemId,title:'LOCAL QA policy bytes',filename:'policy.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA Synthetic Policy')});fileId=f.versionId;documentId=f.id;await l.saveLibraryItem(admin,{...draft,id:itemId,version:1,status:'PUBLISHED'});assert.equal((await l.library(a))[0].id,itemId);});
await test('F019 organization, audience, effective date and withdrawal protect downloads',async()=>{await assert.rejects(w.downloadDocument(b,fileId),/NOT_FOUND/);await assert.rejects(w.downloadDocument(staff,fileId),/NOT_FOUND/);await l.saveLibraryItem(admin,{...draft,id:itemId,version:2,status:'PUBLISHED',effectiveAt:'2099-01-01T00:00:00Z'});await assert.rejects(w.downloadDocument(a,fileId),/NOT_FOUND/);await l.saveLibraryItem(admin,{...draft,id:itemId,version:3,status:'WITHDRAWN'});await assert.rejects(w.downloadDocument(a,fileId),/NOT_FOUND/);await l.saveLibraryItem(admin,{...draft,id:itemId,version:4,status:'PUBLISHED'});assert.ok((await w.downloadDocument(a,fileId)).content.length);await assert.rejects(l.saveLibraryItem(admin,{...draft,id:itemId,version:4,status:'PUBLISHED'}),/VERSION_CONFLICT/);});
await test('F009 policy reads are bound to the current file version and draft carts never complete requests',async()=>{assert.equal((await l.onboardingChecklist(a)).policies[0].read,false);await w.acknowledgeDocument(a,fileId);assert.equal((await l.onboardingChecklist(a)).policies[0].read,true);await w.uploadDocument(admin,{entityType:'library',entityId:itemId,title:'LOCAL QA next policy',documentId,filename:'policy-v2.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA Synthetic Policy V2')});assert.equal((await l.onboardingChecklist(a)).policies[0].read,false);await l.markCatalogSeen(a);assert.equal((await l.onboardingChecklist(a)).catalogSeen,true);assert.equal((await l.onboardingChecklist(b)).catalogSeen,false);assert.equal((await l.onboardingChecklist(a)).commercialRequestCreated,false);assert.equal((await db.query('SELECT user_id FROM cohamy_crm.document_reads WHERE version_id=$1',[fileId])).rows.length,1);});
await test('Document acknowledgements display only own reads and require every current version',async()=>{
 const files=await w.documents(a,'library',itemId),latest=files.find(v=>v.number===2)!;
 assert.ok(files.find(v=>v.version_id===fileId)?.read_at);assert.equal(latest.read_at,null);
 assert.equal((await l.getLibraryItem(a,itemId)).read_confirmed,false);
 assert.equal((await w.documents(admin,'library',itemId)).find(v=>v.version_id===fileId)?.read_at,null);
 await w.acknowledgeDocument(a,latest.version_id);
 assert.equal((await l.getLibraryItem(a,itemId)).read_confirmed,true);assert.equal((await l.library(a))[0].read_confirmed,true);
 assert.equal((await l.getLibraryItem(admin,itemId)).read_confirmed,false);
 await w.uploadDocument(admin,{entityType:'library',entityId:itemId,title:'LOCAL QA Additional Required File',filename:'additional.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA Additional')});
 assert.equal((await l.getLibraryItem(a,itemId)).read_confirmed,false);
 await assert.rejects(l.getLibraryItem(b,itemId),/NOT_FOUND/);
});
await test('F017 owner can lock only own staff, stale writes conflict and sessions are revoked',async()=>{assert.ok(!(await m.dealerMembers(a)).some(v=>v.id===b.membershipId));await assert.rejects(m.dealerMembers(staff),/FORBIDDEN/);await assert.rejects(m.setDealerMember(a,{id:b.membershipId,version:1,active:false,role:'DEALER_STAFF'}),/NOT_FOUND/);await assert.rejects(m.setDealerMember(a,{id:a.membershipId,version:1,active:false,role:'DEALER_STAFF'}),/FORBIDDEN/);await assert.rejects(m.setDealerMember(a,{id:staff.membershipId,version:1,active:false,role:'ADMIN'}),/INVALID_FIELDS/);await m.setDealerMember(a,{id:staff.membershipId,version:1,active:false,role:'DEALER_STAFF'});assert.equal(await authenticate(staffSession.token),null);await assert.rejects(m.setDealerMember(a,{id:staff.membershipId,version:1,active:true,role:'DEALER_STAFF'}),/VERSION_CONFLICT/);await m.setDealerMember(a,{id:staff.membershipId,version:2,active:true,role:'DEALER_STAFF'});assert.equal(await authenticate(staffSession.token),null);assert.ok((await login('library-staff@crm-qa.invalid',qaPassword)).user);});
await test('F003/F008 reviewer filtering, waiting time and normalized duplicate preview are administrator-only',async()=>{const input={companyName:'LOCAL QA Applicant duplicates',representative:'LOCAL QA Person',phone:'0901 122 334',email:'review@crm-qa.invalid',address:'LOCAL QA Address',region:'LOCAL QA Region',password:qaPassword,idempotencyKey:randomUUID()};await db.query('UPDATE cohamy_crm.organizations SET phone=$1 WHERE id=$2',['0901122334',ids.dealerA]);const r=await o.registerApplication(input);await o.assignReviewer(admin,r.id,{version:1,reviewerId:admin.membershipId});assert.equal((await o.reviewQueue(admin,{status:'DRAFT',reviewer:admin.membershipId,q:input.email})).total,1);assert.equal((await o.reviewQueue(admin,{status:'DRAFT',reviewer:'NONE',q:input.email})).total,0);assert.equal((await o.reviewQueue(admin,{status:'DRAFT',minHours:'24',q:input.email})).total,0);assert.ok((await o.applicationDuplicates(admin,r.id)).some(v=>v.id===ids.dealerA));await assert.rejects(o.applicationDuplicates(a,r.id),/FORBIDDEN/);await assert.rejects(o.assignReviewer(admin,r.id,{version:2,reviewerId:sales.membershipId}),/INVALID_ASSIGNEE/);});
}finally{await fs.writeFile('docs/crm/test-results/partner-library-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated fictitious PGlite; policy bytes synthetic',cases,integrationCoverage:{commercialRequest:'COVERED_BY test:crm:commercial-orders'},postgres:'NOT_RUN_IN_THIS_LOCAL_SUITE'},null,2));await db.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
