import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import ExcelJS from 'exceljs';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-data-'+randomUUID();
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture');const {database}=await import('../../lib/crm/db');const {login}=await import('../../lib/crm/auth');const j=await import('../../lib/crm/data-jobs');const work=await import('../../lib/crm/work');const repo=await import('../../lib/crm/repository');const ids=await createQaFixture(),db=await database(),cases:{name:string;status:string}[]=[];
 const test=async(name:string,fn:()=>Promise<void>)=>{try{await fn();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 const workbook=async(rows:unknown[][])=>{const b=new ExcelJS.Workbook(),s=b.addWorksheet('Khách');for(const row of rows)s.addRow(row);return Buffer.from(await b.xlsx.writeBuffer());};
 try{const admin=(await login('admin@crm-qa.invalid',qaPassword)).user,sales=(await login('sales@crm-qa.invalid',qaPassword)).user,dealer=(await login('a@crm-qa.invalid',qaPassword)).user;let previewId='';
 await test('F131 Excel mapping and preview persist without writing business data',async()=>{const bytes=await workbook([['Tên tùy ý','Mã tùy ý','Email','Mã doanh nghiệp'],['LOCAL QA Import One','QA_IMPORT_1','one@crm-qa.invalid','qa 12-34'],['LOCAL QA Import Two','QA_IMPORT_2','two@crm-qa.invalid','QA.5678']]);const p=await j.previewImport(admin,bytes,{idempotencyKey:randomUUID(),kind:'CUSTOMER',mapping:{name:1,code:2,email:3,businessId:4}});previewId=p.id;assert.equal(p.errors,0);assert.equal(p.rows[0].record.code,'QA_IMPORT_1');assert.equal((await db.query("SELECT id FROM cohamy_crm.organizations WHERE code='QA_IMPORT_1'")).rows.length,0);assert.equal((await j.getJob(admin,p.id)).status,'PREVIEW');});
 await test('F131 confirmation and worker retry create each row once',async()=>{await j.confirmImport(admin,previewId);await j.confirmImport(admin,previewId);await j.runNextJob();assert.equal((await j.getJob(admin,previewId)).status,'SUCCEEDED');assert.equal(await j.runNextJob(),false);assert.equal((await db.query('SELECT id FROM cohamy_crm.organizations WHERE import_job_id=$1',[previewId])).rows.length,2);assert.equal((await db.query<{business_key:string}>("SELECT business_key FROM cohamy_crm.organizations WHERE code='QA_IMPORT_1'")).rows[0].business_key,'QA1234');});
 await test('F131 invalid cells, duplicates and invalid email prevent confirmation',async()=>{const bytes=await workbook([['Mã','Tên','Email'],['QA_BAD','LOCAL QA One','invalid'],['QA_BAD',{formula:'1+1'},'bad@crm-qa.invalid']]);const p=await j.previewImport(admin,bytes,{idempotencyKey:randomUUID(),kind:'CUSTOMER',mapping:{code:1,name:2,email:3}});assert.equal(p.errors,2);await assert.rejects(j.confirmImport(admin,p.id),/IMPORT_ERRORS/);assert.equal((await db.query("SELECT id FROM cohamy_crm.organizations WHERE code='QA_BAD'")).rows.length,0);});
 await test('F131 conflicting code introduced after preview rolls back the whole import',async()=>{const bytes=await workbook([['Mã','Tên'],['QA_RACE_1','LOCAL QA race one'],['QA_RACE_2','LOCAL QA race two']]);const p=await j.previewImport(admin,bytes,{idempotencyKey:randomUUID(),kind:'CUSTOMER',mapping:{code:1,name:2}});await repo.createOrganization(admin,{code:'QA_RACE_2',name:'LOCAL QA concurrent existing',kind:'CUSTOMER'});await j.confirmImport(admin,p.id);await j.runNextJob();assert.equal((await j.getJob(admin,p.id)).status,'FAILED');assert.equal((await db.query("SELECT id FROM cohamy_crm.organizations WHERE code='QA_RACE_1'")).rows.length,0);});
 await test('F132 filtered export is a usable XLSX with selected columns and safe formula text',async()=>{await repo.createOrganization(admin,{code:'QA_FORMULA',name:'=LOCAL QA formula',kind:'CUSTOMER'});const input={idempotencyKey:randomUUID(),q:'=LOCAL QA',kind:'CUSTOMER',columns:['code','name']};const job=await j.exportPartners(admin,input);assert.equal((await j.exportPartners(admin,input)).id,job.id);await assert.rejects(j.exportPartners(admin,{...input,q:'changed'}),/IDEMPOTENCY_CONFLICT/);await j.runNextJob();const bytes=await j.downloadExport(admin,job.id),book=new ExcelJS.Workbook();await book.xlsx.load(Buffer.from(bytes) as unknown as ExcelJS.Buffer);assert.equal(book.worksheets[0].getCell('A1').text,'Mã');assert.equal(book.worksheets[0].getCell('B2').text,"'=LOCAL QA formula");assert.equal(book.worksheets[0].rowCount,2);assert.equal(book.worksheets[0].columnCount,2);await assert.rejects(j.downloadExport(sales,job.id),/NOT_FOUND/);});
 await test('E03/E15 worker and download enforce live scope and deny dealer jobs',async()=>{await assert.rejects(j.exportPartners(dealer,{idempotencyKey:randomUUID(),columns:['name']}),/FORBIDDEN/);const job=await j.exportPartners(sales,{idempotencyKey:randomUUID(),kind:'DEALER',columns:['name']});await j.runNextJob();const b=new ExcelJS.Workbook();await b.xlsx.load(Buffer.from(await j.downloadExport(sales,job.id)) as unknown as ExcelJS.Buffer);assert.equal(b.worksheets[0].rowCount,2);assert.ok(!b.worksheets[0].getCell('A2').text.includes('B'));await work.assignStaff(admin,{type:'partner',id:ids.dealerA,membershipIds:[]});await assert.rejects(j.downloadExport(sales,job.id),/FORBIDDEN/);});
 await test('E14 durable queued jobs recover an expired lease without duplicate effects',async()=>{const job=await j.exportPartners(admin,{idempotencyKey:randomUUID(),kind:'CUSTOMER',columns:['name']});await db.query("UPDATE cohamy_crm.data_jobs SET status='RUNNING',lease_until=now()-interval '1 minute',lease_id=$1,attempts=1 WHERE id=$2",[randomUUID(),job.id]);await j.runNextJob();assert.equal((await j.getJob(admin,job.id)).status,'SUCCEEDED');assert.equal((await j.getJob(admin,job.id)).attempts,2);});
 await test('F131 file type and row limits are enforced before any write',async()=>{await assert.rejects(j.previewImport(admin,Buffer.from('not xlsx'),{idempotencyKey:randomUUID(),kind:'CUSTOMER',mapping:{code:1,name:2}}),/FILE_SIZE_INVALID/);const bytes=await workbook([['Mã','Tên'],...Array.from({length:501},(_,i)=>['QA_TOO_'+i,'LOCAL QA Too '+i])]);await assert.rejects(j.previewImport(admin,bytes,{idempotencyKey:randomUUID(),kind:'CUSTOMER',mapping:{code:1,name:2}}),/IMPORT_LIMIT/);});
 }finally{await fs.writeFile('docs/crm/test-results/data-jobs-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated PGlite and actual XLSX parsing',cases,postgresConcurrency:'NOT_RUN',workerRestart:'EXPIRED_LEASE_RECOVERY_ONLY'},null,2));await db.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
