import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-governance-'+randomUUID();
async function main(){
 const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),auth=await import('../../lib/crm/auth'),g=await import('../../lib/crm/governance'),w=await import('../../lib/crm/workspace'),work=await import('../../lib/crm/work'),repo=await import('../../lib/crm/repository');
 const ids=await createQaFixture(),db=await database(),admin=(await auth.login('admin@crm-qa.invalid',qaPassword)).user,sales=(await auth.login('sales@crm-qa.invalid',qaPassword)).user,dealer=(await auth.login('a@crm-qa.invalid',qaPassword)).user,dealerB=(await auth.login('b@crm-qa.invalid',qaPassword)).user,cases:{name:string;status:string}[]=[];
 const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 try{
  await test('F124 column order/width persist per user and reject stale or unsafe widths',async()=>{await w.savePreferences(sales,{version:0,columns:['phone','name'],columnWidths:{phone:180,name:320}});const pref=await w.preferences(sales);assert.deepEqual(pref.columns,['phone','name']);assert.equal(pref.columnWidths.name,320);assert.deepEqual((await w.preferences(dealer)).columnWidths,{});await assert.rejects(w.savePreferences(sales,{...pref,version:0}),/VERSION_CONFLICT/);await assert.rejects(w.savePreferences(sales,{...pref,columnWidths:{name:9999}}),/INVALID_FIELDS/);await assert.rejects(w.savePreferences(sales,{...pref,columns:['password']}),/INVALID_FIELDS/);});
  await test('F123 edit/default/share obey ownership and exactly one personal default',async()=>{const a=await w.saveFilter(admin,{resource:'partners',name:'LOCAL QA A',value:{kind:'DEALER',q:'A'},isDefault:true,shared:true}),b=await w.saveFilter(admin,{resource:'partners',name:'LOCAL QA B',value:{kind:'DEALER',q:'B'},isDefault:true});assert.equal((await w.listFilters(admin,'partners')).filter(f=>f.is_default).length,1);const old=(await w.listFilters(admin,'partners')).find(f=>f.id===a.id)!;await assert.rejects(w.saveFilter(sales,{id:a.id,version:old.version,name:'LOCAL QA foreign edit',resource:'partners',value:{},isDefault:true}),/VERSION_CONFLICT/);await w.saveFilter(admin,{id:b.id,version:1,resource:'partners',name:'LOCAL QA updated',value:{kind:'DEALER',q:'new'},isDefault:true});assert.equal((await w.listFilters(admin,'partners')).find(f=>f.id===b.id)?.value.q,'new');await assert.rejects(w.saveFilter(sales,{resource:'partners',name:'LOCAL QA elevation',value:{},shared:true}),/FORBIDDEN/);});
  await test('F128 preview does not write; one stale member blocks the entire batch',async()=>{const p=await g.bulkPreview(admin,{ids:[ids.dealerA,ids.dealerB],action:'STAGE',stage:'CONTACTED',reason:'LOCAL QA bulk preview'});assert.equal((await repo.getOrganization(admin,ids.dealerA)).stage,'ACTIVE');await db.query('UPDATE cohamy_crm.organizations SET version=version+1 WHERE id=$1',[ids.dealerB]);const r=await g.bulkConfirm(admin,{id:p.id}) as {applied:number;errors:unknown[]};assert.equal(r.applied,0);assert.equal(r.errors.length,1);assert.equal((await repo.getOrganization(admin,ids.dealerA)).stage,'ACTIVE');});
  await test('F128 atomic confirmation is retry safe and current scope/expiry are enforced',async()=>{const p=await g.bulkPreview(admin,{ids:[ids.dealerA,ids.dealerB],action:'STAGE',stage:'CONTACTED',reason:'LOCAL QA atomic'});assert.equal((await g.bulkConfirm(admin,{id:p.id}) as {applied:number}).applied,2);const version=(await repo.getOrganization(admin,ids.dealerA)).version;await g.bulkConfirm(admin,{id:p.id});assert.equal((await repo.getOrganization(admin,ids.dealerA)).version,version);await assert.rejects(g.bulkPreview(sales,{ids:[ids.dealerB],action:'ACTIVATE',reason:'LOCAL QA foreign'}),/NOT_FOUND/);const s=await g.bulkPreview(sales,{ids:[ids.dealerA],action:'ACTIVATE',reason:'LOCAL QA scope'});await work.assignStaff(admin,{type:'partner',id:ids.dealerA,membershipIds:[]});assert.equal((await g.bulkConfirm(sales,{id:s.id}) as {applied:number}).applied,0);await work.assignStaff(admin,{type:'partner',id:ids.dealerA,membershipIds:[ids.sales]});const expired=await g.bulkPreview(admin,{ids:[ids.dealerA],action:'ACTIVATE',reason:'LOCAL QA expiry'});await db.query("UPDATE cohamy_crm.bulk_previews SET expires_at=now()-interval '1 second' WHERE id=$1",[expired.id]);await assert.rejects(g.bulkConfirm(admin,{id:expired.id}),/PREVIEW_EXPIRED/);});
  let field='';const definition={version:0,key:'qa_limit',label:'LOCAL QA limit',kind:'NUMBER',options:[],required:true,readRoles:['ADMIN','SALES','DEALER_OWNER'],writeRoles:['ADMIN','SALES'],active:true};
  await test('F135 type/required/role validation and optimistic value conflicts',async()=>{field=(await g.saveFieldDefinition(admin,definition)).id;await assert.rejects(g.saveFieldDefinition(sales,{...definition,key:'other_qa'}),/FORBIDDEN/);await assert.rejects(g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:1,version:0,value:null}),/CUSTOM_FIELD_REQUIRED/);await assert.rejects(g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:1,version:0,value:42}),/INVALID_FIELDS/);await g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:1,version:0,value:'42.125'});await assert.rejects(g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:1,version:0,value:'0'}),/VERSION_CONFLICT/);await assert.rejects(g.saveCustomValue(dealer,{organizationId:ids.dealerA,fieldId:field,definitionVersion:1,version:1,value:'1'}),/FORBIDDEN/);await assert.rejects(g.customValues(dealerB,ids.dealerA),/NOT_FOUND/);});
  await test('F135 schema changes retain old typed values and immutable history',async()=>{await g.saveFieldDefinition(admin,{...definition,id:field,version:1,kind:'ENUM',options:['A','B']});await g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:2,version:0,value:'A'});const values=await g.customValues(dealer,ids.dealerA);assert.equal(values.length,2);assert.equal(values.find(v=>v.definition_version===1)?.value,'42.125');assert.equal(values.find(v=>v.definition_version===2)?.value,'A');await assert.rejects(g.saveCustomValue(sales,{organizationId:ids.dealerA,fieldId:field,definitionVersion:2,version:1,value:'C'}),/INVALID_FIELDS/);await assert.rejects(db.query("UPDATE cohamy_crm.custom_field_versions SET definition='{}'::jsonb"),/AUDIT_APPEND_ONLY/);await assert.rejects(db.query('DELETE FROM cohamy_crm.custom_value_history'),/AUDIT_APPEND_ONLY/);});
  await test('F108 Vietnam quiet hours cover overnight/boundaries and mandatory security overrides opt-out',async()=>{assert.equal(w.notificationAvailableAt({quietStart:22,quietEnd:7},new Date('2026-09-19T16:10:00Z')).toISOString(),'2026-09-20T00:00:00.000Z');assert.equal(w.notificationAvailableAt({quietStart:22,quietEnd:7},new Date('2026-09-19T23:10:00Z')).toISOString(),'2026-09-20T00:00:00.000Z');assert.equal(w.notificationAvailableAt({quietStart:9,quietEnd:12},new Date('2026-09-19T03:00:00Z')).toISOString(),'2026-09-19T05:00:00.000Z');assert.equal(w.notificationAvailableAt({quietStart:22,quietEnd:7},new Date('2026-09-20T00:00:00Z')).toISOString(),'2026-09-20T00:00:00.000Z');const pref=await w.preferences(sales);await w.savePreferences(sales,{...pref,notificationKinds:[],notificationChannels:[],taskNotifications:false});await db.transaction(async tx=>{await w.enqueueNotification(tx,sales.id,'qa-opt-out','TASK','partner',ids.dealerA,'LOCAL QA suppressed');await w.enqueueNotification(tx,sales.id,'qa-security','SECURITY','account',sales.id,'LOCAL QA security');});assert.equal((await db.query('SELECT id FROM cohamy_crm.notifications WHERE event_key=$1',['qa-opt-out'])).rows.length,0);assert.equal((await w.notifications(sales,'UNREAD')).filter(n=>n.message==='LOCAL QA security').length,1);});
  await test('F107 read/unread filtering and current scope recheck',async()=>{const note=(await w.notifications(sales,'UNREAD')).find(n=>n.message==='LOCAL QA security')!;await w.readNotification(sales,note.id);assert.equal((await w.notifications(sales,'READ')).some(n=>n.id===note.id),true);assert.equal((await w.notifications(sales,'UNREAD')).some(n=>n.id===note.id),false);await assert.rejects(w.readNotification(dealer,note.id),/NOT_FOUND/);});
  await test('F133/F134 metadata search/effect/expiry and version-specific reads',async()=>{const f=await w.uploadDocument(admin,{entityType:'partner',entityId:ids.dealerA,title:'LOCAL QA contract',filename:'effective-qa.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nQA'),effectiveAt:'2026-09-19T00:00:00+07:00',expiresAt:'2027-09-19T00:00:00+07:00'});assert.equal((await w.documents(dealer,'partner',ids.dealerA,'effective-qa.pdf')).length,1);await w.acknowledgeDocument(dealer,f.versionId);assert.equal((await w.documents(admin,'partner',ids.dealerA)).find(v=>v.version_id===f.versionId)?.read_at,null);assert.ok((await w.documents(dealer,'partner',ids.dealerA)).find(v=>v.version_id===f.versionId)?.read_at);await assert.rejects(w.uploadDocument(admin,{entityType:'partner',entityId:ids.dealerA,title:'LOCAL QA inverted',filename:'bad.pdf',mime:'application/pdf',content:Buffer.from('%PDF-QA'),effectiveAt:'2027-01-01T00:00:00Z',expiresAt:'2026-01-01T00:00:00Z'}),/INVALID_FIELDS/);});
  await test('F138 devices identify current session and revoking others keeps this session only',async()=>{const current=await auth.login('b@crm-qa.invalid',qaPassword,{userAgent:'Mozilla Windows Chrome/130 Edg/130'}),other=await auth.login('b@crm-qa.invalid',qaPassword,{userAgent:'Mozilla Android Chrome/130'});const list=await w.sessions(current.user,current.token);assert.equal(list.filter(s=>s.current).length,1);assert.equal(list.find(s=>s.current)?.device_label,'Edge · Windows');await assert.rejects(g.revokeOtherSessions(dealer,current.token),/UNAUTHORIZED/);await g.revokeOtherSessions(current.user,current.token);assert.ok(await auth.authenticate(current.token));assert.equal(await auth.authenticate(other.token),null);assert.equal((await w.sessions(current.user,current.token)).length,1);});
  await test('F136 role preview includes affected sessions; stale/missing preview and escalation blocked',async()=>{const p=await g.rolePreview(admin,{id:ids.sales,role:'WAREHOUSE'});assert.equal(p.previousRole,'SALES');assert.equal(p.membershipVersion,1);assert.ok(Number(p.activeSessions)>0);assert.equal(p.permissions.permissions.some(v=>v.key==='accounts.manage'),false);await assert.rejects(work.manageAccount(admin,ids.sales,{action:'role',role:'WAREHOUSE'}),/ROLE_PREVIEW_REQUIRED/);await work.manageAccount(admin,ids.sales,{action:'role',role:'WAREHOUSE',expectedVersion:p.membershipVersion});await assert.rejects(work.manageAccount(admin,ids.sales,{action:'role',role:'SALES',expectedVersion:p.membershipVersion}),/VERSION_CONFLICT/);await assert.rejects(g.rolePreview(admin,{id:ids.membershipA,role:'ADMIN'}),/INVALID_ROLE_ORGANIZATION/);await assert.rejects(g.rolePreview(dealer,{id:ids.sales,role:'ADMIN'}),/FORBIDDEN/);});
  await test('F139 structured immutable audit supports actor/date filters and redacts nested secrets',async()=>{await db.transaction(tx=>auth.audit(tx,admin.id,'qa.redaction',ids.dealerA,{before:{active:true},after:{active:false},reason:'LOCAL QA reason',password:'hidden',nested:{otp:'hidden',token:'hidden',databaseUrl:'hidden'}}));const rows=await w.auditSearch(admin,{q:'qa.redaction',actor:admin.id,from:'2026-01-01',to:'2030-01-01'});assert.equal(rows.length,1);const payload=rows[0].payload as {reason:string;password:string;nested:{otp:string};before:{active:boolean}};assert.equal(payload.password,'[redacted]');assert.equal(payload.nested.otp,'[redacted]');assert.equal(payload.before.active,true);assert.equal(payload.reason,'LOCAL QA reason');assert.equal((await w.auditSearch(admin,{q:'qa.redaction',from:'2000-01-01',to:'2000-01-02'})).length,0);await assert.rejects(w.auditSearch(dealer,{}),/FORBIDDEN/);await assert.rejects(db.query("UPDATE cohamy_crm.audit_events SET payload='{}'::jsonb"),/AUDIT_APPEND_ONLY/);});
 }finally{await fs.mkdir('.local/reports',{recursive:true});await fs.writeFile('.local/reports/crm-governance-qa.json',JSON.stringify({environment:'LOCAL',status:cases.length===12&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await db.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
