import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import ExcelJS from 'exceljs';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-care-'+randomUUID();
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),{login}=await import('../../lib/crm/auth'),c=await import('../../lib/crm/relationships'),repo=await import('../../lib/crm/repository'),w=await import('../../lib/crm/workspace'),work=await import('../../lib/crm/work'),j=await import('../../lib/crm/data-jobs');const ids=await createQaFixture(),db=await database(),cases:{name:string;status:string}[]=[];const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
try{const admin=(await login('admin@crm-qa.invalid',qaPassword)).user,sales=(await login('sales@crm-qa.invalid',qaPassword)).user,b=(await login('b@crm-qa.invalid',qaPassword)).user;let opportunityId='',reasonId='',visitId='',fileId='';let tagIds:string[]=[];
await test('F025/F026 stage changes keep immutable actor/time/reasons; stale writes and automatic loss are rejected',async()=>{reasonId=(await c.saveCareDictionary(admin,{kind:'reasons',version:0,name:'LOCAL QA Needs approval',active:true})).id;const input={organizationId:ids.dealerA,version:0,title:'LOCAL QA Opportunity',stage:'NEW',notes:'LOCAL QA Initial notes'};const p=await c.saveOpportunity(sales,input);opportunityId=p.id;await assert.rejects(c.saveOpportunity(sales,{...input,id:p.id,version:1,stage:'LOST'}),/REASON_REQUIRED/);await c.saveOpportunity(sales,{...input,id:p.id,version:1,stage:'LOST',reasonId,notes:'LOCAL QA Explicit loss by staff'});assert.equal((await c.opportunities(sales,ids.dealerA))[0].version,2);await assert.rejects(c.saveOpportunity(sales,{...input,id:p.id,version:1,stage:'WON'}),/VERSION_CONFLICT/);const history=(await db.query<{actor_id:string}>('SELECT actor_id FROM cohamy_crm.opportunity_history WHERE opportunity_id=$1',[p.id])).rows;assert.equal(history.length,2);assert.ok(history.every(h=>h.actor_id===sales.id));await assert.rejects(db.query('DELETE FROM cohamy_crm.opportunity_history WHERE opportunity_id=$1',[p.id]),/AUDIT_APPEND_ONLY/);const report=await c.careReport(admin);assert.ok(report.some(r=>r.reason==='LOCAL QA Needs approval'&&r.stage==='LOST'&&r.count==='1'));});
await test('F027 multiple tags combine with AND under server scope and active dictionaries have manager-only writes',async()=>{tagIds=[(await c.saveCareDictionary(admin,{kind:'tags',version:0,name:'LOCAL QA Store',active:true})).id,(await c.saveCareDictionary(admin,{kind:'tags',version:0,name:'LOCAL QA Interested',active:true})).id];await assert.rejects(c.saveCareDictionary(sales,{kind:'tags',version:0,name:'unauthorized',active:true}),/FORBIDDEN/);await c.savePartnerTags(sales,{organizationId:ids.dealerA,version:1,tagIds});await c.savePartnerTags(admin,{organizationId:ids.dealerB,version:1,tagIds:[tagIds[0]]});assert.equal((await repo.listOrganizations(admin,{tags:tagIds.join(',')})).total,1);assert.equal((await repo.listOrganizations(sales,{tags:tagIds[0]})).total,1);assert.equal((await c.partnerTags(sales,ids.dealerA)).length,2);await assert.rejects(c.savePartnerTags(sales,{organizationId:ids.dealerA,version:1,tagIds:[]}),/VERSION_CONFLICT/);await assert.rejects(c.savePartnerTags(sales,{organizationId:ids.dealerB,version:2,tagIds:[]}),/NOT_FOUND/);});
await test('F027/F124/F132 saved combinations and actual XLSX export preserve selected tags',async()=>{await w.saveFilter(sales,{name:'LOCAL QA Tagged',resource:'partners',value:{tags:tagIds.join(',')},shared:false});assert.equal((await w.listFilters(sales,'partners'))[0].value.tags,tagIds.join(','));const job=await j.exportPartners(admin,{idempotencyKey:randomUUID(),tags:tagIds.join(','),columns:['name']});await j.runNextJob();assert.equal((await j.getJob(admin,job.id)).status,'SUCCEEDED',JSON.stringify(await j.getJob(admin,job.id)));const bytes=await j.downloadExport(admin,job.id),book=new ExcelJS.Workbook();await book.xlsx.load(Buffer.from(bytes) as unknown as ExcelJS.Buffer);assert.equal(book.worksheets[0].rowCount,2);});
await test('F028 contact preferences persist without fake SKU or cross-scope reads',async()=>{const product=(await repo.listCatalog(admin))[0];await c.saveContactPreferences(sales,{organizationId:ids.dealerA,version:0,channel:'EMAIL',preferredTime:'LOCAL QA Weekdays 09:00–11:00',interestedSkus:[product.sku],notes:'LOCAL QA Confirm by email'});assert.equal((await c.contactPreferences(sales,ids.dealerA)).interested_skus[0],product.sku);await assert.rejects(c.saveContactPreferences(sales,{organizationId:ids.dealerA,version:1,channel:'PHONE',preferredTime:'',interestedSkus:['UNKNOWN_QA'],notes:''}),/SKU_NOT_ACTIVE/);await assert.rejects(c.contactPreferences(sales,ids.dealerB),/NOT_FOUND/);await assert.rejects(c.contactPreferences(b,ids.dealerA),/FORBIDDEN/);});
await test('F029 visits are append-only, retries preserve one visit and attached photos follow current source access',async()=>{const input={organizationId:ids.dealerA,visitedAt:'2026-09-19T02:00:00Z',result:'LOCAL QA Visit result',supportRequest:'LOCAL QA Display material',idempotencyKey:randomUUID()};const v=await c.createVisit(sales,input);visitId=v.id;assert.equal((await c.createVisit(sales,input)).id,v.id);await assert.rejects(c.createVisit(sales,{...input,result:'changed result'}),/IDEMPOTENCY_CONFLICT/);const f=await w.uploadDocument(sales,{entityType:'visit',entityId:v.id,title:'LOCAL QA Visit photo',filename:'visit.png',mime:'image/png',content:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6MZsAAAAASUVORK5CYII=','base64')});fileId=f.versionId;assert.ok((await w.downloadDocument(sales,fileId)).content.length);assert.equal((await c.visits(sales,ids.dealerA)).length,1);await assert.rejects(db.query('UPDATE cohamy_crm.partner_visits SET result=$1 WHERE id=$2',['changed',v.id]),/AUDIT_APPEND_ONLY/);});
await test('F025–F029 scope revocation hides opportunities, preferences, tag lists, visits and private files',async()=>{await work.assignStaff(admin,{type:'partner',id:ids.dealerA,membershipIds:[]});await assert.rejects(c.opportunities(sales,ids.dealerA),/NOT_FOUND/);await assert.rejects(c.contactPreferences(sales,ids.dealerA),/NOT_FOUND/);await assert.rejects(c.partnerTags(sales,ids.dealerA),/NOT_FOUND/);await assert.rejects(c.getVisit(sales,visitId),/NOT_FOUND/);await assert.rejects(w.downloadDocument(sales,fileId),/NOT_FOUND/);assert.equal((await c.visitDirectory(sales)).length,0);assert.equal((await repo.listOrganizations(sales,{tags:tagIds[0]})).total,0);assert.equal((await db.query('SELECT id FROM cohamy_crm.opportunities WHERE id=$1',[opportunityId])).rows.length,1);});
}finally{await fs.writeFile('docs/crm/test-results/relationships-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated fictitious PGlite',cases,commercialOrders:'NOT_IMPLEMENTED',postgres:'NOT_RUN'},null,2));await db.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
