import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
if(process.env.CRM_ENVIRONMENT!=='STAGING'||process.env.CRM_DATABASE_MODE!=='postgres')throw new Error('ISOLATED_POSTGRES_STAGING_REQUIRED');
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),auth=await import('../../lib/crm/auth'),care=await import('../../lib/crm/care-automation'),work=await import('../../lib/crm/work'),repo=await import('../../lib/crm/repository'),task=await import('../../lib/crm/care'),onboarding=await import('../../lib/crm/onboarding');
 const ids=await createQaFixture(),db=await database(),admin=(await auth.login('admin@crm-qa.invalid',qaPassword)).user,sales=(await auth.login('sales@crm-qa.invalid',qaPassword)).user,cases:{name:string;status:string}[]=[];
 const test=async(name:string,fn:()=>Promise<void>)=>{try{await fn();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 try{
  await test('F103 concurrent PostgreSQL scheduler ticks create exactly one task and immutable successful occurrence',async()=>{const s=await care.saveCareSchedule(sales,{version:0,entityType:'partner',entityId:ids.dealerA,title:'STAGING QA concurrent schedule',assigneeId:ids.sales,kind:'FOLLOW_UP',frequency:'DAILY',every:1,nextDueAt:new Date(Date.now()-60000).toISOString(),enabled:true});await Promise.all(Array.from({length:6},()=>care.runCareAutomation()));const runs=await care.scheduleRuns(admin,s.id);assert.equal(runs.length,1);assert.equal(runs[0].status,'SUCCEEDED');assert.equal((await work.listTasks(admin)).filter(t=>t.title==='STAGING QA concurrent schedule').length,1);});
  await test('F104 opposite concurrent dependencies cannot commit a cycle',async()=>{const base={entityType:'partner',entityId:ids.dealerA,assigneeId:ids.sales,dueAt:new Date(Date.now()+86400000).toISOString()};const a=await work.createTask(admin,{...base,title:'STAGING QA dependency A'}),b=await work.createTask(admin,{...base,title:'STAGING QA dependency B'});const results=await Promise.allSettled([task.saveDependency(admin,{taskId:a.id,prerequisiteId:b.id}),task.saveDependency(admin,{taskId:b.id,prerequisiteId:a.id})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(String((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason),/DEPENDENCY_CYCLE/);});
  await test('F109 simultaneous PostgreSQL escalation ticks persist one log and one transactional notification',async()=>{await care.saveSlaPolicy(admin,{version:0,name:'STAGING QA support SLA',kind:'SUPPORT',delayMinutes:0,recipientId:admin.membershipId,enabled:true});const t=await work.createTask(admin,{entityType:'partner',entityId:ids.dealerA,title:'STAGING QA overdue support',assigneeId:ids.sales,kind:'SUPPORT',dueAt:new Date(Date.now()-60000).toISOString()});await Promise.all(Array.from({length:6},()=>care.runCareAutomation()));assert.equal((await care.escalations(admin)).filter(e=>e.task_id===t.id).length,1);assert.equal((await db.query('SELECT id FROM cohamy_crm.notifications WHERE message LIKE $1',['Chuyển cấp: STAGING QA overdue support%'])).rows.length,1);});
  await test('F110 concurrent PostgreSQL event consumers create one task per actual event/template',async()=>{const r=await care.saveCareRule(admin,{version:0,name:'STAGING QA create follow-up',eventAction:'partner.created',title:'STAGING QA unique event work',kind:'GENERAL',assigneeId:admin.membershipId,dueMinutes:60,enabled:true});await repo.createOrganization(admin,{kind:'CUSTOMER',code:'QA_EVT_'+randomUUID().slice(0,8),name:'STAGING QA event customer',phone:'',email:'',address:''});await Promise.all(Array.from({length:6},()=>care.runCareAutomation()));assert.equal((await care.ruleRuns(admin,r.id)).length,1);assert.equal((await work.listTasks(admin)).filter(t=>t.title==='STAGING QA unique event work').length,1);});
  await test('F110 actual approved application event is consumed once concurrently in PostgreSQL',async()=>{process.env.CRM_REGISTRATION_MODE='OPEN';const rule=await care.saveCareRule(admin,{version:0,name:'STAGING QA application approval rule',eventAction:'application.approved',title:'STAGING QA welcome approved organization',kind:'APPROVAL',assigneeId:admin.membershipId,dueMinutes:60,enabled:true});const app=await onboarding.registerApplication({companyName:'STAGING QA approved business',representative:'QA representative',phone:'0900000123',email:'pg-approval@crm-qa.invalid',address:'STAGING QA address',region:'STAGING QA region',password:qaPassword,idempotencyKey:randomUUID()});let code='';await onboarding.requestVerification(app.id,{send:async(_email,value)=>{code=value;}});await onboarding.verifyApplication(app.id,{code});await onboarding.submitApplication(app.id,{version:(await onboarding.application(app.id)).version});const before=await onboarding.application(app.id);await onboarding.reviewApplication(admin,app.id,{version:before.version,action:'APPROVE',role:'DEALER_OWNER'});await Promise.all(Array.from({length:6},()=>care.runCareAutomation()));const runs=await care.ruleRuns(admin,rule.id);assert.equal(runs.length,1);assert.equal(runs[0].status,'SUCCEEDED');await onboarding.reviewApplication(admin,app.id,{version:before.version,action:'APPROVE',role:'DEALER_OWNER'});await care.runCareAutomation();assert.equal((await care.ruleRuns(admin,rule.id)).length,1);});
  await test('Locked PostgreSQL identity cannot finish a task, post notes or edit checklist from a stale authenticated snapshot',async()=>{const t=await work.createTask(sales,{entityType:'partner',entityId:ids.dealerA,title:'STAGING QA stale identity guard',assigneeId:ids.sales,dueAt:new Date(Date.now()+86400000).toISOString()});const before=(await work.listActivities(admin,'partner',ids.dealerA)).length;await repo.setAccountActive(admin,ids.sales,{active:false});await assert.rejects(work.updateTask(sales,t.id,{version:1,done:true}),/FORBIDDEN/);await assert.rejects(work.addActivity(sales,{entityType:'partner',entityId:ids.dealerA,body:'STAGING QA unauthorized stale note'}),/FORBIDDEN/);await assert.rejects(task.saveChecklist(sales,{taskId:t.id,version:1,items:[]}),/FORBIDDEN/);assert.equal((await task.taskAccess(admin,t.id)).version,1);assert.equal((await task.taskAccess(admin,t.id)).done_at,null);assert.equal((await work.listActivities(admin,'partner',ids.dealerA)).length,before);await repo.setAccountActive(admin,ids.sales,{active:true});});
  await test('F106 PostgreSQL handover competing with old-owner task creation commits a coherent complete outcome',async()=>{await repo.createAccount(admin,{displayName:'STAGING QA new Sales',email:'replacement@crm-qa.invalid',password:qaPassword,role:'SALES',organizationId:admin.organizationId});const replacement=(await auth.login('replacement@crm-qa.invalid',qaPassword)).user;const p=await care.handoverPreview(admin,{fromId:ids.sales,toId:replacement.membershipId,reason:'STAGING QA concurrency handover'});const [transfer,create]=await Promise.allSettled([care.handoverConfirm(admin,{id:p.id}),work.createTask(sales,{entityType:'partner',entityId:ids.dealerA,title:'STAGING QA racing task',assigneeId:ids.sales,dueAt:new Date(Date.now()+86400000).toISOString()})]);if(transfer.status==='fulfilled'){assert.equal(create.status,'rejected');assert.match(String((create as PromiseRejectedResult).reason),/NOT_FOUND|FORBIDDEN/);assert.deepEqual(await work.assignments(admin,'partner',ids.dealerA),[replacement.membershipId]);assert.equal((await db.query('SELECT id FROM cohamy_crm.tasks WHERE assignee_id=$1 AND done_at IS NULL',[ids.sales])).rows.length,0);}else{assert.match(String(transfer.reason),/VERSION_CONFLICT/);assert.equal(create.status,'fulfilled');assert.deepEqual(await work.assignments(admin,'partner',ids.dealerA),[ids.sales]);const freshPreview=await care.handoverPreview(admin,{fromId:ids.sales,toId:replacement.membershipId,reason:'STAGING QA refresh after intervening work'});await care.handoverConfirm(admin,{id:freshPreview.id});assert.equal((await db.query('SELECT id FROM cohamy_crm.tasks WHERE assignee_id=$1 AND done_at IS NULL',[ids.sales])).rows.length,0);}const final=await work.assignments(admin,'partner',ids.dealerA);assert.deepEqual(final,[replacement.membershipId]);await assert.rejects(repo.getOrganization(sales,ids.dealerA),/NOT_FOUND/);});
 }finally{await fs.mkdir('reports',{recursive:true});await fs.writeFile('reports/care-postgres.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'STAGING dedicated QA PostgreSQL, real multi-connection contention; no real business postings',status:cases.length===7&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await db.close();}
}
main().catch(e=>{console.error(e instanceof Error?e.message:'CARE_POSTGRES_QA_FAILED');process.exitCode=1;});
