import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import type {OrderPolicyDefinition} from '../../lib/crm/order-policy';

process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-samples-'+randomUUID();

async function main(){
 const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),auth=await import('../../lib/crm/auth'),repo=await import('../../lib/crm/repository'),inventory=await import('../../lib/crm/inventory'),samples=await import('../../lib/crm/samples'),prices=await import('../../lib/crm/pricing'),fixture=await import('./pricing-fixture'),policy=await import('../../lib/crm/order-policy'),requests=await import('../../lib/crm/order-requests'),orders=await import('../../lib/crm/sales-orders'),{installQaRuntime}=await import('./qa-runtime');
 const ids=await createQaFixture(),owner=await database(),admin=(await auth.login('admin@crm-qa.invalid',qaPassword)).user,sales=(await auth.login('sales@crm-qa.invalid',qaPassword)).user,dealerA=(await auth.login('a@crm-qa.invalid',qaPassword)).user,warehouseUser=(await auth.login('warehouse@crm-qa.invalid',qaPassword)).user,accountant=(await auth.login('accountant@crm-qa.invalid',qaPassword)).user,close=await installQaRuntime(owner),db=await database(),cases:{name:string;status:string}[]=[];
 const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(error){cases.push({name,status:'FAIL'});throw error;}};
 const definition:OrderPolicyDefinition={enabled:true,requireOwnerApproval:false,alwaysManagerApproval:false,managerApprovalAmount:null,creditRequiresApproval:false,nonSelfApproval:true,acceptedQuotePrice:'UNTIL_QUOTE_EXPIRY',pendingPrice:'UNTIL_REQUEST_EXPIRY',requiredPartnerFields:[],approvalRoles:['ADMIN','MANAGER'],confirmationRoles:['ADMIN','MANAGER','SALES']};
 let productId='',warehouseId='',locationId='',sampleId='',sampleVersion=1,orderId='';
 const makeOrder=async()=>{const request=await requests.saveCommercialRequest(dealerA,{version:0,organizationId:ids.dealerA,channel:'PORTAL',basket:fixture.qaBasket,delivery:{recipient:'QA sample receiver',phone:'0900000300',address:'QA fictitious sample conversion'},note:'QA sample conversion order',idempotencyKey:randomUUID()});let head=await requests.commercialRequestAccess(db,dealerA,request.id);await requests.requestAction(dealerA,{id:head.id,version:head.version,versionId:head.latest_version_id,action:'PROPOSE',reason:'QA propose sample conversion',idempotencyKey:randomUUID()});head=await requests.commercialRequestAccess(db,dealerA,head.id);const result=await orders.submitSalesRequest(dealerA,{id:head.id,version:head.version,versionId:head.latest_version_id,reason:'QA submit sample conversion',idempotencyKey:randomUUID()}) as {id:string};const sale=await orders.salesOrderAccess(db,sales,result.id);await orders.salesOrderAction(sales,{id:sale.id,version:sale.version,versionId:sale.latest_version_id,action:'CONFIRM',reason:'QA confirm sample conversion',idempotencyKey:randomUUID()});return result.id;};
 try{
  await test('F030 setup exposes only Cohamy sample warehouses and denies unrelated roles',async()=>{productId=(await fixture.createPriceProducts(admin))[0];const book=await prices.savePriceBook(admin,{version:0,name:'QA sample price',definition:fixture.qaPriceDefinition,idempotencyKey:randomUUID()});await prices.publishPriceBook(admin,{id:book.id,version:book.version,versionId:book.versionId,action:'PUBLISH',reason:'QA sample price policy',idempotencyKey:randomUUID()});await policy.saveOrderPolicy(admin,{version:0,definition,reason:'QA sample order policy',idempotencyKey:randomUUID()});warehouseId=(await repo.createWarehouse(admin,{code:'QA_SAMPLE',name:'LOCAL QA · Kho hàng mẫu',organizationId:admin.organizationId})).id;await db.query('INSERT INTO cohamy_crm.warehouse_assignments(membership_id,warehouse_id) VALUES($1,$2)',[warehouseUser.membershipId,warehouseId]);locationId=(await inventory.createLocation(admin,{warehouseId,code:'PICK_SAMPLE',name:'QA sample pick face',idempotencyKey:randomUUID()}) as {id:string}).id;assert.ok((await samples.sampleWarehouseOptions(sales)).some(w=>w.id===warehouseId));assert.deepEqual((await samples.sampleWarehouseOptions(warehouseUser)).map(w=>w.id),[warehouseId]);await assert.rejects(samples.listSamples(dealerA),/FORBIDDEN/);await assert.rejects(samples.listSamples(accountant),/FORBIDDEN/);});
  await test('F030 request tracks recipient, SKU, quantity and retries idempotently inside sales scope',async()=>{const input={organizationId:ids.dealerA,warehouseId,recipientName:'QA sample recipient',recipientPhone:'0900000301',purpose:'QA evaluate fictitious product',lines:[{productId,quantity:'5'}],reason:'QA approved sample request',idempotencyKey:randomUUID()},created=await samples.createSample(sales,input) as {id:string;version:number};sampleId=created.id;sampleVersion=created.version;assert.deepEqual(await samples.createSample(sales,input),created);const visible=await samples.listSamples(sales);assert.equal(visible[0].recipient_name,'QA sample recipient');assert.equal(visible[0].lines[0].quantity,'5.000000');await assert.rejects(samples.createSample(sales,{...input,organizationId:ids.dealerB,idempotencyKey:randomUUID()}),/SAMPLE_PARTNER_INVALID/);await assert.rejects(samples.createSample(warehouseUser,{...input,idempotencyKey:randomUUID()}),/FORBIDDEN/);});
  await test('F030 issue posts one atomic inventory document and allocates FEFO without touching reserved stock',async()=>{await inventory.postReceipt(admin,{locationId,lines:[{productId,lotCode:'QA-SAMPLE-OLD',manufacturedOn:'2025-01-01',expiresOn:'2027-01-01',quantity:'3'},{productId,lotCode:'QA-SAMPLE-NEW',manufacturedOn:'2026-01-01',expiresOn:'2028-01-01',quantity:'10'}],referenceType:'qa-sample-stock',referenceId:'QA-SAMPLE-R1',reason:'QA fictitious sample receipt',idempotencyKey:randomUUID()});const issued=await samples.issueSample(warehouseUser,{id:sampleId,version:sampleVersion,minimumShelfLifeDays:0,reason:'QA physical sample issue',idempotencyKey:randomUUID()}) as {version:number;allocations:{lotCode:string;quantity:string}[];inventoryDocumentId:string};sampleVersion=issued.version;assert.deepEqual(issued.allocations.map(a=>[a.lotCode,a.quantity]),[['QA-SAMPLE-OLD','3'],['QA-SAMPLE-NEW','2']]);const movements=(await db.query<{quantity:string;reference_type:string}>('SELECT m.quantity::text,d.reference_type FROM cohamy_crm.inventory_movements m JOIN cohamy_crm.inventory_documents d ON d.id=m.document_id WHERE d.id=$1 ORDER BY m.created_at,m.id',[issued.inventoryDocumentId])).rows;assert.deepEqual(movements.map(m=>Number(m.quantity)).sort((a,b)=>a-b),[-3,-2]);assert.ok(movements.every(m=>m.reference_type==='sample-issue'));const bad=await samples.createSample(sales,{organizationId:ids.dealerA,warehouseId,recipientName:'QA insufficient',recipientPhone:'',purpose:'QA insufficient atomic issue',lines:[{productId,quantity:'99'}],reason:'QA test atomic shortage',idempotencyKey:randomUUID()}) as {id:string;version:number},before=(await inventory.listInventory(admin)).reduce((n,row)=>n+Number(row.on_hand),0);await assert.rejects(samples.issueSample(admin,{id:bad.id,version:bad.version,minimumShelfLifeDays:0,reason:'QA cannot partially issue',idempotencyKey:randomUUID()}),/SAMPLE_STOCK_INSUFFICIENT/);const after=(await inventory.listInventory(admin)).reduce((n,row)=>n+Number(row.on_hand),0);assert.equal(after,before);});
  await test('F030 warehouse and sales views stay inside assignment boundaries',async()=>{const otherWarehouse=(await repo.createWarehouse(admin,{code:'QA_SAMPLE_2',name:'LOCAL QA · Kho mẫu khác',organizationId:admin.organizationId})).id,foreign=await samples.createSample(admin,{organizationId:ids.dealerB,warehouseId:otherWarehouse,recipientName:'QA foreign sample',recipientPhone:'',purpose:'QA scope boundary',lines:[{productId,quantity:'1'}],reason:'QA scope boundary fixture',idempotencyKey:randomUUID()}) as {id:string};assert.ok((await samples.listSamples(warehouseUser)).every(row=>row.warehouse_id===warehouseId));assert.ok((await samples.listSamples(sales)).every(row=>row.organization_id===ids.dealerA));assert.ok((await samples.listSamples(admin)).some(row=>row.id===foreign.id));});
  await test('F030 receive and feedback are versioned, replay-safe timeline events',async()=>{const receive={id:sampleId,version:sampleVersion,action:'RECEIVE' as const,feedback:'',outcome:null,salesOrderId:null,reason:'QA recipient confirmed delivery',idempotencyKey:randomUUID()},received=await samples.actSample(sales,receive) as {version:number;status:string};assert.equal(received.status,'RECEIVED');assert.deepEqual(await samples.actSample(sales,receive),received);sampleVersion=received.version;const feedback=await samples.actSample(sales,{id:sampleId,version:sampleVersion,action:'FEEDBACK',feedback:'QA recipient wants a commercial follow-up',outcome:'FOLLOW_UP',salesOrderId:null,reason:'QA recorded phone feedback',idempotencyKey:randomUUID()}) as {version:number;status:string};sampleVersion=feedback.version;assert.equal(feedback.status,'FEEDBACK');const view=(await samples.listSamples(sales)).find(x=>x.id===sampleId)!;assert.equal(view.feedback_outcome,'FOLLOW_UP');assert.deepEqual(view.events.map(e=>e.action),['CREATED','ISSUED','RECEIVE','FEEDBACK']);});
  await test('F030 conversion requires an accessible sales order for the same recipient organization',async()=>{orderId=await makeOrder();await assert.rejects(samples.actSample(sales,{id:sampleId,version:sampleVersion,action:'CONVERT',feedback:'',outcome:null,salesOrderId:randomUUID(),reason:'QA reject unknown conversion',idempotencyKey:randomUUID()}),/NOT_FOUND/);const converted=await samples.actSample(sales,{id:sampleId,version:sampleVersion,action:'CONVERT',feedback:'',outcome:null,salesOrderId:orderId,reason:'QA verified sample conversion',idempotencyKey:randomUUID()}) as {status:string;salesOrderId:string};assert.equal(converted.status,'CONVERTED');assert.equal(converted.salesOrderId,orderId);});
  await test('F030 allocations and progress events are append-only',async()=>{const allocation=(await db.query<{id:string}>('SELECT id FROM cohamy_crm.sample_allocations LIMIT 1')).rows[0],sampleEvent=(await db.query<{id:string}>('SELECT id FROM cohamy_crm.sample_events WHERE issue_id=$1 LIMIT 1',[sampleId])).rows[0];await assert.rejects(db.query('DELETE FROM cohamy_crm.sample_allocations WHERE id=$1',[allocation.id]));await assert.rejects(db.query('UPDATE cohamy_crm.sample_events SET reason=$1 WHERE id=$2',['tampered',sampleEvent.id]));});
  await test('F030 reversing a sample issue restores stock and closes the sample with an immutable event',async()=>{const created=await samples.createSample(sales,{organizationId:ids.dealerA,warehouseId,recipientName:'QA reversed sample',recipientPhone:'',purpose:'QA reversal integrity',lines:[{productId,quantity:'1'}],reason:'QA reversal sample request',idempotencyKey:randomUUID()}) as {id:string;version:number},issued=await samples.issueSample(warehouseUser,{id:created.id,version:created.version,minimumShelfLifeDays:0,reason:'QA reversal sample issue',idempotencyKey:randomUUID()}) as {inventoryDocumentId:string},before=(await inventory.listInventory(admin)).reduce((sum,row)=>sum+Number(row.on_hand),0),input={id:issued.inventoryDocumentId,reason:'QA correct erroneous sample issue',idempotencyKey:randomUUID()},reversed=await inventory.reverseDocument(admin,input);assert.deepEqual(await inventory.reverseDocument(admin,input),reversed);const after=(await inventory.listInventory(admin)).reduce((sum,row)=>sum+Number(row.on_hand),0),head=(await db.query<{status:string}>('SELECT status FROM cohamy_crm.sample_issues WHERE id=$1',[created.id])).rows[0],event=(await db.query<{action:string}>('SELECT action FROM cohamy_crm.sample_events WHERE issue_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1',[created.id])).rows[0];assert.equal(after,before+1);assert.equal(head.status,'CLOSED');assert.equal(event.action,'ISSUE_REVERSED');await assert.rejects(db.query('DELETE FROM cohamy_crm.sample_events WHERE issue_id=$1 AND action=\'ISSUE_REVERSED\'',[created.id]));});
  }finally{await fs.mkdir('docs/crm/test-results',{recursive:true});await fs.writeFile('docs/crm/test-results/samples-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated fictitious PGlite; no real stock/order/provider mutation',status:cases.length===8&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',references:{sampleId,orderId,warehouseId},cases},null,2));await close();await owner.close();}
}
main().catch(error=>{console.error(error instanceof Error?error.stack??error.message:'SAMPLE_QA_FAILED');process.exitCode=1;});
