import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
process.env.CRM_DATABASE_MODE="pglite";process.env.CRM_ENVIRONMENT="LOCAL";process.env.CRM_LOCAL_DATA_DIR=`.local/crm-qa-access-${randomUUID()}`;
async function main() {
  const {createQaFixture,qaPassword}=await import("./qa-fixture");
  const {database}=await import("../../lib/crm/db");
  const {login,authenticate,logout,digest}=await import("../../lib/crm/auth");
  const repo=await import("../../lib/crm/repository");
  const {assertPermission}=await import("../../lib/crm/permissions");
  const {migrate,importWebsiteCatalog}=await import("../../lib/crm/bootstrap");
  const {createWebsiteOrder,listWebsiteOrders}=await import("../../lib/crm/website-orders");
  const cases:{name:string;status:string}[]=[];
  async function test(name:string,run:()=>Promise<void>) {try{await run();cases.push({name,status:"PASS"});console.log(`PASS ${name}`);}catch(error){cases.push({name,status:"FAIL"});throw error;}}
  const ids=await createQaFixture();const db=await database();
  try {
    await test("migration retry and catalog import are idempotent",async()=>{await migrate();assert.equal(await importWebsiteCatalog(),0);const count=await db.query<{total:string}>("SELECT count(*)::text AS total FROM cohamy_crm.products");assert.equal(count.rows[0].total,"10");});
    const admin=await login("admin@crm-qa.invalid",qaPassword);const dealerA=await login("a@crm-qa.invalid",qaPassword);const sales=await login("sales@crm-qa.invalid",qaPassword);const warehouse=await login("warehouse@crm-qa.invalid",qaPassword);const accountant=await login("accountant@crm-qa.invalid",qaPassword);
    await test("opaque session authenticates persisted database user",async()=>{assert.equal((await authenticate(admin.token))?.role,"ADMIN");const session=await db.query<{token_hash:string}>("SELECT token_hash FROM cohamy_crm.sessions WHERE membership_id=$1",[admin.user.membershipId]);assert.equal(session.rows[0].token_hash,digest(admin.token));assert.notEqual(session.rows[0].token_hash,admin.token);});
    await test("wrong/unknown credentials rejected",async()=>{await assert.rejects(login("a@crm-qa.invalid","wrong"),/INVALID_CREDENTIALS/);await assert.rejects(login("nobody@crm-qa.invalid","wrong"),/INVALID_CREDENTIALS/);});
    await test("dealer A cannot fetch or mutate dealer B",async()=>{await assert.rejects(repo.getOrganization(dealerA.user,ids.dealerB),/NOT_FOUND/);const list=await repo.listOrganizations(dealerA.user);assert.deepEqual(list.items.map(item=>item.id),[ids.dealerA]);await assert.rejects(repo.updateOrganization(dealerA.user,ids.dealerB,{}),/FORBIDDEN/);});
    await test("dealer cannot create account, confirm money or raise limit",async()=>{assert.throws(()=>assertPermission(dealerA.user,"accounts.manage"),/FORBIDDEN/);assert.throws(()=>assertPermission(dealerA.user,"finance.confirm"),/FORBIDDEN/);assert.throws(()=>assertPermission(dealerA.user,"credit.write"),/FORBIDDEN/);});
    await test("warehouse ownership and assigned scope isolate A/B",async()=>{assert.deepEqual((await repo.listWarehouses(dealerA.user)).map(item=>item.id),[ids.warehouseA]);assert.deepEqual((await repo.listWarehouses(warehouse.user)).map(item=>item.id),[ids.warehouseA]);await assert.rejects(repo.createWarehouse(dealerA.user,{code:"ESCAPE",name:"Bad",organizationId:ids.dealerB}),/FORBIDDEN/);});
    await test("sales sees only assigned partners",async()=>{assert.deepEqual((await repo.listOrganizations(sales.user)).items.map(item=>item.id),[ids.dealerA]);await assert.rejects(repo.getOrganization(sales.user,ids.dealerB),/NOT_FOUND/);});
    await test("create, edit, version conflict and unique constraint",async()=>{const created=await repo.createOrganization(admin.user,{code:"QA_NEW",name:"LOCAL QA New",kind:"DEALER"});const org=await repo.getOrganization(admin.user,created.id);const input={code:org.code,name:"LOCAL QA Updated",kind:org.kind,phone:org.phone,email:org.email,address:org.address,active:true,version:org.version};await repo.updateOrganization(admin.user,org.id,input);await assert.rejects(repo.updateOrganization(admin.user,org.id,input),/VERSION_CONFLICT/);await assert.rejects(repo.createOrganization(admin.user,{code:"QA_NEW",name:"Duplicate",kind:"DEALER"}));});
    await test("creation options preserve central organization beyond pagination and deny dealer enumeration",async()=>{for(let i=0;i<21;i++)await repo.createOrganization(admin.user,{code:"QA_PAGE_"+i,name:"LOCAL QA Page "+i,kind:"DEALER"});const choices=await repo.listOrganizationOptions(admin.user);assert.equal(choices[0].kind,"COHAMY");assert.ok(choices.some(item=>item.id===ids.dealerA));await assert.rejects(repo.listOrganizationOptions(dealerA.user),/FORBIDDEN/);});
    await test("browser role/credit fields are not trusted",async()=>{await assert.rejects(repo.createOrganization(sales.user,{code:"QA_BAD",name:"Bad",kind:"DEALER",role:"ADMIN",creditLimit:999999}),/INVALID_FIELDS/);});
    await test("account lock revokes existing access immediately",async()=>{await repo.setAccountActive(admin.user,ids.membershipA,{active:false});assert.equal(await authenticate(dealerA.token),null);await repo.setAccountActive(admin.user,ids.membershipA,{active:true});assert.equal((await authenticate(dealerA.token))?.organizationId,ids.dealerA);});
    await test("expired and logged-out sessions denied",async()=>{await db.query("UPDATE cohamy_crm.sessions SET expires_at=now()-interval '1 second' WHERE token_hash=$1",[digest(sales.token)]);assert.equal(await authenticate(sales.token),null);await logout(accountant.token);assert.equal(await authenticate(accountant.token),null);});
    await test("transaction rollback leaves no partial business record",async()=>{const id=randomUUID();await assert.rejects(db.transaction(async tx=>{await tx.query("INSERT INTO cohamy_crm.organizations(id,code,name,kind) VALUES ($1,'QA_ROLLBACK','rollback','DEALER')",[id]);throw new Error("EXPECTED_ROLLBACK");}));assert.equal((await db.query("SELECT id FROM cohamy_crm.organizations WHERE id=$1",[id])).rows.length,0);});
    await test("audit is append-only",async()=>{await assert.rejects(db.query("UPDATE cohamy_crm.audit_events SET action='tampered'"),/AUDIT_APPEND_ONLY/);await assert.rejects(db.query("DELETE FROM cohamy_crm.audit_events"),/AUDIT_APPEND_ONLY/);});
    await test("account role cannot cross organization kind",async()=>{await assert.rejects(repo.createAccount(admin.user,{email:"escape@crm-qa.invalid",displayName:"Bad",password:qaPassword,role:"ADMIN",organizationId:ids.dealerA}),/ROLE_ORGANIZATION_MISMATCH/);});
    await test("login throttling uses persistent atomic counter",async()=>{for(let i=0;i<8;i++)await assert.rejects(login("limited@crm-qa.invalid","wrong"),/INVALID_CREDENTIALS/);await assert.rejects(login("limited@crm-qa.invalid","wrong"),/LOGIN_RATE_LIMITED/);});
    await test("dealer table response exposes no password/session data",async()=>{const data=JSON.stringify(await repo.listOrganizations(dealerA.user));assert.ok(!data.includes("password_hash")&&!data.includes("token_hash")&&!data.includes(ids.dealerB));});
    const order={idempotencyKey:randomUUID(),locale:"vi",payment:"bank",contact:{fullName:"LOCAL QA Buyer",email:"buyer@crm-qa.invalid",phone:"0900000000",address:"LOCAL QA Test Address",city:"LOCAL QA City",district:"",ward:"",note:""},items:[{productId:"cohamy-almond-chocolate",quantity:2}]};
    await test("intake disabled until explicitly configured",async()=>{process.env.CRM_WEBSITE_ORDER_INTAKE="false";await assert.rejects(createWebsiteOrder(order),/ORDER_INTAKE_NOT_ENABLED/);process.env.CRM_WEBSITE_ORDER_INTAKE="true";});
    await test("website order saved once under parallel retry, unpaid with no posting",async()=>{const [first,second]=await Promise.all([createWebsiteOrder(order),createWebsiteOrder(order)]);assert.equal(first.code,second.code);assert.equal(first.paid,false);assert.equal(first.status,"PENDING_REVIEW");assert.equal(first.shippingQuotePending,true);assert.equal((await db.query("SELECT id FROM cohamy_crm.website_orders")).rows.length,1);});
    await test("changed request cannot reuse key; client price injection rejected",async()=>{await assert.rejects(createWebsiteOrder({...order,items:[{productId:"cohamy-almond-chocolate",quantity:3}]}),/IDEMPOTENCY_CONFLICT/);await assert.rejects(createWebsiteOrder({...order,items:[{productId:"cohamy-almond-chocolate",quantity:2,price:1}]}),/INVALID_FIELDS/);});
    await test("unassigned website orders hidden from dealers and sales",async()=>{assert.equal((await listWebsiteOrders(admin.user)).length,1);assert.equal((await listWebsiteOrders(dealerA.user)).length,0);assert.equal((await listWebsiteOrders(sales.user)).length,0);});
  } finally {
    await fs.mkdir("docs/crm/test-results",{recursive:true});await fs.writeFile("docs/crm/test-results/access-local.json",JSON.stringify({environment:"LOCAL",engine:"PGlite (PostgreSQL WASM, single exclusive connection)",fixture:"separate .local/crm-qa-* directory; fictitious .invalid users",testedAt:new Date().toISOString(),cases,standalonePostgres:"NOT RUN",stockFinance:"NOT RUN"},null,2)+"\n");
    await db.close();
  }
  console.log(`${cases.length} passed. No proof of standalone PostgreSQL concurrency or financial workflows.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
