import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {calculatePrice,priceDefinitionSchema,basketSchema,type PriceDefinition,type PriceProduct} from '../../lib/crm/pricing-model';
const products:PriceProduct[]=['QA_A','QA_B','QA_GIFT'].map((sku,i)=>({id:'qa-'+i,sku,name:sku,stockUnit:'Gói',version:3,units:[{code:'BASE',label:'Gói',numerator:'1',denominator:'1',isCase:false,allowFractional:true,version:2},{code:'CASE',label:'Thùng 12 gói',numerator:'12',denominator:'1',isCase:true,allowFractional:false,version:4}]}));
const definition:PriceDefinition={audience:'ALL',tierId:null,organizationId:null,priority:10,startsAt:'2026-09-01T00:00:00+07:00',endsAt:null,quantityBasis:'SKU',rounding:'HALF_UP',taxBasis:'ORDER',taxBasisPoints:800,feeAmount:'1000',maxSalesDiscountBasisPoints:1000,minimum:{amount:'0',cases:0,skus:[]},deliveryTerms:'QA: giao theo thỏa thuận, không phải chính sách thật',quoteValidityHours:72,approval:{nonSelfApproval:true,orderAmountThreshold:null,creditTerms:true},lines:[{sku:'QA_A',unitPrice:'1000',thresholds:[{minBaseQuantity:'12',unitPrice:'900'},{minBaseQuantity:'24',unitPrice:'800'}]},{sku:'QA_B',unitPrice:'2000',thresholds:[]}],gifts:[]};
const basket=(lines:{sku:string;unitCode:string;quantity:string;requestedUnitPrice?:string}[],discountBasisPoints=0,creditTerms=false)=>basketSchema.parse({lines,discountBasisPoints,creditTerms});
const cases:{name:string;status:string}[]=[];
const test=(name:string,run:()=>void)=>{try{run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
async function main(){try{
 test('F033 threshold boundaries apply after exact CASE conversion and split SKU aggregation',()=>{for(const [quantity,price]of [['11.999999','1000'],['12','900'],['23.999999','900'],['24','800']])assert.equal(calculatePrice(definition,basket([{sku:'QA_A',unitCode:'BASE',quantity}]),products).lines[0].unitPrice,price);const r=calculatePrice(definition,basket([{sku:'QA_A',unitCode:'CASE',quantity:'1'},{sku:'QA_A',unitCode:'BASE',quantity:'12'}]),products);assert.deepEqual(r.lines.map(l=>l.unitPrice),['800','800']);assert.equal(r.subtotal,'19200');assert.equal(r.caseCount,'2');});
 test('F033 LINE/SKU/ORDER are distinct; mixed stock units cannot aggregate ORDER thresholds',()=>{const b=basket([{sku:'QA_A',unitCode:'BASE',quantity:'6'},{sku:'QA_A',unitCode:'BASE',quantity:'6'},{sku:'QA_B',unitCode:'BASE',quantity:'12'}]);assert.deepEqual(calculatePrice({...definition,quantityBasis:'LINE'},b,products).lines.map(l=>l.unitPrice),['1000','1000','2000']);assert.deepEqual(calculatePrice(definition,b,products).lines.map(l=>l.unitPrice),['900','900','2000']);assert.deepEqual(calculatePrice({...definition,quantityBasis:'ORDER'},b,products).lines.map(l=>l.unitPrice),['800','800','2000']);assert.throws(()=>calculatePrice({...definition,quantityBasis:'ORDER'},b,products.map(p=>p.sku==='QA_B'?{...p,stockUnit:'Kg'}:p)),/POLICY_UNIT_MISMATCH/);});
 test('Exact totals beyond Number safety preserve discounted tax and fees without floating point',()=>{const r=calculatePrice({...definition,lines:[{sku:'QA_A',unitPrice:'90071992547409930001',thresholds:[]}]},basket([{sku:'QA_A',unitCode:'BASE',quantity:'2'}],1000),products);assert.equal(r.subtotal,'180143985094819860002');assert.equal(r.discount,'18014398509481986000');assert.equal(r.tax,'12970366926827029920');assert.equal(r.total,'175099953512164904922');});
 test('LINE/ORDER tax rounding differs deliberately while each allocation reconciles exactly',()=>{const d={...definition,feeAmount:'0',taxBasisPoints:5000,lines:[{sku:'QA_A',unitPrice:'1',thresholds:[]}]};const b=basket([{sku:'QA_A',unitCode:'BASE',quantity:'1'},{sku:'QA_A',unitCode:'BASE',quantity:'1'}]);assert.equal(calculatePrice({...d,taxBasis:'LINE'},b,products).tax,'2');const r=calculatePrice(d,b,products);assert.equal(r.tax,'1');assert.deepEqual(r.lines.map(l=>l.tax),['1','0']);assert.equal(r.lines.reduce((a,l)=>a+BigInt(l.total),0n).toString(),r.total);});
 test('F034 minimum checks use paid net merchandise, whole converted cases and paid SKU only',()=>{const r=calculatePrice({...definition,minimum:{amount:'30000',cases:3,skus:[{sku:'QA_B',minBaseQuantity:'5'}]}},basket([{sku:'QA_A',unitCode:'CASE',quantity:'2'}],1000),products);assert.deepEqual(r.minimumShortfalls,[{kind:'AMOUNT',missing:'12720'},{kind:'CASES',missing:'1'},{kind:'SKU',sku:'QA_B',missing:'5'}]);});
 test('F038 server explains price override, discount threshold, credit and inclusive amount approval',()=>{const r=calculatePrice({...definition,approval:{...definition.approval,orderAmountThreshold:'0'}},basket([{sku:'QA_A',unitCode:'BASE',quantity:'1',requestedUnitPrice:'500'}],1001,true),products);assert.deepEqual(r.approvalReasons,['SPECIAL_PRICE','DISCOUNT','CREDIT_TERMS','AMOUNT']);assert.equal(r.approvalRequired,true);assert.equal(calculatePrice(definition,basket([{sku:'QA_A',unitCode:'BASE',quantity:'1',requestedUnitPrice:'01000'}],1000),products).approvalRequired,false);});
 test('F039 AND combo conditions require all paid SKUs; free gifts never trigger further gifts',()=>{const gift={name:'QA combo',group:'qa',priority:1,stacking:'STACK' as const,repeat:'PER_THRESHOLD' as const,conditions:[{sku:'QA_A',minBaseQuantity:'12'},{sku:'QA_B',minBaseQuantity:'2'}],giftSku:'QA_GIFT',giftBaseQuantity:'3'};const d={...definition,gifts:[gift,{...gift,name:'QA no gift cascade',group:'other',conditions:[{sku:'QA_GIFT',minBaseQuantity:'1'}]}]};assert.equal(calculatePrice(d,basket([{sku:'QA_A',unitCode:'CASE',quantity:'2'}]),products).lines.filter(l=>l.gift).length,0);const r=calculatePrice(d,basket([{sku:'QA_A',unitCode:'CASE',quantity:'2'},{sku:'QA_B',unitCode:'BASE',quantity:'5'}]),products);assert.equal(r.lines.filter(l=>l.gift).length,1);const g=r.lines.at(-1)!;assert.equal(g.baseQuantity,'6');assert.equal(g.total,'0');assert.equal(g.productVersion,3);assert.equal(g.unitVersion,2);assert.throws(()=>calculatePrice({...d,gifts:[{...gift,giftBaseQuantity:'0.5',repeat:'ONCE'}]},basket([{sku:'QA_A',unitCode:'CASE',quantity:'2'},{sku:'QA_B',unitCode:'BASE',quantity:'5'}]),products.map(p=>p.sku==='QA_GIFT'?{...p,units:p.units.map(u=>({...u,allowFractional:false}))}:p)),/INVALID_GIFT_QUANTITY/);});
 test('F039 exclusive highest priority and stacking groups are deterministic with ONCE/PER_THRESHOLD',()=>{const g={name:'QA low',group:'qa',priority:1,stacking:'EXCLUSIVE' as const,repeat:'ONCE' as const,conditions:[{sku:'QA_A',minBaseQuantity:'12'}],giftSku:'QA_GIFT',giftBaseQuantity:'1'};const d={...definition,gifts:[g,{...g,name:'QA high',priority:10},{...g,name:'QA stack1',group:'stack',stacking:'STACK' as const},{...g,name:'QA stack2',group:'stack',stacking:'STACK' as const,repeat:'PER_THRESHOLD' as const}]};const r=calculatePrice(priceDefinitionSchema.parse(d),basket([{sku:'QA_A',unitCode:'CASE',quantity:'2'}]),products);assert.deepEqual(r.lines.filter(l=>l.gift).map(l=>[l.giftRule,l.baseQuantity]),[['QA high','1'],['QA stack1','1'],['QA stack2','2']]);});
 test('Unconfigured SKU/unit, fractional whole units and impossible quantity ratios fail explicitly',()=>{assert.throws(()=>calculatePrice(definition,basket([{sku:'QA_MISSING',unitCode:'BASE',quantity:'1'}]),products),/SKU_UNCONFIGURED/);assert.throws(()=>calculatePrice(definition,basket([{sku:'QA_A',unitCode:'MISSING',quantity:'1'}]),products),/UNIT_UNCONFIGURED/);assert.throws(()=>calculatePrice(definition,basket([{sku:'QA_A',unitCode:'CASE',quantity:'0.5'}]),products),/INVALID_QUANTITY/);const p=products.map(p=>({...p,units:[{...p.units[0],numerator:'1',denominator:'3'}]}));assert.throws(()=>calculatePrice(definition,basket([{sku:'QA_A',unitCode:'BASE',quantity:'1'}]),p),/UNIT_PRECISION/);});
 test('Policy rejects unknown fields, mismatched audiences, overlapping threshold order and gift ambiguity',()=>{assert.throws(()=>priceDefinitionSchema.parse({...definition,untrusted:true}));assert.throws(()=>priceDefinitionSchema.parse({...definition,audience:'TIER'}));assert.throws(()=>priceDefinitionSchema.parse({...definition,endsAt:definition.startsAt}));assert.throws(()=>priceDefinitionSchema.parse({...definition,lines:[{...definition.lines[0],thresholds:[{minBaseQuantity:'12',unitPrice:'1'},{minBaseQuantity:'11',unitPrice:'2'}]}]}));const g={name:'QA',group:'qa',priority:1,stacking:'EXCLUSIVE',repeat:'ONCE',conditions:[{sku:'QA_A',minBaseQuantity:'1'}],giftSku:'QA_GIFT',giftBaseQuantity:'1'};assert.throws(()=>priceDefinitionSchema.parse({...definition,gifts:[g,{...g,name:'QA duplicate priority'}]}));});
 }finally{await fs.mkdir('docs/crm/test-results',{recursive:true});await fs.writeFile('docs/crm/test-results/pricing-model-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL pure exact price model; fictitious rates only, no production policy or posting',status:cases.length===10&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));}}
main().catch(e=>{console.error(e instanceof Error?e.message:'PRICE_MODEL_QA_FAILED');process.exitCode=1;});
