import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-portal-'+randomUUID();
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture');const {database}=await import('../../lib/crm/db');const {login}=await import('../../lib/crm/auth');const p=await import('../../lib/crm/portal-services');const w=await import('../../lib/crm/workspace');const work=await import('../../lib/crm/work');const repo=await import('../../lib/crm/repository');const o=await import('../../lib/crm/onboarding');const ids=await createQaFixture(),db=await database(),cases:{name:string;status:string}[]=[];const test=async(name:string,fn:()=>Promise<void>)=>{try{await fn();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 try{const admin=(await login('admin@crm-qa.invalid',qaPassword)).user,a=(await login('a@crm-qa.invalid',qaPassword)).user,b=(await login('b@crm-qa.invalid',qaPassword)).user;await repo.createAccount(admin,{email:'staff@crm-qa.invalid',password:qaPassword,displayName:'LOCAL QA Staff',organizationId:ids.dealerA,role:'DEALER_STAFF'});const staff=(await login('staff@crm-qa.invalid',qaPassword)).user;
 await test('F014 carts persist per account, conflict on stale device and cannot inject organization/price',async()=>{const product=(await repo.listCatalog(admin))[0];await work.updateCatalogItem(admin,product.id,{version:1,sku:'QA-PORTAL-01',name:product.name,stockUnit:'Gói',unitsPerCase:24,active:true});await p.saveCart(a,{version:0,lines:[{sku:'QA-PORTAL-01',unit:'Gói',quantity:3}]});assert.equal((await p.cart(a)).lines[0].quantity,3);assert.equal((await p.cart(staff)).lines.length,0);assert.equal((await p.cart(b)).lines.length,0);await assert.rejects(p.saveCart(a,{version:0,lines:[]}),/VERSION_CONFLICT/);await assert.rejects(p.saveCart(a,{version:1,organizationId:ids.dealerB,lines:[]}),/INVALID_FIELDS/);await assert.rejects(p.saveCart(a,{version:1,lines:[{sku:'QA-PORTAL-01',unit:'Thùng',quantity:1}]}),/SKU_UNIT_INVALID/);});
 await test('F016 address defaults, history and owner/staff boundaries persist',async()=>{const d=await p.saveAddress(a,{version:0,label:'LOCAL QA First',recipient:'LOCAL QA Receiver',phone:'0901122334',address:'LOCAL QA First address',isDefault:true,active:true});await p.saveAddress(a,{version:0,label:'LOCAL QA Second',recipient:'LOCAL QA Receiver',phone:'0901122334',address:'LOCAL QA Second address',isDefault:true,active:true});const rows=await p.addresses(staff);assert.equal(rows.filter(x=>x.is_default).length,1);assert.equal((await p.addresses(b)).length,0);await assert.rejects(p.saveAddress(staff,{version:0,label:'bad',recipient:'Bad',phone:'0901122334',address:'bad address',isDefault:false,active:true}),/FORBIDDEN/);await assert.rejects(p.saveAddress(b,{id:d.id,version:1,label:'bad',recipient:'Bad',phone:'0901122334',address:'bad address',isDefault:false,active:true}),/VERSION_CONFLICT/);});
 let ticketId='';await test('F020 support retry creates one ticket, A/B reads are isolated and internal messages remain private',async()=>{const input={title:'LOCAL QA Support',body:'LOCAL QA issue description',idempotencyKey:randomUUID()};const t=await p.createTicket(a,input);ticketId=t.id;assert.equal((await p.createTicket(a,input)).id,t.id);await assert.rejects(p.createTicket(a,{...input,body:'changed description'}),/IDEMPOTENCY_CONFLICT/);await p.replyTicket(admin,{id:t.id,body:'LOCAL QA internal secret',internal:true,idempotencyKey:randomUUID()});await p.replyTicket(admin,{id:t.id,body:'LOCAL QA public reply',internal:false,idempotencyKey:randomUUID()});assert.ok(!(await p.ticketMessages(a,t.id)).some(m=>m.internal));assert.equal((await p.ticketMessages(admin,t.id)).length,3);await assert.rejects(p.getTicket(b,t.id),/NOT_FOUND/);await assert.rejects(p.replyTicket(a,{id:t.id,body:'internal injection',internal:true,idempotencyKey:randomUUID()}),/FORBIDDEN/);await p.updateTicket(admin,{id:t.id,version:1,status:'WAITING_PARTNER'});assert.equal((await p.getTicket(a,t.id)).status,'WAITING_PARTNER');await assert.rejects(p.updateTicket(admin,{id:t.id,version:1,status:'RESOLVED'}),/VERSION_CONFLICT/);});
  await test('F020/F133 ticket attachments and notification content enforce source scope',async()=>{const f=await w.uploadDocument(a,{entityType:'ticket',entityId:ticketId,title:'LOCAL QA Photo',filename:'proof.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA proof')});assert.ok((await w.downloadDocument(staff,f.versionId)).content.length);await assert.rejects(w.downloadDocument(b,f.versionId),/NOT_FOUND/);assert.ok((await w.notifications(a)).some(n=>n.entity_type==='ticket'));const own=await w.uploadDocument(a,{entityType:'partner',entityId:ids.dealerA,title:'LOCAL QA business proof',filename:'business-proof.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA')});assert.ok((await w.downloadDocument(a,own.versionId)).content.length);await assert.rejects(w.uploadDocument(b,{entityType:'partner',entityId:ids.dealerA,title:'cross dealer',filename:'bad.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nLOCAL QA')}),/FORBIDDEN/);});
 await test('F017 owner invitation cannot grant internal role or another dealer organization',async()=>{const i=await o.createInvitation(a,{organizationId:ids.dealerA,role:'DEALER_STAFF',maxUses:1,expiresAt:'2030-01-01T00:00:00Z'});assert.ok(i.token);await assert.rejects(o.createInvitation(staff,{organizationId:ids.dealerA,role:'DEALER_STAFF',maxUses:1,expiresAt:'2030-01-01T00:00:00Z'}),/FORBIDDEN/);await assert.rejects(o.createInvitation(a,{organizationId:ids.dealerB,role:'DEALER_STAFF',maxUses:1,expiresAt:'2030-01-01T00:00:00Z'}),/FORBIDDEN/);});
 }finally{await fs.writeFile('docs/crm/test-results/portal-services-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated fictitious PGlite',cases,integrationCoverage:{commercialCheckout:'COVERED_BY test:crm:commercial-orders'},postgres:'NOT_RUN_IN_THIS_LOCAL_SUITE'},null,2));await db.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
