import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import type {OrderPolicyDefinition} from '../../lib/crm/order-policy';
const postgres=process.env.CRM_DATABASE_MODE==='postgres';
if(!postgres){process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-commercial-orders-'+randomUUID();}
async function main(){
 const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),auth=await import('../../lib/crm/auth'),repo=await import('../../lib/crm/repository'),prices=await import('../../lib/crm/pricing'),fixture=await import('./pricing-fixture'),policy=await import('../../lib/crm/order-policy'),requests=await import('../../lib/crm/order-requests'),orders=await import('../../lib/crm/sales-orders'),quotes=await import('../../lib/crm/quotations'),{installQaRuntime}=await import('./qa-runtime'),{commercialDigest}=await import('../../lib/crm/commercial-common');
 const ids=await createQaFixture(),owner=await database(),admin=(await auth.login('admin@crm-qa.invalid',qaPassword)).user,sales=(await auth.login('sales@crm-qa.invalid',qaPassword)).user,a=(await auth.login('a@crm-qa.invalid',qaPassword)).user,b=(await auth.login('b@crm-qa.invalid',qaPassword)).user,accountant=(await auth.login('accountant@crm-qa.invalid',qaPassword)).user;
 await repo.createAccount(admin,{email:'staff-order@crm-qa.invalid',displayName:'QA order staff',password:qaPassword,role:'DEALER_STAFF',organizationId:ids.dealerA});await repo.createAccount(admin,{email:'manager-order@crm-qa.invalid',displayName:'QA order manager',password:qaPassword,role:'MANAGER',organizationId:admin.organizationId});
 const staff=(await auth.login('staff-order@crm-qa.invalid',qaPassword)).user,manager=(await auth.login('manager-order@crm-qa.invalid',qaPassword)).user,close=await installQaRuntime(owner),db=await database(),cases:{name:string;status:string}[]=[];
 const definition:OrderPolicyDefinition={enabled:true,requireOwnerApproval:true,alwaysManagerApproval:false,managerApprovalAmount:null,creditRequiresApproval:true,nonSelfApproval:true,acceptedQuotePrice:'UNTIL_QUOTE_EXPIRY',pendingPrice:'UNTIL_REQUEST_EXPIRY',requiredPartnerFields:[],approvalRoles:['ADMIN','MANAGER'],confirmationRoles:['ADMIN','MANAGER','SALES']};
 const base={version:0,organizationId:ids.dealerA,channel:'PORTAL' as const,basket:fixture.qaBasket,delivery:{recipient:'QA Nguyễn Thị Ánh Đào',phone:'0900000123',address:'QA original confirmed address'},note:'QA fictitious commercial order',idempotencyKey:randomUUID()};
 const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 const save=(user= a,extra:Record<string,unknown>={})=>requests.saveCommercialRequest(user,{...base,...extra,idempotencyKey:randomUUID()});
 const propose=async(user:typeof a,id:string,action='PROPOSE')=>{const head=await requests.commercialRequestAccess(db,user,id);return requests.requestAction(user,{id,version:head.version,versionId:head.latest_version_id,action,reason:'QA '+action,idempotencyKey:randomUUID()});};
 const submit=async(user:typeof a,id:string)=>{const h=await requests.commercialRequestAccess(db,user,id);return orders.submitSalesRequest(user,{id,version:h.version,versionId:h.latest_version_id,reason:'QA request submitted',idempotencyKey:randomUUID()}) as Promise<{id:string;version:number;versionId:string}>;};
 const action=async(user:typeof a,id:string,verb:string)=>{const h=await orders.salesOrderAccess(db,user,id);return orders.salesOrderAction(user,{id,version:h.version,versionId:h.latest_version_id,action:verb,reason:'QA '+verb,idempotencyKey:randomUUID()});};
 let published:{id:string;version:number;versionId:string},staffRequest='',firstOrder='',confirmedSnapshot='',requestForPrice='',policyVersion=0;
 try{
  await test('F041 no approved active order policy blocks proposal/submission; only manager configures immutable versioned policy',async()=>{
   await fixture.createPriceProducts(admin);published=await prices.savePriceBook(admin,{version:0,name:'QA fictitious order price',definition:fixture.qaPriceDefinition,idempotencyKey:randomUUID()});await prices.publishPriceBook(admin,{id:published.id,version:published.version,versionId:published.versionId,action:'PUBLISH',reason:'QA published source',idempotencyKey:randomUUID()});
   const r=await save();await assert.rejects(propose(a,r.id),/ORDER_POLICY_UNAVAILABLE/);await assert.rejects(policy.saveOrderPolicy(accountant,{}),/FORBIDDEN/);await assert.rejects(policy.saveOrderPolicy(staff,{}),/FORBIDDEN/);
   const request={version:0,definition,reason:'QA explicitly fictitious approval rules',idempotencyKey:randomUUID()},p=await policy.saveOrderPolicy(admin,request);assert.deepEqual(await policy.saveOrderPolicy(admin,request),p);policyVersion=p.version;await assert.rejects(policy.saveOrderPolicy(admin,{...request,reason:'QA altered retry'}),/IDEMPOTENCY_CONFLICT/);await assert.rejects(db.query('DELETE FROM cohamy_crm.order_policies'),postgres?/permission denied/:/AUDIT_APPEND_ONLY/);
  });
  await test('F012/F018 staff SKU proposal stays private until owner approval and explicit submission; no order from proposal',async()=>{
   const r=await save(staff);staffRequest=r.id;await propose(staff,r.id);assert.equal((await requests.commercialRequestAccess(db,staff,r.id)).status,'PENDING_OWNER');assert.equal((await requests.listCommercialRequests(admin)).some(x=>x.id===r.id),false);await assert.rejects(requests.commercialRequestAccess(db,admin,r.id),/NOT_FOUND/);await assert.rejects(submit(staff,r.id),/REQUEST_NOT_READY/);await assert.rejects(propose(staff,r.id,'OWNER_APPROVE'),/FORBIDDEN/);await assert.rejects(requests.commercialRequestAccess(db,b,r.id),/NOT_FOUND/);assert.equal((await orders.listSalesOrders(a)).length,0);
  });
  await test('F018 owner approves exact request version; edits invalidate approval and force fresh proposal',async()=>{
   await propose(a,staffRequest,'OWNER_APPROVE');const head=await requests.commercialRequestAccess(db,staff,staffRequest);assert.equal(head.owner_approved_version_id,head.latest_version_id);
   const r=await requests.saveCommercialRequest(staff,{...base,id:head.id,version:head.version,note:'QA changed before submission',idempotencyKey:randomUUID()});assert.equal((await requests.commercialRequestAccess(db,staff,r.id)).owner_approved_version_id,null);await assert.rejects(submit(staff,r.id),/REQUEST_NOT_READY/);await propose(staff,r.id);await propose(a,r.id,'OWNER_APPROVE');
   const h=await requests.commercialRequestAccess(db,staff,r.id),request={id:h.id,version:h.version,versionId:h.latest_version_id,reason:'QA approved source received',idempotencyKey:randomUUID()},o=await orders.submitSalesRequest(staff,request) as {id:string;version:number;versionId:string};firstOrder=o.id;assert.deepEqual(await orders.submitSalesRequest(staff,request),o);assert.equal((await requests.listCommercialRequests(admin)).some(x=>x.id===r.id),true);await assert.rejects(submit(staff,r.id),/REQUEST_ALREADY_SUBMITTED/);
  });
  await test('F040/F044 confirmation freezes price/unit/policy/address source while delivery/payment remain independent and unposted',async()=>{
   await action(sales,firstOrder,'CONFIRM');const head=await orders.salesOrderAccess(db,a,firstOrder),v=await orders.salesVersionAccess(db,head,head.confirmed_version_id!);assert.equal(head.status,'CONFIRMED');assert.equal(head.delivery_status,'NOT_STARTED');assert.equal(head.payment_status,'UNBILLED');assert.equal(v.snapshot.quote.calculation.subtotal,'19200');assert.equal(v.snapshot.quote.calculation.lines[0].baseQuantity,'24');assert.equal(v.snapshot.quote.delivery.address,base.delivery.address);confirmedSnapshot=JSON.stringify(v.snapshot);await assert.rejects(db.query('UPDATE cohamy_crm.sales_order_versions SET checksum=$1 WHERE id=$2',['qa',v.id]),postgres?/permission denied/:/AUDIT_APPEND_ONLY/);await assert.rejects(orders.salesOrderAccess(db,b,firstOrder),/NOT_FOUND/);assert.equal('definition' in (await orders.salesOrderVersions(a,firstOrder))[0].snapshot.orderPolicy,false);assert.equal((await orders.salesOrderVersions(a,firstOrder))[0].snapshot.quote.policy,undefined);
  });
  await test('F043/F045 exact exception routes require another named approver; Sales/dealer cannot bypass and internal approval reason stays private',async()=>{
   const r=await save(sales,{channel:'PHONE',basket:{...fixture.qaBasket,discountBasisPoints:2000}});await propose(sales,r.id);const o=await submit(sales,r.id);await assert.rejects(action(sales,o.id,'CONFIRM'),/ORDER_APPROVAL_REQUIRED/);await assert.rejects(action(sales,o.id,'APPROVE'),/FORBIDDEN/);await assert.rejects(action(a,o.id,'CONFIRM'),/FORBIDDEN/);await action(manager,o.id,'APPROVE');assert.equal((await requests.commercialTimeline(a,'order',o.id)).some(e=>e.action==='APPROVED'),false);assert.equal((await requests.commercialTimeline(manager,'order',o.id)).find(e=>e.action==='APPROVED')?.actor_name,manager.displayName);await action(sales,o.id,'CONFIRM');
   const self=await save(admin,{channel:'OTHER',basket:{...fixture.qaBasket,discountBasisPoints:2000}});await propose(admin,self.id);const selfOrder=await submit(admin,self.id);await assert.rejects(action(admin,selfOrder.id,'APPROVE'),/SELF_APPROVAL_BLOCKED/);
  });
  await test('F040 changed published price blocks stale request conversion, but confirmed order retains exact historical snapshot',async()=>{
   const r=await save();requestForPrice=r.id;await propose(a,r.id);const book=await prices.getPriceBook(admin,published!.id),newPrice=await prices.savePriceBook(admin,{id:book.id,version:book.version,name:book.name,definition:{...fixture.qaPriceDefinition,lines:[{sku:'QA_PRICE_A',unitPrice:'500',thresholds:[]}]},idempotencyKey:randomUUID()});await prices.publishPriceBook(admin,{id:newPrice.id,version:newPrice.version,versionId:newPrice.versionId,action:'PUBLISH',reason:'QA source changed deliberately',idempotencyKey:randomUUID()});await assert.rejects(submit(a,r.id),/REQUEST_PRICE_CHANGED/);const head=await orders.salesOrderAccess(db,admin,firstOrder);assert.equal(JSON.stringify((await orders.salesVersionAccess(db,head,head.confirmed_version_id!)).snapshot),confirmedSnapshot);
  });
  await test('F013 re-save shows changed exact price before proposal and creates a new immutable request version',async()=>{
   const before=await requests.commercialRequestAccess(db,a,requestForPrice),old=await requests.requestVersionAccess(db,before,before.latest_version_id),saved=await requests.saveCommercialRequest(a,{...base,id:before.id,version:before.version,idempotencyKey:randomUUID()}),after=await requests.requestVersionAccess(db,await requests.commercialRequestAccess(db,a,saved.id),saved.versionId);assert.equal(old.snapshot.calculation.subtotal,'19200');assert.equal(after.snapshot.calculation.subtotal,'12000');assert.notEqual(after.snapshot.priceBook.versionId,old.snapshot.priceBook.versionId);assert.equal((await requests.commercialRequestVersions(a,saved.id)).length,2);await propose(a,saved.id);await submit(a,saved.id);const previews=await import('../../lib/crm/order-previews'),preview=await previews.reorderPreview(a,firstOrder);assert.equal(preview.changed,true);assert.equal(preview.before.subtotal,'19200');assert.equal(preview.after.subtotal,'12000');const reordered=await save(a,{channel:'REORDER',sourceOrderId:firstOrder,basket:preview.basket});assert.equal((await requests.commercialRequestAccess(db,a,reordered.id)).source_order_id,firstOrder);const warning=await previews.duplicateSalesCandidates(a,{organizationId:ids.dealerA,basket:{...fixture.qaBasket,lines:[{sku:'QA_PRICE_A',unitCode:'BASE',quantity:'24'}]}});assert.ok(warning.candidates.some(c=>c.id===firstOrder));assert.equal(warning.automaticAction,'NONE');assert.equal((await previews.duplicateSalesCandidates(b,{organizationId:ids.dealerB,basket:fixture.qaBasket})).candidates.length,0);await assert.rejects(previews.duplicateSalesCandidates(a,{organizationId:ids.dealerB,basket:fixture.qaBasket}),/NOT_FOUND/);
  });
  await test('F041 accepted current quotation converts with exact approved source, changing latest policy never rewrites it',async()=>{
   const q=await quotes.saveQuotation(sales,{version:0,organizationId:ids.dealerA,basket:fixture.qaBasket,delivery:base.delivery,note:'QA accepted quote source',idempotencyKey:randomUUID()});
   let h=await quotes.quotationAccess(db,sales,q.id);await quotes.quotationAction(sales,{id:q.id,version:h.version,versionId:q.versionId,action:'SEND',reason:'QA send source',idempotencyKey:randomUUID()});h=await quotes.quotationAccess(db,a,q.id);await quotes.quotationAction(a,{id:q.id,version:h.version,versionId:q.versionId,action:'ACCEPT',reason:'QA exact acceptance',idempotencyKey:randomUUID()});
   const r=await save(a,{channel:'QUOTATION',sourceQuotationId:q.id});await propose(a,r.id);const o=await submit(a,r.id),v=await orders.salesVersionAccess(db,await orders.salesOrderAccess(db,a,o.id),o.versionId);assert.equal(v.snapshot.request.sourceQuotationId,q.id);assert.deepEqual(v.snapshot.quote.calculation,(await quotes.quotationVersions(admin,q.id))[0].snapshot.calculation);
  });
  await test('F041 injected SQL failure creating sale preserves READY source and rolls back order/version/event atomically',async()=>{
   const r=await save();await propose(a,r.id);await owner.exec("CREATE FUNCTION cohamy_crm.qa_fail_order() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'QA_ORDER_FAILURE'; END; $$; CREATE TRIGGER qa_fail_order BEFORE INSERT ON cohamy_crm.sales_order_versions FOR EACH ROW EXECUTE FUNCTION cohamy_crm.qa_fail_order();");await assert.rejects(submit(a,r.id),/QA_ORDER_FAILURE/);assert.equal((await requests.commercialRequestAccess(db,a,r.id)).status,'READY');assert.equal((await db.query('SELECT id FROM cohamy_crm.sales_orders WHERE request_id=$1',[r.id])).rows.length,0);await owner.exec('DROP TRIGGER qa_fail_order ON cohamy_crm.sales_order_versions; DROP FUNCTION cohamy_crm.qa_fail_order();');
  });
  await test('F040 expired request and pending order cannot silently renew or confirm their old held price',async()=>{
   const r=await save();await propose(a,r.id);const h=await requests.commercialRequestAccess(db,a,r.id),v=await requests.requestVersionAccess(db,h,h.latest_version_id),expired={...v.snapshot,validUntil:new Date(Date.now()-1000).toISOString()};
   await owner.exec('ALTER TABLE cohamy_crm.commercial_request_versions DISABLE TRIGGER commercial_request_versions_immutable');await owner.query('UPDATE cohamy_crm.commercial_request_versions SET snapshot=$1::jsonb,checksum=$2 WHERE id=$3',[JSON.stringify(expired),commercialDigest(expired),v.id]);await owner.exec('ALTER TABLE cohamy_crm.commercial_request_versions ENABLE TRIGGER commercial_request_versions_immutable');await assert.rejects(submit(a,r.id),/REQUEST_EXPIRED/);assert.equal((await requests.commercialRequestAccess(db,a,r.id)).status,'READY');
   const fresh=await save();await propose(a,fresh.id);const o=await submit(a,fresh.id),head=await orders.salesOrderAccess(db,a,o.id),ov=await orders.salesVersionAccess(db,head,o.versionId),expiredOrder={...ov.snapshot,quote:{...ov.snapshot.quote,validUntil:new Date(Date.now()-1000).toISOString()}};
   await owner.exec('ALTER TABLE cohamy_crm.sales_order_versions DISABLE TRIGGER sales_order_versions_immutable');await owner.query('UPDATE cohamy_crm.sales_order_versions SET snapshot=$1::jsonb,checksum=$2 WHERE id=$3',[JSON.stringify(expiredOrder),commercialDigest(expiredOrder),ov.id]);await owner.exec('ALTER TABLE cohamy_crm.sales_order_versions ENABLE TRIGGER sales_order_versions_immutable');await assert.rejects(action(sales,o.id,'CONFIRM'),/ORDER_PRICE_EXPIRED/);assert.equal((await orders.salesOrderAccess(db,a,o.id)).confirmed_version_id,null);
  });
  await test('F043 current partner required fields and disabled policy block whole operation without source submission',async()=>{
   let p=await policy.saveOrderPolicy(admin,{version:policyVersion,definition:{...definition,requiredPartnerFields:['business_id']},reason:'QA required business field',idempotencyKey:randomUUID()});policyVersion=p.version;const r=await save();await propose(a,r.id);await assert.rejects(submit(a,r.id),/PARTNER_INCOMPLETE/);p=await policy.saveOrderPolicy(admin,{version:policyVersion,definition:{...definition,enabled:false},reason:'QA disable production-style gate',idempotencyKey:randomUUID()});policyVersion=p.version;await assert.rejects(submit(a,r.id),/ORDER_POLICY_UNAVAILABLE/);assert.equal((await requests.commercialRequestAccess(db,a,r.id)).status,'READY');
  });
  await test('F011/F018 in-app notifications have source/version keys, private recipients and current entity scope; foreign dealer sees none',async()=>{
   const rows=(await db.query<{user_id:string;entity_type:string}>('SELECT user_id,entity_type FROM cohamy_crm.notifications WHERE entity_id=$1',[staffRequest])).rows;assert.ok(rows.some(r=>r.user_id===a.id));assert.ok(rows.some(r=>r.user_id===staff.id));assert.ok(rows.every(r=>r.user_id!==b.id));const workspace=await import('../../lib/crm/workspace');assert.ok((await workspace.notifications(a)).some(r=>r.entity_id===firstOrder));assert.equal((await workspace.notifications(b)).some(r=>r.entity_id===firstOrder||r.entity_id===staffRequest),false);await assert.rejects(workspace.readNotification(b,(await db.query<{id:string}>('SELECT id FROM cohamy_crm.notifications WHERE entity_id=$1 AND user_id=$2',[firstOrder,a.id])).rows[0].id),/NOT_FOUND/);
  });
  if(postgres)await test('F018 PostgreSQL owner decision competing with staff edit cannot deadlock through notification recipient foreign keys',async()=>{
   await policy.saveOrderPolicy(admin,{version:policyVersion,definition,reason:'QA enable concurrent owner decision',idempotencyKey:randomUUID()});policyVersion++;const r=await save(staff);await propose(staff,r.id);const h=await requests.commercialRequestAccess(db,staff,r.id),results=await Promise.allSettled([requests.requestAction(a,{id:h.id,version:h.version,versionId:h.latest_version_id,action:'OWNER_APPROVE',reason:'QA concurrent owner approval',idempotencyKey:randomUUID()}),requests.saveCommercialRequest(staff,{...base,id:h.id,version:h.version,note:'QA concurrent edit invalidates prior approval',idempotencyKey:randomUUID()})]);assert.ok(results.some(r=>r.status==='fulfilled'));for(const result of results)if(result.status==='rejected')assert.match(String(result.reason),/VERSION_CONFLICT/);
  });
  await test('F136 stale staff identity remains denied after lock/unlock; fresh membership version restores legitimate scoped draft',async()=>{
   await repo.setAccountActive(admin,staff.membershipId,{active:false});await repo.setAccountActive(admin,staff.membershipId,{active:true});await assert.rejects(save(staff),/FORBIDDEN/);const fresh=(await auth.login('staff-order@crm-qa.invalid',qaPassword)).user;assert.ok(fresh.membershipVersion>staff.membershipVersion);assert.ok((await save(fresh)).id);
  });
  if(postgres)await test('F041 five simultaneous same-key PostgreSQL submissions produce one sale/version and exact durable response',async()=>{
   await policy.saveOrderPolicy(admin,{version:policyVersion,definition,reason:'QA restore isolated active policy',idempotencyKey:randomUUID()});const r=await save();await propose(a,r.id);const h=await requests.commercialRequestAccess(db,a,r.id),request={id:h.id,version:h.version,versionId:h.latest_version_id,reason:'QA competing submission',idempotencyKey:randomUUID()},results=await Promise.all(Array.from({length:5},()=>orders.submitSalesRequest(a,request)));for(const result of results)assert.deepEqual(result,results[0]);assert.equal((await db.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.sales_orders WHERE request_id=$1',[r.id])).rows[0].n,'1');
  });
  await test('F024 commercial merge moves only current request/order scope, preserves confirmed source/actors/prices and invalidates both prior dealer identities',async()=>{
   const merge=await import('../../lib/crm/partner-merge'),choices=Object.fromEntries([...merge.mergeFields,'contactPreferences','primaryContact','defaultAddress'].map(k=>[k,'TARGET'])),preview=await merge.mergePreview(admin,{sourceId:ids.dealerA,targetId:ids.dealerB,choices,reason:'QA fictitious legal duplicate confirmed'});assert.ok(preview.manifest.groups.some(g=>g.table==='sales_orders'&&!g.retained));assert.ok(preview.manifest.groups.some(g=>g.table==='sales_order_versions'&&g.retained));await merge.mergeConfirm(admin,{id:preview.id});await assert.rejects(orders.salesOrderVersions(a,firstOrder),/FORBIDDEN/);await assert.rejects(orders.salesOrderVersions(b,firstOrder),/FORBIDDEN/);const fresh=(await auth.login('a@crm-qa.invalid',qaPassword)).user,h=await orders.salesOrderAccess(db,fresh,firstOrder);assert.equal(h.organization_id,ids.dealerB);assert.equal(JSON.stringify((await orders.salesVersionAccess(db,h,h.confirmed_version_id!)).snapshot),confirmedSnapshot);assert.equal((await requests.commercialRequestAccess(db,fresh,h.request_id)).organization_id,ids.dealerB);assert.equal((await orders.salesOrderVersions(fresh,firstOrder)).length,1);
  });
 }finally{await fs.mkdir('docs/crm/test-results',{recursive:true});await fs.writeFile('docs/crm/test-results/commercial-orders-'+(postgres?'postgres':'local')+'.json',JSON.stringify({testedAt:new Date().toISOString(),environment:postgres?'STAGING isolated fictitious PostgreSQL, DML-only service role; no real order/stock/money/provider mutation':'LOCAL isolated fictitious PGlite; no real order/stock/money/provider mutation',status:cases.length===(postgres?16:14)&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await close();await owner.close();}
}
main().catch(e=>{console.error(e instanceof Error?e.message:'COMMERCIAL_ORDER_QA_FAILED');process.exitCode=1;});
