import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
process.env.CRM_MFA_ENCRYPTION_KEY='LOCAL-QA-only-MFA-encryption-key-2026-rotate';
process.env.CRM_EMAIL_ENABLED='false';
process.env.CRM_DATABASE_MODE='pglite';process.env.CRM_ENVIRONMENT='LOCAL';process.env.CRM_LOCAL_DATA_DIR='.local/crm-qa-security-'+randomUUID();
async function main(){const {createQaFixture,qaPassword}=await import('./qa-fixture'),auth=await import('../../lib/crm/auth'),security=await import('../../lib/crm/account-security'),{database}=await import('../../lib/crm/db');await createQaFixture();const db=await database(),cases:{name:string;status:string}[]=[];let admin=await auth.login('admin@crm-qa.invalid',qaPassword),secret='',recovery:string[]=[];const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(error){cases.push({name,status:'FAIL'});throw error;}};
 try{
  await test('F137 enrollment requires password and a current TOTP',async()=>{await assert.rejects(security.beginMfaEnrollment(admin.user,{password:'wrong'}),/INVALID_CREDENTIALS/);const start=await security.beginMfaEnrollment(admin.user,{password:qaPassword});secret=start.secret;assert.match(start.otpauthUrl,/^otpauth:\/\/totp\/Cohamy:/);await assert.rejects(security.confirmMfaEnrollment(admin.user,{password:qaPassword,code:'000000'}),/MFA_CODE_INVALID/);const done=await security.confirmMfaEnrollment(admin.user,{password:qaPassword,code:security.totp(secret)});recovery=done.recoveryCodes;assert.equal(recovery.length,8);assert.equal(await auth.authenticate(admin.token),null);});
  await test('F137 login requires TOTP and accepts the current code',async()=>{await assert.rejects(auth.login('admin@crm-qa.invalid',qaPassword),/MFA_REQUIRED/);await assert.rejects(auth.login('admin@crm-qa.invalid',qaPassword,{secondFactor:'000000'}),/MFA_CODE_INVALID/);admin=await auth.login('admin@crm-qa.invalid',qaPassword,{secondFactor:security.totp(secret)});assert.equal(admin.user.role,'ADMIN');});
  await test('F137 recovery code is single use',async()=>{const first=await auth.login('admin@crm-qa.invalid',qaPassword,{secondFactor:recovery[0]});assert.ok(first.token);await assert.rejects(auth.login('admin@crm-qa.invalid',qaPassword,{secondFactor:recovery[0]}),/MFA_CODE_INVALID/);assert.equal((await security.mfaStatus(admin.user)).recoveryCodesRemaining,7);});
  await test('F137 password reset is generic, expiring, one-use and still requires MFA',async()=>{assert.deepEqual(await security.requestPasswordReset('unknown@crm-qa.invalid'),{accepted:true});const requested=await security.requestPasswordReset('admin@crm-qa.invalid') as {accepted:boolean;qaToken:string};assert.equal(requested.accepted,true);await assert.rejects(security.resetPassword({token:requested.qaToken,newPassword:'Local-New-Secure-2026!'}),/MFA_REQUIRED/);await security.resetPassword({token:requested.qaToken,newPassword:'Local-New-Secure-2026!',secondFactor:security.totp(secret)});await assert.rejects(security.resetPassword({token:requested.qaToken,newPassword:'Again-Secure-2026!',secondFactor:security.totp(secret)}),/RESET_TOKEN_INVALID/);assert.equal(await auth.authenticate(admin.token),null);await auth.login('admin@crm-qa.invalid','Local-New-Secure-2026!',{secondFactor:security.totp(secret)});});
  await test('F137 disabling MFA verifies both password and factor and revokes sessions',async()=>{const logged=await auth.login('admin@crm-qa.invalid','Local-New-Secure-2026!',{secondFactor:security.totp(secret)});await security.disableMfa(logged.user,{password:'Local-New-Secure-2026!',code:security.totp(secret)});assert.equal(await auth.authenticate(logged.token),null);assert.equal((await security.mfaStatus(logged.user)).enabled,false);assert.ok((await auth.login('admin@crm-qa.invalid','Local-New-Secure-2026!')).token);});
 }finally{await fs.mkdir('docs/crm/test-results',{recursive:true});await fs.writeFile('docs/crm/test-results/security-local.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'LOCAL isolated fictitious PGlite; Brevo disabled and no real account/email mutation',status:cases.length===5&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await db.close();}}
main().catch(error=>{console.error(error instanceof Error?error.stack??error.message:'SECURITY_QA_FAILED');process.exitCode=1;});
