import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
if(process.env.CRM_ENVIRONMENT!=='STAGING'||process.env.CRM_DATABASE_MODE!=='postgres')throw new Error('ISOLATED_POSTGRES_STAGING_REQUIRED');
async function main(){
 const {createQaFixture,qaPassword}=await import('./qa-fixture'),{database}=await import('../../lib/crm/db'),{login}=await import('../../lib/crm/auth'),g=await import('../../lib/crm/governance'),w=await import('../../lib/crm/workspace'),repo=await import('../../lib/crm/repository'),o=await import('../../lib/crm/onboarding');
 const ids=await createQaFixture(),db=await database(),admin=(await login('admin@crm-qa.invalid',qaPassword)).user,cases:{name:string;status:string}[]=[];
 const test=async(name:string,run:()=>Promise<void>)=>{try{await run();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){cases.push({name,status:'FAIL'});throw e;}};
 try{
  await test('Concurrent defaults serialize on user; exactly one remains',async()=>{await Promise.all(Array.from({length:4},(_,n)=>w.saveFilter(admin,{resource:'partners',name:'STAGING QA default '+n,value:{kind:'DEALER',q:String(n)},isDefault:true})));assert.equal((await w.listFilters(admin,'partners')).filter(f=>f.is_default).length,1);});
  await test('Concurrent custom value creation yields one winner and one version conflict',async()=>{const def=await g.saveFieldDefinition(admin,{version:0,key:'qa_pg_metric',label:'STAGING QA decimal',kind:'NUMBER',options:[],required:true,readRoles:['ADMIN'],writeRoles:['ADMIN'],active:true});const result=await Promise.allSettled(['1.25','2.50'].map(value=>g.saveCustomValue(admin,{organizationId:ids.dealerA,fieldId:def.id,definitionVersion:1,version:0,value})));assert.equal(result.filter(r=>r.status==='fulfilled').length,1);const rejected=result.find(r=>r.status==='rejected') as PromiseRejectedResult;assert.equal(rejected.reason.code,'VERSION_CONFLICT');assert.equal((await g.customValues(admin,ids.dealerA)).length,1);});
  await test('Overlapping bulk batches lock in stable order; one atomic winner without partial writes',async()=>{const a=await g.bulkPreview(admin,{ids:[ids.dealerA,ids.dealerB],action:'STAGE',stage:'CONTACTED',reason:'STAGING QA first'}),b=await g.bulkPreview(admin,{ids:[ids.dealerB,ids.dealerA],action:'STAGE',stage:'LEAD',reason:'STAGING QA second'});const result=await Promise.all([g.bulkConfirm(admin,{id:a.id}),g.bulkConfirm(admin,{id:b.id})]) as {applied:number;errors:unknown[]}[];assert.deepEqual(result.map(r=>r.applied).sort(),[0,2]);assert.equal((await repo.getOrganization(admin,ids.dealerA)).stage,(await repo.getOrganization(admin,ids.dealerB)).stage);assert.equal((await db.query<{count:string}>("SELECT count(*)::text AS count FROM cohamy_crm.audit_events WHERE action='partner.bulk'")).rows[0].count,'2');});
  await test('Concurrent onboarding approval grants one membership and one organization',async()=>{const {randomUUID}=await import('node:crypto'),input={companyName:'STAGING QA applicant',representative:'QA representative',email:'approved@crm-qa.invalid',phone:'0901112233',address:'QA address',region:'QA region',password:qaPassword,idempotencyKey:randomUUID()},a=await o.registerApplication(input);let code='';await o.requestVerification(a.id,{send:async(_email:string,value:string)=>{code=value;}});await o.verifyApplication(a.id,{code});const application=await o.application(a.id);await o.submitApplication(a.id,{version:application.version});const submitted=await o.application(a.id),decision={version:submitted.version,action:'APPROVE',role:'DEALER_OWNER',message:'STAGING QA concurrent approval'};const result=await Promise.all([o.reviewApplication(admin,a.id,decision),o.reviewApplication(admin,a.id,decision)]);assert.equal(result[0].membershipId,result[1].membershipId);assert.equal((await db.query<{count:string}>('SELECT count(*)::text AS count FROM cohamy_crm.users WHERE email=$1',[input.email])).rows[0].count,'1');});
  await test('New append-only schema and file bytes satisfy integrity checks before restore',async()=>{await w.uploadDocument(admin,{entityType:'partner',entityId:ids.dealerA,title:'STAGING QA restore bytes',filename:'qa.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7\nSTAGING QA restore')});await assert.rejects(db.query('DELETE FROM cohamy_crm.custom_field_versions'),/AUDIT_APPEND_ONLY/);await assert.rejects(db.query('DELETE FROM cohamy_crm.audit_events'),/AUDIT_APPEND_ONLY/);assert.equal((await db.query<{count:string}>('SELECT count(*)::text AS count FROM cohamy_crm.document_versions WHERE checksum IS NOT NULL AND octet_length(content)=size')).rows[0].count,'1');});
 }finally{await fs.mkdir('reports',{recursive:true});await fs.writeFile('reports/governance-postgres.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'STAGING independent PostgreSQL QA database, fictitious recipients; verification delivery MOCK',status:cases.length===5&&cases.every(c=>c.status==='PASS')?'PASS':'FAIL',cases},null,2));await db.close();}
}
main().catch(e=>{console.error(e instanceof Error?e.message:'STAGING_QA_FAILED');process.exitCode=1;});
