import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {chromium} from '@playwright/test';
const base='http://localhost:4310',reference='http://127.0.0.1:4311';
const password='Local-QA-Only-2026!';
const output=path.resolve('docs/crm/test-results/screenshots');await fs.mkdir(output,{recursive:true});await fs.mkdir('.impeccable/review',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const cases=[],captures=[],metrics=[],errors=[];let pageCacheControl=null;
async function test(name,fn){try{await fn();cases.push({name,status:'PASS'});console.log('PASS '+name);}catch(error){cases.push({name,status:'FAIL',error:String(error)});throw error;}}
async function settled(page,selector){await page.locator(selector).first().waitFor();await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(animation=>animation.effect?.getComputedTiming().iterations!==Infinity).map(animation=>animation.finished.catch(()=>{})));});}
async function screenshot(page,name){await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));const file=path.join(output,name+'.png');await page.screenshot({path:file,fullPage:false});captures.push(file);const full=path.join(output,name+'-full.png');await page.screenshot({path:full,fullPage:true});captures.push(full);}
async function dimensions(page){return page.locator('.crm-module-tile').first().evaluate(tile=>{const box=tile.getBoundingClientRect(),style=getComputedStyle(tile);const grid=getComputedStyle(tile.parentElement);const h=document.querySelector('.crm-dashboard__hero h1');const dock=document.querySelector('.portal-bottom-navigation').getBoundingClientRect();return {tile:{width:box.width,height:box.height,radius:style.borderRadius,background:style.backgroundImage},grid:{columns:grid.gridTemplateColumns,gap:grid.gap},headingSize:getComputedStyle(h).fontSize,dock:{width:dock.width,left:dock.left,bottom:innerHeight-dock.bottom}};});}
try {
 const anonymous=await browser.newContext();const anon=await anonymous.newPage();
 await test('anonymous CRM page redirects to non-localized login',async()=>{await anon.goto(base+'/crm');assert.equal(new URL(anon.url()).pathname,'/crm/login');await settled(anon,'#login-email');});
 await test('anonymous APIs reject private reads',async()=>{assert.equal((await anonymous.request.get(base+'/api/crm/partners')).status(),401);assert.equal((await anonymous.request.get(base+'/api/crm/accounts')).status(),401);});
 await test('cross-origin and missing-origin writes rejected',async()=>{const body={email:'admin@crm-qa.invalid',password};assert.equal((await anonymous.request.post(base+'/api/crm/auth/login',{data:body,headers:{origin:'https://attacker.invalid'}})).status(),403);assert.equal((await anonymous.request.post(base+'/api/crm/auth/login',{data:body})).status(),403);});
 const admin=await browser.newContext();const page=await admin.newPage();page.on('pageerror',error=>errors.push(String(error)));
 await test('real browser form login and persisted session',async()=>{await page.goto(base+'/crm/login');await page.getByLabel('Email',{exact:true}).fill('admin@crm-qa.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill(password);await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await page.waitForURL(base+'/crm');await settled(page,'.crm-module-tile');await page.reload();assert.equal((await admin.request.get(base+'/api/crm/me')).status(),200);const cookies=await admin.cookies();const cookie=cookies.find(cookie=>cookie.name==='cohamy_crm_session');assert.ok(cookie.httpOnly);assert.equal(cookie.sameSite,'Strict');});
 const ref=await browser.newPage();
 for(const viewport of [{width:1366,height:768,name:'desktop'},{width:390,height:844,name:'mobile'},{width:320,height:844,name:'320'}]) {
  await test('visual capture and no page overflow '+viewport.name,async()=>{
   await page.setViewportSize(viewport);await ref.setViewportSize(viewport);
   await page.goto(base+'/crm');await ref.goto(reference+'/dashboard');await settled(page,'.crm-module-tile');await settled(ref,'.crm-module-tile');
   await screenshot(page,'cohamy-dashboard-'+viewport.name);await screenshot(ref,'humanbank-reference-dashboard-'+viewport.name);
   const target=await dimensions(page),source=await dimensions(ref);metrics.push({viewport,source,target});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Dashboard overflows');
   assert.equal(target.tile.width,source.tile.width);assert.equal(target.tile.height,source.tile.height);assert.equal(target.tile.radius,source.tile.radius);assert.equal(target.headingSize,source.headingSize);assert.equal(target.grid.gap,source.grid.gap);assert.equal(target.dock.width,source.dock.width);
   await page.goto(base+'/crm/goods');await settled(page,'.data-table');await screenshot(page,'cohamy-catalog-'+viewport.name);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Catalog overflows');
   const home=page.getByRole('navigation',{name:'Truy cập nhanh',exact:true}).getByRole('link',{name:'Home',exact:true});assert.ok(await home.evaluate(anchor=>{const rect=anchor.getBoundingClientRect();return anchor.contains(document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2));}),'Home pointer target is obstructed');await home.click();await page.waitForURL(base+'/crm');
   await anon.setViewportSize(viewport);await anon.goto(base+'/crm/login');await ref.goto(reference+'/login');await settled(anon,'#login-email');await settled(ref,'#login-email');await screenshot(anon,'cohamy-login-'+viewport.name);await screenshot(ref,'humanbank-reference-login-'+viewport.name);assert.ok(await anon.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Login overflows');
  });
 }
 await test('keyboard focus, menu and reduced motion',async()=>{await page.goto(base+'/crm');await page.keyboard.press('Tab');assert.ok(await page.locator(':focus').count());await page.getByLabel('Mở menu người dùng').click();await page.getByRole('link',{name:'Hồ sơ và phiên đăng nhập'}).waitFor();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>/^0s(?:, 0s)*$/u.test(getComputedStyle(document.querySelector('.crm-module-tile')).transitionDuration));});
 await test('create and edit a dealer through real UI',async()=>{const stamp=Date.now(),created='LOCAL QA · Tạo từ trình duyệt '+stamp,updated='LOCAL QA · Đã sửa và lưu '+stamp;await page.goto(base+'/crm/dealers/new');await page.getByLabel('Mã',{exact:true}).fill('QA_BROWSER_'+stamp);await page.getByLabel('Tên hồ sơ').fill(created);await page.getByRole('button',{name:'Lưu dữ liệu'}).click();await page.waitForURL(base+'/crm/dealers');await page.getByRole('link',{name:new RegExp(created)}).click();await page.getByLabel('Tên hồ sơ').fill(updated);await page.getByRole('button',{name:'Lưu dữ liệu'}).click();await page.waitForURL(base+'/crm/dealers');await page.getByText(updated,{exact:true}).waitFor();});
 const dealer=await browser.newContext();const dealerPage=await dealer.newPage();await dealerPage.goto(base+'/portal/login');await dealerPage.getByLabel('Email',{exact:true}).fill('a@crm-qa.invalid');await dealerPage.getByLabel('Mật khẩu',{exact:true}).fill(password);await dealerPage.getByRole('button',{name:'Đăng nhập',exact:true}).click();await dealerPage.waitForURL(base+'/portal');
 await test('dealer A cannot access B by ID/API or account list',async()=>{const result=await admin.request.get(base+'/api/crm/partners?kind=DEALER');const list=await result.json();const b=list.items.find(item=>item.code==='QA_B');assert.ok(b);assert.equal((await dealer.request.get(base+'/api/crm/partners/'+b.id)).status(),404);assert.equal((await dealer.request.get(base+'/api/crm/accounts')).status(),403);assert.equal((await dealer.request.patch(base+'/api/crm/accounts/'+b.id,{data:{active:true},headers:{origin:base}})).status(),403);const own=await (await dealer.request.get(base+'/api/crm/warehouses')).json();assert.equal(own.items.length,1);assert.equal(own.items[0].code,'QA_KHO_A');});
 await test('dealer portal menu excludes internal account administration',async()=>{assert.equal(await dealerPage.getByRole('link',{name:'Tài khoản và quyền',exact:true}).count(),0);await dealerPage.goto(base+'/portal/inventory');await dealerPage.getByText('QA_KHO_A',{exact:true}).waitFor();assert.equal(await dealerPage.getByText('QA_KHO_B',{exact:true}).count(),0);await dealerPage.setViewportSize({width:390,height:844});await dealerPage.goto(base+'/portal');await settled(dealerPage,'.crm-module-tile');await screenshot(dealerPage,'cohamy-dealer-portal-mobile');});
 const publicPage=await anonymous.newPage();
 const publicBefore={};
 await test('public website, product URLs and five locales remain available',async()=>{for(const locale of ['vi','en','zh','ko','ja']){const response=await publicPage.goto(base+'/'+locale+'/products');assert.equal(response.status(),200);assert.equal(await publicPage.locator('.portal-shell').count(),0);}for(const route of ['/vi/cart','/vi/contact','/vi/blog','/admin/login']){const response=await publicPage.goto(base+route);assert.ok(response.status()<500,route);}await publicPage.goto(base+'/vi/products');publicBefore.font=await publicPage.locator('body').evaluate(el=>getComputedStyle(el).fontFamily);await publicPage.goto(base+'/crm/login');await publicPage.goto(base+'/vi/products');assert.equal(await publicPage.locator('body').evaluate(el=>getComputedStyle(el).fontFamily),publicBefore.font);});
 await test('checkout preserves cart on 503, saves once on double-submit and remains unpaid',async()=>{
  const catalog=await (await admin.request.get(base+'/api/crm/catalog')).json();const product=catalog.items.find(item=>item.website_id==='cohamy-almond-chocolate');assert.ok(product);
  await publicPage.goto(base+'/vi/san-pham/cohamy-socola-hanh-nhan');await publicPage.evaluate(()=>localStorage.removeItem('cohamy-cart'));await publicPage.reload();
  await publicPage.getByRole('button',{name:'Thêm vào yêu cầu đặt hàng',exact:true}).click();await publicPage.getByRole('button',{name:'Thêm vào yêu cầu đặt hàng',exact:true}).click();
  await publicPage.locator('header').getByRole('link',{name:'Giỏ hàng',exact:true}).click();await publicPage.waitForURL(base+'/vi/gio-hang');assert.equal(await publicPage.evaluate(()=>JSON.parse(localStorage.getItem('cohamy-cart')).state.items[0].quantity),2);
  // Deliberately tamper only the displayed browser price; server must reprice.
  await publicPage.evaluate(()=>{const cart=JSON.parse(localStorage.getItem('cohamy-cart'));cart.state.items[0].price=1;localStorage.setItem('cohamy-cart',JSON.stringify(cart));});await publicPage.reload();
  await publicPage.getByRole('link',{name:'Gửi yêu cầu đặt hàng',exact:true}).click();await publicPage.waitForURL(base+'/vi/thanh-toan');
  await publicPage.goto(base+'/vi/checkout');for(const [name,value] of Object.entries({fullName:'LOCAL QA Buyer',email:'checkout@crm-qa.invalid',phone:'0900000000',address:'LOCAL QA Test Address',city:'LOCAL QA City'}))await publicPage.locator('[name="'+name+'"]').fill(value);
  await publicPage.route('**/api/orders',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"QA_SIMULATED_OUTAGE"}'}));
  await publicPage.locator('button[type="submit"]').click();await publicPage.locator('form').getByRole('alert').waitFor();assert.equal(await publicPage.evaluate(()=>JSON.parse(localStorage.getItem('cohamy-cart')).state.items.length),1);
  await publicPage.unroute('**/api/orders');const savedResponse=publicPage.waitForResponse(response=>response.url()===base+'/api/orders'&&response.status()===201);
  await publicPage.locator('form').evaluate(form=>{form.requestSubmit();form.requestSubmit();});const saved=await (await savedResponse).json();assert.equal(saved.status,'PENDING_REVIEW');assert.equal(saved.paid,false);assert.equal(saved.subtotal,(BigInt(product.retail_price)*2n).toString());await publicPage.getByText('Mã yêu cầu: '+saved.code).waitFor();
  assert.equal(await publicPage.evaluate(()=>JSON.parse(localStorage.getItem('cohamy-cart')).state.items.length),0);await page.goto(base+'/crm/orders');await page.getByText(saved.code,{exact:true}).waitFor();await page.reload();await page.getByText(saved.code,{exact:true}).waitFor();
  await page.setViewportSize({width:1366,height:768});await screenshot(page,'cohamy-orders-intake-desktop');
  await publicPage.setViewportSize({width:1366,height:768});
  await screenshot(publicPage,'cohamy-checkout-receipt-desktop');
 });
 await test('private API no-store, CRM noindex and robots exclusion',async()=>{const response=await admin.request.get(base+'/crm');assert.ok(response.headers()['x-robots-tag'].includes('noindex'));pageCacheControl=response.headers()['cache-control'];assert.ok(pageCacheControl.includes('no-cache'));const api=await admin.request.get(base+'/api/crm/me');assert.ok(api.headers()['cache-control'].includes('no-store'));const robots=await (await admin.request.get(base+'/robots.txt')).text();assert.ok(robots.includes('Disallow: /crm')&&robots.includes('Disallow: /portal'));});
 await test('logout revokes database session',async()=>{await page.goto(base+'/crm');await page.getByRole('button',{name:'Thoát',exact:true}).click();await page.waitForURL(base+'/crm/login');assert.equal((await admin.request.get(base+'/api/crm/me')).status(),401);});
 assert.deepEqual(errors,[]);
 await fs.copyFile(path.join(output,'cohamy-dashboard-desktop.png'),'.impeccable/review/desktop.png');await fs.copyFile(path.join(output,'cohamy-dashboard-mobile.png'),'.impeccable/review/mobile.png');await fs.copyFile(path.join(output,'cohamy-dashboard-320.png'),'.impeccable/review/user-320.png');
}finally {await browser.close();await fs.writeFile('docs/crm/test-results/browser-local.json',JSON.stringify({environment:'LOCAL',backend:'PGlite database, fictitious .invalid users',cmsSource:'Explicit legacy static catalog in QA server only; no proof of live Sheets/WordPress availability or delivery',pageCacheControl,cacheLimit:'Next dev overrides page Cache-Control to no-cache, must-revalidate (installed base-server.js). Private API no-store verified; production page header NOT RUN.',reference:'Actual HumanBank shell/dashboard/login components and full current CSS cascade; mocked auth/router, no HumanBank backend or production session',testedAt:new Date().toISOString(),cases,captures,metrics,errors},null,2)+'\n');}
