<?php
namespace Cohamy;
defined('ABSPATH') || exit;

add_action('admin_menu',function () { add_menu_page('Vận hành Cohamy','Vận hành Cohamy','cohamy_operate','cohamy-operations',__NAMESPACE__.'\\operations_screen','dashicons-chart-area',26); });
add_action('admin_enqueue_scripts',function () {
    if (($_GET['page'] ?? '')!=='cohamy-operations') return;
    wp_enqueue_script('cohamy-operations',plugins_url('operations.js',__FILE__),['wp-api-fetch'],OPERATIONS_VERSION,true);
    wp_add_inline_script('cohamy-operations','window.cohamyOperations='.wp_json_encode(['root'=>rest_url('cohamy/v1/ops/'),'nonce'=>wp_create_nonce('wp_rest'),'admin'=>current_user_can('manage_options')]).';','before');
});
function operations_screen(): void {
    if (!current_user_can('cohamy_operate')) return;
    ?>
    <div class="wrap" id="cohamy-operations"><h1>Vận hành nội dung Cohamy</h1>
    <p>WordPress sở hữu nội dung; website Next.js hiển thị dữ liệu đã lưu. Campaign chạy ở server qua Action Scheduler và cron, không cần giữ tab mở.</p>
    <nav class="nav-tab-wrapper" aria-label="Công cụ Cohamy">
    <?php foreach (['content'=>'Bài viết / Trang','transfer'=>'Import / Mapping','records'=>'Dữ liệu','templates'=>'Template','campaigns'=>'Campaign','exports'=>'Export URL','redirects'=>'Redirect / 404','connections'=>'Kết nối SEO','ai'=>'AI soạn nháp','status'=>'Trạng thái / Audit'] as $key=>$label) echo '<button type="button" class="nav-tab" data-panel="'.esc_attr($key).'">'.esc_html($label).'</button>'; ?>
    </nav><div id="cohamy-message" role="status" aria-live="polite"></div>
    <?php require __DIR__.'/operations-content-screen.php'; ?>
    <?php require __DIR__.'/operations-transfer-screen.php'; ?>
    <section data-view="records"><h2>Dữ liệu tham chiếu</h2><p>Stable ID giữ nguyên khi cập nhật. Dữ liệu thay đổi theo thời gian cần nguồn HTTPS, ngày kiểm chứng và hạn sử dụng. Chỉ record đã duyệt, chưa hết hạn được dùng để tạo bài.</p>
    <form data-operation="record"><p><label>Stable ID <input name="entity_id" required maxlength="64" pattern="[a-zA-Z0-9_-]+"></label> <label>Tên <input name="name" required></label></p>
    <p><label>Loại <select name="type"><option>location</option><option>subject</option><option>topic</option><option>country</option><option>school</option><option>program</option></select></label> <label>Trạng thái <select name="state"><option>draft</option><option>approved</option><option>archived</option></select></label></p>
    <p><label>Fields JSON <br><textarea name="fields" rows="5" cols="70" required>{"slug":"","description":""}</textarea></label></p>
    <p><label>Nguồn <input name="reference_source" type="url" placeholder="https://…"></label> <label>Ngày kiểm chứng <input name="reference_date" type="date"></label> <label>Hết hạn <input name="expires_at" type="date"></label></p><input type="hidden" name="version" value="0"><button class="button button-primary">Lưu record</button> <button type="reset" class="button">Tạo record khác</button></form>
    <p><label>Tìm dữ liệu <input data-search="record" type="search"></label> <button type="button" class="button" data-refresh="record">Tìm</button></p><div data-results="record"></div></section>
    <section data-view="templates" hidden><h2>Template có phiên bản</h2><p>Soạn bài gốc bằng Gutenberg, nhập SEO trong Rank Math, rồi chụp template từ ID bài. Dùng biến như {{location.name}}, {{location.slug}}, {{subject.name}}. Cập nhật phiên bản không làm đổi khóa chống trùng bài.</p>
    <form data-operation="template-from-post"><label>ID bài gốc <input name="post_id" type="number" min="1" required></label> <label>Stable ID template <input name="entity_id" required></label> <label>Tên <input name="name" required></label> <button class="button">Chụp từ bài Gutenberg</button></form>
    <form data-operation="template"><p><label>Stable ID <input name="entity_id" required></label> <label>Tên <input name="name" required></label> <label>Trạng thái <select name="state"><option>draft</option><option>approved</option><option>archived</option></select></label></p>
    <p><label>Payload JSON (title, slug, content_html, seo_title, seo_description, locale, category, required_variables…)<br><textarea name="payload" rows="10" cols="90" required>{"title":"Cohamy tại {{location.name}}","slug":"cohamy-{{location.slug}}","content_html":"<p>Khám phá Cohamy tại {{location.name}}.</p>","seo_title":"Cohamy tại {{location.name}}","seo_description":"Tìm hiểu Cohamy tại {{location.name}}.","locale":"vi","category":"brand-story","required_variables":["location.name","location.slug"]}</textarea></label></p><input type="hidden" name="version" value="0"><button class="button button-primary">Lưu phiên bản</button> <button type="reset" class="button">Tạo template khác</button></form>
    <p><label>Tìm template <input data-search="template" type="search"></label> <button type="button" class="button" data-refresh="template">Tìm</button></p><div data-results="template"></div></section>
    <section data-view="campaigns" hidden><h2>Tạo bài theo template và địa điểm</h2><p>Preview không ghi bài. Mặc định draft. Quota áp dụng theo ngày Việt Nam, cửa sổ chạy 5 phút; bỏ qua lịch đã lỡ để tránh dồn bài. Concurrency mặc định 1, batch tối đa 10.</p>
    <form data-operation="campaign"><p><label>Tên <input name="name" required></label> <label>Template IDs, ngăn bằng dấu phẩy <input name="templates" required></label> <label>Location IDs <input name="locations" required></label> <label>Subject ID (tùy chọn) <input name="subject"></label></p>
    <p><label>Chế độ <select name="publish_mode"><option>draft</option><option>pending</option><option>scheduled</option><option>published</option></select></label> <label>Đặt lịch bài (ISO UTC/+07:00) <input name="scheduled_at"></label> <label>Giờ chạy hằng ngày <input name="daily_at" type="time"></label> <label>Quota/ngày <input name="daily_quota" type="number" min="1" max="1000" value="100"></label> <label>Batch <input name="batch_size" type="number" min="1" max="10" value="5"></label></p>
    <button name="intent" value="preview" class="button">Preview và validate</button> <button name="intent" value="start" class="button button-primary">Xác nhận chạy campaign</button></form><pre data-preview="campaign" tabindex="0"></pre><p><button type="button" class="button" data-refresh="campaigns">Tải trạng thái</button></p><div data-results="campaigns"></div></section>
    <section data-view="exports" hidden><h2>Export URL</h2><p>Danh sách được chụp cố định khi bắt đầu. Mỗi file tối đa 10.000 URL; ZIP kèm manifest, số dòng và SHA-256. Tab đóng vẫn tiếp tục chạy.</p><form data-operation="export"><label>Format <select name="format"><option>txt</option><option>csv</option></select></label> <label>Locale <select name="locale"><option value="">Tất cả</option><?php foreach (LOCALES as $l) echo '<option>'.esc_html($l).'</option>'; ?></select></label> <label>Trạng thái <input name="status" placeholder="publish/draft/trash…"></label> <label>WordPress IDs đã chọn <input name="wp_ids" placeholder="10549,10551; để trống để dùng bộ lọc"></label> <label>Campaign ID <input name="campaign_id"></label> <label>Location ID <input name="location_id"></label> <label>Template gốc <input name="template_base"></label> <label><input name="indexable_only" type="checkbox" checked> Chỉ URL đủ điều kiện index</label> <label>Loại nội dung <select name="content_type"><option value="">Tất cả</option><option value="post">Bài viết</option><option value="page">Trang</option></select></label><label>Country ID <input name="country_id"></label><label>Topic ID <input name="topic_id"></label><label>Subject ID <input name="subject_id"></label><label>Danh mục (slug) <input name="category"></label><label>Từ ngày sửa (VN) <input name="from" type="date"></label><label>Đến ngày sửa (VN) <input name="to" type="date"></label><button class="button button-primary">Bắt đầu export</button></form><p><button class="button" data-refresh="exports">Tải trạng thái</button></p><div data-results="exports"></div></section>
    <section data-view="redirects" hidden><h2>Redirect và 404</h2><p>Chỉ nhận đường dẫn website Cohamy; không nhận route quản trị. Kiểm tra vòng lặp trước khi lưu. Không redirect tất cả 404 về trang chủ.</p><form data-operation="redirect"><label>URL nguồn <input name="source" required placeholder="/vi/bai-viet/slug-cu"></label> <label>URL đích <input name="target"></label> <label>HTTP code <select name="code"><option>301</option><option>302</option><option>307</option><option>308</option><option>410</option></select></label> <label><input name="enabled" type="checkbox" checked> Bật</label> <button class="button button-primary">Validate và lưu</button></form><p><button class="button" data-refresh="redirects">Tải redirect</button> <button class="button" data-refresh="404">Tải 404 (giữ 30 ngày)</button></p><form data-operation="redirects-filter"><label>Tìm redirect <input name="q" type="search"></label><label>Trạng thái rule <select name="enabled"><option value="">Tất cả</option><option value="1">Bật</option><option value="0">Tắt</option></select></label><label>Lọc HTTP code <input name="code" type="number"></label><button class="button">Lọc redirect</button></form><div data-results="redirects"></div><form data-operation="404-filter"><label>Tìm 404 <input name="q" type="search"></label><label>Hits từ <input name="min_hits" type="number" min="1" value="1"></label><label>Ngày đầu <input name="from" type="date"></label><label>Ngày cuối <input name="to" type="date"></label><button class="button">Lọc 404</button></form><div data-results="404"></div></section>
    <section data-view="connections" hidden><h2>Kết nối SEO</h2><div data-results="connections"></div><p>IndexNow được gửi bởi Cohamy Bridge; module native Rank Math tắt để không gửi trùng hoặc gửi URL CMS. Tiếp nhận không có nghĩa đã index. GSC cần service account riêng được cấp quyền property.</p>
    <?php if (current_user_can('manage_options')): ?>
    <form data-operation="indexnow-config"><label><input name="enabled" type="checkbox"> Bật hàng đợi</label> <label><input name="live_authorized" type="checkbox"> Cho phép submit LIVE tới IndexNow (thay đổi cấu hình có tác động bên ngoài)</label> <button class="button">Lưu IndexNow</button></form>
    <form data-operation="gsc-config"><p><label>Property <input name="property" value="<?php echo esc_attr(public_base().'/'); ?>"></label></p><label>Service account JSON (lưu riêng server, không xuất lại key)<br><textarea name="credentials" rows="4" cols="80" required autocomplete="off"></textarea></label> <button class="button">Lưu GSC</button></form>
    <form data-operation="ai-config"><p><label>Endpoint <select name="endpoint"><option>https://api.openai.com/v1</option><option>https://api.deepseek.com</option></select></label> <label>Model <input name="model" required></label> <label>API key <input name="api_key" type="password" required autocomplete="new-password"></label> <label>Token/ngày <input name="daily_token_budget" type="number" value="10000"></label></p><label>Giọng văn <textarea name="voice" rows="2" cols="70">Rõ ràng, tự nhiên, không hứa hẹn sai sự thật.</textarea></label> <button class="button">Lưu AI</button></form>
    <?php endif; ?>
    <form data-operation="indexnow-submit"><label>URL public, mỗi dòng một URL<br><textarea name="urls" rows="4" cols="80"></textarea></label><label>File TXT/CSV UTF-8, CSV có cột url <input name="file" type="file" accept=".txt,.csv"></label><label>Loại <select name="kind"><option value="updated">Cập nhật / xuất bản</option><option value="deleted">Đã gỡ</option></select></label><label>WordPress IDs <input name="wp_ids"></label><label>Campaign ID <input name="campaign_id"></label><label>Từ ngày sửa (VN) <input name="from" type="date"></label><label>Đến ngày sửa (VN) <input name="to" type="date"></label><button name="intent" value="preview" class="button">Preview URL</button><button name="intent" value="queue" class="button button-primary">Xác nhận đưa vào hàng đợi</button></form><pre data-preview="indexnow" tabindex="0"></pre><div data-results="indexnow"></div>
    <form data-operation="gsc-inspect"><label>URL cần inspect <input name="url" required></label><button class="button">URL Inspection</button></form><form data-operation="gsc-analytics"><label>Từ <input name="start_date" type="date" required></label> <label>Đến <input name="end_date" type="date" required></label> <button class="button">Đọc clicks / impressions / CTR / position</button></form><p><button type="button" class="button" data-api="gsc/verify">Kiểm tra quyền property</button> <button type="button" class="button" data-api="gsc/sitemap">Submit sitemap Cohamy cho GSC</button> <button type="button" class="button" data-gsc-history>Tải kết quả đã lưu / quota</button></p><pre data-preview="connections" tabindex="0"></pre></section>
    <section data-view="ai" hidden><h2>AI gợi ý, người dùng duyệt</h2><p>AI chỉ nhận dữ liệu đã duyệt, chưa hết hạn và có nguồn kiểm chứng. Job lưu trên server, retry tối đa 3 lần theo Retry-After. Kết quả chưa rõ giữ dự phòng token; apply từ chối nếu bài đã được người dùng sửa. Gợi ý nội dung gần trùng chỉ xét 100 bài public gần nhất cùng ngôn ngữ.</p><?php if(current_user_can('manage_options')): ?><p><button type="button" class="button" data-api="ai/connection-test">Kiểm tra kết nối và model AI</button></p><?php endif; ?><form data-operation="ai-generate"><label>ID bài <input name="post_id" type="number" min="1" required></label> <label>Record IDs <input name="records" required></label> <label>Tác vụ <select name="task"><option>draft</option><option>outline</option><option>seo</option><option>image_alt</option><option>faq</option><option>internal_link_suggestions</option></select></label> <button class="button">Tạo gợi ý</button></form><pre data-preview="ai" tabindex="0"></pre><button type="button" class="button button-primary" data-ai-apply disabled>Xác nhận diff và áp dụng</button><p><button type="button" class="button" data-refresh="ai-jobs">Tải job đã lưu</button></p><div data-results="ai-jobs"></div></section>
    <section data-view="status" hidden><h2>Trạng thái vận hành</h2><p>Trạng thái cấu hình chưa chứng minh SMTP/credential hoạt động. Kiểm tra kết nối trả lỗi cụ thể.</p><div data-results="status"></div><h3>Hàng đợi</h3><button type="button" class="button" data-queue-repair>Kiểm tra và bổ sung lịch chạy bị mất</button><div data-results="queue"></div><h2>Audit trước / sau</h2><div data-results="audit"></div></section>
    </div>
    <style>#cohamy-operations section{padding:12px 0}#cohamy-operations textarea{max-width:100%;box-sizing:border-box}#cohamy-operations input{max-width:100%}#cohamy-operations select{max-width:100%;box-sizing:border-box}#cohamy-operations label{max-width:calc(100% - 12px);display:inline-block;margin:5px 12px 5px 0;vertical-align:top}#cohamy-operations pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:420px;overflow:auto;background:#fff;border:1px solid #c3c4c7;padding:12px}#cohamy-operations [data-results]{overflow-x:auto}#cohamy-operations table td{overflow-wrap:anywhere;max-width:280px}#cohamy-message{padding:8px 0}#cohamy-message[data-error=true]{color:#b32d2e}</style>
    <?php
}
add_action('rest_api_init',function () {
    op_route('templates/from-post','POST','cohamy_templates',function ($r) {
        $id=(int)$r['post_id']; if (!current_user_can('edit_post',$id) || get_post_type($id)!=='post') return op_error('Không có quyền chụp bài gốc.',403);
        $row=row_for($id); foreach (['id','group_id','canonical_url','created_at','updated_at','published_at','scheduled_at'] as $key) unset($row[$key]);
        $row['content_html']=get_post($id)->post_content; $row['seo_title']=get_post_meta($id,'rank_math_title',true); $row['seo_description']=get_post_meta($id,'rank_math_description',true); $row['focus_keyword']=get_post_meta($id,'rank_math_focus_keyword',true); $row['base_id']='wp-original-'.$id;
        return entity_save(['entity_id'=>$r['entity_id'],'name'=>$r['name'],'kind'=>'template','payload'=>$row,'state'=>'draft']);
    });
});
add_filter('manage_post_posts_columns',function ($columns) { return array_merge($columns,['cohamy_identity'=>'ID / Ngôn ngữ / Campaign','cohamy_seo'=>'SEO public / Phân tích']); });
add_action('manage_post_posts_custom_column',function ($column,$id) {
    if ($column==='cohamy_identity') echo esc_html(meta($id,'legacy_id').' / '.meta($id,'locale').' / '.meta($id,'campaign_id'));
    if ($column==='cohamy_seo') { echo esc_html(indexable($id) ? 'Index' : 'Noindex'); echo '<br>'; echo metadata_exists('post',$id,'rank_math_seo_score') ? esc_html('Rank Math: '.get_post_meta($id,'rank_math_seo_score',true)) : 'Chưa phân tích — mở Rank Math trong editor'; if (is_public($id)) echo '<br><a href="'.esc_url(public_url($id)).'" target="_blank" rel="noopener">URL public</a>'; }
},20,2);



