<?php namespace Cohamy; defined('ABSPATH') || exit; ?>
<section data-view="transfer" hidden><h2>Import CSV / JSON và mapping</h2>
<p>CSV UTF-8 nhận dấu ; hoặc , và dấu nháy, HTML, xuống dòng. Preview kiểm tra từng dòng trước khi ghi. Mặc định draft, chỉ giữ trạng thái khi chọn rõ ràng và đủ quyền. Sau xác nhận, cron tiếp tục xử lý khi đóng tab.</p>
<p>Bài viết dùng 23 cột của <a href="<?php echo esc_url(admin_url('edit.php?page=cohamy-import')); ?>">CSV mẫu bài viết cũ</a>. Record dùng entity_id,name,type,state,fields_json,reference_source,reference_date,expires_at. Template dùng entity_id,name,state,payload_json. Redirect dùng source,target,code,enabled. JSON nhận một mảng object theo cùng tên field; payload có thể là object.</p>
<button type="button" class="button" data-transfer-example="record">Tải CSV mẫu record</button> <button type="button" class="button" data-transfer-example="template">Tải JSON mẫu template</button> <button type="button" class="button" data-entity-export="record">Export JSON records (mọi trang)</button> <button type="button" class="button" data-entity-export="template">Export JSON templates</button> <button type="button" class="button" data-redirect-export>Export JSON redirects</button>
<form data-operation="transfer"><p><label>Loại <select name="kind"><option value="record">Records</option><option value="template">Templates</option><option value="post">Bài viết</option><option value="redirect">Redirect</option></select></label> <label>Chế độ <select name="mode"><option value="create">Chỉ tạo mới</option><option value="upsert">Tạo mới / cập nhật theo ID</option></select></label> <label><input type="checkbox" name="preserve_state"> Giữ trạng thái trong file (cần quyền duyệt / publish)</label> <label><input type="checkbox" name="skip_invalid"> Bỏ dòng lỗi sau khi xem preview</label></p>
<label>File UTF-8 <input name="file" type="file" accept=".csv,.json" required></label><label>Mapping JSON: tên cột nguồn → tên field đích<br><textarea name="mapping" rows="3" cols="70">{}</textarea></label>
<button class="button" name="intent" value="preview">Preview / validate</button><button class="button button-primary" name="intent" value="start">Xác nhận import</button></form><pre data-preview="transfer" tabindex="0"></pre><p><button type="button" class="button" data-refresh="imports">Tải trạng thái job</button></p><div data-results="imports"></div>
</section>
