<?php
// REAL WordPress database/API behavior; external providers intercepted in THIS CLI process only.
if(PHP_SAPI!=='cli')exit(1);define('COHAMY_PROVIDER_CONTRACT_MOCK',true);$_SERVER['HTTP_HOST']='127.0.0.1:8081';require dirname(__DIR__,2).'/.local/wordpress/wp-load.php';
if(!defined('COHAMY_LOCAL_SETUP') || !COHAMY_LOCAL_SETUP || wp_get_environment_type()!=='local')exit(1);
if(get_option('cohamy_gsc_credentials') || get_option('cohamy_ai_config') || get_option('cohamy_indexnow_live_authorized'))throw new RuntimeException('Refuse contract fixture with configured LIVE providers.');
wp_set_current_user(1);$run='contract-'.substr(str_replace('-','',wp_generate_uuid4()),0,12);$results=[];$captured=[];$index_status=429;$ai_missing=true;$ai_status=200;
function expect_contract($condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function contract_request(string $path,array $data=[]):WP_REST_Response{$r=new WP_REST_Request('POST','/cohamy/v1/ops/'.$path);$r->set_header('Content-Type','application/json');$r->set_body(wp_json_encode($data));return rest_do_request($r);}
$keypair=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA,'config'=>__DIR__.'/openssl-contract.cnf']);if(!$keypair)throw new RuntimeException('Local RSA fixture generation failed.');openssl_pkey_export($keypair,$private,null,['config'=>__DIR__.'/openssl-contract.cnf']);$public=openssl_pkey_get_details($keypair)['key'];
$filters=[
 'pre_option_cohamy_indexnow_enabled'=>fn()=>true,
 'pre_option_cohamy_indexnow_live_authorized'=>fn()=>true,
 'pre_option_cohamy_indexnow_key'=>fn()=>'contract-key-only-123456',
 'pre_option_cohamy_gsc_credentials'=>fn()=>['client_email'=>'contract@cohamy-test.iam.gserviceaccount.com','private_key'=>$private],
 'pre_option_cohamy_gsc_property'=>fn()=>Cohamy\public_base().'/',
 'pre_option_cohamy_ai_config'=>fn()=>['api_key'=>'mock-not-a-live-key','endpoint'=>'https://api.openai.com/v1','model'=>'contract-fixture','voice'=>'Chỉ dùng nguồn được duyệt.','daily_token_budget'=>100000,'max_tokens'=>256],
 'pre_transient_cohamy_gsc_access_token'=>fn()=>false,
];foreach($filters as $hook=>$cb)add_filter($hook,$cb);
$transport=function($pre,$args,$url)use(&$captured,&$index_status,&$ai_missing,&$ai_status,$public){
 $captured[]=['url'=>$url,'method'=>$args['method'] ?? 'GET'];$status=200;$headers=[];$body=[];
 if(str_contains($url,'/indexnow/contract-key-only-123456.txt'))return ['response'=>['code'=>200,'message'=>'MOCK'],'headers'=>[],'body'=>'contract-key-only-123456'];
 elseif($url==='https://api.indexnow.org/indexnow'){$payload=json_decode($args['body'],true);expect_contract($payload['host']==='cohamy.vn' && count($payload['urlList'])<=10000 && $payload['keyLocation']===Cohamy\public_base().'/indexnow/contract-key-only-123456.txt','IndexNow official request contract.');$status=$index_status;$headers=['retry-after'=>'120'];}
 elseif($url==='https://oauth2.googleapis.com/token'){$parts=explode('.',$args['body']['assertion']);$decode=fn($s)=>base64_decode(strtr($s,'-_','+/'));expect_contract(openssl_verify($parts[0].'.'.$parts[1],$decode($parts[2]),$public,OPENSSL_ALGO_SHA256)===1,'Actual RS256 signature.');$claims=json_decode($decode($parts[1]),true);expect_contract($claims['scope']==='https://www.googleapis.com/auth/webmasters' && $claims['exp']-$claims['iat']===3600,'OAuth scope/time contract.');$body=['access_token'=>'MOCK-only-token','expires_in'=>3600];}
 elseif($url==='https://www.googleapis.com/webmasters/v3/sites')$body=['siteEntry'=>[['siteUrl'=>Cohamy\public_base().'/','permissionLevel'=>'siteOwner']]];
 elseif(str_contains($url,'/searchAnalytics/query')){$p=json_decode($args['body'],true);expect_contract($p['dimensions']===['page','query'] && $p['rowLimit']<=25000,'Official Search Analytics query.');$body=['rows'=>[['keys'=>['https://cohamy.vn/vi/bai-viet/fixture','cohamy'],'clicks'=>4,'impressions'=>100,'ctr'=>0.04,'position'=>8.2]]];}
 elseif($url==='https://searchconsole.googleapis.com/v1/urlInspection/index:inspect'){$p=json_decode($args['body'],true);expect_contract($p['siteUrl']===Cohamy\public_base().'/' && str_starts_with($p['inspectionUrl'],Cohamy\public_base().'/'),'Inspection exact public property.');$body=['inspectionResult'=>['indexStatusResult'=>['verdict'=>'NEUTRAL','coverageState'=>'Crawled - currently not indexed']]];}
 elseif(str_contains($url,'/sitemaps/')){expect_contract($args['method']==='PUT','Sitemap official PUT.');$body=[];}
 elseif($url==='https://api.openai.com/v1/models')$body=['data'=>[['id'=>'contract-fixture']]];
 elseif($url==='https://api.openai.com/v1/chat/completions'){$p=json_decode($args['body'],true);expect_contract($p['model']==='contract-fixture' && str_contains($p['messages'][0]['content'],'không suy đoán'),'AI approved facts instructions.');$status=$ai_status;$headers=['retry-after'=>'120'];$body=['usage'=>['total_tokens'=>37],'choices'=>[['message'=>['content'=>wp_json_encode(['title'=>'Gợi ý AI kiểm thử','excerpt'=>'Nguồn đã duyệt','content_html'=>'<p>AI_CONTRACT_APPLIED_FROM_APPROVED_FACTS</p>','seo_title'=>'SEO từ provider mock','seo_description'=>'Mô tả có nguồn','focus_keyword'=>'Cohamy','missing_fields'=>$ai_missing?['reference_detail']:[]])]]]];}
 else throw new RuntimeException('MOCK refuses every unexpected external URL: '.$url);
 if($url==='https://api.openai.com/v1/chat/completions' && ($p['messages'][1]['content'] ?? '')){$input=json_decode($p['messages'][1]['content'],true);if(($input['task'] ?? '')==='internal_link_suggestions'){$suggestion=json_decode($body['choices'][0]['message']['content'],true);$suggestion['suggested_links']=array_map(fn($c)=>['url'=>$c['url'],'anchor'=>$c['title']],array_slice($input['link_candidates'] ?? [],0,1));$body['choices'][0]['message']['content']=wp_json_encode($suggestion);}}
 $body['_cohamy_contract_mock']=true;return ['response'=>['code'=>$status,'message'=>'MOCK'],'headers'=>$headers,'body'=>wp_json_encode($body)];
};add_filter('pre_http_request',$transport,10,3);
try{
 $url=Cohamy\public_base().'/vi/bai-viet/'.$run;Cohamy\index_event($url);$start=time();Cohamy\indexnow_tick();$row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Cohamy\op_table('index_event').' WHERE event_key=%s',hash('sha256',$url)),ARRAY_A);expect_contract($row['state']==='queued' && (int)$row['http_code']===429 && (int)$row['next_attempt']>=$start+120,'Retry-After persisted.');
 $index_status=202;$wpdb->update(Cohamy\op_table('index_event'),['next_attempt'=>time()],['event_key'=>$row['event_key']]);Cohamy\indexnow_tick();$state=$wpdb->get_var($wpdb->prepare('SELECT state FROM '.Cohamy\op_table('index_event').' WHERE event_key=%s',$row['event_key']));expect_contract($state==='accepted_not_indexed','202 must never mean indexed.');$results[]=['name'=>'IndexNow request, key verification, retry and accepted state','status'=>'PASS / CONTRACT MOCK'];
 $verify=contract_request('gsc/verify');expect_contract($verify->get_status()===200,'GSC verify.');$analytics=contract_request('gsc/analytics',['start_date'=>'2026-09-01','end_date'=>'2026-09-17']);expect_contract($analytics->get_data()['rows'][0]['clicks']===4,'Metrics from response.');$inspection=contract_request('gsc/inspect',['url'=>$url]);expect_contract($inspection->get_data()['state']==='not_indexed','Persisted not indexed, distinct from API error.');expect_contract(contract_request('gsc/sitemap')->get_status()===200,'Sitemap submit contract.');$results[]=['name'=>'GSC RS256, property, analytics, persisted inspection and sitemap PUT','status'=>'PASS / CONTRACT MOCK'];
 $entity=Cohamy\entity_save(['entity_id'=>$run,'name'=>'Địa điểm có nguồn','kind'=>'record','state'=>'approved','payload'=>['type'=>'location','fields'=>['description'=>'Chocolate Cohamy'],'reference_source'=>'https://cohamy.vn','reference_date'=>'2026-09-18']]);expect_contract(!is_wp_error($entity),'Approved facts fixture.');
 $post=wp_insert_post(['post_type'=>'post','post_status'=>'draft','post_title'=>$run,'post_content'=>'<p>Original content</p>'],true);$identity=['locale'=>'vi','slug'=>$run,'group_id'=>$run,'legacy_id'=>$run];expect_contract(!is_wp_error(Cohamy\reserve_identity($post,$identity)),'Actual identity reservation.');Cohamy\commit_identity($post,$post,$identity);
 $input=['post_id'=>$post,'records'=>[$run],'task'=>'draft'];$missing=contract_request('ai/generate',$input);expect_contract($missing->get_status()===422,'Missing facts not silently fabricated.');$ai_missing=false;$suggestion=contract_request('ai/generate',$input);expect_contract($suggestion->get_status()===200,'AI preview persists.');wp_update_post(['ID'=>$post,'post_title'=>'Human edited']);$conflict=contract_request('ai/apply',['draft_id'=>$suggestion->get_data()['draft_id'],'confirmed'=>true]);expect_contract($conflict->get_status()===409,'AI cannot overwrite human edit.');
 $suggestion=contract_request('ai/generate',$input);$applied=contract_request('ai/apply',['draft_id'=>$suggestion->get_data()['draft_id'],'confirmed'=>true]);expect_contract($applied->get_status()===200 && str_contains(get_post($post)->post_content,'AI_CONTRACT_APPLIED_FROM_APPROVED_FACTS'),'Actual WP content apply.');$results[]=['name'=>'AI missing facts, preview, CAS conflict, apply and usage log','status'=>'PASS / CONTRACT MOCK'];
 $connection=contract_request('ai/connection-test');expect_contract($connection->get_status()===200 && $connection->get_data()['evidence']==='CONTRACT_MOCK' && $connection->get_data()['model_available'],'Model connection check must persist explicit evidence.');
 $created=contract_request('ai/jobs',$input);expect_contract($created->get_status()===202,'Durable AI job.');$uuid=$created->get_data()['job_id'];$ai_status=429;$at=time();Cohamy\ai_job_tick($uuid);$job=Cohamy\ai_job_get($uuid);expect_contract($job['state']==='retrying' && $job['attempts']===1 && $job['next_attempt']>=$at+120,'AI Retry-After checkpoint.');
 $job['next_attempt']=time();update_option('cohamy_ai_job_'.$uuid,wp_json_encode($job),false);$ai_status=200;Cohamy\ai_job_tick($uuid);$job=Cohamy\ai_job_get($uuid);expect_contract($job['state']==='completed' && $job['attempts']===2 && !empty($job['result']['draft_id']),'Native worker retries into private preview, never auto applies.');
 $created=contract_request('ai/jobs',$input);$uuid=$created->get_data()['job_id'];$ai_status=429;for($i=0;$i<3;$i++){$job=Cohamy\ai_job_get($uuid);$job['next_attempt']=time();update_option('cohamy_ai_job_'.$uuid,wp_json_encode($job),false);Cohamy\ai_job_tick($uuid);} $job=Cohamy\ai_job_get($uuid);expect_contract($job['state']==='failed' && $job['attempts']===3,'AI retries bounded at three.');
 $created=contract_request('ai/jobs',$input);$uuid=$created->get_data()['job_id'];wp_update_post(['ID'=>$post,'post_title'=>'HUMAN_EDIT_AFTER_AI_JOB']);$before=count($captured);Cohamy\ai_job_tick($uuid);expect_contract(Cohamy\ai_job_get($uuid)['state']==='failed' && count($captured)===$before,'Human edit invalidates job before dispatch.');$results[]=['name'=>'AI model connection, durable retry checkpoint, bounded failures and human conflict','status'=>'PASS / CONTRACT MOCK / CONTROLLED RETRY CLOCK'];
 $ai_status=200;$faq=contract_request('ai/generate',array_merge($input,['task'=>'faq']));expect_contract($faq->get_status()===200 && $faq->get_data()['apply_behavior']==='append_faq_preserve_existing','FAQ append preview.');$old=get_post($post);$old_seo=get_post_meta($post,'rank_math_title',true);$applied=contract_request('ai/apply',['draft_id'=>$faq->get_data()['draft_id'],'confirmed'=>true]);$current=get_post($post);expect_contract($applied->get_status()===200 && str_starts_with($current->post_content,$old->post_content) && $current->post_title===$old->post_title && get_post_meta($post,'rank_math_title',true)===$old_seo,'FAQ must preserve original content/title/SEO.');
 $links=contract_request('ai/generate',array_merge($input,['task'=>'internal_link_suggestions']));expect_contract($links->get_status()===200 && !$links->get_data()['apply_allowed'],'Internal link suggestions are stored for explicit Gutenberg insertion.');expect_contract(contract_request('ai/apply',['draft_id'=>$links->get_data()['draft_id'],'confirmed'=>true])->get_status()===422,'Link suggestions cannot overwrite article.');$results[]=['name'=>'FAQ append preserves article and SEO; links use supplied internal URLs and remain advisory','status'=>'PASS / CONTRACT MOCK'];
}finally{remove_filter('pre_http_request',$transport,10);foreach($filters as $hook=>$cb)remove_filter($hook,$cb);delete_transient('cohamy_gsc_access_token');}
$report=['environment'=>'LOCAL WordPress REAL persistence / EXTERNAL TRANSPORT CONTRACT MOCK ONLY','external_live_requests'=>0,'results'=>$results,'captured_requests'=>$captured];file_put_contents(dirname(__DIR__,2).'/docs/content-upgrade/test-results/providers.json',wp_json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));echo wp_json_encode($report).PHP_EOL;

