<?php
if(PHP_SAPI!=='cli')exit(1);$_SERVER['HTTP_HOST']='127.0.0.1:8081';require dirname(__DIR__,2).'/.local/wordpress/wp-load.php';
if(!defined('COHAMY_LOCAL_SETUP') || !COHAMY_LOCAL_SETUP || wp_get_environment_type()!=='local')exit(1);
wp_set_current_user(1);$run='recovery-'.substr(str_replace('-','',wp_generate_uuid4()),0,12);$results=[];
function queue_expect($condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function queue_call(string $path,array $input):array{$r=new WP_REST_Request('POST','/cohamy/v1/ops/'.$path);$r->set_header('Content-Type','application/json');$r->set_body(wp_json_encode($input));$result=rest_do_request($r);queue_expect($result->get_status()<300,wp_json_encode($result->get_data()));return $result->get_data();}
function queue_count(array $job,string $state):int{foreach($job['stats'] as $stat)if($stat['state']===$state)return (int)$stat['count'];return 0;}
function queue_payload(string $id,array $changes):void{global $wpdb;$c=Cohamy\campaign_get($id);$wpdb->update(Cohamy\op_table('campaign'),['payload'=>wp_json_encode(array_merge($c['payload'],$changes))],['campaign_id'=>$id]);}
try{
 for($i=1;$i<=3;$i++)queue_call('entities',['entity_id'=>$run.'-l'.$i,'kind'=>'record','name'=>'Queue location '.$i,'state'=>'approved','payload'=>['type'=>'location','fields'=>['slug'=>$run.'-l'.$i]]]);
 for($i=1;$i<=2;$i++)queue_call('entities',['entity_id'=>$run.'-t'.$i,'kind'=>'template','name'=>'Queue template '.$i,'state'=>'approved','payload'=>['title'=>'Queue {{location.name}}','slug'=>$run.'-t'.$i.'-{{location.slug}}','content_html'=>'<p>QUEUE_RECOVERY_REAL {{location.name}}</p>','seo_title'=>'Queue {{location.name}}','seo_description'=>'Dữ liệu test queue.','locale'=>'vi','category'=>'brand-story','required_variables'=>['location.slug']]]);
 $c=queue_call('campaigns',['templates'=>[$run.'-t1',$run.'-t2'],'locations'=>[$run.'-l1',$run.'-l2',$run.'-l3'],'confirmed'=>true,'publish_mode'=>'published','batch_size'=>1,'daily_quota'=>1]);$id=$c['campaign_id'];
 queue_call('campaigns/'.$id.'/control',['action'=>'pause']);Cohamy\campaign_tick($id);queue_expect(queue_count(Cohamy\campaign_get($id),'completed')===0,'Paused job wrote a post.');
 queue_call('campaigns/'.$id.'/control',['action'=>'resume']);Cohamy\campaign_tick($id);queue_expect(queue_count(Cohamy\campaign_get($id),'completed')===1,'First durable item missing.');Cohamy\campaign_tick($id);queue_expect(queue_count(Cohamy\campaign_get($id),'completed')===1,'Daily quota exceeded.');
 $results[]=['name'=>'pause/resume and Vietnamese daily quota','status'=>'PASS','detail'=>'Native server worker wrote one of six then deferred remaining work to next Vietnamese day.'];
 // Persist yesterday's quota as a controlled clock-boundary fixture, without changing OS time.
 queue_payload($id,['quota_date'=>wp_date('Y-m-d',time()-DAY_IN_SECONDS,new DateTimeZone('Asia/Ho_Chi_Minh')),'completed_today'=>1]);Cohamy\campaign_tick($id);queue_expect(queue_count(Cohamy\campaign_get($id),'completed')===2,'Vietnamese date rollover did not reset quota.');
 $results[]=['name'=>'quota rollover from persisted yesterday checkpoint','status'=>'PASS / CONTROLLED DATE FIXTURE','detail'=>'Real database checkpoint and native date logic; not a live overnight observation.'];
 queue_payload($id,['daily_quota'=>100]);queue_call('campaigns/'.$id.'/control',['action'=>'stop']);Cohamy\campaign_tick($id);queue_expect(queue_count(Cohamy\campaign_get($id),'completed')===2,'Stopped job continued.');queue_call('campaigns/'.$id.'/control',['action'=>'resume']);
 $item=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Cohamy\op_table('campaign_item')." WHERE campaign_id=%s AND state='queued' ORDER BY item_key LIMIT 1",$id),ARRAY_A);$data=json_decode($item['payload'],true);$ref=Cohamy\entity_get($data['location_id']);queue_call('entities',array_merge($ref,['state'=>'archived']));
 for($i=0;$i<8;$i++)Cohamy\campaign_tick($id);$failed=Cohamy\campaign_get($id);queue_expect(queue_count($failed,'failed')>0,'Expected bounded failures from archived input.');
 $ref=Cohamy\entity_get($data['location_id']);queue_call('entities',array_merge($ref,['state'=>'approved']));queue_call('campaigns/'.$id.'/control',['action'=>'retry']);
 for($i=0;$i<8;$i++)Cohamy\campaign_tick($id);$done=Cohamy\campaign_get($id);queue_expect(queue_count($done,'completed')===6 && queue_count($done,'failed')===0,'Retry did not reconcile six stable keys.');
 $preview=queue_call('campaigns/preview',['templates'=>[$run.'-t1',$run.'-t2'],'locations'=>[$run.'-l1',$run.'-l2',$run.'-l3']]);queue_expect($preview['new']===0 && $preview['duplicates']===6,'Rerun duplicate.');
 $results[]=['name'=>'stop/resume, mid-job failure, bounded retry and stable idempotence','status'=>'PASS','detail'=>'Archiving one live record caused real failed items; approval + explicit retry completed all six; rerun creates zero.'];
 // Create a second durable job and deliberately remove its scheduling entry, then repair.
 $fresh=queue_call('entities',['entity_id'=>$run.'-extra','kind'=>'record','name'=>'Repair fixture','state'=>'approved','payload'=>['type'=>'location','fields'=>['slug'=>$run.'-extra']]]);
 $repair=queue_call('campaigns',['templates'=>[$run.'-t1'],'locations'=>[$fresh['entity_id']],'confirmed'=>true,'batch_size'=>1]);as_unschedule_all_actions('cohamy_campaign_tick',[$repair['campaign_id']],'cohamy');Cohamy\operations_housekeeping();
 queue_expect((bool)as_get_scheduled_actions(['hook'=>'cohamy_campaign_tick','args'=>[$repair['campaign_id']],'status'=>'pending','group'=>'cohamy','per_page'=>1],'ids'),'Missing scheduler action was not repaired.');
 update_option('cohamy_generation_global',wp_json_encode(['owner'=>'crashed-fixture','until'=>time()-1]),false);update_option('cohamy_campaign_lock_'.$repair['campaign_id'],wp_json_encode(['owner'=>'crashed-fixture','until'=>time()-1]),false);
 Cohamy\campaign_tick($repair['campaign_id']);queue_expect(queue_count(Cohamy\campaign_get($repair['campaign_id']),'completed')===1,'Expired crashed-worker lease did not recover.');
 $results[]=['name'=>'missing action repair and expired worker lease recovery','status'=>'PASS / CONTROLLED CRASH FIXTURE','detail'=>'Actual SQL CAS leases and Action Scheduler entry recreated; subsequent PHP worker reconciled persisted job.'];
 queue_call('campaigns/'.$id.'/control',['action'=>'stop']);$scope=queue_call('campaigns/'.$id.'/rollback',[]);queue_expect($scope['count']===6,'Rollback scope mismatch.');$rollback=queue_call('campaigns/'.$id.'/rollback',['confirmed'=>true,'mode'=>'draft']);queue_expect(count($rollback)===6 && !array_filter($rollback,fn($r)=>!$r['ok']),'Rollback failure.');foreach($done['items'] as $item)queue_expect(get_post_status((int)$item['post_id'])==='draft','Rollback did not unpublish.');
 $results[]=['name'=>'scoped recoverable campaign rollback','status'=>'PASS','detail'=>'Only six posts owned by this campaign were returned to draft; extra job retained its draft.'];
}catch(Throwable $e){$results[]=['name'=>'queue recovery','status'=>'FAIL','detail'=>$e->getMessage()];fwrite(STDERR,$e->getMessage().PHP_EOL);exit(1);}finally{$report=['environment'=>'LOCAL / REAL WORDPRESS + ACTION SCHEDULER / CONTROLLED DATE AND CRASH FIXTURES','run'=>$run,'finished_at'=>gmdate('c'),'results'=>$results];file_put_contents(dirname(__DIR__,2).'/docs/content-upgrade/test-results/queue.json',json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));}
echo json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
