import 'server-only';
import bcrypt from 'bcryptjs';
import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {audit,digest} from './auth';
import {sendTransactionalEmail} from './brevo';
import {database,type Sql} from './db';
import {CrmError} from './permissions';
import type {Principal} from './types';

const factorCode=z.string().trim().regex(/^(?:\d{6}|[A-Z2-9]{4}-[A-Z2-9]{4})$/iu);
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function b32(bytes:Uint8Array){let bits='';for(const byte of bytes)bits+=byte.toString(2).padStart(8,'0');let result='';for(let i=0;i<bits.length;i+=5)result+=alphabet[Number.parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return result;}
function unb32(value:string){let bits='';for(const char of value.replaceAll('=','').toUpperCase()){const n=alphabet.indexOf(char);if(n<0)throw new CrmError('MFA_CODE_INVALID',401);bits+=n.toString(2).padStart(5,'0');}const out=[];for(let i=0;i+8<=bits.length;i+=8)out.push(Number.parseInt(bits.slice(i,i+8),2));return Buffer.from(out);}
function encryptionKey(){const value=process.env.CRM_MFA_ENCRYPTION_KEY;if(!value||value.length<32)throw new CrmError('MFA_NOT_CONFIGURED',503);return createHash('sha256').update(value).digest();}
function seal(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv),content=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),content].map(v=>v.toString('base64url')).join('.');}
function open(value:string){const parts=value.split('.').map(v=>Buffer.from(v,'base64url'));if(parts.length!==3)throw new CrmError('MFA_CONFIGURATION_INVALID',503);const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),parts[0]);decipher.setAuthTag(parts[1]);return Buffer.concat([decipher.update(parts[2]),decipher.final()]).toString('utf8');}
function hotp(secret:string,counter:number){const buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const hash=createHmac('sha1',unb32(secret)).update(buffer).digest(),offset=hash[19]&15,code=((hash[offset]&127)<<24|(hash[offset+1]&255)<<16|(hash[offset+2]&255)<<8|(hash[offset+3]&255))%1_000_000;return String(code).padStart(6,'0');}
export function totp(secret:string,at=Date.now()){return hotp(secret,Math.floor(at/30000));}
function constantText(a:string,b:string){const left=Buffer.from(a),right=Buffer.from(b);return left.length===right.length&&timingSafeEqual(left,right);}
async function activeFactor(sql:Sql,userId:string,lock=false){return(await sql.query<{id:string;secret_ciphertext:string;status:string;version:number}>(`SELECT id,secret_ciphertext,status,version FROM cohamy_crm.mfa_factors WHERE user_id=$1 AND status='ACTIVE'${lock?' FOR UPDATE':''}`,[userId])).rows[0];}
export async function verifySecondFactor(sql:Sql,userId:string,input:string){const value=factorCode.safeParse(input);if(!value.success)throw new CrmError('MFA_CODE_INVALID',401);const factor=await activeFactor(sql,userId,true);if(!factor)throw new CrmError('MFA_NOT_ENABLED',409);const normalized=value.data.toUpperCase();if(/^\d{6}$/u.test(normalized)){const secret=open(factor.secret_ciphertext),now=Date.now(),valid=[-1,0,1].some(step=>constantText(totp(secret,now+step*30000),normalized));if(!valid)throw new CrmError('MFA_CODE_INVALID',401);return {recovery:false};}const codeHash=digest(normalized),row=(await sql.query<{id:string}>('SELECT id FROM cohamy_crm.mfa_recovery_codes WHERE factor_id=$1 AND code_hash=$2 AND used_at IS NULL FOR UPDATE',[factor.id,codeHash])).rows[0];if(!row)throw new CrmError('MFA_CODE_INVALID',401);await sql.query('UPDATE cohamy_crm.mfa_recovery_codes SET used_at=now() WHERE id=$1',[row.id]);return {recovery:true};}

export async function mfaStatus(user:Principal){const db=await database(),factor=(await db.query<{id:string;status:string;version:number;confirmed_at:string|null}>('SELECT id,status,version,confirmed_at FROM cohamy_crm.mfa_factors WHERE user_id=$1',[user.id])).rows[0],remaining=factor?(await db.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.mfa_recovery_codes WHERE factor_id=$1 AND used_at IS NULL',[factor.id])).rows[0].n:'0';return {enabled:factor?.status==='ACTIVE',status:factor?.status??'NONE',version:factor?.version??0,confirmedAt:factor?.confirmed_at??null,recoveryCodesRemaining:Number(remaining)};}
export async function beginMfaEnrollment(user:Principal,input:unknown){const d=z.object({password:z.string().min(1).max(72)}).strict().safeParse(input);if(!d.success)throw new CrmError('INVALID_FIELDS',400);return(await database()).transaction(async sql=>{const account=(await sql.query<{password_hash:string;email:string}>('SELECT password_hash,email FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id])).rows[0];if(!account||!await bcrypt.compare(d.data.password,account.password_hash))throw new CrmError('INVALID_CREDENTIALS',400);const current=(await sql.query<{status:string}>('SELECT status FROM cohamy_crm.mfa_factors WHERE user_id=$1',[user.id])).rows[0];if(current?.status==='ACTIVE')throw new CrmError('MFA_ALREADY_ENABLED',409);const secret=b32(randomBytes(20)),id=randomUUID();await sql.query("INSERT INTO cohamy_crm.mfa_factors(id,user_id,status,secret_ciphertext) VALUES($1,$2,'PENDING',$3) ON CONFLICT(user_id) DO UPDATE SET status='PENDING',secret_ciphertext=excluded.secret_ciphertext,confirmed_at=NULL,version=cohamy_crm.mfa_factors.version+1,updated_at=now()",[id,user.id,seal(secret)]);await audit(sql,user.id,'mfa.enrollment-started',user.id);return {secret,otpauthUrl:`otpauth://totp/Cohamy:${encodeURIComponent(account.email)}?secret=${secret}&issuer=Cohamy&algorithm=SHA1&digits=6&period=30`};});}
export async function confirmMfaEnrollment(user:Principal,input:unknown){const d=z.object({code:z.string().trim().regex(/^\d{6}$/u),password:z.string().min(1).max(72)}).strict().safeParse(input);if(!d.success)throw new CrmError('INVALID_FIELDS',400);return(await database()).transaction(async sql=>{const account=(await sql.query<{password_hash:string}>('SELECT password_hash FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id])).rows[0],factor=(await sql.query<{id:string;secret_ciphertext:string;status:string}>('SELECT id,secret_ciphertext,status FROM cohamy_crm.mfa_factors WHERE user_id=$1 FOR UPDATE',[user.id])).rows[0];if(!account||!await bcrypt.compare(d.data.password,account.password_hash))throw new CrmError('INVALID_CREDENTIALS',400);if(!factor||factor.status!=='PENDING')throw new CrmError('MFA_ENROLLMENT_NOT_FOUND',409);if(!constantText(totp(open(factor.secret_ciphertext)),d.data.code))throw new CrmError('MFA_CODE_INVALID',401);const codes=Array.from({length:8},()=>b32(randomBytes(5)).slice(0,4)+'-'+b32(randomBytes(5)).slice(0,4));await sql.query('DELETE FROM cohamy_crm.mfa_recovery_codes WHERE factor_id=$1',[factor.id]);for(const code of codes)await sql.query('INSERT INTO cohamy_crm.mfa_recovery_codes(id,factor_id,code_hash) VALUES($1,$2,$3)',[randomUUID(),factor.id,digest(code)]);await sql.query("UPDATE cohamy_crm.mfa_factors SET status='ACTIVE',confirmed_at=now(),version=version+1,updated_at=now() WHERE id=$1",[factor.id]);await sql.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id IN(SELECT id FROM cohamy_crm.memberships WHERE user_id=$1) AND revoked_at IS NULL',[user.id]);await audit(sql,user.id,'mfa.enabled',user.id);return {enabled:true,recoveryCodes:codes,reauthenticate:true};});}
export async function disableMfa(user:Principal,input:unknown){const d=z.object({password:z.string().min(1).max(72),code:z.string().trim()}).strict().safeParse(input);if(!d.success)throw new CrmError('INVALID_FIELDS',400);return(await database()).transaction(async sql=>{const account=(await sql.query<{password_hash:string}>('SELECT password_hash FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id])).rows[0];if(!account||!await bcrypt.compare(d.data.password,account.password_hash))throw new CrmError('INVALID_CREDENTIALS',400);await verifySecondFactor(sql,user.id,d.data.code);await sql.query("UPDATE cohamy_crm.mfa_factors SET status='DISABLED',version=version+1,updated_at=now() WHERE user_id=$1",[user.id]);await sql.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id IN(SELECT id FROM cohamy_crm.memberships WHERE user_id=$1) AND revoked_at IS NULL',[user.id]);await audit(sql,user.id,'mfa.disabled',user.id);return {enabled:false,reauthenticate:true};});}

export async function requestPasswordReset(email:string){const normalized=z.email().parse(email.toLowerCase()),db=await database(),row=(await db.query<{id:string;email:string}>('SELECT id,email FROM cohamy_crm.users WHERE email=$1 AND active',[normalized])).rows[0];if(!row)return {accepted:true};const token=randomBytes(32).toString('base64url');await db.transaction(async sql=>{await sql.query('UPDATE cohamy_crm.password_reset_tokens SET used_at=now() WHERE user_id=$1 AND used_at IS NULL',[row.id]);await sql.query("INSERT INTO cohamy_crm.password_reset_tokens(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '30 minutes')",[randomUUID(),row.id,digest(token)]);await audit(sql,row.id,'password-reset.requested',row.id);});const origin=process.env.CRM_PUBLIC_ORIGIN;try{if(!origin?.startsWith('https://')&&process.env.CRM_ENVIRONMENT!=='LOCAL')throw new CrmError('CRM_HTTPS_ORIGIN_REQUIRED',503);await sendTransactionalEmail(row.email,'Đặt lại mật khẩu Cohamy',`Mở liên kết sau trong 30 phút để đặt lại mật khẩu: ${origin??'http://localhost:3000'}/crm/reset-password?token=${token}\nNếu bạn không yêu cầu, hãy bỏ qua email này.`);}catch(error){await db.transaction(sql=>audit(sql,row.id,'password-reset.delivery-failed',row.id,{code:error instanceof CrmError?error.code:'DELIVERY_FAILED'}));}return {accepted:true,...(process.env.CRM_ENVIRONMENT==='LOCAL'?{qaToken:token}:{})};}
export async function resetPassword(input:unknown){const d=z.object({token:z.string().regex(/^[A-Za-z0-9_-]{43}$/u),newPassword:z.string().min(12).max(72),secondFactor:z.string().trim().optional()}).strict().safeParse(input);if(!d.success)throw new CrmError('INVALID_FIELDS',400);return(await database()).transaction(async sql=>{const row=(await sql.query<{id:string;user_id:string}>('SELECT id,user_id FROM cohamy_crm.password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() FOR UPDATE',[digest(d.data.token)])).rows[0];if(!row)throw new CrmError('RESET_TOKEN_INVALID',400);const factor=await activeFactor(sql,row.user_id);if(factor){if(!d.data.secondFactor)throw new CrmError('MFA_REQUIRED',428);await verifySecondFactor(sql,row.user_id,d.data.secondFactor);}await sql.query('UPDATE cohamy_crm.users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(d.data.newPassword,12),row.user_id]);await sql.query('UPDATE cohamy_crm.password_reset_tokens SET used_at=now() WHERE id=$1',[row.id]);await sql.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id IN(SELECT id FROM cohamy_crm.memberships WHERE user_id=$1) AND revoked_at IS NULL',[row.user_id]);await audit(sql,row.user_id,'password-reset.completed',row.user_id,{mfaVerified:Boolean(factor)});return {reset:true};});}
