import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit,membershipPrincipal,digest} from './auth';
import {assertPermission,CrmError} from './permissions';
import {entityAccess,enqueueNotification,parse} from './workspace';
import {createTaskInTransaction} from './work';
import type {Principal} from './types';
const kinds=['GENERAL','FOLLOW_UP','SUPPORT','APPROVAL'] as const;
export const careKindLabels:Record<string,string>={GENERAL:'Công việc chung',FOLLOW_UP:'Chăm sóc',SUPPORT:'Hỗ trợ',APPROVAL:'Xét duyệt'};
function writer(user:Principal){if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);assertPermission(user,'partners.write');}
function manager(user:Principal){writer(user);if(!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);}
export async function lockCare(sql:Sql){await sql.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');}
async function fresh(sql:Sql,id:string){await sql.query('SELECT m.id FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.id=$1 FOR SHARE OF m,u,o',[id]);const p=await membershipPrincipal(id,sql);if(!p)throw new CrmError('ACTION_USER_INACTIVE',409);return p;}
async function activeSource(sql:Sql,user:Principal,type:'partner'|'order',id:string){
 await sql.query(`SELECT id FROM cohamy_crm.${type==='partner'?'organizations':'website_orders'} WHERE id=$1 FOR SHARE`,[id]);
 const p=await entityAccess(user,type,id,sql);if('active' in p&&!p.active)throw new CrmError('SOURCE_INACTIVE',409);return p;
}
async function assignee(sql:Sql,user:Principal,id:string,type:'partner'|'order',entityId:string){const p=await fresh(sql,id);writer(p);if(id!==user.membershipId)manager(user);await activeSource(sql,p,type,entityId);return p;}
export interface CareSchedule{id:string;creator_membership_id:string;entity_type:'partner'|'order';entity_id:string;title:string;assignee_id:string;care_kind:string;frequency:'DAILY'|'WEEKLY'|'MONTHLY';every:number;anchor_day:number;next_due_at:string;enabled:boolean;error_code:string;version:number;assignee_name:string}
export function nextCareOccurrence(frequency:CareSchedule['frequency'],every:number,anchorDay:number,due:Date){
 const local=new Date(due.getTime()+7*3600000);
 if(frequency==='MONTHLY'){
  const first=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth()+every,1)),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();
  local.setUTCDate(1);local.setUTCFullYear(first.getUTCFullYear(),first.getUTCMonth(),Math.min(anchorDay,last));
 }else local.setUTCDate(local.getUTCDate()+every*(frequency==='WEEKLY'?7:1));
 return new Date(local.getTime()-7*3600000);
}
export async function careSchedules(user:Principal){writer(user);const rows=(await(await database()).query<CareSchedule>(`SELECT s.*,u.display_name AS assignee_name FROM cohamy_crm.care_schedules s JOIN cohamy_crm.memberships m ON m.id=s.assignee_id JOIN cohamy_crm.users u ON u.id=m.user_id WHERE creator_membership_id=$1 OR $2 ORDER BY next_due_at,id`,[user.membershipId,['ADMIN','MANAGER'].includes(user.role)])).rows;const result=[];for(const s of rows){try{await entityAccess(user,s.entity_type,s.entity_id);result.push(s);}catch(e){if(!(e instanceof CrmError)||![403,404].includes(e.status))throw e;}}return result;}
const scheduleSchema=z.object({id:z.uuid().optional(),version:z.number().int().min(0),entityType:z.enum(['partner','order']),entityId:z.uuid(),title:z.string().trim().min(2).max(240),assigneeId:z.uuid(),kind:z.enum(kinds),frequency:z.enum(['DAILY','WEEKLY','MONTHLY']),every:z.number().int().min(1).max(52),nextDueAt:z.iso.datetime({offset:true}),enabled:z.boolean()}).strict();
export async function saveCareSchedule(user:Principal,input:unknown){writer(user);const d=parse(scheduleSchema,input);const due=new Date(d.nextDueAt);if(due.getTime()<Date.now()-7*86400000||due.getTime()>Date.now()+2*366*86400000)throw new CrmError('SCHEDULE_DATE_RANGE',400);
 return(await database()).transaction(async tx=>{
  await lockCare(tx);const current=await fresh(tx,user.membershipId);writer(current);await activeSource(tx,current,d.entityType,d.entityId);await assignee(tx,current,d.assigneeId,d.entityType,d.entityId);
  const id=d.id??randomUUID();let before:CareSchedule|null=null;
  if(d.version===0){if(d.id)throw new CrmError('INVALID_FIELDS',400);if(Number((await tx.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.care_schedules WHERE creator_membership_id=$1',[current.membershipId])).rows[0].n)>=100)throw new CrmError('SCHEDULE_LIMIT',409);}
  else{before=(await tx.query<CareSchedule>('SELECT * FROM cohamy_crm.care_schedules WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!before)throw new CrmError('NOT_FOUND',404);if(before.creator_membership_id!==current.membershipId)manager(current);if(before.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(before.entity_type!==d.entityType||before.entity_id!==d.entityId)throw new CrmError('SOURCE_IMMUTABLE',409);}
  const anchor=new Date(due.getTime()+7*3600000).getUTCDate();
  if(before)await tx.query("UPDATE cohamy_crm.care_schedules SET title=$1,assignee_id=$2,care_kind=$3,frequency=$4,every=$5,anchor_day=$6,next_due_at=$7,enabled=$8,error_code='',version=version+1 WHERE id=$9",[d.title,d.assigneeId,d.kind,d.frequency,d.every,anchor,d.nextDueAt,d.enabled,id]);
  else await tx.query('INSERT INTO cohamy_crm.care_schedules(id,creator_membership_id,entity_type,entity_id,title,assignee_id,care_kind,frequency,every,anchor_day,next_due_at,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[id,current.membershipId,d.entityType,d.entityId,d.title,d.assigneeId,d.kind,d.frequency,d.every,anchor,d.nextDueAt,d.enabled]);
  await audit(tx,current.id,'care.schedule-saved',d.entityId,{scheduleId:id,before:before&&{title:before.title,frequency:before.frequency,every:before.every,nextDueAt:before.next_due_at,enabled:before.enabled},after:{title:d.title,frequency:d.frequency,every:d.every,nextDueAt:d.nextDueAt,enabled:d.enabled},reason:'Lịch công việc do người phụ trách cấu hình.'});return {id,version:d.version+1};
 });
}
export async function scheduleRuns(user:Principal,id:string){const schedule=(await careSchedules(user)).find(s=>s.id===id);if(!schedule)throw new CrmError('NOT_FOUND',404);return(await(await database()).query<{id:string;task_id:string|null;scheduled_at:string;status:string;error_code:string;definition_version:number}>('SELECT * FROM cohamy_crm.care_schedule_runs WHERE schedule_id=$1 ORDER BY created_at DESC,id DESC LIMIT 50',[id])).rows;}
async function runSchedule(){return(await database()).transaction(async tx=>{
 await lockCare(tx);const s=(await tx.query<CareSchedule>('SELECT * FROM cohamy_crm.care_schedules WHERE enabled AND next_due_at<=now() ORDER BY next_due_at,id LIMIT 1 FOR UPDATE SKIP LOCKED')).rows[0];if(!s)return false;
 const next=nextCareOccurrence(s.frequency,s.every,s.anchor_day,new Date(s.next_due_at));
 if(!(await tx.query('SELECT id FROM cohamy_crm.care_schedule_runs WHERE schedule_id=$1 AND scheduled_at=$2 AND status=\'SUCCEEDED\'',[s.id,s.next_due_at])).rows.length){
  await tx.exec('SAVEPOINT care_effect');
  try{const creator=await fresh(tx,s.creator_membership_id);writer(creator);await activeSource(tx,creator,s.entity_type,s.entity_id);await assignee(tx,creator,s.assignee_id,s.entity_type,s.entity_id);const task=await createTaskInTransaction(creator,{entityType:s.entity_type,entityId:s.entity_id,title:s.title,assigneeId:s.assignee_id,dueAt:new Date(s.next_due_at).toISOString(),kind:s.care_kind},tx);
   await tx.query("INSERT INTO cohamy_crm.care_schedule_runs(id,schedule_id,scheduled_at,definition_version,status,task_id) VALUES ($1,$2,$3,$4,'SUCCEEDED',$5)",[randomUUID(),s.id,s.next_due_at,s.version,task.id]);await tx.exec('RELEASE SAVEPOINT care_effect');
  }catch(e){await tx.exec('ROLLBACK TO SAVEPOINT care_effect');await tx.exec('RELEASE SAVEPOINT care_effect');if(!(e instanceof CrmError))throw e;await tx.query("INSERT INTO cohamy_crm.care_schedule_runs(id,schedule_id,scheduled_at,definition_version,status,error_code) VALUES ($1,$2,$3,$4,'BLOCKED',$5)",[randomUUID(),s.id,s.next_due_at,s.version,e.code]);await tx.query('UPDATE cohamy_crm.care_schedules SET enabled=false,error_code=$1,version=version+1 WHERE id=$2',[e.code,s.id]);return true;}
 }
 await tx.query('UPDATE cohamy_crm.care_schedules SET next_due_at=$1,version=version+1 WHERE id=$2',[next.toISOString(),s.id]);return true;
});}
export interface CareRule{id:string;name:string;event_action:string;title:string;care_kind:string;assignee_id:string;created_by:string;due_minutes:number;enabled:boolean;version:number;assignee_name:string}
export async function careRules(user:Principal){manager(user);return(await(await database()).query<CareRule>('SELECT r.*,u.display_name AS assignee_name FROM cohamy_crm.care_task_rules r JOIN cohamy_crm.memberships m ON m.id=r.assignee_id JOIN cohamy_crm.users u ON u.id=m.user_id ORDER BY name,id LIMIT 100')).rows;}
export async function saveCareRule(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(2).max(120),eventAction:z.enum(['application.approved','partner.created']),title:z.string().trim().min(2).max(240),kind:z.enum(kinds),assigneeId:z.uuid(),dueMinutes:z.number().int().min(1).max(525600),enabled:z.boolean()}).strict(),input);
 return(await database()).transaction(async tx=>{await lockCare(tx);manager(await fresh(tx,user.membershipId));writer(await fresh(tx,d.assigneeId));const id=d.id??randomUUID();
  if(d.version===0){if(d.id)throw new CrmError('INVALID_FIELDS',400);if(Number((await tx.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.care_task_rules')).rows[0].n)>=100)throw new CrmError('CARE_CONFIG_LIMIT',409);await tx.query('INSERT INTO cohamy_crm.care_task_rules(id,name,event_action,title,care_kind,assignee_id,created_by,due_minutes,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,d.name,d.eventAction,d.title,d.kind,d.assigneeId,user.membershipId,d.dueMinutes,d.enabled]);}
  else{const old=(await tx.query<CareRule>('SELECT * FROM cohamy_crm.care_task_rules WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!old)throw new CrmError('NOT_FOUND',404);if(old.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(old.event_action!==d.eventAction)throw new CrmError('SOURCE_IMMUTABLE',409);await tx.query('UPDATE cohamy_crm.care_task_rules SET name=$1,title=$2,care_kind=$3,assignee_id=$4,due_minutes=$5,activated_at=CASE WHEN NOT enabled AND $6 THEN now() ELSE activated_at END,enabled=$6,version=version+1 WHERE id=$7',[d.name,d.title,d.kind,d.assigneeId,d.dueMinutes,d.enabled,id]);}
  await audit(tx,user.id,'care.rule-saved',id,{after:{name:d.name,eventAction:d.eventAction,enabled:d.enabled},reason:'Mẫu áp dụng cho sự kiện từ thời điểm kích hoạt.'});return {id};
 });
}
export async function ruleRuns(user:Principal,id:string){manager(user);return(await(await database()).query<{task_id:string|null;status:string;error_code:string;created_at:string;rule_version:number}>('SELECT * FROM cohamy_crm.care_rule_runs WHERE rule_id=$1 ORDER BY created_at DESC,event_id DESC LIMIT 50',[parse(z.uuid(),id)])).rows;}
async function runRule(){return(await database()).transaction(async tx=>{
 await lockCare(tx);const row=(await tx.query<CareRule&{event_id:string;source_id:string;payload:{organizationId?:string};event_time:string}>(`SELECT r.*,a.id AS event_id,a.entity_id AS source_id,a.payload,a.created_at AS event_time FROM cohamy_crm.care_task_rules r JOIN cohamy_crm.audit_events a ON a.action=r.event_action AND a.created_at>=r.activated_at WHERE r.enabled AND NOT EXISTS(SELECT 1 FROM cohamy_crm.care_rule_runs x WHERE x.rule_id=r.id AND x.event_id=a.id) ORDER BY a.created_at,a.id,r.id LIMIT 1 FOR UPDATE OF r SKIP LOCKED`)).rows[0];if(!row)return false;
 const entityId=row.event_action==='application.approved'?row.payload.organizationId:row.source_id;if(!entityId||!z.uuid().safeParse(entityId).success)throw new Error('CARE_EVENT_SOURCE_INVALID');
 await tx.exec('SAVEPOINT care_effect');let taskId:string|null=null,error='';
 try{const creator=await fresh(tx,row.created_by);manager(creator);await activeSource(tx,creator,'partner',entityId);await assignee(tx,creator,row.assignee_id,'partner',entityId);taskId=(await createTaskInTransaction(creator,{entityType:'partner',entityId,title:row.title,assigneeId:row.assignee_id,kind:row.care_kind,dueAt:new Date(new Date(row.event_time).getTime()+row.due_minutes*60000).toISOString()},tx)).id;await tx.exec('RELEASE SAVEPOINT care_effect');}
 catch(e){await tx.exec('ROLLBACK TO SAVEPOINT care_effect');await tx.exec('RELEASE SAVEPOINT care_effect');if(!(e instanceof CrmError))throw e;error=e.code;}
 await tx.query('INSERT INTO cohamy_crm.care_rule_runs(rule_id,event_id,rule_version,entity_id,task_id,status,error_code) VALUES ($1,$2,$3,$4,$5,$6,$7)',[row.id,row.event_id,row.version,entityId,taskId,taskId?'SUCCEEDED':'BLOCKED',error]);return true;
});}
export interface SlaPolicy{id:string;name:string;care_kind:string;delay_minutes:number;recipient_id:string;enabled:boolean;version:number;recipient_name:string}
export async function slaPolicies(user:Principal){manager(user);return(await(await database()).query<SlaPolicy>('SELECT p.*,u.display_name AS recipient_name FROM cohamy_crm.care_sla_policies p JOIN cohamy_crm.memberships m ON m.id=p.recipient_id JOIN cohamy_crm.users u ON u.id=m.user_id ORDER BY name,id LIMIT 100')).rows;}
export async function saveSlaPolicy(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(2).max(120),kind:z.enum(kinds),delayMinutes:z.number().int().min(0).max(525600),recipientId:z.uuid(),enabled:z.boolean()}).strict(),input);
 return(await database()).transaction(async tx=>{await lockCare(tx);manager(await fresh(tx,user.membershipId));manager(await fresh(tx,d.recipientId));const id=d.id??randomUUID();if(d.version===0){if(d.id)throw new CrmError('INVALID_FIELDS',400);if(Number((await tx.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.care_sla_policies')).rows[0].n)>=100)throw new CrmError('CARE_CONFIG_LIMIT',409);}const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.care_sla_policies(id,name,care_kind,delay_minutes,recipient_id,enabled) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id',[id,d.name,d.kind,d.delayMinutes,d.recipientId,d.enabled]):await tx.query('UPDATE cohamy_crm.care_sla_policies SET name=$1,care_kind=$2,delay_minutes=$3,recipient_id=$4,enabled=$5,version=version+1 WHERE id=$6 AND version=$7 RETURNING id',[d.name,d.kind,d.delayMinutes,d.recipientId,d.enabled,id,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'care.sla-saved',id,{after:{name:d.name,kind:d.kind,delayMinutes:d.delayMinutes,enabled:d.enabled},reason:'Chuyển cấp sau hạn của việc; người nhận được cấu hình rõ.'});return {id};});
}
export async function escalations(user:Principal){manager(user);return(await(await database()).query<{task_id:string;title:string;policy_name:string;recipient_name:string;deadline:string;created_at:string}>(`SELECT e.*,t.title,p.name AS policy_name,u.display_name AS recipient_name FROM cohamy_crm.care_escalations e JOIN cohamy_crm.tasks t ON t.id=e.task_id JOIN cohamy_crm.care_sla_policies p ON p.id=e.policy_id JOIN cohamy_crm.memberships m ON m.id=e.recipient_id JOIN cohamy_crm.users u ON u.id=m.user_id ORDER BY e.created_at DESC,e.task_id LIMIT 100`)).rows;}
async function runSla(){return(await database()).transaction(async tx=>{
 await lockCare(tx);const r=(await tx.query<SlaPolicy&{task_id:string;title:string;entity_type:'partner'|'order';entity_id:string;deadline:string}>(`SELECT p.*,t.id AS task_id,t.title,t.entity_type,t.entity_id,t.due_at+p.delay_minutes*interval '1 minute' AS deadline FROM cohamy_crm.care_sla_policies p JOIN cohamy_crm.tasks t ON t.care_kind=p.care_kind WHERE p.enabled AND t.done_at IS NULL AND t.due_at+p.delay_minutes*interval '1 minute'<=now() AND NOT EXISTS(SELECT 1 FROM cohamy_crm.care_escalations e WHERE e.task_id=t.id AND e.policy_id=p.id) ORDER BY t.due_at,t.id,p.id LIMIT 1 FOR UPDATE OF p,t SKIP LOCKED`)).rows[0];if(!r)return false;
 let recipient:Principal;
 try{recipient=await fresh(tx,r.recipient_id);manager(recipient);await activeSource(tx,recipient,r.entity_type,r.entity_id);}
 catch(e){if(!(e instanceof CrmError))throw e;await tx.query('UPDATE cohamy_crm.care_sla_policies SET enabled=false,version=version+1 WHERE id=$1',[r.id]);await audit(tx,null,'care.sla-blocked',r.id,{reason:e.code});return true;}
 await enqueueNotification(tx,recipient.id,'care-sla:'+r.id+':'+r.task_id,'TASK',r.entity_type,r.entity_id,'Chuyển cấp: '+r.title+' · '+r.name);
 await tx.query('INSERT INTO cohamy_crm.care_escalations(policy_id,task_id,policy_version,recipient_id,deadline) VALUES ($1,$2,$3,$4,$5)',[r.id,r.task_id,r.version,recipient.membershipId,r.deadline]);await audit(tx,null,'care.escalated',r.entity_id,{taskId:r.task_id,recipientId:recipient.membershipId,policyVersion:r.version,reason:r.name});return true;
});}
export async function runCareAutomation(limit=20){let worked=0;for(let i=0;i<Math.max(1,Math.min(100,limit));i++){const results=[await runSchedule(),await runRule(),await runSla()];worked+=results.filter(Boolean).length;if(!results.some(Boolean))break;}return worked;}
export async function readCareTask(user:Principal,id:string,sql?:Sql){writer(user);const row=(await(sql??await database()).query<{id:string;entity_type:'partner'|'order';entity_id:string;assignee_id:string;title:string;version:number;done_at:string|null}>('SELECT * FROM cohamy_crm.tasks WHERE id=$1',[parse(z.uuid(),id)])).rows[0];if(!row)throw new CrmError('NOT_FOUND',404);await entityAccess(user,row.entity_type,row.entity_id,sql);return row;}
export async function taskWatchers(user:Principal,id:string){await readCareTask(user,id);return(await(await database()).query<{membership_id:string;name:string}>('SELECT w.membership_id,u.display_name AS name FROM cohamy_crm.task_watchers w JOIN cohamy_crm.memberships m ON m.id=w.membership_id JOIN cohamy_crm.users u ON u.id=m.user_id WHERE task_id=$1 AND m.active AND u.active ORDER BY u.display_name',[id])).rows;}
export async function followTask(user:Principal,input:unknown){writer(user);const d=parse(z.object({taskId:z.uuid(),follow:z.boolean()}).strict(),input);return(await database()).transaction(async tx=>{await lockCare(tx);const current=await fresh(tx,user.membershipId);await readCareTask(current,d.taskId,tx);if(d.follow)await tx.query('INSERT INTO cohamy_crm.task_watchers(task_id,membership_id,user_id) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING',[d.taskId,current.membershipId,current.id]);else await tx.query('DELETE FROM cohamy_crm.task_watchers WHERE task_id=$1 AND membership_id=$2',[d.taskId,current.membershipId]);await audit(tx,current.id,d.follow?'task.followed':'task.unfollowed',d.taskId);return {following:d.follow};});}
export async function notifyTaskWatchers(sql:Sql,task:{id:string;entity_type:'partner'|'order';entity_id:string;title:string;version:number},done:boolean){
 const rows=(await sql.query<{membership_id:string}>('SELECT membership_id FROM cohamy_crm.task_watchers WHERE task_id=$1',[task.id])).rows;
 for(const w of rows){const p=await membershipPrincipal(w.membership_id,sql);if(!p)continue;try{writer(p);await entityAccess(p,task.entity_type,task.entity_id,sql);}catch(e){if(!(e instanceof CrmError)||![403,404].includes(e.status))throw e;continue;}await enqueueNotification(sql,p.id,'task-watch:'+task.id+':'+(task.version+1),'TASK',task.entity_type,task.entity_id,(done?'Đã hoàn thành: ':'Mở lại công việc: ')+task.title);}
}
export async function recordMentions(sql:Sql,actor:Principal,activityId:string,type:'partner'|'order',entityId:string,ids:string[]){
 for(const id of [...new Set(ids)].sort()){const p=await fresh(sql,id);if(p.area!=='crm')throw new CrmError('INVALID_MENTION',400);await entityAccess(p,type,entityId,sql);await sql.query('INSERT INTO cohamy_crm.activity_mentions(activity_id,membership_id) VALUES ($1,$2)',[activityId,id]);await enqueueNotification(sql,p.id,'activity-mention:'+activityId,'TASK',type,entityId,actor.displayName+' nhắc bạn trong ghi chú chăm sóc.');}
}
export async function mentionCandidates(user:Principal,type:'partner'|'order',id:string){writer(user);await entityAccess(user,type,id);const sql=await database(),rows=(await sql.query<{id:string;name:string;role:string}>('SELECT m.id,u.display_name AS name,m.role FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.active AND u.active AND o.active AND o.kind=\'COHAMY\' ORDER BY u.display_name,m.id')).rows,result=[];
 for(const r of rows){const p=await membershipPrincipal(r.id,sql);if(!p)continue;try{await entityAccess(p,type,id,sql);result.push(r);}catch(e){if(!(e instanceof CrmError)||![403,404].includes(e.status))throw e;}}return result;
}
type HandoverManifest={memberships:{id:string;version:number}[];partners:{id:string;version:number;name:string}[];orders:{id:string;version:number;code:string}[];tasks:{id:string;version:number;title:string}[];schedules:{id:string;version:number;title:string}[];rules:{id:string;version:number;name:string}[];sessions:number};
function canonicalJson(value:unknown):string{const normalize=(item:unknown):unknown=>Array.isArray(item)?item.map(normalize):item&&typeof item==='object'?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b)).map(([key,v])=>[key,normalize(v)])):item;return JSON.stringify(normalize(value));}
async function handoverManifest(sql:Sql,from:string,to:string):Promise<HandoverManifest>{
 for(const id of [from,to].sort()){const p=await fresh(sql,id);if(p.area!=='crm'||p.role!=='SALES')throw new CrmError('HANDOVER_SALES_ONLY',400);}
 const memberships=(await sql.query<{id:string;version:number}>('SELECT id,version FROM cohamy_crm.memberships WHERE id=ANY($1::uuid[]) ORDER BY id',[[from,to]])).rows;
 const partners=(await sql.query<HandoverManifest['partners'][number]>('SELECT o.id,o.version,o.name FROM cohamy_crm.partner_assignments a JOIN cohamy_crm.organizations o ON o.id=a.organization_id WHERE a.membership_id=$1 ORDER BY o.id',[from])).rows;
 const orders=(await sql.query<HandoverManifest['orders'][number]>('SELECT id,version,code FROM cohamy_crm.website_orders WHERE assigned_to=$1 ORDER BY id',[from])).rows;
 const tasks=(await sql.query<HandoverManifest['tasks'][number]>('SELECT id,version,title FROM cohamy_crm.tasks WHERE assignee_id=$1 AND done_at IS NULL ORDER BY id',[from])).rows;
 const schedules=(await sql.query<HandoverManifest['schedules'][number]>('SELECT id,version,title FROM cohamy_crm.care_schedules WHERE assignee_id=$1 OR creator_membership_id=$1 ORDER BY id',[from])).rows;
 const rules=(await sql.query<HandoverManifest['rules'][number]>('SELECT id,version,name FROM cohamy_crm.care_task_rules WHERE assignee_id=$1 ORDER BY id',[from])).rows;
 if([partners,orders,tasks,schedules,rules].some(r=>r.length>500))throw new CrmError('HANDOVER_LIMIT',409);
 const sessions=Number((await sql.query<{n:string}>('SELECT count(*)::text AS n FROM cohamy_crm.sessions WHERE membership_id=$1 AND revoked_at IS NULL AND expires_at>now()',[from])).rows[0].n);
 return {memberships,partners,orders,tasks,schedules,rules,sessions};
}
export async function handoverPreview(user:Principal,input:unknown){manager(user);const d=parse(z.object({fromId:z.uuid(),toId:z.uuid(),reason:z.string().trim().min(3).max(1000)}).strict(),input);if(d.fromId===d.toId)throw new CrmError('INVALID_FIELDS',400);
 return(await database()).transaction(async tx=>{await lockCare(tx);manager(await fresh(tx,user.membershipId));const manifest=await handoverManifest(tx,d.fromId,d.toId),id=randomUUID();await tx.query('INSERT INTO cohamy_crm.care_handover_previews(id,user_id,from_id,to_id,reason,manifest) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[id,user.id,d.fromId,d.toId,d.reason,JSON.stringify(manifest)]);return {id,manifest,expiresInMinutes:10};});
}
export async function handoverConfirm(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid()}).strict(),input);return(await database()).transaction(async tx=>{
 await lockCare(tx);manager(await fresh(tx,user.membershipId));const p=(await tx.query<{from_id:string;to_id:string;reason:string;manifest:HandoverManifest;expires_at:string;result:unknown}>('SELECT * FROM cohamy_crm.care_handover_previews WHERE id=$1 AND user_id=$2 FOR UPDATE',[d.id,user.id])).rows[0];if(!p)throw new CrmError('NOT_FOUND',404);if(p.result)return p.result;if(new Date(p.expires_at).getTime()<=Date.now())throw new CrmError('PREVIEW_EXPIRED',409);
 // Assignment and new-work writers take the same care lock before evaluating scope.
 await tx.query('SELECT id FROM cohamy_crm.memberships WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE',[[p.from_id,p.to_id]]);
 for(const [table,records] of [['organizations',p.manifest.partners],['website_orders',p.manifest.orders],['tasks',p.manifest.tasks],['care_schedules',p.manifest.schedules],['care_task_rules',p.manifest.rules]] as const){for(const r of records)await tx.query(`SELECT id FROM cohamy_crm.${table} WHERE id=$1 FOR UPDATE`,[r.id]);}
 const current=await handoverManifest(tx,p.from_id,p.to_id);
 // Login/logout does not invalidate a business preview; business versions and sets do.
 if(digest(canonicalJson({...current,sessions:0}))!==digest(canonicalJson({...p.manifest,sessions:0})))throw new CrmError('VERSION_CONFLICT',409);
 const target=await fresh(tx,p.to_id);
 for(const t of current.tasks){const task=await readCareTask(user,t.id,tx);if(task.entity_type==='partner'&&!current.partners.some(r=>r.id===task.entity_id))await entityAccess(target,'partner',task.entity_id,tx);if(task.entity_type==='order'&&!current.orders.some(r=>r.id===task.entity_id))await entityAccess(target,'order',task.entity_id,tx);}
 for(const o of current.partners)await tx.query('INSERT INTO cohamy_crm.partner_assignments(membership_id,organization_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',[p.to_id,o.id]);
 await tx.query('DELETE FROM cohamy_crm.partner_assignments WHERE membership_id=$1',[p.from_id]);
 await tx.query('UPDATE cohamy_crm.website_orders SET assigned_to=$1,version=version+1,updated_at=now() WHERE assigned_to=$2',[p.to_id,p.from_id]);
 await tx.query('UPDATE cohamy_crm.tasks SET assignee_id=$1,version=version+1 WHERE assignee_id=$2 AND done_at IS NULL',[p.to_id,p.from_id]);
 await tx.query('UPDATE cohamy_crm.care_schedules SET assignee_id=CASE WHEN assignee_id=$2 THEN $1 ELSE assignee_id END,creator_membership_id=CASE WHEN creator_membership_id=$2 THEN $1 ELSE creator_membership_id END,version=version+1 WHERE assignee_id=$2 OR creator_membership_id=$2',[p.to_id,p.from_id]);
 await tx.query('UPDATE cohamy_crm.care_task_rules SET assignee_id=$1,version=version+1 WHERE assignee_id=$2',[p.to_id,p.from_id]);
 await tx.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id=$1 AND revoked_at IS NULL',[p.from_id]);
 await tx.query('UPDATE cohamy_crm.memberships SET version=version+1 WHERE id=ANY($1::uuid[])',[[p.from_id,p.to_id]]);
 const result={partners:current.partners.length,orders:current.orders.length,tasks:current.tasks.length,schedules:current.schedules.length,rules:current.rules.length,revokedSessions:current.sessions};
 await audit(tx,user.id,'care.handover',p.from_id,{previewId:d.id,before:{responsible:p.from_id},after:{responsible:p.to_id,...result},reason:p.reason});await tx.query('UPDATE cohamy_crm.care_handover_previews SET result=$1::jsonb,completed_at=now() WHERE id=$2',[JSON.stringify(result),d.id]);return result;
});}
