import 'server-only';
import {createHmac,randomUUID,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {database} from './db';
import {assertCurrentPrincipal,audit} from './auth';
import {CrmError} from './permissions';
import {commercialDigest as digest,parseCommercial as parse} from './commercial-common';
import type {Principal} from './types';
const statuses=['CREATED','PICKED_UP','IN_TRANSIT','DELIVERED','FAILED','RETURNING','RETURNED'] as const;
function secret(code:string){return process.env['CARRIER_WEBHOOK_SECRET_'+code.toUpperCase().replace(/[^A-Z0-9]/g,'_')]??'';}
export async function saveCarrierConnection(user:Principal,input:unknown){
 if(user.area!=='crm'||!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),code:z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/),name:z.string().trim().min(2).max(120),enabled:z.boolean(),idempotencyKey:z.uuid()}).strict(),input),h=digest(d);if(d.enabled&&!secret(d.code))throw new CrmError('CARRIER_SECRET_UNAVAILABLE',409);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const old=(await sql.query<{request_hash:string;result:unknown}>('SELECT request_hash,result FROM cohamy_crm.fulfillment_actions WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(old){if(old.request_hash!==h)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return old.result;}const current=(await sql.query<{id:string;version:number}>('SELECT id,version FROM cohamy_crm.carrier_connections WHERE code=$1 FOR UPDATE',[d.code])).rows[0];if((current?.version??0)!==d.version||d.id&&d.id!==current?.id)throw new CrmError('VERSION_CONFLICT',409);const id=current?.id??randomUUID();await sql.query('INSERT INTO cohamy_crm.carrier_connections(id,code,name,enabled) VALUES($1,$2,$3,$4) ON CONFLICT(code) DO UPDATE SET name=excluded.name,enabled=excluded.enabled,version=cohamy_crm.carrier_connections.version+1,updated_at=now()',[id,d.code,d.name,d.enabled]);const result={id,version:d.version+1,enabled:d.enabled};await sql.query("INSERT INTO cohamy_crm.fulfillment_actions(id,action,resource_id,actor_id,idempotency_key,request_hash,result) VALUES($1,'CARRIER_CONNECTION_SAVED',$2,$3,$4,$5,$6::jsonb)",[randomUUID(),id,user.id,d.idempotencyKey,h,JSON.stringify(result)]);await audit(sql,user.id,'delivery.carrier-connection',id,{after:{code:d.code,name:d.name,enabled:d.enabled}});return result;});
}
export async function carrierCallback(code:string,eventId:string,raw:Uint8Array,signature:string){
 const normalized=parse(z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/),code),id=parse(z.string().trim().min(1).max(200),eventId),value=secret(normalized);if(!value)throw new CrmError('CARRIER_UNAVAILABLE',503);const expected=createHmac('sha256',value).update(raw).digest('hex'),provided=signature.replace(/^sha256=/,'').toLowerCase();if(!/^[a-f0-9]{64}$/.test(provided)||!timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(provided,'hex')))throw new CrmError('CARRIER_SIGNATURE_INVALID',401);let json:unknown;try{json=JSON.parse(Buffer.from(raw).toString('utf8'));}catch{throw new CrmError('INVALID_FIELDS',400);}const d=parse(z.object({parcelCode:z.string().trim().min(1).max(120),status:z.enum(statuses),trackingCode:z.string().trim().max(120).nullable().default(null)}).strict(),json);
 return(await database()).transaction(async sql=>{const connection=(await sql.query<{id:string;enabled:boolean}>('SELECT id,enabled FROM cohamy_crm.carrier_connections WHERE code=$1 FOR SHARE',[normalized])).rows[0];if(!connection?.enabled)throw new CrmError('CARRIER_UNAVAILABLE',503);const duplicate=(await sql.query<{id:string;status:string}>('SELECT id,status FROM cohamy_crm.carrier_events WHERE connection_id=$1 AND provider_event_id=$2',[connection.id,id])).rows[0];if(duplicate)return {id:duplicate.id,status:duplicate.status,replayed:true};const parcel=(await sql.query<{id:string}>('SELECT id FROM cohamy_crm.delivery_parcels WHERE code=$1 FOR UPDATE',[d.parcelCode])).rows[0];if(!parcel)throw new CrmError('NOT_FOUND',404);const latest=(await sql.query<{status:string}>('SELECT status FROM cohamy_crm.carrier_events WHERE parcel_id=$1 AND connection_id=$2 AND verified AND NOT manual ORDER BY created_at DESC,id DESC LIMIT 1',[parcel.id,connection.id])).rows[0];if(latest&&statuses.indexOf(d.status)<statuses.indexOf(latest.status as typeof statuses[number]))throw new CrmError('CARRIER_EVENT_OUT_OF_ORDER',409);const resultId=randomUUID();await sql.query('INSERT INTO cohamy_crm.carrier_events(id,parcel_id,connection_id,provider_event_id,status,tracking_code,verified,manual,payload) VALUES($1,$2,$3,$4,$5,$6,true,false,$7::jsonb)',[resultId,parcel.id,connection.id,id,d.status,d.trackingCode,JSON.stringify(d)]);return {id:resultId,status:d.status,replayed:false};});
}
