import 'server-only';
import ExcelJS from 'exceljs';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit,digest,membershipPrincipal} from './auth';
import {CrmError,assertPermission} from './permissions';
import {parse} from './workspace';
import {organizationSchema,partnerScope,getOrganization} from './repository';
import type {Principal} from './types';
const columns=['code','name','phone','email','address','contactName','source','segment','businessId'] as const;
const columnLabels:Record<string,string>={code:'Mã',name:'Tên hồ sơ',phone:'Điện thoại',email:'Email',address:'Địa chỉ',contactName:'Người liên hệ',source:'Nguồn',segment:'Nhóm',businessId:'Mã doanh nghiệp'};
type ImportRow={row:number;record:z.infer<typeof organizationSchema>;errors:string[]};
interface Job{id:string;user_id:string;membership_id:string;role:string;kind:'IMPORT_PARTNERS'|'EXPORT_PARTNERS';status:string;input:Record<string,unknown>;input_hash:string;scope_hash:string;result:Record<string,unknown>;error:string|null;attempts:number;lease_id:string|null;output?:Uint8Array;created_at:string}
function internal(user:Principal){if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}
export async function scopeHash(user:Principal,sql?:Sql){const tx=sql??await database();const p=(await tx.query<{organization_id:string}>('SELECT organization_id FROM cohamy_crm.partner_assignments WHERE membership_id=$1 ORDER BY organization_id',[user.membershipId])).rows;return digest(JSON.stringify([user.membershipId,user.role,user.organizationId,p]));}
function boundedXlsx(bytes:Buffer){if(bytes.length>2097152||bytes.length<22)throw new CrmError('FILE_SIZE_INVALID',413);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(bytes.readUInt32LE(i)===0x06054b50){eocd=i;break;}}if(eocd<0||bytes.readUInt16LE(eocd+4)||bytes.readUInt16LE(eocd+6))throw new CrmError('FILE_TYPE_INVALID',400);const count=bytes.readUInt16LE(eocd+10),start=bytes.readUInt32LE(eocd+16);if(count>1000||start>=eocd)throw new CrmError('FILE_SIZE_INVALID',413);let pos=start,total=0;for(let i=0;i<count;i++){if(pos+46>eocd||bytes.readUInt32LE(pos)!==0x02014b50)throw new CrmError('FILE_TYPE_INVALID',400);const size=bytes.readUInt32LE(pos+24),nameLength=bytes.readUInt16LE(pos+28),extra=bytes.readUInt16LE(pos+30),comment=bytes.readUInt16LE(pos+32);total+=size;if(total>20971520||size===0xffffffff||bytes.readUInt16LE(pos+8)&1)throw new CrmError('FILE_SIZE_INVALID',413);const name=bytes.subarray(pos+46,pos+46+nameLength).toString();if(name.includes('vbaProject')||name.includes('..')||name.startsWith('/'))throw new CrmError('FILE_TYPE_INVALID',400);pos+=46+nameLength+extra+comment;}if(pos>eocd)throw new CrmError('FILE_TYPE_INVALID',400);}
export async function previewImport(user:Principal,bytes:Buffer,input:unknown){internal(user);assertPermission(user,'partners.write');const d=parse(z.object({idempotencyKey:z.uuid(),kind:z.enum(['CUSTOMER','DEALER']),mapping:z.partialRecord(z.enum(columns),z.number().int().min(1).max(50))}).strict(),input);if(!d.mapping.code||!d.mapping.name)throw new CrmError('INVALID_FIELDS',400);boundedXlsx(bytes);const workbook=new ExcelJS.Workbook();try{await workbook.xlsx.load(bytes as unknown as ExcelJS.Buffer);}catch{throw new CrmError('FILE_TYPE_INVALID',400);}const sheet=workbook.worksheets[0];if(!sheet||sheet.rowCount<2||sheet.rowCount>501||sheet.columnCount>50)throw new CrmError('IMPORT_LIMIT',400);const rows:ImportRow[]=[],seen=new Set<string>();
 for(let n=2;n<=sheet.rowCount;n++){const values:Record<string,string>={},errors:string[]=[];for(const [field,column]of Object.entries(d.mapping)){const cell=sheet.getRow(n).getCell(column);if(cell.type===ExcelJS.ValueType.Formula||cell.type===ExcelJS.ValueType.Hyperlink)errors.push('Ô công thức hoặc link không được nhập.');values[field]=cell.text.trim();}if(Object.values(values).every(v=>!v))continue;const parsed=organizationSchema.safeParse({...values,kind:d.kind});if(!parsed.success)errors.push('Thiếu hoặc sai định dạng mã, tên hoặc email.');const key=values.code??'';if(seen.has(key))errors.push('Mã bị trùng trong file.');seen.add(key);if((await(await database()).query('SELECT id FROM cohamy_crm.organizations WHERE code=$1',[key])).rows.length)errors.push('Mã không khả dụng.');rows.push({row:n,record:parsed.success?parsed.data:{code:key,name:values.name??'',kind:d.kind,phone:values.phone??'',email:values.email??'',businessId:values.businessId??'',address:values.address??'',contactName:'',source:'',segment:'',stage:'ACTIVE'},errors});}
 if(!rows.length)throw new CrmError('INVALID_FIELDS',400);const payload={rows,kind:d.kind,fileChecksum:digest(bytes.toString('base64'))};const id=await createJob(user,d.idempotencyKey,'IMPORT_PARTNERS',payload,'PREVIEW');return {id,rows,total:rows.length,errors:rows.filter(r=>r.errors.length).length};}
async function createJob(user:Principal,key:string,kind:Job['kind'],input:Record<string,unknown>,status:string){const hash=digest(JSON.stringify(input)),scope=await scopeHash(user),id=randomUUID();return(await database()).transaction(async tx=>{const r=await tx.query<{id:string;input_hash:string;kind:string}>('INSERT INTO cohamy_crm.data_jobs(id,user_id,membership_id,role,idempotency_key,kind,status,input,input_hash,scope_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING id,input_hash,kind',[id,user.id,user.membershipId,user.role,key,kind,status,JSON.stringify(input),hash,scope]);const job=r.rows[0]??(await tx.query<{id:string;input_hash:string;kind:string}>('SELECT id,input_hash,kind FROM cohamy_crm.data_jobs WHERE user_id=$1 AND idempotency_key=$2',[user.id,key])).rows[0];if(job.input_hash!==hash||job.kind!==kind)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return job.id;});}
export async function getJob(user:Principal,id:string){internal(user);const row=(await(await database()).query<Job>('SELECT id,user_id,membership_id,role,kind,status,input,input_hash,scope_hash,result,error,attempts,lease_id,created_at FROM cohamy_crm.data_jobs WHERE id=$1 AND user_id=$2',[id,user.id])).rows[0];if(!row)throw new CrmError('NOT_FOUND',404);if(row.role!==user.role||row.membership_id!==user.membershipId||row.scope_hash!==await scopeHash(user))throw new CrmError('FORBIDDEN',403);return row;}
export async function listJobs(user:Principal){internal(user);const rows=(await(await database()).query<Job>('SELECT id,user_id,membership_id,role,kind,status,input,input_hash,scope_hash,result,error,attempts,lease_id,created_at FROM cohamy_crm.data_jobs WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[user.id])).rows;const scope=await scopeHash(user);return rows.filter(r=>r.role===user.role&&r.membership_id===user.membershipId&&r.scope_hash===scope);}
export async function confirmImport(user:Principal,id:string){assertPermission(user,'partners.write');const job=await getJob(user,id);if(job.kind!=='IMPORT_PARTNERS')throw new CrmError('INVALID_FIELDS',400);if((job.input.rows as ImportRow[]).some(r=>r.errors.length))throw new CrmError('IMPORT_ERRORS',409);await(await database()).query("UPDATE cohamy_crm.data_jobs SET status='QUEUED',updated_at=now() WHERE id=$1 AND status='PREVIEW'",[id]);return {id};}
export async function exportPartners(user:Principal,input:unknown){internal(user);assertPermission(user,'partners.read');const d=parse(z.object({idempotencyKey:z.uuid(),q:z.string().max(120).default(''),tags:z.string().max(1200).refine(v=>!v||v.split(',').every(id=>z.uuid().safeParse(id).success)).default(''),kind:z.enum(['CUSTOMER','DEALER']).optional(),columns:z.array(z.enum(columns)).min(1).max(9)}).strict(),input);return {id:await createJob(user,d.idempotencyKey,'EXPORT_PARTNERS',{q:d.q,tags:d.tags,kind:d.kind??null,columns:d.columns},'QUEUED')};}
export async function runNextJob(){const db=await database(),leaseId=randomUUID();await db.query("UPDATE cohamy_crm.data_jobs SET status='FAILED',error='JOB_RETRY_EXHAUSTED',updated_at=now() WHERE status='RUNNING' AND lease_until<now() AND attempts>=5");const job=await db.transaction(async tx=>{const j=(await tx.query<Job>("SELECT * FROM cohamy_crm.data_jobs WHERE (status='QUEUED' OR (status='RUNNING' AND lease_until<now())) AND attempts<5 ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1")).rows[0];if(!j)return null;await tx.query("UPDATE cohamy_crm.data_jobs SET status='RUNNING',attempts=attempts+1,lease_id=$1,lease_until=now()+interval '2 minutes',updated_at=now() WHERE id=$2",[leaseId,j.id]);return j;});if(!job)return false;
 try{await db.transaction(async tx=>{if(!(await tx.query('SELECT id FROM cohamy_crm.data_jobs WHERE id=$1 AND lease_id=$2 FOR UPDATE',[job.id,leaseId])).rows.length)throw new CrmError('JOB_LEASE_EXPIRED',409);const user=await membershipPrincipal(job.membership_id,tx);if(!user||user.role!==job.role||await scopeHash(user,tx)!==job.scope_hash)throw new CrmError('JOB_PERMISSION_REVOKED',403);internal(user);
 if(job.kind==='IMPORT_PARTNERS'){assertPermission(user,'partners.write');const rows=job.input.rows as ImportRow[];let imported=0;for(const row of rows){if(row.errors.length)throw new CrmError('IMPORT_ERRORS',409);const r=parse(organizationSchema,row.record),id=randomUUID();const inserted=await tx.query<{id:string}>('INSERT INTO cohamy_crm.organizations(id,code,name,kind,phone,email,address,contact_name,source,segment,stage,import_job_id,import_row,business_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(import_job_id,import_row) WHERE import_job_id IS NOT NULL DO NOTHING RETURNING id',[id,r.code,r.name,r.kind,r.phone,r.email,r.address,r.contactName,r.source,r.segment,r.stage,job.id,row.row,r.businessId]);if(inserted.rows.length){if(user.role==='SALES')await tx.query('INSERT INTO cohamy_crm.partner_assignments(membership_id,organization_id) VALUES ($1,$2)',[user.membershipId,id]);await audit(tx,user.id,'partner.imported',id,{jobId:job.id,row:row.row});imported++;}}await tx.query("UPDATE cohamy_crm.data_jobs SET status='SUCCEEDED',result=$1::jsonb,lease_until=NULL,updated_at=now() WHERE id=$2 AND lease_id=$3",[JSON.stringify({imported,total:rows.length}),job.id,leaseId]);
 await tx.query('UPDATE cohamy_crm.data_jobs SET scope_hash=$1 WHERE id=$2',[await scopeHash(user,tx),job.id]);
 }else{assertPermission(user,'partners.read');const scope=partnerScope(user),params=[...scope.params,'%'+String(job.input.q??'')+'%',job.input.kind];const n=scope.params.length,tagIds=String(job.input.tags??'').split(',').filter(Boolean);let tagWhere='';for(const tagId of tagIds){params.push(tagId);tagWhere+=` AND EXISTS(SELECT 1 FROM cohamy_crm.partner_tags pt WHERE pt.organization_id=o.id AND pt.tag_id=$${params.length})`;}const rows=(await tx.query<{id:string;code:string;name:string;phone:string;email:string;address:string;contact_name:string;source:string;segment:string}>(`SELECT o.id,o.code,o.name,o.phone,o.email,o.address,o.contact_name,o.source,o.segment,o.business_id FROM cohamy_crm.organizations o WHERE (${scope.sql}) AND o.merged_into_id IS NULL AND (o.name ILIKE $${n+1} OR o.code ILIKE $${n+1} OR o.phone ILIKE $${n+1} OR o.email ILIKE $${n+1}) AND ($${n+2}::text IS NULL OR o.kind=$${n+2}) ${tagWhere} ORDER BY o.name,o.id LIMIT 5001`,params)).rows;if(rows.length>5000)throw new CrmError('EXPORT_LIMIT',400);const cols=job.input.columns as string[],book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Hồ sơ');sheet.columns=cols.map(key=>({header:columnLabels[key],key,width:key==='address'?48:28}));sheet.getRow(1).font={bold:true};sheet.views=[{state:'frozen',ySplit:1}];for(const row of rows){const value:Record<string,string>={};for(const col of cols){const raw=String(row[(col==='contactName'?'contact_name':col==='businessId'?'business_id':col) as keyof typeof row]??'');value[col]=/^[\s]*[=+@-]/.test(raw)?"'"+raw:raw;}sheet.addRow(value);}sheet.autoFilter={from:{row:1,column:1},to:{row:rows.length+1,column:cols.length}};const output=Buffer.from(await book.xlsx.writeBuffer());await tx.query("UPDATE cohamy_crm.data_jobs SET status='SUCCEEDED',result=$1::jsonb,output=$2,lease_until=NULL,updated_at=now() WHERE id=$3 AND lease_id=$4",[JSON.stringify({total:rows.length,entityIds:rows.map(r=>r.id),checksum:digest(output.toString('base64'))}),output,job.id,leaseId]);await audit(tx,user.id,'partners.exported',job.id,{total:rows.length});}
 });}catch(e){const code=e instanceof CrmError?e.code:(e as {code?:string}).code==='23505'?'DUPLICATE_RECORD':'JOB_FAILED';await db.query("UPDATE cohamy_crm.data_jobs SET status='FAILED',error=$1,lease_until=NULL,updated_at=now() WHERE id=$2 AND lease_id=$3",[code,job.id,leaseId]);}return true;}
export async function downloadExport(user:Principal,id:string){const job=await getJob(user,id);if(job.kind!=='EXPORT_PARTNERS'||job.status!=='SUCCEEDED')throw new CrmError('NOT_FOUND',404);assertPermission(user,'partners.read');for(const entityId of job.result.entityIds as string[])await getOrganization(user,entityId);const row=(await(await database()).query<{output:Uint8Array}>('SELECT output FROM cohamy_crm.data_jobs WHERE id=$1',[id])).rows[0];return row.output;}
