import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {assertCurrentPrincipal,audit} from './auth';
import {assertPermission,CrmError} from './permissions';
import {commercialDigest as digest,parseCommercial as parse,vietnamBusinessDate} from './commercial-common';
import {fixed,fixedText} from './decimal';
import {salesOrderAccess,salesVersionAccess} from './sales-orders';
import type {Principal} from './types';

const quantity=z.string().regex(/^\d{1,18}(?:\.\d{1,6})?$/).refine(v=>fixed(v)>0n);
const reason=z.string().trim().min(3).max(2000);
const key=z.uuid();
type Balance={warehouse_id:string;location_id:string;product_id:string;lot_id:string;on_hand:string;reserved:string;version:number};
type Location={id:string;warehouse_id:string;code:string;name:string;kind:string;active:boolean;warehouse_active:boolean;organization_id:string};
type Lot={id:string;product_id:string;code:string;manufactured_on:string|null;expires_on:string|null;status:string;version:number};
function dateOnly(value:unknown){return value===null||value===undefined?null:value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);}

function warehouseWhere(user:Principal,alias='w',offset=0){
 if(user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role))return {sql:'true',params:[] as unknown[]};
 if(user.area==='portal')return {sql:`${alias}.organization_id=$${offset+1}`,params:[user.organizationId] as unknown[]};
 if(user.area==='crm'&&user.role==='WAREHOUSE')return {sql:`EXISTS(SELECT 1 FROM cohamy_crm.warehouse_assignments wa WHERE wa.warehouse_id=${alias}.id AND wa.membership_id=$${offset+1})`,params:[user.membershipId] as unknown[]};
 return {sql:'false',params:[] as unknown[]};
}
function inventoryWriter(user:Principal,manage=false){
 if(user.area!=='crm'||!(manage?['ADMIN','MANAGER']:['ADMIN','MANAGER','WAREHOUSE']).includes(user.role))throw new CrmError('FORBIDDEN',403);
}
async function locationAccess(sql:Sql,user:Principal,id:string,write=false){
 parse(z.uuid(),id);const s=warehouseWhere(user);
 const row=(await sql.query<Location>(`SELECT l.*,w.active AS warehouse_active,w.organization_id FROM cohamy_crm.warehouse_locations l JOIN cohamy_crm.warehouses w ON w.id=l.warehouse_id WHERE (${s.sql}) AND l.id=$${s.params.length+1}`,[...s.params,id])).rows[0];
 if(!row)throw new CrmError('NOT_FOUND',404);if(write&&(!row.active||!row.warehouse_active))throw new CrmError('INVENTORY_LOCATION_INACTIVE',409);return row;
}
async function lotAccess(sql:Sql,id:string,productId?:string){
 const row=(await sql.query<Lot>('SELECT * FROM cohamy_crm.inventory_lots WHERE id=$1',[parse(z.uuid(),id)])).rows[0];
 if(!row||productId&&row.product_id!==productId)throw new CrmError('INVENTORY_LOT_INVALID',409);return row;
}
async function productSnapshot(sql:Sql,id:string){
 const row=(await sql.query<{id:string;sku:string;name:string;stock_unit:string;active:boolean}>('SELECT id,sku,name,stock_unit,active FROM cohamy_crm.products WHERE id=$1',[parse(z.uuid(),id)])).rows[0];
 if(!row||!row.active)throw new CrmError('INVENTORY_PRODUCT_INACTIVE',409);return {productId:row.id,sku:row.sku,name:row.name,code:row.stock_unit,stockUnit:row.stock_unit,numerator:'1',denominator:'1'};
}
async function priorAction(sql:Sql,user:Principal,idempotencyKey:string,requestHash:string){
 const row=(await sql.query<{request_hash:string;result:unknown}>('SELECT request_hash,result FROM cohamy_crm.inventory_actions WHERE actor_id=$1 AND idempotency_key=$2',[user.id,idempotencyKey])).rows[0];
 if(row&&row.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return row?.result;
}
async function recordAction(sql:Sql,user:Principal,action:string,resourceId:string,idempotencyKey:string,requestHash:string,result:unknown){
 await sql.query('INSERT INTO cohamy_crm.inventory_actions(id,action,resource_id,actor_id,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[randomUUID(),action,resourceId,user.id,idempotencyKey,requestHash,JSON.stringify(result)]);
}
async function lockBalance(sql:Sql,location:Location,productId:string,lotId:string){
 await sql.query('INSERT INTO cohamy_crm.inventory_balances(warehouse_id,location_id,product_id,lot_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[location.warehouse_id,location.id,productId,lotId]);
 return (await sql.query<Balance>('SELECT * FROM cohamy_crm.inventory_balances WHERE warehouse_id=$1 AND location_id=$2 AND product_id=$3 AND lot_id=$4 FOR UPDATE',[location.warehouse_id,location.id,productId,lotId])).rows[0];
}
async function updateBalance(sql:Sql,b:Balance,onHand:bigint,reserved=fixed(b.reserved)){
 if(onHand<0n||reserved<0n||reserved>onHand)throw new CrmError('INVENTORY_INSUFFICIENT',409);
 await sql.query('UPDATE cohamy_crm.inventory_balances SET on_hand=$1,reserved=$2,version=version+1,updated_at=now() WHERE warehouse_id=$3 AND location_id=$4 AND product_id=$5 AND lot_id=$6',[fixedText(onHand),fixedText(reserved),b.warehouse_id,b.location_id,b.product_id,b.lot_id]);
}
async function createDocument(sql:Sql,user:Principal,kind:string,organizationId:string,referenceType:string,referenceId:string,reasonText:string,requestHash:string,result:unknown,reversalId?:string){
 const id=randomUUID(),code=`KHO-${kind.slice(0,3)}-${vietnamBusinessDate(new Date())}-${id.slice(0,8).toUpperCase()}`;
 await sql.query('INSERT INTO cohamy_crm.inventory_documents(id,code,kind,organization_id,reference_type,reference_id,actor_id,reason,idempotency_key,request_hash,result,reversal_document_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12)',[id,code,kind,organizationId,referenceType,referenceId,user.id,reasonText,randomUUID(),requestHash,JSON.stringify(result),reversalId??null]);return {id,code};
}
async function movement(sql:Sql,user:Principal,documentId:string,b:Balance,delta:bigint,unitSnapshot:unknown,sourceOrderId?:string,reversalOf?:string){
 const next=fixed(b.on_hand)+delta;await updateBalance(sql,b,next);const id=randomUUID();
 await sql.query('INSERT INTO cohamy_crm.inventory_movements(id,document_id,warehouse_id,location_id,product_id,lot_id,quantity,balance_after,unit_snapshot,source_order_id,reversal_of,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12)',[id,documentId,b.warehouse_id,b.location_id,b.product_id,b.lot_id,fixedText(delta),fixedText(next),JSON.stringify(unitSnapshot),sourceOrderId??null,reversalOf??null,user.id]);return id;
}

export async function listInventory(user:Principal){
 assertPermission(user,'warehouses.read');const s=warehouseWhere(user);
 return(await(await database()).query<Balance&{warehouse_code:string;location_code:string;location_kind:string;sku:string;product_name:string;lot_code:string;expires_on:string|null;lot_status:string;available:string}>(`SELECT b.*,w.code AS warehouse_code,l.code AS location_code,l.kind AS location_kind,p.sku,p.name AS product_name,t.code AS lot_code,t.expires_on,t.status AS lot_status,(CASE WHEN l.kind='PICK' AND l.active AND t.status='AVAILABLE' THEN b.on_hand-b.reserved ELSE 0 END)::text AS available FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.warehouses w ON w.id=b.warehouse_id JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id JOIN cohamy_crm.products p ON p.id=b.product_id JOIN cohamy_crm.inventory_lots t ON t.id=b.lot_id WHERE (${s.sql}) ORDER BY w.code,l.code,p.sku,t.expires_on NULLS LAST,t.code`,s.params)).rows;
}
export async function orderInventoryState(user:Principal,orderId:string){return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const order=await salesOrderAccess(sql,user,orderId);const rows=(await sql.query<{id:string;status:string;quantity:string;consumed:string;released:string;sku:string;product_name:string;lot_code:string;location_code:string}>('SELECT r.id,r.status,r.quantity::text,r.consumed::text,r.released::text,p.sku,p.name AS product_name,t.code AS lot_code,l.code AS location_code FROM cohamy_crm.inventory_reservations r JOIN cohamy_crm.products p ON p.id=r.product_id JOIN cohamy_crm.inventory_lots t ON t.id=r.lot_id JOIN cohamy_crm.warehouse_locations l ON l.id=r.location_id WHERE r.order_id=$1 ORDER BY r.created_at,r.id',[order.id])).rows;return {rows,active:rows.some(r=>['ACTIVE','PARTIAL'].includes(r.status)),consumed:fixedText(rows.reduce((sum,r)=>sum+fixed(r.consumed),0n)),released:fixedText(rows.reduce((sum,r)=>sum+fixed(r.released),0n))};});}
export async function listLocations(user:Principal){assertPermission(user,'warehouses.read');const s=warehouseWhere(user);return(await(await database()).query<Location&{warehouse_code:string}>(`SELECT l.*,w.code AS warehouse_code,w.active AS warehouse_active,w.organization_id FROM cohamy_crm.warehouse_locations l JOIN cohamy_crm.warehouses w ON w.id=l.warehouse_id WHERE (${s.sql}) ORDER BY w.code,l.code`,s.params)).rows;}
export async function inventoryOperations(user:Principal){
 assertPermission(user,'warehouses.read');const s=warehouseWhere(user),db=await database();return {
  documents:(await db.query(`SELECT d.id,d.code,d.kind,d.status,d.reference_type,d.reference_id,d.reason,d.created_at FROM cohamy_crm.inventory_documents d WHERE EXISTS(SELECT 1 FROM cohamy_crm.inventory_movements m JOIN cohamy_crm.warehouses w ON w.id=m.warehouse_id WHERE m.document_id=d.id AND (${s.sql})) ORDER BY d.created_at DESC,d.id LIMIT 100`,s.params)).rows,
  transfers:(await db.query(`SELECT t.id,t.code,t.status,t.version,t.created_at,sw.code AS source_code,dw.code AS destination_code,t.snapshot FROM cohamy_crm.inventory_transfers t JOIN cohamy_crm.warehouses sw ON sw.id=t.source_warehouse_id JOIN cohamy_crm.warehouses dw ON dw.id=t.destination_warehouse_id JOIN cohamy_crm.warehouses w ON w.id=t.source_warehouse_id WHERE (${s.sql}) ORDER BY t.created_at DESC,t.id LIMIT 100`,s.params)).rows,
  counts:(await db.query(`SELECT c.id,c.code,c.status,c.version,c.created_at,w.code AS warehouse_code,c.snapshot FROM cohamy_crm.stock_counts c JOIN cohamy_crm.warehouses w ON w.id=c.warehouse_id WHERE (${s.sql}) ORDER BY c.created_at DESC,c.id LIMIT 100`,s.params)).rows,
  recalls:(await db.query(`SELECT r.id,r.status,r.version,r.reason,r.created_at,t.id AS lot_id,t.code AS lot_code,p.sku FROM cohamy_crm.lot_recalls r JOIN cohamy_crm.inventory_lots t ON t.id=r.lot_id JOIN cohamy_crm.products p ON p.id=t.product_id WHERE EXISTS(SELECT 1 FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.warehouses w ON w.id=b.warehouse_id WHERE b.lot_id=t.id AND (${s.sql})) ORDER BY r.created_at DESC,r.id LIMIT 100`,s.params)).rows
 };
}
export async function createLocation(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({warehouseId:z.uuid(),code:z.string().trim().min(1).max(40).regex(/^[A-Za-z0-9_-]+$/),name:z.string().trim().min(2).max(120),kind:z.enum(['PICK','QUARANTINE','DAMAGED']).default('PICK'),idempotencyKey:key}).strict(),input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const s=warehouseWhere(user),w=(await sql.query<{id:string;organization_id:string;active:boolean}>(`SELECT * FROM cohamy_crm.warehouses w WHERE (${s.sql}) AND w.id=$${s.params.length+1} FOR UPDATE`,[...s.params,d.warehouseId])).rows[0];if(!w||!w.active)throw new CrmError('NOT_FOUND',404);const id=randomUUID();await sql.query('INSERT INTO cohamy_crm.warehouse_locations(id,warehouse_id,code,name,kind) VALUES($1,$2,$3,$4,$5)',[id,w.id,d.code,d.name,d.kind]);const result={id};await recordAction(sql,user,'LOCATION_CREATED',id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.location-created',id,{after:d});return result;});
}

const receiptSchema=z.object({locationId:z.uuid(),lines:z.array(z.object({productId:z.uuid(),lotCode:z.string().trim().min(1).max(80),manufacturedOn:z.iso.date().nullable(),expiresOn:z.iso.date().nullable(),quantity}).strict()).min(1).max(200),referenceType:z.string().trim().min(2).max(80),referenceId:z.string().trim().min(1).max(120),reason,idempotencyKey:key}).strict();
export async function postReceipt(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(receiptSchema,input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const loc=await locationAccess(sql,user,d.locationId,true),prepared=[] as {productId:string;lotId:string;quantity:bigint;unit:unknown;balance:Balance}[];
  for(const line of d.lines){const unit=await productSnapshot(sql,line.productId);let lot=(await sql.query<Lot>('SELECT * FROM cohamy_crm.inventory_lots WHERE product_id=$1 AND code=$2 FOR UPDATE',[line.productId,line.lotCode])).rows[0];if(!lot){const id=randomUUID();await sql.query('INSERT INTO cohamy_crm.inventory_lots(id,product_id,code,manufactured_on,expires_on) VALUES($1,$2,$3,$4,$5)',[id,line.productId,line.lotCode,line.manufacturedOn,line.expiresOn]);lot=await lotAccess(sql,id,line.productId);}else if(dateOnly(lot.manufactured_on)!==line.manufacturedOn||dateOnly(lot.expires_on)!==line.expiresOn)throw new CrmError('LOT_DATE_CONFLICT',409);if(lot.status!=='AVAILABLE')throw new CrmError('LOT_BLOCKED',409);prepared.push({productId:line.productId,lotId:lot.id,quantity:fixed(line.quantity),unit,balance:await lockBalance(sql,loc,line.productId,lot.id)});}
  const document=await createDocument(sql,user,'RECEIPT',loc.organization_id,d.referenceType,d.referenceId,d.reason,h,{});for(const row of prepared)await movement(sql,user,document.id,row.balance,row.quantity,row.unit);const result={id:document.id,code:document.code,lines:prepared.length};await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),document.id]);await recordAction(sql,user,'RECEIPT_POSTED',document.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.receipt-posted',document.id,{after:{locationId:loc.id,lines:prepared.length},reason:d.reason});return result;
 });
}
export async function reverseDocument(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({id:z.uuid(),reason,idempotencyKey:key}).strict(),input),h=digest(d);
  return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const s=warehouseWhere(user,'w',1),doc=(await sql.query<{id:string;kind:string;status:string;organization_id:string;code:string;reference_type:string;reference_id:string}>(`SELECT d.* FROM cohamy_crm.inventory_documents d WHERE d.id=$1 AND EXISTS(SELECT 1 FROM cohamy_crm.inventory_movements m JOIN cohamy_crm.warehouses w ON w.id=m.warehouse_id WHERE m.document_id=d.id AND (${s.sql})) FOR UPDATE`,[d.id,...s.params])).rows[0];if(!doc)throw new CrmError('NOT_FOUND',404);if(doc.status==='REVERSED')throw new CrmError('DOCUMENT_ALREADY_REVERSED',409);const rows=(await sql.query<(Balance&{movement_id:string;quantity:string;unit_snapshot:unknown;source_order_id:string|null})>('SELECT b.*,m.id AS movement_id,m.quantity::text,m.unit_snapshot,m.source_order_id FROM cohamy_crm.inventory_movements m JOIN cohamy_crm.inventory_balances b USING(warehouse_id,location_id,product_id,lot_id) WHERE m.document_id=$1 ORDER BY m.id FOR UPDATE OF b',[doc.id])).rows;for(const row of rows){const next=fixed(row.on_hand)+fixed(row.quantity,6,true)*-1n;if(next<fixed(row.reserved))throw new CrmError('REVERSAL_RESERVED_STOCK',409);}const rev=await createDocument(sql,user,'REVERSAL',doc.organization_id,'inventory-document',doc.id,d.reason,h,{},doc.id);for(const row of rows)await movement(sql,user,rev.id,row,fixed(row.quantity,6,true)*-1n,row.unit_snapshot,row.source_order_id??undefined,row.movement_id);await sql.query("UPDATE cohamy_crm.inventory_documents SET status='REVERSED' WHERE id=$1",[doc.id]);const result={id:rev.id,code:rev.code,reversedId:doc.id};await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),rev.id]);if(doc.reference_type==='sample-issue'){const sample=(await sql.query<{id:string;status:string;version:number}>('UPDATE cohamy_crm.sample_issues SET status=\'CLOSED\',version=version+1,updated_at=now() WHERE id=$1 AND inventory_document_id=$2 RETURNING id,status,version',[doc.reference_id,doc.id])).rows[0];if(!sample)throw new CrmError('SAMPLE_REVERSAL_TARGET_INVALID',409);const sampleResult={...result,sampleId:sample.id,status:sample.status,version:sample.version};await sql.query("INSERT INTO cohamy_crm.sample_events(id,issue_id,action,payload,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,'ISSUE_REVERSED',$3::jsonb,$4,$5,$6,$7,$8::jsonb)",[randomUUID(),sample.id,JSON.stringify({inventoryDocumentId:doc.id,reversalDocumentId:rev.id}),user.id,d.reason,d.idempotencyKey,h,JSON.stringify(sampleResult)]);}await recordAction(sql,user,'DOCUMENT_REVERSED',doc.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.document-reversed',doc.id,{after:{reversalId:rev.id,referenceType:doc.reference_type},reason:d.reason});return result;});
}

export async function reserveOrder(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(z.object({orderId:z.uuid(),warehouseId:z.uuid(),minimumShelfLifeDays:z.number().int().min(0).max(3650).default(0),reason,idempotencyKey:key}).strict(),input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const order=await salesOrderAccess(sql,user,d.orderId,true);if(order.status!=='CONFIRMED'||!order.confirmed_version_id)throw new CrmError('ORDER_NOT_CONFIRMED',409);if((await sql.query('SELECT id FROM cohamy_crm.inventory_reservations WHERE order_id=$1 AND status IN(\'ACTIVE\',\'PARTIAL\')',[order.id])).rows.length)throw new CrmError('ORDER_ALREADY_RESERVED',409);const version=await salesVersionAccess(sql,order,order.confirmed_version_id),s=warehouseWhere(user),warehouse=(await sql.query<{id:string}>(`SELECT id FROM cohamy_crm.warehouses w WHERE (${s.sql}) AND w.id=$${s.params.length+1} AND w.active FOR UPDATE`,[...s.params,d.warehouseId])).rows[0];if(!warehouse)throw new CrmError('NOT_FOUND',404);
  const wanted=new Map<string,bigint>();for(const line of version.snapshot.quote.calculation.lines)wanted.set(line.productId,(wanted.get(line.productId)??0n)+fixed(line.baseQuantity));const ids:string[]=[];
  for(const [productId,needTotal] of [...wanted].sort(([a],[b])=>a.localeCompare(b))){let need=needTotal;const candidates=(await sql.query<(Balance&{expires_on:string|null;lot_status:string;location_active:boolean})>(`SELECT b.*,t.expires_on,t.status AS lot_status,l.active AS location_active FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.inventory_lots t ON t.id=b.lot_id JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id WHERE b.warehouse_id=$1 AND b.product_id=$2 AND b.on_hand>b.reserved AND t.status='AVAILABLE' AND l.active AND l.kind='PICK' AND(t.expires_on IS NULL OR t.expires_on>=current_date+$3::integer) ORDER BY t.expires_on NULLS LAST,t.code,l.code FOR UPDATE OF b`,[warehouse.id,productId,d.minimumShelfLifeDays])).rows;for(const b of candidates){if(!need)break;const free=fixed(b.on_hand)-fixed(b.reserved),take=free<need?free:need,id=randomUUID();await updateBalance(sql,b,fixed(b.on_hand),fixed(b.reserved)+take);await sql.query('INSERT INTO cohamy_crm.inventory_reservations(id,order_id,order_version_id,warehouse_id,location_id,product_id,lot_id,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,order.id,version.id,b.warehouse_id,b.location_id,b.product_id,b.lot_id,fixedText(take)]);await sql.query("INSERT INTO cohamy_crm.inventory_reservation_events(id,reservation_id,action,quantity,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,'RESERVED',$3,$4,$5,$6,$7,$8::jsonb)",[randomUUID(),id,fixedText(take),user.id,d.reason,randomUUID(),h,JSON.stringify({orderId:order.id})]);ids.push(id);need-=take;}if(need>0n)throw new CrmError('INVENTORY_INSUFFICIENT',409);}
  const result={orderId:order.id,reservationIds:ids,count:ids.length};await recordAction(sql,user,'ORDER_RESERVED',order.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.order-reserved',order.id,{after:{warehouseId:warehouse.id,reservations:ids.length,orderVersionId:version.id},reason:d.reason});return result;
 });
}
export async function releaseOrderReservations(user:Principal,input:unknown){return reservationTransition(user,input,'RELEASED');}
export async function consumeOrderReservations(user:Principal,input:unknown){return reservationTransition(user,input,'CONSUMED');}
async function reservationTransition(user:Principal,input:unknown,action:'RELEASED'|'CONSUMED'){
 inventoryWriter(user);const d=parse(z.object({orderId:z.uuid(),reason,idempotencyKey:key}).strict(),input),h=digest({...d,action});
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const order=await salesOrderAccess(sql,user,d.orderId,true),rows=(await sql.query<(Balance&{reservation_id:string;quantity:string;consumed:string;released:string;reservation_version:number;unit_snapshot:unknown})>(`SELECT b.*,r.id AS reservation_id,r.quantity::text,r.consumed::text,r.released::text,r.version AS reservation_version,jsonb_build_object('productId',p.id,'sku',p.sku,'name',p.name,'code',p.stock_unit,'stockUnit',p.stock_unit,'numerator','1','denominator','1') AS unit_snapshot FROM cohamy_crm.inventory_reservations r JOIN cohamy_crm.inventory_balances b USING(warehouse_id,location_id,product_id,lot_id) JOIN cohamy_crm.products p ON p.id=r.product_id WHERE r.order_id=$1 AND r.status IN('ACTIVE','PARTIAL') ORDER BY r.id FOR UPDATE OF r,b`,[order.id])).rows;if(!rows.length)throw new CrmError('NO_ACTIVE_RESERVATION',409);let document:{id:string;code:string}|undefined;if(action==='CONSUMED'){const owner=(await sql.query<{organization_id:string}>('SELECT organization_id FROM cohamy_crm.warehouses WHERE id=$1',[rows[0].warehouse_id])).rows[0];document=await createDocument(sql,user,'ISSUE',owner.organization_id,'sales-order',order.id,d.reason,h,{});}for(const row of rows){const remaining=fixed(row.quantity)-fixed(row.consumed)-fixed(row.released);if(remaining<=0n)continue;const reserved=fixed(row.reserved)-remaining;if(action==='RELEASED')await updateBalance(sql,row,fixed(row.on_hand),reserved);else{const next=fixed(row.on_hand)-remaining;await updateBalance(sql,row,next,reserved);await sql.query('INSERT INTO cohamy_crm.inventory_movements(id,document_id,warehouse_id,location_id,product_id,lot_id,quantity,balance_after,unit_snapshot,source_order_id,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)',[randomUUID(),document!.id,row.warehouse_id,row.location_id,row.product_id,row.lot_id,fixedText(-remaining),fixedText(next),JSON.stringify(row.unit_snapshot),order.id,user.id]);}await sql.query(`UPDATE cohamy_crm.inventory_reservations SET ${action==='RELEASED'?'released':'consumed'}=${action==='RELEASED'?'released':'consumed'}+$1,status=$2,version=version+1,updated_at=now() WHERE id=$3`,[fixedText(remaining),action,row.reservation_id]);await sql.query('INSERT INTO cohamy_crm.inventory_reservation_events(id,reservation_id,action,quantity,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[randomUUID(),row.reservation_id,action==='RELEASED'?'RELEASED':'CONSUMED',fixedText(remaining),user.id,d.reason,randomUUID(),h,JSON.stringify({orderId:order.id})]);}
  const result={orderId:order.id,action,documentId:document?.id??null};if(document)await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),document.id]);await recordAction(sql,user,`ORDER_${action}`,order.id,d.idempotencyKey,h,result);await audit(sql,user.id,`inventory.order-${action.toLowerCase()}`,order.id,{after:{documentId:document?.id??null},reason:d.reason});return result;
 });
}

export async function inventoryAlerts(user:Principal){
 assertPermission(user,'warehouses.read');const s=warehouseWhere(user);return(await(await database()).query(`WITH evaluated AS(SELECT r.id,r.warehouse_id,w.code AS warehouse_code,r.product_id,p.sku,p.name,r.low_available,r.slow_days,r.near_expiry_days,COALESCE((SELECT sum(b.on_hand-b.reserved) FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.inventory_lots t ON t.id=b.lot_id JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id WHERE b.warehouse_id=r.warehouse_id AND b.product_id=r.product_id AND t.status='AVAILABLE' AND l.active AND l.kind='PICK'),0) AS available,(SELECT count(DISTINCT t.id) FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.inventory_lots t ON t.id=b.lot_id JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id WHERE b.warehouse_id=r.warehouse_id AND b.product_id=r.product_id AND t.status='AVAILABLE' AND l.active AND l.kind='PICK' AND t.expires_on BETWEEN current_date AND current_date+r.near_expiry_days) AS near_expiry_lots,(SELECT max(m.created_at) FROM cohamy_crm.inventory_movements m WHERE m.warehouse_id=r.warehouse_id AND m.product_id=r.product_id AND m.quantity<0) AS last_out_at FROM cohamy_crm.inventory_alert_rules r JOIN cohamy_crm.warehouses w ON w.id=r.warehouse_id JOIN cohamy_crm.products p ON p.id=r.product_id WHERE (${s.sql}) AND r.active) SELECT id,warehouse_id,warehouse_code,product_id,sku,name,available::text,low_available::text,slow_days,near_expiry_days,near_expiry_lots::text,last_out_at FROM evaluated WHERE available<=low_available OR near_expiry_lots>0 OR(slow_days>0 AND(last_out_at IS NULL OR last_out_at<=now()-(slow_days*interval '1 day'))) ORDER BY warehouse_code,sku`,s.params)).rows;
}
export async function openRecall(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({lotId:z.uuid(),reason,idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const lot=await lotAccess(sql,d.lotId);if(lot.status==='RECALLED')throw new CrmError('LOT_ALREADY_RECALLED',409);await sql.query("UPDATE cohamy_crm.inventory_lots SET status='RECALLED',version=version+1 WHERE id=$1",[lot.id]);const id=randomUUID(),result={id,lotId:lot.id};await sql.query("INSERT INTO cohamy_crm.lot_recalls(id,lot_id,status,reason,actor_id) VALUES($1,$2,'OPEN',$3,$4)",[id,lot.id,d.reason,user.id]);await sql.query("INSERT INTO cohamy_crm.lot_recall_events(id,recall_id,action,note,actor_id,idempotency_key,request_hash,result) VALUES($1,$2,'OPENED',$3,$4,$5,$6,$7::jsonb)",[randomUUID(),id,d.reason,user.id,randomUUID(),h,JSON.stringify(result)]);await recordAction(sql,user,'LOT_RECALLED',lot.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.lot-recalled',lot.id,{after:{recallId:id},reason:d.reason});return result;});
}
export async function lotTrace(user:Principal,id:string){
 assertPermission(user,'warehouses.read');parse(z.uuid(),id);const s=warehouseWhere(user,'w',1),db=await database();return {movements:(await db.query(`SELECT m.id,m.quantity::text,m.balance_after::text,m.created_at,d.code AS document_code,d.kind,d.reference_type,d.reference_id,w.code AS warehouse_code,l.code AS location_code,m.source_order_id FROM cohamy_crm.inventory_movements m JOIN cohamy_crm.inventory_documents d ON d.id=m.document_id JOIN cohamy_crm.warehouses w ON w.id=m.warehouse_id JOIN cohamy_crm.warehouse_locations l ON l.id=m.location_id WHERE m.lot_id=$1 AND (${s.sql}) ORDER BY m.created_at,m.id`,[id,...s.params])).rows,reservations:(await db.query(`SELECT r.id,r.order_id,r.quantity::text,r.consumed::text,r.released::text,r.status FROM cohamy_crm.inventory_reservations r JOIN cohamy_crm.warehouses w ON w.id=r.warehouse_id WHERE r.lot_id=$1 AND (${s.sql}) ORDER BY r.created_at,r.id`,[id,...s.params])).rows};
}

const transferLine=z.object({productId:z.uuid(),lotId:z.uuid(),quantity,destinationLocationId:z.uuid()}).strict();
type TransferSnapshot={lines:{productId:string;lotId:string;quantity:string;sourceLocationId:string;destinationLocationId:string;unit:unknown}[]};
export async function shipTransfer(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(z.object({sourceLocationId:z.uuid(),lines:z.array(transferLine).min(1).max(200),reason,idempotencyKey:key}).strict(),input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const source=await locationAccess(sql,user,d.sourceLocationId,true),transferId=randomUUID(),prepared:TransferSnapshot['lines']=[],locked=[] as {b:Balance;q:bigint;unit:unknown}[],destinations=new Set<string>();
  for(const line of [...d.lines].sort((a,b)=>(a.productId+a.lotId).localeCompare(b.productId+b.lotId))){const destination=await locationAccess(sql,user,line.destinationLocationId,true);destinations.add(destination.warehouse_id);if(destination.warehouse_id===source.warehouse_id||destination.organization_id!==source.organization_id||destinations.size>1)throw new CrmError('TRANSFER_DESTINATION_INVALID',409);const lot=await lotAccess(sql,line.lotId,line.productId);if(lot.status!=='AVAILABLE')throw new CrmError('LOT_BLOCKED',409);const unit=await productSnapshot(sql,line.productId),b=await lockBalance(sql,source,line.productId,line.lotId),q=fixed(line.quantity);if(fixed(b.on_hand)-fixed(b.reserved)<q)throw new CrmError('INVENTORY_INSUFFICIENT',409);prepared.push({...line,sourceLocationId:source.id,unit});locked.push({b,q,unit});}
  const snapshot:TransferSnapshot={lines:prepared},code=`CK-${vietnamBusinessDate(new Date())}-${transferId.slice(0,8).toUpperCase()}`,result={id:transferId,code,version:1,status:'IN_TRANSIT'};await sql.query("INSERT INTO cohamy_crm.inventory_transfers(id,code,source_warehouse_id,destination_warehouse_id,status,snapshot,checksum,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,'IN_TRANSIT',$5::jsonb,$6,$7,$8,$9,$10,$11::jsonb)",[transferId,code,source.warehouse_id,[...destinations][0],JSON.stringify(snapshot),digest(snapshot),user.id,d.reason,d.idempotencyKey,h,JSON.stringify(result)]);const document=await createDocument(sql,user,'TRANSFER',source.organization_id,'inventory-transfer',transferId,d.reason,h,result);for(let i=0;i<locked.length;i++)await movement(sql,user,document.id,locked[i].b,-locked[i].q,locked[i].unit);await recordAction(sql,user,'TRANSFER_SHIPPED',transferId,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.transfer-shipped',transferId,{after:{sourceWarehouseId:source.warehouse_id,lines:prepared.length},reason:d.reason});return result;
 });
}
export async function receiveTransfer(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),lines:z.array(z.object({index:z.number().int().min(0).max(199),quantity,shortage:z.string().regex(/^\d{1,18}(?:\.\d{1,6})?$/).default('0')}).strict()).min(1).max(200),final:z.boolean(),reason,idempotencyKey:key}).strict(),input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const t=(await sql.query<{id:string;version:number;status:string;snapshot:TransferSnapshot;checksum:string;destination_warehouse_id:string}>("SELECT * FROM cohamy_crm.inventory_transfers WHERE id=$1 FOR UPDATE",[d.id])).rows[0];if(!t)throw new CrmError('NOT_FOUND',404);if(t.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(!['IN_TRANSIT','PARTIAL'].includes(t.status)||t.checksum!==digest(t.snapshot))throw new CrmError('TRANSFER_NOT_RECEIVABLE',409);const existing=(await sql.query<{lines:{index:number;quantity:string;shortage:string}[]}>('SELECT lines FROM cohamy_crm.inventory_transfer_receipts WHERE transfer_id=$1 ORDER BY number',[t.id])).rows,received=new Map<number,bigint>(),short=new Map<number,bigint>();for(const receipt of existing)for(const line of receipt.lines){received.set(line.index,(received.get(line.index)??0n)+fixed(line.quantity));short.set(line.index,(short.get(line.index)??0n)+fixed(line.shortage));}const unique=new Set<number>();for(const line of d.lines){if(unique.has(line.index)||!t.snapshot.lines[line.index])throw new CrmError('TRANSFER_LINE_INVALID',400);unique.add(line.index);const shipped=fixed(t.snapshot.lines[line.index].quantity),next=(received.get(line.index)??0n)+fixed(line.quantity)+(short.get(line.index)??0n)+fixed(line.shortage);if(next>shipped)throw new CrmError('TRANSFER_OVER_RECEIPT',409);}
  const destination=(await sql.query<{organization_id:string}>('SELECT organization_id FROM cohamy_crm.warehouses WHERE id=$1',[t.destination_warehouse_id])).rows[0],number=existing.length+1,document=await createDocument(sql,user,'RECEIPT',destination.organization_id,'inventory-transfer',t.id,d.reason,h,{});for(const line of d.lines){const source=t.snapshot.lines[line.index],loc=await locationAccess(sql,user,source.destinationLocationId,true);if(loc.warehouse_id!==t.destination_warehouse_id)throw new CrmError('TRANSFER_DESTINATION_INVALID',409);const b=await lockBalance(sql,loc,source.productId,source.lotId);await movement(sql,user,document.id,b,fixed(line.quantity),source.unit);received.set(line.index,(received.get(line.index)??0n)+fixed(line.quantity));short.set(line.index,(short.get(line.index)??0n)+fixed(line.shortage));}
  const complete=t.snapshot.lines.every((line,i)=>(received.get(i)??0n)+(short.get(i)??0n)===fixed(line.quantity));if(d.final&&!complete)throw new CrmError('TRANSFER_REMAINDER_REQUIRED',409);const anyShort=[...short.values()].some(v=>v>0n),status=complete?(anyShort?'SHORT':'RECEIVED'):'PARTIAL',version=t.version+1,result={id:t.id,version,status,receiptNumber:number,documentId:document.id};await sql.query('INSERT INTO cohamy_crm.inventory_transfer_receipts(id,transfer_id,number,lines,checksum,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10::jsonb)',[randomUUID(),t.id,number,JSON.stringify(d.lines),digest(d.lines),user.id,d.reason,d.idempotencyKey,h,JSON.stringify(result)]);await sql.query('UPDATE cohamy_crm.inventory_transfers SET status=$1,version=$2,updated_at=now(),result=$3::jsonb WHERE id=$4',[status,version,JSON.stringify(result),t.id]);await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),document.id]);await recordAction(sql,user,'TRANSFER_RECEIVED',t.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.transfer-received',t.id,{after:{status,receiptNumber:number},reason:d.reason});return result;
 });
}

type CountSnapshot={baselineAt:string;baseline:{warehouseId:string;locationId:string;productId:string;lotId:string;onHand:string}[];counted?:{locationId:string;productId:string;lotId:string;quantity:string}[];observedAt?:string;differences?:{locationId:string;productId:string;lotId:string;quantity:string}[]};
export async function startStockCount(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(z.object({warehouseId:z.uuid(),reason,idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const s=warehouseWhere(user),warehouse=(await sql.query<{id:string}>(`SELECT id FROM cohamy_crm.warehouses w WHERE (${s.sql}) AND id=$${s.params.length+1} AND active FOR UPDATE`,[...s.params,d.warehouseId])).rows[0];if(!warehouse)throw new CrmError('NOT_FOUND',404);const baselineAt=new Date((await sql.query<{now:string}>('SELECT now() AS now')).rows[0].now).toISOString(),baseline=(await sql.query<{warehouseId:string;locationId:string;productId:string;lotId:string;onHand:string}>('SELECT warehouse_id AS "warehouseId",location_id AS "locationId",product_id AS "productId",lot_id AS "lotId",on_hand::text AS "onHand" FROM cohamy_crm.inventory_balances WHERE warehouse_id=$1 ORDER BY location_id,product_id,lot_id',[warehouse.id])).rows,snapshot:CountSnapshot={baselineAt,baseline},id=randomUUID(),code=`KK-${vietnamBusinessDate(new Date(baselineAt))}-${id.slice(0,8).toUpperCase()}`,result={id,code,version:1,status:'COUNTING'};await sql.query("INSERT INTO cohamy_crm.stock_counts(id,code,warehouse_id,status,baseline_at,snapshot,checksum,actor_id,reason) VALUES($1,$2,$3,'COUNTING',$4,$5::jsonb,$6,$7,$8)",[id,code,warehouse.id,baselineAt,JSON.stringify(snapshot),digest(snapshot),user.id,d.reason]);await recordAction(sql,user,'COUNT_STARTED',id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.count-started',id,{after:{warehouseId:warehouse.id,baselineRows:baseline.length},reason:d.reason});return result;});
}
export async function recordStockCount(user:Principal,input:unknown){
 inventoryWriter(user);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),lines:z.array(z.object({locationId:z.uuid(),productId:z.uuid(),lotId:z.uuid(),quantity:z.string().regex(/^\d{1,18}(?:\.\d{1,6})?$/)}).strict()).min(1).max(5000),reason,idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const c=(await sql.query<{id:string;warehouse_id:string;version:number;status:string;snapshot:CountSnapshot}>("SELECT * FROM cohamy_crm.stock_counts WHERE id=$1 FOR UPDATE",[d.id])).rows[0];if(!c)throw new CrmError('NOT_FOUND',404);if(c.version!==d.version||c.status!=='COUNTING')throw new CrmError('COUNT_VERSION_CONFLICT',409);const seen=new Set<string>();for(const line of d.lines){const loc=await locationAccess(sql,user,line.locationId,true);if(loc.warehouse_id!==c.warehouse_id)throw new CrmError('COUNT_LOCATION_INVALID',409);await lotAccess(sql,line.lotId,line.productId);const signature=line.locationId+line.productId+line.lotId;if(seen.has(signature))throw new CrmError('COUNT_DUPLICATE_LINE',400);seen.add(signature);}const observedAt=new Date((await sql.query<{now:string}>('SELECT now() AS now')).rows[0].now).toISOString(),snapshot:CountSnapshot={...c.snapshot,counted:d.lines,observedAt},result={id:c.id,version:c.version+1,status:'PREVIEW'};await sql.query("UPDATE cohamy_crm.stock_counts SET status='PREVIEW',snapshot=$1::jsonb,checksum=$2,version=version+1,updated_at=now() WHERE id=$3",[JSON.stringify(snapshot),digest(snapshot),c.id]);await sql.query("INSERT INTO cohamy_crm.stock_count_events(id,count_id,action,snapshot,checksum,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,'COUNTED',$3::jsonb,$4,$5,$6,$7,$8,$9::jsonb)",[randomUUID(),c.id,JSON.stringify(snapshot),digest(snapshot),user.id,d.reason,d.idempotencyKey,h,JSON.stringify(result)]);await recordAction(sql,user,'COUNT_RECORDED',c.id,d.idempotencyKey,h,result);return result;});
}
export async function previewStockCount(user:Principal,id:string){
 inventoryWriter(user);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const c=(await sql.query<{id:string;warehouse_id:string;version:number;status:string;snapshot:CountSnapshot;checksum:string}>('SELECT * FROM cohamy_crm.stock_counts WHERE id=$1 FOR UPDATE',[parse(z.uuid(),id)])).rows[0];if(!c||c.status!=='PREVIEW'||c.checksum!==digest(c.snapshot)||!c.snapshot.counted||!c.snapshot.observedAt)throw new CrmError('COUNT_NOT_READY',409);const baseline=new Map(c.snapshot.baseline.map(r=>[[r.locationId,r.productId,r.lotId].join(':'),fixed(r.onHand)])),differences=[] as NonNullable<CountSnapshot['differences']>;for(const line of c.snapshot.counted){const signature=[line.locationId,line.productId,line.lotId].join(':'),moves=(await sql.query<{q:string}>('SELECT COALESCE(sum(quantity),0)::text AS q FROM cohamy_crm.inventory_movements WHERE warehouse_id=$1 AND location_id=$2 AND product_id=$3 AND lot_id=$4 AND created_at>$5 AND created_at<=$6',[c.warehouse_id,line.locationId,line.productId,line.lotId,c.snapshot.baselineAt,c.snapshot.observedAt])).rows[0],expected=(baseline.get(signature)??0n)+fixed(moves.q,6,true),difference=fixed(line.quantity)-expected;if(difference)differences.push({locationId:line.locationId,productId:line.productId,lotId:line.lotId,quantity:fixedText(difference)});}const snapshot={...c.snapshot,differences};await sql.query('UPDATE cohamy_crm.stock_counts SET snapshot=$1::jsonb,checksum=$2,updated_at=now() WHERE id=$3',[JSON.stringify(snapshot),digest(snapshot),c.id]);return {id:c.id,version:c.version,differences,concurrentPolicy:'APPLY_COUNT_DIFFERENCE_TO_CURRENT_BALANCE' as const};});
}
export async function approveStockCount(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),reason,idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const c=(await sql.query<{id:string;warehouse_id:string;version:number;status:string;snapshot:CountSnapshot;checksum:string}>("SELECT * FROM cohamy_crm.stock_counts WHERE id=$1 FOR UPDATE",[d.id])).rows[0];if(!c||c.version!==d.version||c.status!=='PREVIEW'||c.checksum!==digest(c.snapshot)||!c.snapshot.differences)throw new CrmError('COUNT_VERSION_CONFLICT',409);const owner=(await sql.query<{organization_id:string}>('SELECT organization_id FROM cohamy_crm.warehouses WHERE id=$1',[c.warehouse_id])).rows[0],document=await createDocument(sql,user,'COUNT',owner.organization_id,'stock-count',c.id,d.reason,h,{});for(const line of c.snapshot.differences){const loc=await locationAccess(sql,user,line.locationId,true),b=await lockBalance(sql,loc,line.productId,line.lotId),delta=fixed(line.quantity,6,true);if(fixed(b.on_hand)+delta<fixed(b.reserved))throw new CrmError('COUNT_WOULD_BREAK_RESERVATION',409);await movement(sql,user,document.id,b,delta,await productSnapshot(sql,line.productId));}const result={id:c.id,version:c.version+1,status:'POSTED',documentId:document.id};await sql.query("UPDATE cohamy_crm.stock_counts SET status='POSTED',version=version+1,updated_at=now() WHERE id=$1",[c.id]);await sql.query("INSERT INTO cohamy_crm.stock_count_events(id,count_id,action,snapshot,checksum,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,'POSTED',$3::jsonb,$4,$5,$6,$7,$8,$9::jsonb)",[randomUUID(),c.id,JSON.stringify(c.snapshot),c.checksum,user.id,d.reason,d.idempotencyKey,h,JSON.stringify(result)]);await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),document.id]);await recordAction(sql,user,'COUNT_POSTED',c.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.count-posted',c.id,{after:{documentId:document.id,differences:c.snapshot.differences.length},reason:d.reason});return result;});
}

export async function saveAlertRule(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({id:z.uuid().optional(),warehouseId:z.uuid(),productId:z.uuid(),lowAvailable:z.string().regex(/^\d{1,18}(?:\.\d{1,6})?$/),slowDays:z.number().int().min(0).max(3650),nearExpiryDays:z.number().int().min(0).max(3650),version:z.number().int().min(0),active:z.boolean(),idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const s=warehouseWhere(user),w=(await sql.query<{id:string}>(`SELECT id FROM cohamy_crm.warehouses w WHERE (${s.sql}) AND id=$${s.params.length+1}`,[...s.params,d.warehouseId])).rows[0];if(!w)throw new CrmError('NOT_FOUND',404);await productSnapshot(sql,d.productId);const current=(await sql.query<{id:string;version:number}>('SELECT id,version FROM cohamy_crm.inventory_alert_rules WHERE warehouse_id=$1 AND product_id=$2 FOR UPDATE',[d.warehouseId,d.productId])).rows[0];if((current?.version??0)!==d.version||d.id&&current?.id!==d.id)throw new CrmError('VERSION_CONFLICT',409);const id=current?.id??randomUUID();await sql.query('INSERT INTO cohamy_crm.inventory_alert_rules(id,warehouse_id,product_id,low_available,slow_days,near_expiry_days,active) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(warehouse_id,product_id) DO UPDATE SET low_available=excluded.low_available,slow_days=excluded.slow_days,near_expiry_days=excluded.near_expiry_days,active=excluded.active,version=cohamy_crm.inventory_alert_rules.version+1,updated_at=now()',[id,d.warehouseId,d.productId,d.lowAvailable,d.slowDays,d.nearExpiryDays,d.active]);const result={id,version:d.version+1};await recordAction(sql,user,'ALERT_RULE_SAVED',id,d.idempotencyKey,h,result);return result;});
}
export async function updateRecall(user:Principal,input:unknown){
 inventoryWriter(user,true);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),action:z.enum(['PROGRESS','CLOSE']),note:reason,idempotencyKey:key}).strict(),input),h=digest(d);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const prior=await priorAction(sql,user,d.idempotencyKey,h);if(prior)return prior;const r=(await sql.query<{id:string;lot_id:string;status:string;version:number}>('SELECT * FROM cohamy_crm.lot_recalls WHERE id=$1 FOR UPDATE',[d.id])).rows[0];if(!r)throw new CrmError('NOT_FOUND',404);if(r.version!==d.version||r.status!=='OPEN')throw new CrmError('VERSION_CONFLICT',409);const status=d.action==='CLOSE'?'CLOSED':'OPEN',result={id:r.id,version:r.version+1,status};await sql.query('UPDATE cohamy_crm.lot_recalls SET status=$1,version=version+1,updated_at=now() WHERE id=$2',[status,r.id]);await sql.query('INSERT INTO cohamy_crm.lot_recall_events(id,recall_id,action,note,actor_id,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[randomUUID(),r.id,d.action==='CLOSE'?'CLOSED':'PROGRESS',d.note,user.id,d.idempotencyKey,h,JSON.stringify(result)]);await recordAction(sql,user,'RECALL_'+d.action,r.id,d.idempotencyKey,h,result);await audit(sql,user.id,'inventory.recall-'+d.action.toLowerCase(),r.id,{after:{status},reason:d.note});return result;});
}
