import 'server-only';
import bcrypt from 'bcryptjs';
import {randomBytes,randomUUID,randomInt} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit,digest} from './auth';
import {CrmError,assertPermission} from './permissions';
import {parse,enqueueNotification} from './workspace';
import {brevoMailer,type VerificationMailer} from './brevo';
import type {Principal} from './types';
export const APPLICANT_COOKIE='cohamy_applicant_session';
const profileSchema=z.object({companyName:z.string().trim().min(2).max(200),representative:z.string().trim().min(2).max(120),phone:z.string().trim().regex(/^\+?[0-9 ()-]{8,25}$/),address:z.string().trim().min(5).max(500),region:z.string().trim().min(2).max(120)}).strict();
export interface Application{id:string;email:string;company_name:string;representative:string;phone:string;address:string;region:string;status:string;email_verified_at:string|null;version:number;created_at:string;updated_at:string;membership_id:string|null;organization_id:string|null;assigned_to:string|null;reviewer_id:string|null}
const publicCols='id,email,company_name,representative,phone,address,region,status,email_verified_at,version,created_at,updated_at,membership_id,organization_id,assigned_to,reviewer_id';
const admin=(u:Principal)=>{assertPermission(u,'accounts.manage');if(u.area!=='crm')throw new CrmError('FORBIDDEN',403);};
async function history(tx:Sql,id:string,action:string,message='',fields:string[]=[],actor:string|null=null){await tx.query('INSERT INTO cohamy_crm.application_history(id,application_id,actor_id,action,message,fields) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[randomUUID(),id,actor,action,message,JSON.stringify(fields)]);}
async function rate(key:string,max:number){const r=await(await database()).query<{attempts:number}>(`INSERT INTO cohamy_crm.login_attempts(key_hash,attempts) VALUES ($1,1) ON CONFLICT(key_hash) DO UPDATE SET attempts=CASE WHEN cohamy_crm.login_attempts.window_start<now()-interval '15 minutes' THEN 1 ELSE cohamy_crm.login_attempts.attempts+1 END,window_start=CASE WHEN cohamy_crm.login_attempts.window_start<now()-interval '15 minutes' THEN now() ELSE cohamy_crm.login_attempts.window_start END RETURNING attempts`,[digest(key)]);if(r.rows[0].attempts>max)throw new CrmError('LOGIN_RATE_LIMITED',429);}
export async function registerApplication(input:unknown){const d=parse(profileSchema.extend({email:z.email().toLowerCase(),password:z.string().min(12).max(72).refine(value=>Buffer.byteLength(value,'utf8')<=72),idempotencyKey:z.uuid(),invitationToken:z.string().regex(/^[A-Za-z0-9_-]{43}$/).optional()}).strict(),input);await rate('register:'+d.email,8);const hash=await bcrypt.hash(d.password,12);const registrationHash=digest(JSON.stringify([d.companyName,d.representative,d.phone,d.email,d.address,d.region,d.invitationToken??null]));
 return(await database()).transaction(async tx=>{const existing=(await tx.query<{id:string;password_hash:string;email:string;idempotency_key:string;registration_hash:string}>(`SELECT id,password_hash,email,idempotency_key,registration_hash FROM cohamy_crm.partner_applications WHERE email=$1 OR idempotency_key=$2 FOR UPDATE`,[d.email,d.idempotencyKey])).rows[0];if(existing){if(existing.email!==d.email||existing.idempotency_key!==d.idempotencyKey||existing.registration_hash!==registrationHash||!await bcrypt.compare(d.password,existing.password_hash))throw new CrmError('REGISTRATION_CONFLICT',409);return newApplicantSession(tx,existing.id);}
 if((await tx.query('SELECT id FROM cohamy_crm.users WHERE email=$1',[d.email])).rows.length)throw new CrmError('REGISTRATION_CONFLICT',409);
 let invitationId:string|null=null;if(d.invitationToken){const inv=(await tx.query<{id:string;uses:number;max_uses:number;expires_at:string;revoked_at:string|null}>('SELECT * FROM cohamy_crm.partner_invitations WHERE token_hash=$1 FOR UPDATE',[digest(d.invitationToken)])).rows[0];if(!inv||inv.revoked_at||new Date(inv.expires_at).getTime()<=Date.now()||inv.uses>=inv.max_uses)throw new CrmError('INVITATION_INVALID',409);invitationId=inv.id;await tx.query('UPDATE cohamy_crm.partner_invitations SET uses=uses+1 WHERE id=$1',[inv.id]);}else if((process.env.CRM_REGISTRATION_MODE??'OPEN')!=='OPEN')throw new CrmError('INVITATION_REQUIRED',403);
 const id=randomUUID();await tx.query('INSERT INTO cohamy_crm.partner_applications(id,idempotency_key,email,password_hash,company_name,representative,phone,address,region,invitation_id,registration_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,d.idempotencyKey,d.email,hash,d.companyName,d.representative,d.phone,d.address,d.region,invitationId,registrationHash]);await history(tx,id,'REGISTERED');await audit(tx,null,'application.registered',id);return newApplicantSession(tx,id);});}
async function newApplicantSession(tx:Sql,id:string){const token=randomBytes(32).toString('base64url');await tx.query('INSERT INTO cohamy_crm.applicant_sessions(token_hash,application_id,expires_at) VALUES ($1,$2,$3)',[digest(token),id,new Date(Date.now()+8*3600000)]);return {id,token};}
export async function applicantIdentity(token?:string){if(!token||!/^[A-Za-z0-9_-]{43}$/.test(token))return null;return(await(await database()).query<{id:string}>('SELECT a.id FROM cohamy_crm.applicant_sessions s JOIN cohamy_crm.partner_applications a ON a.id=s.application_id WHERE s.token_hash=$1 AND s.expires_at>now() AND s.revoked_at IS NULL',[digest(token)])).rows[0]?.id??null;}
const dummy=bcrypt.hashSync('not-an-applicant-password',12);
export async function applicantLogin(input:unknown){const d=parse(z.object({email:z.email().toLowerCase(),password:z.string().min(1).max(72)}).strict(),input);await rate('applicant-login:'+d.email,8);const row=(await(await database()).query<{id:string;password_hash:string}>('SELECT id,password_hash FROM cohamy_crm.partner_applications WHERE email=$1',[d.email])).rows[0];const valid=await bcrypt.compare(d.password,row?.password_hash??dummy);if(!row||!valid)throw new CrmError('INVALID_CREDENTIALS',401);return(await database()).transaction(tx=>newApplicantSession(tx,row.id));}
export async function applicantLogout(token?:string){if(token)await(await database()).query('UPDATE cohamy_crm.applicant_sessions SET revoked_at=now() WHERE token_hash=$1',[digest(token)]);}
export async function application(id:string){const r=(await(await database()).query<Application>(`SELECT ${publicCols} FROM cohamy_crm.partner_applications WHERE id=$1`,[id])).rows[0];if(!r)throw new CrmError('NOT_FOUND',404);const h=(await(await database()).query<{action:string;message:string;fields:string[];created_at:string}>('SELECT action,message,fields,created_at FROM cohamy_crm.application_history WHERE application_id=$1 ORDER BY created_at,id',[id])).rows;return {...r,history:h};}
export async function editApplication(id:string,input:unknown){const d=parse(profileSchema.extend({version:z.number().int().positive()}).strict(),input);return(await database()).transaction(async tx=>{const r=(await tx.query<Application>(`SELECT ${publicCols} FROM cohamy_crm.partner_applications WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!r)throw new CrmError('NOT_FOUND',404);if(!['DRAFT','NEEDS_INFO'].includes(r.status))throw new CrmError('APPLICATION_LOCKED',409);if(r.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);await tx.query('UPDATE cohamy_crm.partner_applications SET company_name=$1,representative=$2,phone=$3,address=$4,region=$5,version=version+1,updated_at=now() WHERE id=$6',[d.companyName,d.representative,d.phone,d.address,d.region,id]);await history(tx,id,'EDITED');return {version:r.version+1};});}
export async function requestVerification(id:string,mailer:VerificationMailer=brevoMailer){await rate('verification:'+id,5);const code=randomInt(0,1000000).toString().padStart(6,'0');const email=await(await database()).transaction(async tx=>{const r=(await tx.query<Application>(`SELECT ${publicCols} FROM cohamy_crm.partner_applications WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!r||!['DRAFT','NEEDS_INFO'].includes(r.status)||r.email_verified_at)throw new CrmError('APPLICATION_LOCKED',409);const old=(await tx.query<{requested_at:string}>('SELECT requested_at FROM cohamy_crm.application_verifications WHERE application_id=$1',[id])).rows[0];if(old&&Date.now()-new Date(old.requested_at).getTime()<60000)throw new CrmError('VERIFICATION_RATE_LIMITED',429);await tx.query(`INSERT INTO cohamy_crm.application_verifications(application_id,token_hash,expires_at,delivery_status) VALUES ($1,$2,$3,'PENDING') ON CONFLICT(application_id) DO UPDATE SET token_hash=$2,expires_at=$3,attempts=0,consumed_at=NULL,delivery_status='PENDING',requested_at=now()`,[id,digest(id+':'+code),new Date(Date.now()+600000)]);return r.email;});
 try{await mailer.send(email,code);}catch(e){await(await database()).query("UPDATE cohamy_crm.application_verifications SET delivery_status='FAILED' WHERE application_id=$1 AND token_hash=$2",[id,digest(id+':'+code)]);throw e;}
 await(await database()).query("UPDATE cohamy_crm.application_verifications SET delivery_status='SENT' WHERE application_id=$1 AND token_hash=$2",[id,digest(id+':'+code)]);return {sent:true};}
export async function verifyApplication(id:string,input:unknown){const d=parse(z.object({code:z.string().regex(/^\d{6}$/)}).strict(),input);const result=await(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.partner_applications WHERE id=$1 FOR UPDATE',[id]);const v=(await tx.query<{token_hash:string;expires_at:string;attempts:number;consumed_at:string|null;delivery_status:string}>('SELECT * FROM cohamy_crm.application_verifications WHERE application_id=$1 FOR UPDATE',[id])).rows[0];if(!v||v.consumed_at||new Date(v.expires_at).getTime()<=Date.now()||v.attempts>=5||v.delivery_status!=='SENT')return {error:'VERIFICATION_INVALID'};await tx.query('UPDATE cohamy_crm.application_verifications SET attempts=attempts+1 WHERE application_id=$1',[id]);if(v.token_hash!==digest(id+':'+d.code))return {error:'VERIFICATION_INVALID'};await tx.query('UPDATE cohamy_crm.application_verifications SET consumed_at=now() WHERE application_id=$1',[id]);await tx.query('UPDATE cohamy_crm.partner_applications SET email_verified_at=now(),version=version+1,updated_at=now() WHERE id=$1',[id]);await history(tx,id,'EMAIL_VERIFIED');return {verified:true};});if(result.error)throw new CrmError(result.error,400);return result;}
export async function submitApplication(id:string,input:unknown){const d=parse(z.object({version:z.number().int().positive()}).strict(),input);return(await database()).transaction(async tx=>{const a=(await tx.query<Application>(`SELECT ${publicCols} FROM cohamy_crm.partner_applications WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!a)throw new CrmError('NOT_FOUND',404);if(a.status==='SUBMITTED'&&a.version===d.version+1)return {submitted:true};if(a.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(!['DRAFT','NEEDS_INFO'].includes(a.status))throw new CrmError('APPLICATION_LOCKED',409);if(!a.email_verified_at)throw new CrmError('EMAIL_VERIFICATION_REQUIRED',409);await tx.query("UPDATE cohamy_crm.partner_applications SET status='SUBMITTED',version=version+1,updated_at=now() WHERE id=$1",[id]);await history(tx,id,'SUBMITTED');await audit(tx,null,'application.submitted',id);return {submitted:true};});}
export async function reviewQueue(user:Principal,q:Record<string,string>={}){admin(user);const status=parse(z.enum(['ALL','DRAFT','SUBMITTED','NEEDS_INFO','APPROVED','REJECTED']),q.status??'SUBMITTED');const page=Math.max(1,Math.min(10000,Number(q.page)||1)),hours=parse(z.coerce.number().int().min(0).max(8760),q.minHours||0),reviewer=q.reviewer??'';if(reviewer&&reviewer!=='NONE')parse(z.uuid(),reviewer);const where="($1='ALL' OR status=$1) AND (company_name ILIKE $2 OR email ILIKE $2) AND ($3='' OR ($3='NONE' AND reviewer_id IS NULL) OR reviewer_id::text=$3) AND created_at<=now()-($4::int * interval '1 hour')";const params=[status,'%'+(q.q??'').slice(0,120)+'%',reviewer,hours];const db=await database();return {items:(await db.query<Application>(`SELECT ${publicCols},reviewer_id FROM cohamy_crm.partner_applications WHERE ${where} ORDER BY created_at,id LIMIT 20 OFFSET $5`,[...params,(page-1)*20])).rows,total:Number((await db.query<{total:string}>(`SELECT count(*)::text AS total FROM cohamy_crm.partner_applications WHERE ${where}`,params)).rows[0].total),page};}
export async function assignReviewer(user:Principal,id:string,input:unknown){admin(user);const d=parse(z.object({version:z.number().int().positive(),reviewerId:z.uuid().nullable()}).strict(),input);return(await database()).transaction(async tx=>{if(d.reviewerId&&!(await tx.query("SELECT m.id FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.id=$1 AND m.role='ADMIN' AND m.active AND u.active AND o.active AND o.kind='COHAMY' FOR SHARE OF m,u,o",[d.reviewerId])).rows.length)throw new CrmError('INVALID_ASSIGNEE',400);const r=await tx.query("UPDATE cohamy_crm.partner_applications SET reviewer_id=$1,version=version+1,updated_at=now() WHERE id=$2 AND version=$3 AND status IN ('DRAFT','SUBMITTED','NEEDS_INFO') RETURNING id",[d.reviewerId,id,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'application.reviewer-assigned',id,{reviewerId:d.reviewerId});return {version:d.version+1};});}
export async function applicationDuplicates(user:Principal,id:string){admin(user);const a=await application(id);return(await(await database()).query<{id:string;name:string;code:string;phone:string;email:string}>(`SELECT id,name,code,phone,email FROM cohamy_crm.organizations WHERE kind='DEALER' AND (lower(email)=lower($1) OR regexp_replace(phone,'[^0-9]','','g')=regexp_replace($2,'[^0-9]','','g')) ORDER BY name LIMIT 20`,[a.email,a.phone])).rows;}
export async function reviewApplication(user:Principal,id:string,input:unknown){admin(user);const d=parse(z.object({version:z.number().int().positive(),action:z.enum(['NEEDS_INFO','REJECTED','APPROVE']),message:z.string().trim().max(1000).default(''),fields:z.array(z.enum(['companyName','representative','phone','address','region'])).max(5).default([]),organizationId:z.uuid().optional(),role:z.enum(['DEALER_OWNER','DEALER_STAFF']).optional(),assigneeId:z.uuid().optional()}).strict(),input);
 return(await database()).transaction(async tx=>{const a=(await tx.query<Application&{password_hash:string;invitation_id:string|null;approval_hash:string|null}>(`SELECT ${publicCols},password_hash,invitation_id,approval_hash FROM cohamy_crm.partner_applications WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!a)throw new CrmError('NOT_FOUND',404);if(a.status==='APPROVED'&&d.action==='APPROVE'&&a.version===d.version+1&&a.approval_hash===digest(JSON.stringify(d)))return {membershipId:a.membership_id,organizationId:a.organization_id};if(a.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(a.status!=='SUBMITTED')throw new CrmError('APPLICATION_LOCKED',409);
 if(d.action!=='APPROVE'){if(!d.message||(d.action==='NEEDS_INFO'&&!d.fields.length))throw new CrmError('REASON_REQUIRED',400);await tx.query('UPDATE cohamy_crm.partner_applications SET status=$1,version=version+1,updated_at=now() WHERE id=$2',[d.action,id]);await history(tx,id,d.action,d.message,d.fields,user.id);await audit(tx,user.id,'application.'+d.action.toLowerCase(),id);return {status:d.action};}
 if(!a.email_verified_at)throw new CrmError('EMAIL_VERIFICATION_REQUIRED',409);if(!d.role)throw new CrmError('INVALID_FIELDS',400);
 let organizationId=d.organizationId;if(a.invitation_id){const inv=(await tx.query<{organization_id:string|null;role:string;revoked_at:string|null;expires_at:string}>('SELECT organization_id,role,revoked_at,expires_at FROM cohamy_crm.partner_invitations WHERE id=$1 FOR SHARE',[a.invitation_id])).rows[0];if(inv.revoked_at||new Date(inv.expires_at).getTime()<=Date.now())throw new CrmError('INVITATION_INVALID',409);if(inv.organization_id&&organizationId!==inv.organization_id)throw new CrmError('INVITATION_SCOPE_MISMATCH',409);if(d.role!==inv.role)throw new CrmError('INVITATION_SCOPE_MISMATCH',409);}
 if(organizationId){if(!(await tx.query("SELECT id FROM cohamy_crm.organizations WHERE id=$1 AND kind='DEALER' AND active FOR SHARE",[organizationId])).rows.length)throw new CrmError('INVALID_ORGANIZATION',400);}else{if(d.role!=='DEALER_OWNER')throw new CrmError('INVALID_ORGANIZATION',400);organizationId=randomUUID();await tx.query("INSERT INTO cohamy_crm.organizations(id,code,name,kind,phone,email,address,contact_name,source) VALUES ($1,$2,$3,'DEALER',$4,$5,$6,$7,'Partner registration')",[organizationId,'DL-'+id.slice(0,8).toUpperCase(),a.company_name,a.phone,a.email,a.address,a.representative]);}
 if((await tx.query('SELECT id FROM cohamy_crm.users WHERE email=$1',[a.email])).rows.length)throw new CrmError('ACCOUNT_ALREADY_EXISTS',409);const userId=randomUUID(),membershipId=randomUUID();await tx.query('INSERT INTO cohamy_crm.users(id,email,display_name,password_hash) VALUES ($1,$2,$3,$4)',[userId,a.email,a.representative,a.password_hash]);await tx.query('INSERT INTO cohamy_crm.memberships(id,user_id,organization_id,role) VALUES ($1,$2,$3,$4)',[membershipId,userId,organizationId,d.role]);
 if(d.assigneeId){const m=(await tx.query("SELECT m.id FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.id=$1 AND m.role='SALES' AND m.active AND u.active AND o.active AND o.kind='COHAMY' FOR SHARE OF m,u,o",[d.assigneeId])).rows[0];if(!m)throw new CrmError('INVALID_ASSIGNEE',400);await tx.query('INSERT INTO cohamy_crm.partner_assignments(membership_id,organization_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',[d.assigneeId,organizationId]);}
 await tx.query("UPDATE cohamy_crm.partner_applications SET status='APPROVED',membership_id=$1,organization_id=$2,assigned_to=$3,version=version+1,updated_at=now(),approval_hash=$5 WHERE id=$4",[membershipId,organizationId,d.assigneeId??null,id,digest(JSON.stringify(d))]);await history(tx,id,'APPROVED',d.message,[],user.id);await audit(tx,user.id,'application.approved',id,{organizationId,membershipId,role:d.role});await enqueueNotification(tx,userId,'application-approved:'+id,'ONBOARDING','account',userId,'Hồ sơ đối tác đã được duyệt. Bạn có thể sử dụng cổng đại lý.');return {membershipId,organizationId};});}
export async function createInvitation(user:Principal,input:unknown){const d=parse(z.object({organizationId:z.uuid().optional(),role:z.enum(['DEALER_OWNER','DEALER_STAFF']),expiresAt:z.iso.datetime({offset:true}),maxUses:z.number().int().min(1).max(100)}).strict(),input);if(user.area==='portal'){if(user.role!=='DEALER_OWNER'||d.role!=='DEALER_STAFF'||d.organizationId!==user.organizationId)throw new CrmError('FORBIDDEN',403);}else admin(user);if(new Date(d.expiresAt).getTime()<=Date.now())throw new CrmError('INVALID_FIELDS',400);if(d.organizationId&&!(await(await database()).query("SELECT id FROM cohamy_crm.organizations WHERE id=$1 AND kind='DEALER' AND active",[d.organizationId])).rows.length)throw new CrmError('INVALID_ORGANIZATION',400);const token=randomBytes(32).toString('base64url'),id=randomUUID();await(await database()).transaction(async tx=>{await tx.query('INSERT INTO cohamy_crm.partner_invitations(id,token_hash,created_by,organization_id,role,expires_at,max_uses) VALUES ($1,$2,$3,$4,$5,$6,$7)',[id,digest(token),user.id,d.organizationId??null,d.role,d.expiresAt,d.maxUses]);await audit(tx,user.id,'invitation.created',id);});return {id,token};}
export async function invitations(user:Principal){if(user.area==='crm')admin(user);else if(user.role!=='DEALER_OWNER')throw new CrmError('FORBIDDEN',403);return(await(await database()).query<{id:string;role:string;uses:number;max_uses:number;expires_at:string;revoked_at:string|null}>('SELECT id,role,uses,max_uses,expires_at,revoked_at FROM cohamy_crm.partner_invitations WHERE created_by=$1 ORDER BY created_at DESC LIMIT 100',[user.id])).rows;}
export async function revokeInvitation(user:Principal,id:string){await(await database()).transaction(async tx=>{const row=(await tx.query<{created_by:string}>('SELECT created_by FROM cohamy_crm.partner_invitations WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row||row.created_by!==user.id)throw new CrmError('NOT_FOUND',404);await tx.query('UPDATE cohamy_crm.partner_invitations SET revoked_at=now() WHERE id=$1',[id]);await audit(tx,user.id,'invitation.revoked',id);});return {revoked:true};}
