import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit} from './auth';
import {CrmError,assertPermission} from './permissions';
import {parse} from './workspace';
import type {Principal} from './types';

export interface LibraryItem {id:string;title:string;category:string;audience:string;organization_id:string|null;required_read:boolean;status:string;effective_at:string;expires_at:string|null;version:number;read_confirmed?:boolean}
async function currentLibraryRead(user:Principal,id:string,sql?:Sql){
 const row=(await(sql??await database()).query<{confirmed:boolean}>(`SELECT count(v.id)>0 AND bool_and(r.read_at IS NOT NULL) AS confirmed
  FROM cohamy_crm.private_documents d JOIN cohamy_crm.document_versions v ON v.document_id=d.id
  LEFT JOIN cohamy_crm.document_reads r ON r.version_id=v.id AND r.user_id=$2
  WHERE d.entity_type='library' AND d.entity_id=$1
  AND v.number=(SELECT max(n.number) FROM cohamy_crm.document_versions n WHERE n.document_id=d.id)`,[id,user.id])).rows[0];
 return row?.confirmed??false;
}
function admin(user:Principal){assertPermission(user,'accounts.manage');if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}
function available(user:Principal,item:LibraryItem){return user.area==='portal'&&['DEALER_OWNER','DEALER_STAFF'].includes(user.role)&&item.status==='PUBLISHED'&&new Date(item.effective_at).getTime()<=Date.now()&&(!item.expires_at||new Date(item.expires_at).getTime()>Date.now())&&(!item.organization_id||item.organization_id===user.organizationId)&&(item.audience==='ALL_DEALERS'||item.audience===user.role);}
export async function getLibraryItem(user:Principal,id:string,sql?:Sql){if(!z.uuid().safeParse(id).success)throw new CrmError('NOT_FOUND',404);const item=(await(sql??await database()).query<LibraryItem>('SELECT * FROM cohamy_crm.partner_library WHERE id=$1',[id])).rows[0];if(!item)throw new CrmError('NOT_FOUND',404);if(user.area==='crm'){admin(user);}else if(!available(user,item))throw new CrmError('NOT_FOUND',404);return {...item,read_confirmed:item.required_read&&await currentLibraryRead(user,id,sql)};}
export async function library(user:Principal,q:Record<string,string>={}){if(user.area==='crm')admin(user);else assertPermission(user,'catalog.read');const category=q.category??'ALL';parse(z.enum(['ALL','CATALOGUE','IMAGE','GUIDE','POLICY']),category);const rows=(await(await database()).query<LibraryItem>(`SELECT * FROM cohamy_crm.partner_library WHERE title ILIKE $1 AND ($2='ALL' OR category=$2) AND ($3='crm' OR (status='PUBLISHED' AND effective_at<=now() AND (expires_at IS NULL OR expires_at>now()) AND (organization_id IS NULL OR organization_id=$4::uuid) AND (audience='ALL_DEALERS' OR audience=$5))) ORDER BY created_at DESC,id LIMIT 200`,['%'+(q.q??'').slice(0,120)+'%',category,user.area,user.organizationId,user.role])).rows;return Promise.all(rows.filter(item=>user.area==='crm'||available(user,item)).map(async item=>({...item,read_confirmed:item.required_read&&await currentLibraryRead(user,item.id)})));}
const schema=z.object({id:z.uuid().optional(),version:z.number().int().min(0),title:z.string().trim().min(2).max(200),category:z.enum(['CATALOGUE','IMAGE','GUIDE','POLICY']),audience:z.enum(['ALL_DEALERS','DEALER_OWNER','DEALER_STAFF']),organizationId:z.uuid().nullable().default(null),requiredRead:z.boolean(),status:z.enum(['DRAFT','PUBLISHED','WITHDRAWN']),effectiveAt:z.iso.datetime({offset:true}),expiresAt:z.iso.datetime({offset:true}).nullable().default(null)}).strict();
export async function saveLibraryItem(user:Principal,input:unknown){admin(user);const d=parse(schema,input);if(d.expiresAt&&d.expiresAt<=d.effectiveAt)throw new CrmError('INVALID_FIELDS',400);return(await database()).transaction(async tx=>{const id=d.id??randomUUID();if(d.organizationId&&!(await tx.query("SELECT id FROM cohamy_crm.organizations WHERE id=$1 AND kind='DEALER' AND active FOR SHARE",[d.organizationId])).rows.length)throw new CrmError('INVALID_ORGANIZATION',400);if(d.version===0){if(d.id||d.status!=='DRAFT')throw new CrmError('INVALID_FIELDS',400);await tx.query('INSERT INTO cohamy_crm.partner_library(id,title,category,audience,organization_id,required_read,status,effective_at,expires_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,d.title,d.category,d.audience,d.organizationId,d.requiredRead,d.status,d.effectiveAt,d.expiresAt,user.id]);}else{await tx.query('SELECT id FROM cohamy_crm.partner_library WHERE id=$1 FOR UPDATE',[id]);const prior=await getLibraryItem(user,id,tx);if(prior.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(d.status==='PUBLISHED'&&!(await tx.query("SELECT d.id FROM cohamy_crm.private_documents d JOIN cohamy_crm.document_versions v ON v.document_id=d.id WHERE d.entity_type='library' AND d.entity_id=$1",[id])).rows.length)throw new CrmError('LIBRARY_FILE_REQUIRED',409);await tx.query('UPDATE cohamy_crm.partner_library SET title=$1,category=$2,audience=$3,organization_id=$4,required_read=$5,status=$6,effective_at=$7,expires_at=$8,version=version+1 WHERE id=$9',[d.title,d.category,d.audience,d.organizationId,d.requiredRead,d.status,d.effectiveAt,d.expiresAt,id]);}await audit(tx,user.id,'library.saved',id,{status:d.status,audience:d.audience,requiredRead:d.requiredRead});return {id};});}
export async function markCatalogSeen(user:Principal){if(user.area!=='portal')return;await(await database()).query('INSERT INTO cohamy_crm.onboarding_progress(user_id,catalog_seen_at) VALUES ($1,now()) ON CONFLICT(user_id) DO UPDATE SET catalog_seen_at=COALESCE(cohamy_crm.onboarding_progress.catalog_seen_at,EXCLUDED.catalog_seen_at)',[user.id]);}
export async function onboardingChecklist(user:Principal){if(user.area!=='portal')throw new CrmError('FORBIDDEN',403);const db=await database(),org=(await db.query<{name:string;phone:string;email:string;address:string}>('SELECT name,phone,email,address FROM cohamy_crm.organizations WHERE id=$1',[user.organizationId])).rows[0],progress=(await db.query<{catalog_seen_at:string|null}>('SELECT catalog_seen_at FROM cohamy_crm.onboarding_progress WHERE user_id=$1',[user.id])).rows[0];const policies=(await library(user)).filter(i=>i.required_read);const required=[];for(const item of policies){const versions=(await db.query<{id:string;read_at:string|null}>(`SELECT v.id,r.read_at FROM cohamy_crm.private_documents d JOIN cohamy_crm.document_versions v ON v.document_id=d.id LEFT JOIN cohamy_crm.document_reads r ON r.version_id=v.id AND r.user_id=$2 WHERE d.entity_type='library' AND d.entity_id=$1 AND v.number=(SELECT max(n.number) FROM cohamy_crm.document_versions n WHERE n.document_id=d.id)`,[item.id,user.id])).rows;required.push({id:item.id,title:item.title,read:versions.length>0&&versions.every(v=>!!v.read_at)});}return {profileComplete:!!org&&[org.name,org.phone,org.email,org.address].every(s=>s.trim().length>0),catalogSeen:!!progress?.catalog_seen_at,policies:required,commercialRequestCreated:false};}
