import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit} from './auth';
import {CrmError,can} from './permissions';
import {parse,enqueueNotification} from './workspace';
import {getOrganization,partnerScope} from './repository';
import type {Principal} from './types';
function dealer(user:Principal){if(user.area!=='portal')throw new CrmError('FORBIDDEN',403);}
export async function addresses(user:Principal){dealer(user);return(await(await database()).query<{id:string;label:string;recipient:string;phone:string;address:string;is_default:boolean;active:boolean;version:number}>('SELECT id,label,recipient,phone,address,is_default,active,version FROM cohamy_crm.dealer_addresses WHERE organization_id=$1 ORDER BY active DESC,is_default DESC,label',[user.organizationId])).rows;}
export async function saveAddress(user:Principal,input:unknown){dealer(user);if(user.role!=='DEALER_OWNER')throw new CrmError('FORBIDDEN',403);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),label:z.string().trim().min(2).max(100),recipient:z.string().trim().min(2).max(120),phone:z.string().regex(/^\+?[0-9 ()-]{8,25}$/),address:z.string().trim().min(5).max(500),isDefault:z.boolean(),active:z.boolean()}).strict(),input);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.organizations WHERE id=$1 FOR UPDATE',[user.organizationId]);const id=d.id??randomUUID();if(d.isDefault&&!d.active)throw new CrmError('INVALID_FIELDS',400);if(d.isDefault)await tx.query('UPDATE cohamy_crm.dealer_addresses SET is_default=false,version=version+1 WHERE organization_id=$1 AND is_default AND id<>$2',[user.organizationId,id]);const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.dealer_addresses(id,organization_id,label,recipient,phone,address,is_default,active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[id,user.organizationId,d.label,d.recipient,d.phone,d.address,d.isDefault,d.active]):await tx.query('UPDATE cohamy_crm.dealer_addresses SET label=$1,recipient=$2,phone=$3,address=$4,is_default=$5,active=$6,version=version+1 WHERE id=$7 AND organization_id=$8 AND version=$9 RETURNING id',[d.label,d.recipient,d.phone,d.address,d.isDefault,d.active,id,user.organizationId,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'dealer.address-saved',user.organizationId,{addressId:id});return {id};});}
export async function cart(user:Principal){dealer(user);return(await(await database()).query<{lines:{sku:string;quantity:number;unit:string}[];version:number;updated_at:string}>('SELECT lines,version,updated_at FROM cohamy_crm.dealer_carts WHERE user_id=$1 AND organization_id=$2',[user.id,user.organizationId])).rows[0]??{lines:[],version:0,updated_at:null};}
export async function saveCart(user:Principal,input:unknown){dealer(user);const d=parse(z.object({version:z.number().int().min(0),lines:z.array(z.object({sku:z.string().regex(/^[A-Za-z0-9_-]{2,80}$/),quantity:z.number().int().min(1).max(100000),unit:z.string().trim().min(1).max(40)}).strict()).max(100)}).strict(),input);if(new Set(d.lines.map(x=>x.sku)).size!==d.lines.length)throw new CrmError('DUPLICATE_SKU',400);return(await database()).transaction(async tx=>{for(const line of d.lines){const p=(await tx.query<{stock_unit:string}>('SELECT stock_unit FROM cohamy_crm.products WHERE sku=$1 AND active FOR SHARE',[line.sku])).rows[0];if(!p||!p.stock_unit||p.stock_unit!==line.unit)throw new CrmError('SKU_UNIT_INVALID',400);}const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.dealer_carts(user_id,organization_id,lines) VALUES ($1,$2,$3::jsonb) ON CONFLICT DO NOTHING RETURNING version',[user.id,user.organizationId,JSON.stringify(d.lines)]):await tx.query('UPDATE cohamy_crm.dealer_carts SET lines=$1::jsonb,version=version+1,updated_at=now() WHERE user_id=$2 AND organization_id=$3 AND version=$4 RETURNING version',[JSON.stringify(d.lines),user.id,user.organizationId,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);return r.rows[0];});}
export interface Ticket{id:string;organization_id:string;created_by:string;title:string;body:string;status:string;assigned_to:string|null;version:number;created_at:string;updated_at:string}
export async function getTicket(user:Principal,id:string,sql?:Sql){if(!z.uuid().safeParse(id).success)throw new CrmError('NOT_FOUND',404);const r=(await(sql??await database()).query<Ticket>('SELECT * FROM cohamy_crm.support_tickets WHERE id=$1',[id])).rows[0];if(!r)throw new CrmError('NOT_FOUND',404);if(user.area==='portal'){if(r.organization_id!==user.organizationId)throw new CrmError('NOT_FOUND',404);}else await getOrganization(user,r.organization_id,sql);return r;}
export async function listTickets(user:Principal,q:Record<string,string>={}){const scope=user.area==='portal'?{sql:'t.organization_id=$1',params:[user.organizationId]}:partnerScope(user);if(user.area==='crm'&&!can(user,'partners.read'))throw new CrmError('FORBIDDEN',403);const n=scope.params.length,status=parse(z.enum(['ALL','OPEN','IN_PROGRESS','WAITING_PARTNER','RESOLVED']),q.status??'ALL'),page=Math.max(1,Math.min(10000,Number(q.page)||1));return(await(await database()).query<Ticket>(`SELECT t.* FROM cohamy_crm.support_tickets t JOIN cohamy_crm.organizations o ON o.id=t.organization_id WHERE (${scope.sql}) AND ($${n+1}='ALL' OR t.status=$${n+1}) AND t.title ILIKE $${n+2} ORDER BY t.created_at DESC,t.id LIMIT 20 OFFSET $${n+3}`,[...scope.params,status,'%'+(q.q??'').slice(0,120)+'%',(page-1)*20])).rows;}
export async function createTicket(user:Principal,input:unknown){dealer(user);const d=parse(z.object({title:z.string().trim().min(2).max(240),body:z.string().trim().min(5).max(4000),idempotencyKey:z.uuid()}).strict(),input);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id]);const prior=(await tx.query<{ticket_id:string;body:string}>('SELECT ticket_id,body FROM cohamy_crm.support_messages WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){const old=await getTicket(user,prior.ticket_id,tx);if(old.title!==d.title||old.body!==d.body)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return {id:old.id};}const id=randomUUID();await tx.query('INSERT INTO cohamy_crm.support_tickets(id,organization_id,created_by,title,body) VALUES ($1,$2,$3,$4,$5)',[id,user.organizationId,user.id,d.title,d.body]);await tx.query('INSERT INTO cohamy_crm.support_messages(id,ticket_id,actor_id,body,idempotency_key) VALUES ($1,$2,$3,$4,$5)',[randomUUID(),id,user.id,d.body,d.idempotencyKey]);await audit(tx,user.id,'support.created',id);return {id};});}
export async function ticketMessages(user:Principal,id:string){await getTicket(user,id);return(await(await database()).query<{id:string;body:string;internal:boolean;created_at:string;actor_name:string}>('SELECT m.id,m.body,m.internal,m.created_at,u.display_name AS actor_name FROM cohamy_crm.support_messages m JOIN cohamy_crm.users u ON u.id=m.actor_id WHERE ticket_id=$1 AND ($2::boolean OR NOT internal) ORDER BY created_at,m.id',[id,user.area==='crm'])).rows;}
export async function replyTicket(user:Principal,input:unknown){const d=parse(z.object({id:z.uuid(),body:z.string().trim().min(1).max(4000),internal:z.boolean().default(false),idempotencyKey:z.uuid()}).strict(),input);if(user.area==='portal'&&d.internal)throw new CrmError('FORBIDDEN',403);if(user.area==='crm'&&!can(user,'partners.write'))throw new CrmError('FORBIDDEN',403);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.support_tickets WHERE id=$1 FOR UPDATE',[d.id]);const t=await getTicket(user,d.id,tx);const prior=(await tx.query<{ticket_id:string;body:string;internal:boolean}>('SELECT ticket_id,body,internal FROM cohamy_crm.support_messages WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.ticket_id!==d.id||prior.body!==d.body||prior.internal!==d.internal)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return {saved:true};}await tx.query('INSERT INTO cohamy_crm.support_messages(id,ticket_id,actor_id,body,internal,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6)',[randomUUID(),d.id,user.id,d.body,d.internal,d.idempotencyKey]);await audit(tx,user.id,'support.replied',d.id,{internal:d.internal});if(!d.internal&&user.area==='crm')await enqueueNotification(tx,t.created_by,'support-reply:'+d.idempotencyKey,'SUPPORT','ticket',t.id,'Cohamy đã phản hồi phiếu hỗ trợ: '+t.title);return {saved:true};});}
export async function updateTicket(user:Principal,input:unknown){if(user.area!=='crm'||!can(user,'partners.write'))throw new CrmError('FORBIDDEN',403);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),status:z.enum(['OPEN','IN_PROGRESS','WAITING_PARTNER','RESOLVED']),assigneeId:z.uuid().optional()}).strict(),input);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.support_tickets WHERE id=$1 FOR UPDATE',[d.id]);const t=await getTicket(user,d.id,tx);if(t.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(d.assigneeId){if(!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);const {membershipPrincipal}=await import('./auth');const staff=await membershipPrincipal(d.assigneeId,tx);if(!staff||staff.area!=='crm'||!can(staff,'partners.write'))throw new CrmError('INVALID_ASSIGNEE',400);await getOrganization(staff,t.organization_id,tx);}await tx.query('UPDATE cohamy_crm.support_tickets SET status=$1,assigned_to=COALESCE($2,assigned_to),version=version+1,updated_at=now() WHERE id=$3',[d.status,d.assigneeId??null,d.id]);await audit(tx,user.id,'support.updated',d.id,{from:t.status,to:d.status});return {version:t.version+1};});}
