import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {assertCurrentPrincipal,audit} from './auth';
import {assertPermission,CrmError} from './permissions';
import {getOrganization} from './repository';
import type {Principal,Organization} from './types';
import {integer} from './decimal';
import {priceDefinitionSchema,basketSchema,calculatePrice,type PriceDefinition,type Basket,type PriceProduct} from './pricing-model';
import {parseCommercial as parse,commercialManager as manager,commercialDigest as hash} from './commercial-common';

export interface PriceBook {id:string;name:string;version:number;latest_version_id:string|null;published_version_id:string|null;status:'DRAFT'|'PUBLISHED'|'WITHDRAWN';audience:string|null;tier_id:string|null;organization_id:string|null;priority:number|null;starts_at:string|null;ends_at:string|null}
export interface PriceVersion {id:string;book_id:string;number:number;definition:PriceDefinition;checksum:string;actor_id:string;created_at:string}
export async function pricingOrganization(sql:Sql,user:Principal,id:string){
 parse(z.uuid(),id);if(user.area==='portal'){if(id!==user.organizationId)throw new CrmError('NOT_FOUND',404);}else await getOrganization(user,id,sql);
 const org=(await sql.query<Organization>('SELECT * FROM cohamy_crm.organizations WHERE id=$1 FOR SHARE',[id])).rows[0];if(!org||!org.active||org.merged_into_id||!['DEALER','CUSTOMER'].includes(org.kind))throw new CrmError('COMMERCIAL_PARTNER_UNAVAILABLE',409);return org;
}
export async function priceTiers(user:Principal){manager(user);return(await(await database()).query<{id:string;code:string;name:string;active:boolean;version:number}>('SELECT * FROM cohamy_crm.price_tiers ORDER BY code')).rows;}
export async function savePriceTier(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),code:z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9_-]+$/),name:z.string().trim().min(2).max(120),active:z.boolean()}).strict(),input);if(Boolean(d.id)!==(d.version>0))throw new CrmError('INVALID_FIELDS',400);
 return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const id=d.id??randomUUID(),r=d.id?await tx.query('UPDATE cohamy_crm.price_tiers SET code=$1,name=$2,active=$3,version=version+1 WHERE id=$4 AND version=$5 RETURNING id',[d.code,d.name,d.active,id,d.version]):await tx.query('INSERT INTO cohamy_crm.price_tiers(id,code,name,active) VALUES($1,$2,$3,$4) RETURNING id',[id,d.code,d.name,d.active]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'pricing.tier-saved',id,{after:d,reason:'Cấu hình cấp giá; chưa phát hành bảng giá.'});return {id,version:d.version+1};});
}
export async function organizationTier(user:Principal,id:string,sql?:Sql){const tx=sql??await database();await pricingOrganization(tx,user,id);return(await tx.query<{tier_id:string;version:number;name:string}>('SELECT p.tier_id,p.version,t.name FROM cohamy_crm.organization_pricing p JOIN cohamy_crm.price_tiers t ON t.id=p.tier_id WHERE p.organization_id=$1',[id])).rows[0]??null;}
export async function assignPriceTier(user:Principal,input:unknown){manager(user);const d=parse(z.object({organizationId:z.uuid(),tierId:z.uuid(),version:z.number().int().min(0),reason:z.string().trim().min(3).max(500)}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await pricingOrganization(tx,user,d.organizationId);if(!(await tx.query('SELECT id FROM cohamy_crm.price_tiers WHERE id=$1 AND active FOR SHARE',[d.tierId])).rows.length)throw new CrmError('TIER_UNAVAILABLE',409);const before=await organizationTier(user,d.organizationId,tx),r=d.version===0?await tx.query('INSERT INTO cohamy_crm.organization_pricing(organization_id,tier_id,updated_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING organization_id',[d.organizationId,d.tierId,user.id]):await tx.query('UPDATE cohamy_crm.organization_pricing SET tier_id=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE organization_id=$3 AND version=$4 RETURNING organization_id',[d.tierId,user.id,d.organizationId,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'pricing.tier-assigned',d.organizationId,{before,after:{tierId:d.tierId,version:d.version+1},reason:d.reason});return {version:d.version+1};});}

export async function productPriceUnits(user:Principal,productId:string,sql?:Sql){assertPermission(user,'catalog.read');parse(z.uuid(),productId);return(await(sql??await database()).query<{code:string;label:string;numerator:string;denominator:string;is_case:boolean;allow_fractional:boolean;active:boolean;version:number}>('SELECT code,label,numerator::text,denominator::text,is_case,allow_fractional,active,version FROM cohamy_crm.commercial_units WHERE product_id=$1 '+(user.area==='portal'?'AND active ':'')+'ORDER BY code',[productId])).rows;}
export async function savePriceUnit(user:Principal,input:unknown){manager(user);const d=parse(z.object({productId:z.uuid(),productVersion:z.number().int().positive(),code:z.string().min(1).max(40).regex(/^[A-Za-z0-9_-]+$/),label:z.string().trim().min(1).max(80),numerator:z.string().regex(/^\d{1,24}$/),denominator:z.string().regex(/^\d{1,24}$/),isCase:z.boolean(),allowFractional:z.boolean(),active:z.boolean(),version:z.number().int().min(0),reason:z.string().trim().min(3).max(500)}).strict(),input);if(integer(d.numerator)<=0n||integer(d.denominator)<=0n||(d.code==='BASE'&&(integer(d.numerator)!==1n||integer(d.denominator)!==1n)))throw new CrmError('INVALID_UNIT_RATIO',400);
 return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const p=(await tx.query<{version:number;active:boolean;stock_unit:string}>('SELECT version,active,stock_unit FROM cohamy_crm.products WHERE id=$1 FOR UPDATE',[d.productId])).rows[0];if(!p||!p.active||!p.stock_unit)throw new CrmError('SKU_UNCONFIGURED',409);if(p.version!==d.productVersion)throw new CrmError('VERSION_CONFLICT',409);const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.commercial_units(product_id,code,label,numerator,denominator,is_case,allow_fractional,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING RETURNING code',[d.productId,d.code,d.label,d.numerator,d.denominator,d.isCase,d.allowFractional,d.active]):await tx.query('UPDATE cohamy_crm.commercial_units SET label=$1,numerator=$2,denominator=$3,is_case=$4,allow_fractional=$5,active=$6,version=version+1 WHERE product_id=$7 AND code=$8 AND version=$9 RETURNING code',[d.label,d.numerator,d.denominator,d.isCase,d.allowFractional,d.active,d.productId,d.code,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await tx.query('UPDATE cohamy_crm.products SET version=version+1 WHERE id=$1',[d.productId]);await tx.query('INSERT INTO cohamy_crm.commercial_unit_versions(id,product_id,code,version,snapshot,actor_id) VALUES($1,$2,$3,$4,$5::jsonb,$6)',[randomUUID(),d.productId,d.code,d.version+1,JSON.stringify(d),user.id]);await audit(tx,user.id,'pricing.unit-saved',d.productId,{after:d,reason:d.reason});return {version:d.version+1,productVersion:p.version+1};});
}
export async function loadPriceProducts(sql:Sql,skus:string[],lock=false):Promise<PriceProduct[]>{const rows=(await sql.query<{id:string;sku:string;name:string;stock_unit:string;version:number}>('SELECT id,sku,name,stock_unit,version FROM cohamy_crm.products WHERE active AND sku=ANY($1::text[]) ORDER BY id'+(lock?' FOR SHARE':''),[[...new Set(skus)]])).rows;const products:PriceProduct[]=[];for(const p of rows){const units=(await sql.query<{code:string;label:string;numerator:string;denominator:string;is_case:boolean;allow_fractional:boolean;version:number}>('SELECT code,label,numerator::text,denominator::text,is_case,allow_fractional,version FROM cohamy_crm.commercial_units WHERE product_id=$1 AND active ORDER BY code'+(lock?' FOR SHARE':''),[p.id])).rows;products.push({id:p.id,sku:p.sku,name:p.name,stockUnit:p.stock_unit,version:p.version,units:units.map(u=>({code:u.code,label:u.label,numerator:u.numerator,denominator:u.denominator,isCase:u.is_case,allowFractional:u.allow_fractional,version:u.version}))});}return products;}
async function validateDefinition(sql:Sql,d:PriceDefinition){
 if(d.audience==='TIER'&&!(await sql.query('SELECT id FROM cohamy_crm.price_tiers WHERE id=$1 AND active FOR SHARE',[d.tierId])).rows.length)throw new CrmError('TIER_UNAVAILABLE',409);
 if(d.audience==='ORGANIZATION'&&!(await sql.query("SELECT id FROM cohamy_crm.organizations WHERE id=$1 AND active AND merged_into_id IS NULL AND kind IN('DEALER','CUSTOMER') FOR SHARE",[d.organizationId])).rows.length)throw new CrmError('COMMERCIAL_PARTNER_UNAVAILABLE',409);
 const skus=[...new Set([...d.lines.map(l=>l.sku),...d.minimum.skus.map(l=>l.sku),...d.gifts.flatMap(g=>[g.giftSku,...g.conditions.map(c=>c.sku)])])],products=await loadPriceProducts(sql,skus,true);
 if(skus.length!==products.length||products.some(p=>!p.stockUnit||!p.units.some(u=>u.code==='BASE'&&integer(u.numerator)===1n&&integer(u.denominator)===1n)))throw new CrmError('SKU_UNCONFIGURED',409);
 for(const g of d.gifts){const p=products.find(p=>p.sku===g.giftSku)!;if(!p.units.find(u=>u.code==='BASE')!.allowFractional&&g.giftBaseQuantity.includes('.')&&Number(g.giftBaseQuantity.split('.')[1])!==0)throw new CrmError('INVALID_GIFT_QUANTITY',400);}
 if(d.minimum.cases>0&&d.lines.every(l=>!products.find(p=>p.sku===l.sku)!.units.some(u=>u.isCase)))throw new CrmError('CASE_UNIT_UNCONFIGURED',409);
}
export async function listPriceBooks(user:Principal){manager(user);return(await(await database()).query<PriceBook>('SELECT * FROM cohamy_crm.price_books ORDER BY updated_at DESC,id LIMIT 200')).rows;}
export async function getPriceBook(user:Principal,id:string){manager(user);parse(z.uuid(),id);const book=(await(await database()).query<PriceBook>('SELECT * FROM cohamy_crm.price_books WHERE id=$1',[id])).rows[0];if(!book)throw new CrmError('NOT_FOUND',404);return book;}
export async function priceBookVersions(user:Principal,id:string){manager(user);parse(z.uuid(),id);return(await(await database()).query<PriceVersion>('SELECT id,book_id,number,definition,checksum,actor_id,created_at FROM cohamy_crm.price_book_versions WHERE book_id=$1 ORDER BY number DESC',[id])).rows;}
export async function savePriceBook(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(2).max(120),definition:priceDefinitionSchema,idempotencyKey:z.uuid()}).strict(),input);if(Boolean(d.id)!==(d.version>0))throw new CrmError('INVALID_FIELDS',400);const requestHash=hash(d);
 return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await tx.exec('LOCK TABLE cohamy_crm.price_books IN SHARE ROW EXCLUSIVE MODE');const prior=(await tx.query<{id:string;book_id:string;number:number;request_hash:string}>('SELECT id,book_id,number,request_hash FROM cohamy_crm.price_book_versions WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return {id:prior.book_id,version:d.version+1,versionId:prior.id,number:prior.number};}
 await validateDefinition(tx,d.definition);const id=d.id??randomUUID();if(d.id){const head=(await tx.query<PriceBook>('SELECT * FROM cohamy_crm.price_books WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!head||head.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);}else await tx.query('INSERT INTO cohamy_crm.price_books(id,name,created_by) VALUES($1,$2,$3)',[id,d.name,user.id]);const number=Number((await tx.query<{n:string}>('SELECT COALESCE(max(number),0)::text AS n FROM cohamy_crm.price_book_versions WHERE book_id=$1',[id])).rows[0].n)+1,versionId=randomUUID();await tx.query('INSERT INTO cohamy_crm.price_book_versions(id,book_id,number,definition,checksum,actor_id,idempotency_key,request_hash) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8)',[versionId,id,number,JSON.stringify(d.definition),hash(d.definition),user.id,d.idempotencyKey,requestHash]);await tx.query('UPDATE cohamy_crm.price_books SET name=$1,latest_version_id=$2,version=$3,updated_at=now() WHERE id=$4',[d.name,versionId,d.version+1,id]);await audit(tx,user.id,'pricing.draft-saved',id,{after:{versionId,number,checksum:hash(d.definition)},reason:'Lưu phiên bản nháp; giữ nguyên bảng đang phát hành.'});return {id,version:d.version+1,versionId,number};});
}
export async function publishPriceBook(user:Principal,input:unknown){manager(user);const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),versionId:z.uuid(),action:z.enum(['PUBLISH','WITHDRAW']),reason:z.string().trim().min(3).max(500),idempotencyKey:z.uuid()}).strict(),input),requestHash=hash(d);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await tx.exec('LOCK TABLE cohamy_crm.price_books IN SHARE ROW EXCLUSIVE MODE');const prior=(await tx.query<{request_hash:string;result:{id:string;version:number}}> ('SELECT request_hash,result FROM cohamy_crm.price_events WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return prior.result;}const head=(await tx.query<PriceBook>('SELECT * FROM cohamy_crm.price_books WHERE id=$1 FOR UPDATE',[d.id])).rows[0],v=(await tx.query<PriceVersion>('SELECT * FROM cohamy_crm.price_book_versions WHERE id=$1 AND book_id=$2',[d.versionId,d.id])).rows[0];if(!head||head.version!==d.version||!v)throw new CrmError('VERSION_CONFLICT',409);
 if(d.action==='PUBLISH'){if(head.latest_version_id!==v.id)throw new CrmError('VERSION_CONFLICT',409);await validateDefinition(tx,v.definition);const p=v.definition;const overlap=(await tx.query("SELECT id FROM cohamy_crm.price_books WHERE id<>$1 AND status='PUBLISHED' AND priority=$2 AND audience=$3 AND tier_id IS NOT DISTINCT FROM $4::uuid AND organization_id IS NOT DISTINCT FROM $5::uuid AND ($6::timestamptz IS NULL OR starts_at<$6) AND (ends_at IS NULL OR ends_at>$7)",[head.id,p.priority,p.audience,p.tierId,p.organizationId,p.endsAt,p.startsAt])).rows;if(overlap.length)throw new CrmError('PRICE_WINDOW_CONFLICT',409);await tx.query("UPDATE cohamy_crm.price_books SET published_version_id=$1,status='PUBLISHED',audience=$2,tier_id=$3,organization_id=$4,priority=$5,starts_at=$6,ends_at=$7,version=version+1,updated_at=now() WHERE id=$8",[v.id,p.audience,p.tierId,p.organizationId,p.priority,p.startsAt,p.endsAt,head.id]);}
 else {if(head.status!=='PUBLISHED'||head.published_version_id!==v.id)throw new CrmError('VERSION_CONFLICT',409);await tx.query("UPDATE cohamy_crm.price_books SET status='WITHDRAWN',version=version+1,updated_at=now() WHERE id=$1",[head.id]);}const result={id:head.id,version:head.version+1};await tx.query('INSERT INTO cohamy_crm.price_events(id,book_id,version_id,action,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[randomUUID(),head.id,v.id,d.action==='PUBLISH'?'PUBLISHED':'WITHDRAWN',user.id,d.reason,d.idempotencyKey,requestHash,JSON.stringify(result)]);await audit(tx,user.id,'pricing.'+d.action.toLowerCase(),head.id,{after:{versionId:v.id},reason:d.reason});return result;});}

export async function eligiblePriceBook(sql:Sql,user:Principal,organizationId:string,at?:Date):Promise<{book:PriceBook;priceVersion:PriceVersion}>{await pricingOrganization(sql,user,organizationId);const tier=(await sql.query<{tier_id:string}>('SELECT p.tier_id FROM cohamy_crm.organization_pricing p JOIN cohamy_crm.price_tiers t ON t.id=p.tier_id WHERE p.organization_id=$1 AND t.active FOR SHARE OF p,t',[organizationId])).rows[0];const now=at??new Date((await sql.query<{now:string}>('SELECT now() AS now')).rows[0].now);const books=(await sql.query<PriceBook>("SELECT * FROM cohamy_crm.price_books WHERE status='PUBLISHED' AND starts_at<=$1 AND (ends_at IS NULL OR ends_at>$1) AND (audience='ALL' OR (audience='TIER' AND tier_id=$2) OR (audience='ORGANIZATION' AND organization_id=$3)) ORDER BY priority DESC,CASE audience WHEN 'ORGANIZATION' THEN 3 WHEN 'TIER' THEN 2 ELSE 1 END DESC,id FOR SHARE",[now,tier?.tier_id??null,organizationId])).rows;if(!books.length)throw new CrmError('PRICE_UNAVAILABLE',409);const book=books[0],priceVersion=(await sql.query<PriceVersion>('SELECT * FROM cohamy_crm.price_book_versions WHERE id=$1',[book.published_version_id])).rows[0];if(!priceVersion||priceVersion.checksum!==hash(priceVersion.definition))throw new CrmError('PRICE_SNAPSHOT_INVALID',503);return {book,priceVersion};}
export async function calculateForOrganization(sql:Sql,user:Principal,organizationId:string,basket:Basket,at?:Date){const chosen=await eligiblePriceBook(sql,user,organizationId,at),products=await loadPriceProducts(sql,[...basket.lines.map(l=>l.sku),...chosen.priceVersion.definition.gifts.map(g=>g.giftSku)],true);return {...chosen,calculation:calculatePrice(chosen.priceVersion.definition,basket,products)};}
export async function previewPrice(user:Principal,input:unknown){assertPermission(user,'catalog.read');const d=parse(z.object({organizationId:z.uuid(),basket:basketSchema}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const r=await calculateForOrganization(tx,user,d.organizationId,d.basket);return {priceBookId:r.book.id,priceVersionId:r.priceVersion.id,priceVersionNumber:r.priceVersion.number,name:r.book.name,startsAt:r.book.starts_at,endsAt:r.book.ends_at,calculation:r.calculation};});}
