import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {assertCurrentPrincipal,audit} from './auth';
import {CrmError,assertPermission} from './permissions';
import {partnerScope} from './repository';
import {pricingOrganization,calculateForOrganization} from './pricing';
import {basketSchema,type Basket,type PriceDefinition,type PriceCalculation} from './pricing-model';
import {parseCommercial as parse,commercialWriter as writer,commercialManager as manager,commercialDigest as hash,vietnamBusinessDate} from './commercial-common';
import type {Principal} from './types';
export interface Quotation {id:string;code:string;organization_id:string;creator_membership_id:string;version:number;latest_version_id:string|null;sent_version_id:string|null;accepted_version_id:string|null;updated_at:string;organization_name?:string}
export interface QuotationSnapshot {organization:{id:string;code:string;name:string;phone:string;email:string;businessId:string;address:string};delivery:{recipient:string;phone:string;address:string};basket:Basket;calculation:PriceCalculation;priceBook:{id:string;name:string;versionId:string;number:number;checksum:string};policy:PriceDefinition;note:string;currency:'VND';issuedAt:string;validUntil:string}
export interface QuotationVersion {id:string;quotation_id:string;number:number;price_version_id:string;snapshot:QuotationSnapshot;checksum:string;approval_required:boolean;creator_id:string;valid_until:string;created_at:string}
export type QuotationViewVersion=Omit<QuotationVersion,'snapshot'> & {snapshot:Omit<QuotationSnapshot,'policy'> & {policy?:PriceDefinition}};
const deliverySchema=z.object({recipient:z.string().trim().min(2).max(120),phone:z.string().trim().min(5).max(40),address:z.string().trim().min(3).max(500)}).strict();
export async function quotationAccess(sql:Sql,user:Principal,id:string,lock=false):Promise<Quotation>{parse(z.uuid(),id);assertPermission(user,'orders.read');const scope=partnerScope(user);const roleSql=user.area==='portal'?'q.sent_version_id IS NOT NULL':"true";const portalStaff=user.area==='portal'&&user.role==='DEALER_STAFF';const result=(await sql.query<Quotation>(`SELECT q.*,o.name AS organization_name FROM cohamy_crm.quotations q JOIN cohamy_crm.organizations o ON o.id=q.organization_id WHERE ${portalStaff?'(o.id=$1 OR o.merged_into_id=$1)':scope.sql} AND ${roleSql} AND q.id=$${scope.params.length+1}`+(lock?' FOR UPDATE OF q':''),[...scope.params,id])).rows[0];if(!result)throw new CrmError('NOT_FOUND',404);return user.area==='portal'?{...result,latest_version_id:result.sent_version_id}:result;}
export async function listQuotations(user:Principal,q=''){assertPermission(user,'orders.read');const s=partnerScope(user),p=[...s.params,'%'+q.trim().slice(0,120)+'%'];return(await(await database()).query<Quotation>(`SELECT q.*,o.name AS organization_name FROM cohamy_crm.quotations q JOIN cohamy_crm.organizations o ON o.id=q.organization_id WHERE (${s.sql}) ${user.area==='portal'?'AND q.sent_version_id IS NOT NULL':''} AND(q.code ILIKE $${p.length} OR o.name ILIKE $${p.length}) ORDER BY q.updated_at DESC,q.id LIMIT 100`,p)).rows;}
export async function quotationVersions(user:Principal,id:string,sql?:Sql):Promise<QuotationViewVersion[]>{const tx=sql??await database(),head=await quotationAccess(tx,user,id);const rows=(await tx.query<QuotationVersion>(`SELECT v.* FROM cohamy_crm.quotation_versions v WHERE quotation_id=$1 ${user.area==='portal'?"AND EXISTS(SELECT 1 FROM cohamy_crm.quotation_events e WHERE e.version_id=v.id AND e.action='SENT')":''} ORDER BY number DESC`,[head.id])).rows;return rows.map(v=>user.area==='portal'?{...v,snapshot:{...v.snapshot,policy:undefined}}:v);}
export async function quoteVersionAccess(sql:Sql,user:Principal,head:Quotation,id:string):Promise<QuotationVersion>{const v=(await sql.query<QuotationVersion>('SELECT * FROM cohamy_crm.quotation_versions WHERE id=$1 AND quotation_id=$2',[parse(z.uuid(),id),head.id])).rows[0];if(!v||(user.area==='portal'&&!(await sql.query("SELECT id FROM cohamy_crm.quotation_events WHERE version_id=$1 AND action='SENT'",[id])).rows.length))throw new CrmError('NOT_FOUND',404);if(v.checksum!==hash(v.snapshot))throw new CrmError('QUOTE_SNAPSHOT_INVALID',503);return v;}
export async function quotationEvents(user:Principal,id:string,sql?:Sql){const tx=sql??await database();await quotationAccess(tx,user,id);return(await tx.query<{id:string;version_id:string;action:string;reason:string;actor_name:string;created_at:string}>(`SELECT e.id,e.version_id,e.action,e.reason,u.display_name AS actor_name,e.created_at FROM cohamy_crm.quotation_events e JOIN cohamy_crm.users u ON u.id=e.actor_id WHERE e.quotation_id=$1 ${user.area==='portal'?"AND e.action IN('SENT','ACCEPTED','REVISION_REQUESTED')":''} ORDER BY e.created_at DESC,e.id`,[id])).rows;}
export async function saveQuotation(user:Principal,input:unknown){writer(user);const d=parse(z.object({id:z.uuid().optional(),version:z.number().int().min(0),organizationId:z.uuid(),basket:basketSchema,delivery:deliverySchema,note:z.string().trim().max(2000),idempotencyKey:z.uuid()}).strict(),input);if(Boolean(d.id)!==(d.version>0))throw new CrmError('INVALID_FIELDS',400);const requestHash=hash(d);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id]);await assertCurrentPrincipal(tx,user);const prior=(await tx.query<{id:string;quotation_id:string;number:number;request_hash:string}>('SELECT id,quotation_id,number,request_hash FROM cohamy_crm.quotation_versions WHERE creator_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);await quotationAccess(tx,user,prior.quotation_id);return {id:prior.quotation_id,version:d.version+1,versionId:prior.id,number:prior.number};}
 const org=await pricingOrganization(tx,user,d.organizationId);let head:Quotation|undefined;if(d.id){head=await quotationAccess(tx,user,d.id,true);if(head.version!==d.version||head.organization_id!==org.id)throw new CrmError('VERSION_CONFLICT',409);if(head.accepted_version_id)throw new CrmError('QUOTE_ALREADY_ACCEPTED',409);}const r=await calculateForOrganization(tx,user,org.id,d.basket),now=new Date((await tx.query<{now:string}>('SELECT now() AS now')).rows[0].now),validUntil=new Date(now.getTime()+r.priceVersion.definition.quoteValidityHours*3600000).toISOString(),id=d.id??randomUUID(),versionId=randomUUID();const snapshot:QuotationSnapshot={organization:{id:org.id,code:org.code,name:org.name,phone:org.phone,email:org.email,businessId:org.business_id??'',address:org.address},delivery:d.delivery,basket:d.basket,calculation:r.calculation,priceBook:{id:r.book.id,name:r.book.name,versionId:r.priceVersion.id,number:r.priceVersion.number,checksum:r.priceVersion.checksum},policy:r.priceVersion.definition,note:d.note,currency:'VND',issuedAt:now.toISOString(),validUntil};if(!head)await tx.query('INSERT INTO cohamy_crm.quotations(id,code,organization_id,creator_membership_id) VALUES($1,$2,$3,$4)',[id,'BG-'+vietnamBusinessDate(now)+'-'+id.slice(0,8).toUpperCase(),org.id,user.membershipId]);const number=Number((await tx.query<{n:string}>('SELECT COALESCE(max(number),0)::text AS n FROM cohamy_crm.quotation_versions WHERE quotation_id=$1',[id])).rows[0].n)+1;await tx.query('INSERT INTO cohamy_crm.quotation_versions(id,quotation_id,number,price_version_id,snapshot,checksum,approval_required,creator_id,valid_until,idempotency_key,request_hash) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11)',[versionId,id,number,r.priceVersion.id,JSON.stringify(snapshot),hash(snapshot),r.calculation.approvalRequired,user.id,validUntil,d.idempotencyKey,requestHash]);await tx.query('UPDATE cohamy_crm.quotations SET latest_version_id=$1,version=$2,updated_at=now() WHERE id=$3',[versionId,d.version+1,id]);await audit(tx,user.id,'quotation.version-created',id,{after:{number,versionId,checksum:hash(snapshot),priceVersionId:r.priceVersion.id},reason:'Lưu bản báo giá mới; không thay bản đã gửi.'});return {id,version:d.version+1,versionId,number};});}
export async function quotationAction(user:Principal,input:unknown){const d=parse(z.object({id:z.uuid(),version:z.number().int().positive(),versionId:z.uuid(),action:z.enum(['APPROVE','REJECT','SEND','ACCEPT','REQUEST_REVISION']),reason:z.string().trim().min(3).max(2000),idempotencyKey:z.uuid()}).strict(),input);if(['APPROVE','REJECT'].includes(d.action))manager(user);else if(d.action==='SEND')writer(user);else if(user.area!=='portal'||user.role!=='DEALER_OWNER')throw new CrmError('FORBIDDEN',403);const requestHash=hash(d);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const head=await quotationAccess(tx,user,d.id,true),prior=(await tx.query<{request_hash:string;result:{id:string;version:number}}>('SELECT request_hash,result FROM cohamy_crm.quotation_events WHERE actor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return prior.result;}if(head.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(head.accepted_version_id)throw new CrmError('QUOTE_ALREADY_ACCEPTED',409);await pricingOrganization(tx,user,head.organization_id);const v=await quoteVersionAccess(tx,user,head,d.versionId),now=new Date((await tx.query<{now:string}>('SELECT now() AS now')).rows[0].now);if(new Date(v.valid_until)<=now)throw new CrmError('QUOTE_EXPIRED',409);
 if(d.action==='APPROVE'||d.action==='REJECT'){if(head.latest_version_id!==v.id||!v.approval_required)throw new CrmError('QUOTE_APPROVAL_NOT_REQUIRED',409);if(v.snapshot.policy.approval.nonSelfApproval&&v.creator_id===user.id)throw new CrmError('SELF_APPROVAL_BLOCKED',403);if((await tx.query("SELECT id FROM cohamy_crm.quotation_events WHERE version_id=$1 AND action IN('APPROVED','REJECTED','SENT')",[v.id])).rows.length)throw new CrmError('QUOTE_ALREADY_DECIDED',409);}
 if(d.action==='SEND'){if(head.latest_version_id!==v.id)throw new CrmError('VERSION_CONFLICT',409);if(v.snapshot.calculation.minimumShortfalls.length)throw new CrmError('ORDER_MINIMUM_NOT_MET',409);if(v.approval_required&&!(await tx.query("SELECT id FROM cohamy_crm.quotation_events WHERE version_id=$1 AND action='APPROVED'",[v.id])).rows.length)throw new CrmError('QUOTE_APPROVAL_REQUIRED',409);if((await tx.query("SELECT id FROM cohamy_crm.quotation_events WHERE version_id=$1 AND action='SENT'",[v.id])).rows.length)throw new CrmError('QUOTE_ALREADY_SENT',409);const {renderQuotationPdf,pdfChecksum}=await import('./quotation-pdf');const bytes=await renderQuotationPdf(head,v,true);await tx.query('INSERT INTO cohamy_crm.quotation_pdfs(version_id,content,checksum,actor_id) VALUES($1,$2,$3,$4)',[v.id,bytes,pdfChecksum(bytes),user.id]);await tx.query('UPDATE cohamy_crm.quotations SET sent_version_id=$1 WHERE id=$2',[v.id,head.id]);}
 if(d.action==='ACCEPT'||d.action==='REQUEST_REVISION'){if(head.sent_version_id!==v.id)throw new CrmError('QUOTE_SUPERSEDED',409);if(d.action==='ACCEPT')await tx.query('UPDATE cohamy_crm.quotations SET accepted_version_id=$1 WHERE id=$2',[v.id,head.id]);}
 const action={APPROVE:'APPROVED',REJECT:'REJECTED',SEND:'SENT',ACCEPT:'ACCEPTED',REQUEST_REVISION:'REVISION_REQUESTED'}[d.action],result={id:head.id,version:head.version+1};await tx.query('INSERT INTO cohamy_crm.quotation_events(id,quotation_id,version_id,action,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[randomUUID(),head.id,v.id,action,user.id,d.reason,d.idempotencyKey,requestHash,JSON.stringify(result)]);await tx.query('UPDATE cohamy_crm.quotations SET version=version+1,updated_at=now() WHERE id=$1',[head.id]);await audit(tx,user.id,'quotation.'+action.toLowerCase(),head.id,{after:{versionId:v.id,number:v.number},reason:d.reason});return result;});}
export function compareQuoteVersions(before:QuotationViewVersion,after:QuotationViewVersion){if(before.quotation_id!==after.quotation_id)throw new CrmError('INVALID_FIELDS',400);return {beforeNumber:before.number,afterNumber:after.number,total:{before:before.snapshot.calculation.total,after:after.snapshot.calculation.total},delivery:{before:before.snapshot.delivery,after:after.snapshot.delivery},lines:{before:before.snapshot.calculation.lines,after:after.snapshot.calculation.lines},terms:{before:before.snapshot.calculation.deliveryTerms,after:after.snapshot.calculation.deliveryTerms},validUntil:{before:before.valid_until,after:after.valid_until}};}
