import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit,digest,assertCurrentPrincipal} from './auth';
import {getOrganization,partnerScope,assertWritableOrganization} from './repository';
import {CrmError,assertPermission} from './permissions';
import {parse} from './workspace';
import type {Principal} from './types';
const internal=(user:Principal)=>{if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);assertPermission(user,'partners.read');};
const editor=(user:Principal)=>{internal(user);assertPermission(user,'partners.write');};
export const opportunityStages=['NEW','NEEDS','QUOTED','WON','LOST'] as const;
export interface Opportunity {id:string;organization_id:string;title:string;stage:string;reason_id:string|null;reason_name:string|null;notes:string;version:number;updated_at:string;actor_name:string}
export async function careDictionary(user:Principal,kind:'tags'|'reasons'){internal(user);return(await(await database()).query<{id:string;name:string;active:boolean;version:number}>(`SELECT * FROM cohamy_crm.care_${kind} ORDER BY name,id`)).rows;}
export async function saveCareDictionary(user:Principal,input:unknown){editor(user);if(!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);const d=parse(z.object({kind:z.enum(['tags','reasons']),id:z.uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(2).max(100),active:z.boolean()}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const id=d.id??randomUUID();const r=d.version===0?await tx.query(`INSERT INTO cohamy_crm.care_${d.kind}(id,name,active) VALUES ($1,$2,$3) RETURNING id`,[id,d.name,d.active]):await tx.query(`UPDATE cohamy_crm.care_${d.kind} SET name=$1,active=$2,version=version+1 WHERE id=$3 AND version=$4 RETURNING id`,[d.name,d.active,id,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'care.dictionary-saved',id,{kind:d.kind,active:d.active});return {id};});}
export async function partnerTags(user:Principal,id:string){internal(user);await getOrganization(user,id);return(await(await database()).query<{id:string;name:string;active:boolean}>('SELECT t.id,t.name,t.active FROM cohamy_crm.partner_tags p JOIN cohamy_crm.care_tags t ON t.id=p.tag_id WHERE p.organization_id=$1 ORDER BY t.name',[id])).rows;}
export async function savePartnerTags(user:Principal,input:unknown){editor(user);const d=parse(z.object({organizationId:z.uuid(),version:z.number().int().positive(),tagIds:z.array(z.uuid()).max(30).refine(ids=>new Set(ids).size===ids.length)}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await tx.query('SELECT id FROM cohamy_crm.organizations WHERE id=$1 FOR UPDATE',[d.organizationId]);const org=await assertWritableOrganization(tx,user,d.organizationId);if(org.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);for(const id of d.tagIds)if(!(await tx.query('SELECT id FROM cohamy_crm.care_tags WHERE id=$1 AND active FOR SHARE',[id])).rows.length)throw new CrmError('INVALID_TAG',400);await tx.query('DELETE FROM cohamy_crm.partner_tags WHERE organization_id=$1',[d.organizationId]);for(const id of d.tagIds)await tx.query('INSERT INTO cohamy_crm.partner_tags(organization_id,tag_id) VALUES ($1,$2)',[d.organizationId,id]);await tx.query('UPDATE cohamy_crm.organizations SET version=version+1 WHERE id=$1',[d.organizationId]);await audit(tx,user.id,'partner.tags-updated',d.organizationId,{tagIds:d.tagIds});return {version:org.version+1};});}
export async function contactPreferences(user:Principal,id:string){internal(user);await getOrganization(user,id);return(await(await database()).query<{channel:string;preferred_time:string;interested_skus:string[];notes:string;version:number}>('SELECT * FROM cohamy_crm.contact_preferences WHERE organization_id=$1',[id])).rows[0]??{channel:'PHONE',preferred_time:'',interested_skus:[],notes:'',version:0};}
export async function saveContactPreferences(user:Principal,input:unknown){editor(user);const d=parse(z.object({organizationId:z.uuid(),version:z.number().int().min(0),channel:z.enum(['PHONE','EMAIL','ZALO','IN_PERSON']),preferredTime:z.string().trim().max(200),interestedSkus:z.array(z.string().trim().min(1).max(80)).max(30).refine(ids=>new Set(ids).size===ids.length),notes:z.string().trim().max(1000)}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await assertWritableOrganization(tx,user,d.organizationId);for(const sku of d.interestedSkus)if(!(await tx.query('SELECT id FROM cohamy_crm.products WHERE sku=$1 AND active FOR SHARE',[sku])).rows.length)throw new CrmError('SKU_NOT_ACTIVE',400);const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.contact_preferences(organization_id,channel,preferred_time,interested_skus,notes) VALUES ($1,$2,$3,$4::jsonb,$5) ON CONFLICT DO NOTHING RETURNING organization_id',[d.organizationId,d.channel,d.preferredTime,JSON.stringify(d.interestedSkus),d.notes]):await tx.query('UPDATE cohamy_crm.contact_preferences SET channel=$1,preferred_time=$2,interested_skus=$3::jsonb,notes=$4,version=version+1,updated_at=now() WHERE organization_id=$5 AND version=$6 RETURNING organization_id',[d.channel,d.preferredTime,JSON.stringify(d.interestedSkus),d.notes,d.organizationId,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'partner.contact-preferences',d.organizationId);return {version:d.version+1};});}
export async function opportunities(user:Principal,id:string){internal(user);await getOrganization(user,id);return(await(await database()).query<Opportunity>('SELECT p.*,r.name AS reason_name,u.display_name AS actor_name FROM cohamy_crm.opportunities p LEFT JOIN cohamy_crm.care_reasons r ON r.id=p.reason_id JOIN cohamy_crm.users u ON u.id=p.updated_by WHERE organization_id=$1 ORDER BY p.updated_at DESC,p.id LIMIT 100',[id])).rows;}
export async function saveOpportunity(user:Principal,input:unknown){editor(user);const d=parse(z.object({id:z.uuid().optional(),organizationId:z.uuid(),version:z.number().int().min(0),title:z.string().trim().min(2).max(200),stage:z.enum(opportunityStages),reasonId:z.uuid().nullable().default(null),notes:z.string().trim().max(1000)}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await assertWritableOrganization(tx,user,d.organizationId);if(d.stage==='LOST'&&!d.reasonId)throw new CrmError('REASON_REQUIRED',400);if(d.reasonId&&!(await tx.query('SELECT id FROM cohamy_crm.care_reasons WHERE id=$1 AND active FOR SHARE',[d.reasonId])).rows.length)throw new CrmError('REASON_REQUIRED',400);const id=d.id??randomUUID();let fromStage:string|null=null;if(d.version===0){await tx.query('INSERT INTO cohamy_crm.opportunities(id,organization_id,title,stage,reason_id,notes,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7)',[id,d.organizationId,d.title,d.stage,d.reasonId,d.notes,user.id]);}else{const old=(await tx.query<Opportunity>('SELECT * FROM cohamy_crm.opportunities WHERE id=$1 AND organization_id=$2 FOR UPDATE',[id,d.organizationId])).rows[0];if(!old)throw new CrmError('NOT_FOUND',404);if(old.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);fromStage=old.stage;await tx.query('UPDATE cohamy_crm.opportunities SET title=$1,stage=$2,reason_id=$3,notes=$4,version=version+1,updated_by=$5,updated_at=now() WHERE id=$6',[d.title,d.stage,d.reasonId,d.notes,user.id,id]);}await tx.query('INSERT INTO cohamy_crm.opportunity_history(id,opportunity_id,actor_id,from_stage,to_stage,reason_id,notes) VALUES ($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),id,user.id,fromStage,d.stage,d.reasonId,d.notes]);await audit(tx,user.id,'opportunity.updated',d.organizationId,{opportunityId:id,from:fromStage,to:d.stage});return {id};});}
export interface Visit{id:string;organization_id:string;visitor_id:string;visitor_name:string;visited_at:string;result:string;support_request:string}
export async function getVisit(user:Principal,id:string,sql?:Sql){internal(user);if(!z.uuid().safeParse(id).success)throw new CrmError('NOT_FOUND',404);const tx=sql??await database(),row=(await tx.query<Visit>('SELECT v.*,u.display_name AS visitor_name FROM cohamy_crm.partner_visits v JOIN cohamy_crm.users u ON u.id=v.visitor_id WHERE v.id=$1',[id])).rows[0];if(!row)throw new CrmError('NOT_FOUND',404);await getOrganization(user,row.organization_id,tx);return row;}
export async function visits(user:Principal,id:string){internal(user);await getOrganization(user,id);const db=await database(),family=await (await import('./partner-merge')).partnerFamily(db,id);return(await db.query<Visit>('SELECT v.*,u.display_name AS visitor_name FROM cohamy_crm.partner_visits v JOIN cohamy_crm.users u ON u.id=v.visitor_id WHERE organization_id=ANY($1::uuid[]) ORDER BY visited_at DESC,v.id LIMIT 50',[family])).rows;}
export async function createVisit(user:Principal,input:unknown){editor(user);const d=parse(z.object({organizationId:z.uuid(),visitedAt:z.iso.datetime({offset:true}),result:z.string().trim().min(2).max(2000),supportRequest:z.string().trim().max(1000),idempotencyKey:z.uuid()}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);await assertWritableOrganization(tx,user,d.organizationId);await tx.query('SELECT id FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id]);const hash=digest(JSON.stringify(d)),prior=(await tx.query<{id:string;request_hash:string}>('SELECT id,request_hash FROM cohamy_crm.partner_visits WHERE visitor_id=$1 AND idempotency_key=$2',[user.id,d.idempotencyKey])).rows[0];if(prior){if(prior.request_hash!==hash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return {id:prior.id};}const id=randomUUID();await tx.query('INSERT INTO cohamy_crm.partner_visits(id,organization_id,visitor_id,visited_at,result,support_request,idempotency_key,request_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',[id,d.organizationId,user.id,d.visitedAt,d.result,d.supportRequest,d.idempotencyKey,hash]);await audit(tx,user.id,'partner.visited',d.organizationId,{visitId:id});return {id};});}
export async function visitDirectory(user:Principal,q:Record<string,string>={}){internal(user);const scope=partnerScope(user),params=[...scope.params,'%'+(q.q??'').slice(0,120)+'%',(Math.max(1,Math.min(10000,Number(q.page)||1))-1)*20];return(await(await database()).query<Visit&{organization_name:string}>(`SELECT v.*,u.display_name AS visitor_name,o.name AS organization_name FROM cohamy_crm.partner_visits v JOIN cohamy_crm.organizations o ON o.id=v.organization_id JOIN cohamy_crm.users u ON u.id=v.visitor_id WHERE (${scope.sql}) AND (o.name ILIKE $${params.length-1} OR v.result ILIKE $${params.length-1}) ORDER BY v.visited_at DESC,v.id LIMIT 20 OFFSET $${params.length}`,params)).rows;}
export async function careReport(user:Principal){internal(user);assertPermission(user,'reports.read');const scope=partnerScope(user);return(await(await database()).query<{reason:string;stage:string;count:string}>(`SELECT COALESCE(r.name,'Chưa ghi nhận lý do') AS reason,p.stage,count(*)::text AS count FROM cohamy_crm.opportunities p JOIN cohamy_crm.organizations o ON o.id=p.organization_id LEFT JOIN cohamy_crm.care_reasons r ON r.id=p.reason_id WHERE (${scope.sql}) GROUP BY r.name,p.stage ORDER BY p.stage,r.name`,scope.params)).rows;}
