import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {assertCurrentPrincipal,audit,membershipPrincipal} from './auth';
import {database,type Sql} from './db';
import {fixed,fixedText} from './decimal';
import {assertPermission,can,CrmError} from './permissions';
import type {PriceCalculation} from './pricing-model';
import type {Principal} from './types';

const day=z.iso.date(),filtersSchema=z.object({from:day,to:day,inactivityDays:z.number().int().min(1).max(730).default(60),organizationId:z.uuid().optional(),sku:z.string().trim().max(80).optional()}).strict().refine(v=>v.from<=v.to&&new Date(v.to).getTime()-new Date(v.from).getTime()<=366*86400000,{message:'REPORT_RANGE_TOO_LARGE'});
export type ReportFilters=z.infer<typeof filtersSchema>;
type Snapshot={quote:{calculation:PriceCalculation}};
const amount=(value:bigint)=>value.toString();
const allPartnerScope=(user:Principal)=>user.area==='crm'&&['ADMIN','MANAGER','ACCOUNTANT'].includes(user.role);
function check(user:Principal){assertPermission(user,'reports.read');if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}
export async function defaultReportFilters(){return(await(await database()).query<ReportFilters>("SELECT (current_date-interval '30 days')::date::text AS \"from\",current_date::text AS \"to\",60 AS \"inactivityDays\"")).rows[0];}

export async function operationalReports(user:Principal,input:unknown){check(user);const f=filtersSchema.parse(input),db=await database(),global=allPartnerScope(user),scope=[f.from,f.to,user.membershipId,global,f.organizationId??null,f.sku??null];
 const [sources,stages,dealers,delivered,costs,returns,speed,inventory,consignment,quality]=await Promise.all([
  db.query<{source:string;partners:string;converted:string}>(`SELECT COALESCE(NULLIF(o.source,''),'Chưa ghi nhận') AS source,count(*)::text AS partners,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM cohamy_crm.sales_orders s WHERE s.organization_id=o.id AND s.status='CONFIRMED'))::text AS converted FROM cohamy_crm.organizations o WHERE o.kind IN('CUSTOMER','DEALER') AND o.merged_into_id IS NULL AND o.created_at::date BETWEEN $1 AND $2 AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR o.id=$5) GROUP BY COALESCE(NULLIF(o.source,''),'Chưa ghi nhận') ORDER BY partners DESC,source`,scope.slice(0,5)),
  db.query<{stage:string;records:string;average_days:string;lost_reason:string}>(`SELECT o.stage,count(*)::text AS records,round(avg(extract(epoch FROM(now()-COALESCE(h.changed_at,o.created_at)))/86400)::numeric,1)::text AS average_days,COALESCE(r.name,'') AS lost_reason FROM cohamy_crm.opportunities o JOIN cohamy_crm.organizations p ON p.id=o.organization_id LEFT JOIN LATERAL(SELECT max(created_at) AS changed_at FROM cohamy_crm.opportunity_history x WHERE x.opportunity_id=o.id AND x.to_stage=o.stage)h ON true LEFT JOIN cohamy_crm.care_reasons r ON r.id=o.reason_id WHERE o.created_at::date BETWEEN $1 AND $2 AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=p.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR p.id=$5) GROUP BY o.stage,r.name ORDER BY o.stage,r.name`,scope.slice(0,5)),
  db.query<{id:string;name:string;region:string;created_at:string;last_order_at:string|null;activity_state:string}>(`SELECT o.id,o.name,COALESCE(NULLIF(o.region,''),'Chưa ghi nhận') AS region,o.created_at,last_order.last_order_at,CASE WHEN last_order.last_order_at IS NULL THEN 'NO_ORDERS' WHEN last_order.last_order_at::date<($2::date-$6::int) THEN 'DECLINING' ELSE 'ACTIVE' END AS activity_state FROM cohamy_crm.organizations o LEFT JOIN LATERAL(SELECT max(s.created_at)::text AS last_order_at FROM cohamy_crm.sales_orders s WHERE s.organization_id=o.id AND s.status='CONFIRMED')last_order ON true WHERE o.kind='DEALER' AND o.merged_into_id IS NULL AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR o.id=$5) AND (o.created_at::date BETWEEN $1 AND $2 OR last_order.last_order_at IS NULL OR last_order.last_order_at::date<($2::date-$6::int)) ORDER BY activity_state,o.name`,[f.from,f.to,user.membershipId,global,f.organizationId??null,f.inactivityDays]),
  db.query<{delivery_line_id:string;delivered:string;product_id:string;sku:string;product_name:string;organization_id:string;organization_name:string;region:string;sales_name:string;snapshot:Snapshot;occurred_at:string}>(`SELECT dl.id AS delivery_line_id,dl.delivered::text,r.product_id,p.sku,p.name AS product_name,o.id AS organization_id,o.name AS organization_name,COALESCE(NULLIF(o.region,''),'Chưa ghi nhận') AS region,u.display_name AS sales_name,v.snapshot,d.updated_at::text AS occurred_at FROM cohamy_crm.delivery_lines dl JOIN cohamy_crm.deliveries d ON d.id=dl.delivery_id JOIN cohamy_crm.inventory_reservations r ON r.id=dl.reservation_id JOIN cohamy_crm.products p ON p.id=r.product_id JOIN cohamy_crm.sales_orders s ON s.id=d.order_id JOIN cohamy_crm.sales_order_versions v ON v.id=s.confirmed_version_id JOIN cohamy_crm.organizations o ON o.id=s.organization_id JOIN cohamy_crm.users u ON u.id=s.creator_id WHERE dl.delivered>0 AND d.updated_at::date BETWEEN $1 AND $2 AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR o.id=$5) AND ($6::text IS NULL OR p.sku=$6) ORDER BY d.updated_at,dl.id`,scope),
  db.query<{product_id:string;accepted:string;cost_amount:string}>(`SELECT po.product_id,sum(gl.accepted)::text AS accepted,sum(gl.accepted*po.unit_price)::numeric(30,0)::text AS cost_amount FROM cohamy_crm.goods_receipt_lines gl JOIN cohamy_crm.goods_receipts g ON g.id=gl.receipt_id JOIN cohamy_crm.purchase_order_lines po ON po.id=gl.order_line_id WHERE gl.accepted>0 AND g.received_at::date<=$1 GROUP BY po.product_id`,[f.to]),
  db.query<{delivery_line_id:string;quantity:string}>(`SELECT rl.delivery_line_id,sum(rd.quantity)::text AS quantity FROM cohamy_crm.return_dispositions rd JOIN cohamy_crm.return_request_lines rl ON rl.id=rd.request_line_id WHERE rd.created_at::date BETWEEN $1 AND $2 GROUP BY rl.delivery_line_id`,scope.slice(0,2)),
  db.query<{order_id:string;code:string;created_at:string;confirmed_at:string|null;delivery_created_at:string|null;packed_at:string|null;delivered_at:string|null}>(`SELECT s.id AS order_id,s.code,s.created_at::text,(SELECT min(e.created_at)::text FROM cohamy_crm.commercial_events e WHERE e.order_id=s.id AND e.action='CONFIRMED') AS confirmed_at,(SELECT min(d.created_at)::text FROM cohamy_crm.deliveries d WHERE d.order_id=s.id) AS delivery_created_at,(SELECT min(e.created_at)::text FROM cohamy_crm.delivery_events e JOIN cohamy_crm.deliveries d ON d.id=e.delivery_id WHERE d.order_id=s.id AND e.action='PACK') AS packed_at,(SELECT min(e.created_at)::text FROM cohamy_crm.delivery_events e JOIN cohamy_crm.deliveries d ON d.id=e.delivery_id WHERE d.order_id=s.id AND e.action='DELIVER') AS delivered_at FROM cohamy_crm.sales_orders s JOIN cohamy_crm.organizations o ON o.id=s.organization_id WHERE s.created_at::date BETWEEN $1 AND $2 AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR o.id=$5) ORDER BY s.created_at,s.id`,scope.slice(0,5)),
  db.query<{warehouse:string;location_kind:string;sku:string;lot_code:string;on_hand:string;reserved:string;available:string;expires_on:string|null;last_movement_at:string|null;slow_days:number;near_expiry_days:number}>(`SELECT w.code AS warehouse,l.kind AS location_kind,p.sku,lot.code AS lot_code,b.on_hand::text,b.reserved::text,(b.on_hand-b.reserved)::text AS available,lot.expires_on::text,(SELECT max(m.created_at)::text FROM cohamy_crm.inventory_movements m WHERE m.warehouse_id=b.warehouse_id AND m.location_id=b.location_id AND m.product_id=b.product_id AND m.lot_id=b.lot_id) AS last_movement_at,COALESCE(rule.slow_days,0) AS slow_days,COALESCE(rule.near_expiry_days,0) AS near_expiry_days FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.warehouses w ON w.id=b.warehouse_id JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id JOIN cohamy_crm.products p ON p.id=b.product_id JOIN cohamy_crm.inventory_lots lot ON lot.id=b.lot_id LEFT JOIN cohamy_crm.inventory_alert_rules rule ON rule.warehouse_id=b.warehouse_id AND rule.product_id=b.product_id AND rule.active WHERE ($2 OR EXISTS(SELECT 1 FROM cohamy_crm.warehouse_assignments a WHERE a.warehouse_id=b.warehouse_id AND a.membership_id=$1)) AND ($3::text IS NULL OR p.sku=$3) ORDER BY w.code,p.sku,lot.expires_on`,[user.membershipId,global,f.sku??null]),
  db.query<{sku:string;quantity:string}>(`SELECT p.sku,sum(b.received+b.adjusted-b.sold-b.returned)::text AS quantity FROM cohamy_crm.consignment_batches b JOIN cohamy_crm.products p ON p.id=b.product_id GROUP BY p.sku ORDER BY p.sku`),
  db.query<{sku:string;lot_code:string;delivered:string;returned:string;failed_deliveries:string;reasons:string}>(`SELECT p.sku,lot.code AS lot_code,COALESCE(sum(dl.delivered),0)::text AS delivered,COALESCE(sum(rd.quantity),0)::text AS returned,count(DISTINCT d.id) FILTER(WHERE d.status='FAILED')::text AS failed_deliveries,COALESCE(string_agg(DISTINCT NULLIF(rr.reason,''),'; '),'') AS reasons FROM cohamy_crm.deliveries d JOIN cohamy_crm.delivery_lines dl ON dl.delivery_id=d.id JOIN cohamy_crm.inventory_reservations ir ON ir.id=dl.reservation_id JOIN cohamy_crm.products p ON p.id=ir.product_id JOIN cohamy_crm.inventory_lots lot ON lot.id=ir.lot_id JOIN cohamy_crm.sales_orders s ON s.id=d.order_id JOIN cohamy_crm.organizations o ON o.id=s.organization_id LEFT JOIN cohamy_crm.return_request_lines rl ON rl.delivery_line_id=dl.id LEFT JOIN cohamy_crm.return_requests rr ON rr.id=rl.request_id LEFT JOIN cohamy_crm.return_dispositions rd ON rd.request_line_id=rl.id WHERE d.updated_at::date BETWEEN $1 AND $2 AND ($4 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$3)) AND ($5::uuid IS NULL OR o.id=$5) AND ($6::text IS NULL OR p.sku=$6) GROUP BY p.sku,lot.code ORDER BY p.sku,lot.code`,scope)
 ]);
 const returnByLine=new Map(returns.rows.map(r=>[r.delivery_line_id,fixed(r.quantity)])),costByProduct=new Map(costs.rows.map(r=>[r.product_id,{quantity:fixed(r.accepted),amount:BigInt(r.cost_amount)}])),salesMap=new Map<string,{sku:string;product:string;organization:string;region:string;sales:string;quantity:bigint;returned:bigint;net:bigint;cost:bigint|null}>();
 for(const row of delivered.rows){const line=row.snapshot.quote.calculation.lines.find(l=>l.productId===row.product_id&&!l.gift),base=line?fixed(line.baseQuantity):0n,deliveredQuantity=fixed(row.delivered),returnedQuantity=returnByLine.get(row.delivery_line_id)??0n,netQuantity=deliveredQuantity>returnedQuantity?deliveredQuantity-returnedQuantity:0n,net=line&&base>0n?BigInt(line.total)*netQuantity/base:0n,costSource=costByProduct.get(row.product_id),cost=costSource&&costSource.quantity>0n?costSource.amount*netQuantity/costSource.quantity:null,key=[row.sku,row.organization_id,row.region,row.sales_name].join('|'),current=salesMap.get(key)??{sku:row.sku,product:row.product_name,organization:row.organization_name,region:row.region,sales:row.sales_name,quantity:0n,returned:0n,net:0n,cost:cost===null?null:0n};current.quantity+=netQuantity;current.returned+=returnedQuantity;current.net+=net;if(current.cost!==null&&cost!==null)current.cost+=cost;else current.cost=null;salesMap.set(key,current);}
 const sales=[...salesMap.values()].map(r=>({...r,quantity:fixedText(r.quantity),returned:fixedText(r.returned),net:amount(r.net),cost:r.cost===null?null:amount(r.cost),margin:r.cost===null?null:amount(r.net-r.cost)}));
 const elapsed=(a:string|null,b:string|null)=>a&&b?Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/60000)):null;
 return {filters:f,definitions:{conversion:'Tổ chức không gộp tạo trong kỳ; chuyển đổi khi có ít nhất một đơn CONFIRMED.',sales:'Lượng giao thực tế trừ lượng trả đã phân loại trong kỳ; tiền phân bổ theo snapshot dòng đơn. Đây là bán hàng vận hành, không tự ghi nhận doanh thu kế toán.',margin:'Giá vốn bình quân có trọng số từ dòng thực nhận nhà cung cấp. SKU thiếu nguồn giá vốn trả về null, không coi là 0.',activity:`Giảm hoạt động khi đơn CONFIRMED gần nhất cách ngày cuối kỳ hơn ${f.inactivityDays} ngày; NO_ORDERS được tách riêng.`,inventory:'Số dư hiện tại từ sổ kho; tuổi từ movement gần nhất, cận hạn theo quy tắc SKU/kho; tách reserved, cách ly và ký gửi.'},sourceConversion:sources.rows.map(r=>({...r,rate:Number(r.partners)?Math.round(Number(r.converted)*10000/Number(r.partners))/100:null})),stages:stages.rows,dealerActivity:dealers.rows,sales,marginComplete:sales.every(r=>r.cost!==null),speed:speed.rows.map(r=>({...r,approvalMinutes:elapsed(r.created_at,r.confirmed_at),stockMinutes:elapsed(r.confirmed_at,r.delivery_created_at),packingMinutes:elapsed(r.delivery_created_at,r.packed_at),deliveryMinutes:elapsed(r.packed_at,r.delivered_at)})),inventory:inventory.rows.map(r=>({...r,consigned:consignment.rows.find(c=>c.sku===r.sku)?.quantity??'0'})),quality:quality.rows};
}

export async function roleDashboard(user:Principal){if(user.area!=='crm')return [];const db=await database(),items:{label:string;value:string;href:string}[]=[];
 if(can(user,'warehouses.read')){const row=(await db.query<{deliveries:string;alerts:string}>(`SELECT (SELECT count(*)::text FROM cohamy_crm.deliveries d WHERE d.status IN('PLANNED','PICKING','PACKED') AND ($2 OR EXISTS(SELECT 1 FROM cohamy_crm.delivery_lines dl JOIN cohamy_crm.inventory_reservations r ON r.id=dl.reservation_id JOIN cohamy_crm.warehouse_assignments a ON a.warehouse_id=r.warehouse_id WHERE dl.delivery_id=d.id AND a.membership_id=$1))) AS deliveries,(SELECT count(*)::text FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.inventory_alert_rules r ON r.warehouse_id=b.warehouse_id AND r.product_id=b.product_id AND r.active WHERE b.on_hand-b.reserved<=r.low_available AND ($2 OR EXISTS(SELECT 1 FROM cohamy_crm.warehouse_assignments a WHERE a.warehouse_id=b.warehouse_id AND a.membership_id=$1))) AS alerts`,[user.membershipId,['ADMIN','MANAGER'].includes(user.role)])).rows[0];items.push({label:'Phiếu giao đang xử lý',value:row.deliveries,href:'/crm/inventory'},{label:'Cảnh báo tồn khả dụng',value:row.alerts,href:'/crm/inventory'});}
 if(can(user,'finance.read')){const row=(await db.query<{receivables:string;cash:string}>("SELECT (SELECT count(*)::text FROM cohamy_crm.receivables WHERE status IN('OPEN','PARTIAL','DISPUTED')) AS receivables,(SELECT count(*)::text FROM cohamy_crm.cash_requests WHERE status IN('REQUESTED','APPROVED')) AS cash")).rows[0];items.push({label:'Khoản phải thu đang mở',value:row.receivables,href:'/crm/debts'},{label:'Đề nghị thu chi chờ xử lý',value:row.cash,href:'/crm/cash'});}
 if(can(user,'orders.read')){const row=(await db.query<{orders:string}>(`SELECT count(*)::text AS orders FROM cohamy_crm.sales_orders s JOIN cohamy_crm.organizations o ON o.id=s.organization_id WHERE s.status IN('PENDING_APPROVAL','CONFIRMED') AND ($2 OR EXISTS(SELECT 1 FROM cohamy_crm.partner_assignments a WHERE a.organization_id=o.id AND a.membership_id=$1))`,[user.membershipId,allPartnerScope(user)])).rows[0];items.push({label:'Đơn bán đang theo dõi',value:row.orders,href:'/crm/sales'});}
 return items;
}

const subscriptionSchema=z.object({id:z.uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(2).max(100),reportKey:z.enum(['EXECUTIVE','SALES','FULFILLMENT','INVENTORY','FINANCE','QUALITY']),filters:filtersSchema,frequency:z.enum(['DAILY','WEEKLY','MONTHLY']),nextRunAt:z.iso.datetime({offset:true}),channel:z.enum(['IN_APP','EMAIL']),recipient:z.string().trim().max(254),enabled:z.boolean()}).strict();
export async function saveReportSubscription(user:Principal,input:unknown){check(user);const d=subscriptionSchema.parse(input);if(d.channel==='EMAIL'&&!z.email().safeParse(d.recipient).success)throw new CrmError('INVALID_FIELDS',400);if(d.channel==='IN_APP'&&d.recipient!==user.id)throw new CrmError('FORBIDDEN',403);return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const id=d.id??randomUUID(),row=d.version===0?await sql.query('INSERT INTO cohamy_crm.report_subscriptions(id,user_id,name,report_key,filters,frequency,next_run_at,channel,recipient,enabled) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING RETURNING id',[id,user.id,d.name,d.reportKey,JSON.stringify(d.filters),d.frequency,d.nextRunAt,d.channel,d.recipient,d.enabled]):await sql.query('UPDATE cohamy_crm.report_subscriptions SET name=$1,report_key=$2,filters=$3::jsonb,frequency=$4,next_run_at=$5,channel=$6,recipient=$7,enabled=$8,version=version+1,updated_at=now() WHERE id=$9 AND user_id=$10 AND version=$11 RETURNING id',[d.name,d.reportKey,JSON.stringify(d.filters),d.frequency,d.nextRunAt,d.channel,d.recipient,d.enabled,id,user.id,d.version]);if(!row.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(sql,user.id,'report.subscription-saved',id,{after:{name:d.name,reportKey:d.reportKey,frequency:d.frequency,channel:d.channel,enabled:d.enabled}});return {id,version:d.version+1};});}
export async function reportSubscriptions(user:Principal){check(user);return(await(await database()).query('SELECT * FROM cohamy_crm.report_subscriptions WHERE user_id=$1 ORDER BY name,id',[user.id])).rows;}
export async function reportRunAccess(sql:Sql,user:Principal,id:string){const row=(await sql.query<{id:string;user_id:string;status:string;created_at:string}>('SELECT r.id,s.user_id,r.status,r.created_at FROM cohamy_crm.report_runs r JOIN cohamy_crm.report_subscriptions s ON s.id=r.subscription_id WHERE r.id=$1',[id])).rows[0];if(!row||row.user_id!==user.id)throw new CrmError('NOT_FOUND',404);return row;}
function nextRun(from:string,frequency:string,now=new Date()){
 const d=new Date(from);
 const advance=()=>{if(frequency==='DAILY')d.setUTCDate(d.getUTCDate()+1);else if(frequency==='WEEKLY')d.setUTCDate(d.getUTCDate()+7);else d.setUTCMonth(d.getUTCMonth()+1);};
 do advance();while(d<=now);
 return d.toISOString();
}
export async function runDueReportSubscriptions(){const db=await database(),due=(await db.query<{id:string;user_id:string;report_key:string;filters:ReportFilters;frequency:string;next_run_at:string;channel:string;recipient:string}>("SELECT id,user_id,report_key,filters,frequency,next_run_at,channel,recipient FROM cohamy_crm.report_subscriptions WHERE enabled AND next_run_at<=now() ORDER BY next_run_at,id LIMIT 50")).rows;let processed=0;for(const item of due){const membership=(await db.query<{id:string}>('SELECT id FROM cohamy_crm.memberships WHERE user_id=$1 AND active ORDER BY id LIMIT 1',[item.user_id])).rows[0],principal=membership?await membershipPrincipal(membership.id):null,runId=randomUUID();let status='SKIPPED',reason='Quyền báo cáo không còn hiệu lực',snapshot:unknown={reportKey:item.report_key};if(principal&&can(principal,'reports.read')){try{const data=await operationalReports(principal,item.filters);snapshot={reportKey:item.report_key,filters:data.filters,definitions:data.definitions,sourceConversion:data.sourceConversion,sales:data.sales,quality:data.quality};status='SENT';reason='';}catch(error){status='FAILED';reason=error instanceof CrmError?error.code:'REPORT_FAILED';}}
  try{await db.transaction(async sql=>{const inserted=await sql.query('INSERT INTO cohamy_crm.report_runs(id,subscription_id,scheduled_for,actor_membership_id,snapshot,status,reason) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7) ON CONFLICT(subscription_id,scheduled_for) DO NOTHING RETURNING id',[runId,item.id,item.next_run_at,principal?.membershipId??null,JSON.stringify(snapshot),status,reason]);if(!inserted.rows.length)return;await sql.query('UPDATE cohamy_crm.report_subscriptions SET next_run_at=$1,version=version+1,updated_at=now() WHERE id=$2 AND next_run_at=$3',[nextRun(item.next_run_at,item.frequency),item.id,item.next_run_at]);if(status==='SENT'&&item.channel==='IN_APP')await sql.query("INSERT INTO cohamy_crm.notifications(id,user_id,event_key,kind,entity_type,entity_id,message,available_at) VALUES($1,$2,$3,'SYSTEM','report',$4,$5,now()) ON CONFLICT(user_id,event_key) DO NOTHING",[randomUUID(),item.user_id,'report-run:'+runId,runId,'Báo cáo định kỳ đã sẵn sàng.']);if(status==='SENT'&&item.channel==='EMAIL')await sql.query("INSERT INTO cohamy_crm.notification_outbox(id,user_id,event_key,channel,recipient,subject,body,available_at) VALUES($1,$2,$3,'EMAIL',$4,$5,$6,now()) ON CONFLICT(user_id,event_key,channel) DO NOTHING",[randomUUID(),item.user_id,'report-run:'+runId,item.recipient,'Báo cáo định kỳ Cohamy',`Báo cáo ${item.report_key} đã chạy. Đăng nhập Cohamy để xem dữ liệu trong phạm vi quyền hiện tại.`]);processed++;});}catch{/* Another worker may have inserted the unique run. */}}
 return {processed};
}
