import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {assertCurrentPrincipal,audit} from './auth';
import {assertPermission,CrmError} from './permissions';
import {commercialDigest as digest,parseCommercial as parse,vietnamBusinessDate} from './commercial-common';
import {fixed,fixedText} from './decimal';
import {partnerScope} from './repository';
import {salesOrderAccess} from './sales-orders';
import type {Principal} from './types';

const key=z.uuid(),quantity=z.string().regex(/^\d{1,18}(?:\.\d{1,6})?$/).refine(v=>fixed(v)>0n),reason=z.string().trim().min(3).max(2000);
type SampleStatus='REQUESTED'|'SENT'|'RECEIVED'|'FEEDBACK'|'CONVERTED'|'CLOSED';
export interface SampleIssue {id:string;code:string;organization_id:string;warehouse_id:string;recipient_name:string;recipient_phone:string;purpose:string;status:SampleStatus;inventory_document_id:string|null;sales_order_id:string|null;requested_by:string;received_at:string|null;feedback_text:string;feedback_outcome:string|null;version:number;created_at:string;updated_at:string;organization_name:string;warehouse_code:string;warehouse_name:string;inventory_document_code:string|null;sales_order_code:string|null}
export interface SampleLine {id:string;issue_id:string;product_id:string;quantity:string;sku:string;product_name:string;stock_unit:string;allocations:{location_code:string;lot_code:string;quantity:string;movement_id:string}[]}
export interface SampleEvent {id:string;issue_id:string;action:string;payload:unknown;reason:string;created_at:string;actor_name:string}
export interface SampleView extends SampleIssue {lines:SampleLine[];events:SampleEvent[]}

function writer(user:Principal,roles:Principal['role'][]){assertPermission(user,'samples.read');if(user.area!=='crm'||!roles.includes(user.role))throw new CrmError('FORBIDDEN',403);}
function scope(user:Principal,alias='s'){
 if(user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role))return {sql:'true',params:[] as unknown[]};
 if(user.area==='crm'&&user.role==='SALES')return {sql:`EXISTS(SELECT 1 FROM cohamy_crm.organizations so JOIN cohamy_crm.partner_assignments pa ON pa.organization_id=COALESCE(so.merged_into_id,so.id) WHERE so.id=${alias}.organization_id AND pa.membership_id=$1)`,params:[user.membershipId] as unknown[]};
 if(user.area==='crm'&&user.role==='WAREHOUSE')return {sql:`EXISTS(SELECT 1 FROM cohamy_crm.warehouse_assignments wa WHERE wa.warehouse_id=${alias}.warehouse_id AND wa.membership_id=$1)`,params:[user.membershipId] as unknown[]};
 return {sql:'false',params:[] as unknown[]};
}
async function sampleAccess(sql:Sql,user:Principal,id:string,lock=false){
 assertPermission(user,'samples.read');const s=scope(user);
 const row=(await sql.query<SampleIssue>(`SELECT x.*,o.name AS organization_name,w.code AS warehouse_code,w.name AS warehouse_name,d.code AS inventory_document_code,so.code AS sales_order_code FROM cohamy_crm.sample_issues x JOIN cohamy_crm.organizations o ON o.id=x.organization_id JOIN cohamy_crm.warehouses w ON w.id=x.warehouse_id LEFT JOIN cohamy_crm.inventory_documents d ON d.id=x.inventory_document_id LEFT JOIN cohamy_crm.sales_orders so ON so.id=x.sales_order_id WHERE (${s.sql.replaceAll('s.', 'x.')}) AND x.id=$${s.params.length+1}`+(lock?' FOR UPDATE OF x':''),[...s.params,parse(z.uuid(),id)])).rows[0];
 if(!row)throw new CrmError('NOT_FOUND',404);return row;
}
async function prior(sql:Sql,user:Principal,idempotencyKey:string,requestHash:string){const row=(await sql.query<{request_hash:string;result:unknown}>('SELECT request_hash,result FROM cohamy_crm.sample_events WHERE actor_id=$1 AND idempotency_key=$2',[user.id,idempotencyKey])).rows[0];if(row&&row.request_hash!==requestHash)throw new CrmError('IDEMPOTENCY_CONFLICT',409);return row?.result;}
async function event(sql:Sql,user:Principal,issueId:string,action:string,payload:unknown,reasonText:string,idempotencyKey:string,requestHash:string,result:unknown){await sql.query('INSERT INTO cohamy_crm.sample_events(id,issue_id,action,payload,actor_id,reason,idempotency_key,request_hash,result) VALUES($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9::jsonb)',[randomUUID(),issueId,action,JSON.stringify(payload),user.id,reasonText,idempotencyKey,requestHash,JSON.stringify(result)]);}

export async function sampleWarehouseOptions(user:Principal){
 assertPermission(user,'samples.read');const assigned=user.role==='WAREHOUSE';
 return(await(await database()).query<{id:string;code:string;name:string}>(`SELECT w.id,w.code,w.name FROM cohamy_crm.warehouses w JOIN cohamy_crm.organizations o ON o.id=w.organization_id WHERE w.active AND o.active AND o.kind='COHAMY' AND ($1::boolean=false OR EXISTS(SELECT 1 FROM cohamy_crm.warehouse_assignments wa WHERE wa.warehouse_id=w.id AND wa.membership_id=$2)) ORDER BY w.code,w.id`,[assigned,user.membershipId])).rows;
}
export async function listSamples(user:Principal){
 assertPermission(user,'samples.read');const s=scope(user),db=await database();
 const heads=(await db.query<SampleIssue>(`SELECT x.*,o.name AS organization_name,w.code AS warehouse_code,w.name AS warehouse_name,d.code AS inventory_document_code,so.code AS sales_order_code FROM cohamy_crm.sample_issues x JOIN cohamy_crm.organizations o ON o.id=x.organization_id JOIN cohamy_crm.warehouses w ON w.id=x.warehouse_id LEFT JOIN cohamy_crm.inventory_documents d ON d.id=x.inventory_document_id LEFT JOIN cohamy_crm.sales_orders so ON so.id=x.sales_order_id WHERE (${s.sql.replaceAll('s.', 'x.')}) ORDER BY x.updated_at DESC,x.id LIMIT 200`,s.params)).rows;if(!heads.length)return [];
 const ids=heads.map(x=>x.id),lines=(await db.query<Omit<SampleLine,'allocations'>>('SELECT l.id,l.issue_id,l.product_id,l.quantity::text,p.sku,p.name AS product_name,p.stock_unit FROM cohamy_crm.sample_issue_lines l JOIN cohamy_crm.products p ON p.id=l.product_id WHERE l.issue_id=ANY($1::uuid[]) ORDER BY p.sku,l.id',[ids])).rows;
 const allocations=(await db.query<{line_id:string;location_code:string;lot_code:string;quantity:string;movement_id:string}>('SELECT a.line_id,l.code AS location_code,t.code AS lot_code,a.quantity::text,a.movement_id FROM cohamy_crm.sample_allocations a JOIN cohamy_crm.warehouse_locations l ON l.id=a.location_id JOIN cohamy_crm.inventory_lots t ON t.id=a.lot_id WHERE a.line_id=ANY($1::uuid[]) ORDER BY a.created_at,a.id',[lines.map(l=>l.id)])).rows;
 const events=(await db.query<SampleEvent>('SELECT e.id,e.issue_id,e.action,e.payload,e.reason,e.created_at,u.display_name AS actor_name FROM cohamy_crm.sample_events e JOIN cohamy_crm.users u ON u.id=e.actor_id WHERE e.issue_id=ANY($1::uuid[]) ORDER BY e.created_at,e.id',[ids])).rows;
 return heads.map(head=>({...head,lines:lines.filter(line=>line.issue_id===head.id).map(line=>({...line,allocations:allocations.filter(a=>a.line_id===line.id)})),events:events.filter(e=>e.issue_id===head.id)})) as SampleView[];
}

const createSchema=z.object({organizationId:z.uuid(),warehouseId:z.uuid(),recipientName:z.string().trim().min(2).max(120),recipientPhone:z.string().trim().max(40).default(''),purpose:z.string().trim().min(3).max(1000),lines:z.array(z.object({productId:z.uuid(),quantity}).strict()).min(1).max(50).refine(v=>new Set(v.map(x=>x.productId)).size===v.length),reason,idempotencyKey:key}).strict();
export async function createSample(user:Principal,input:unknown){
 writer(user,['ADMIN','MANAGER','SALES']);const d=parse(createSchema,input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const cached=await prior(sql,user,d.idempotencyKey,h);if(cached)return cached;const ps=partnerScope(user),org=(await sql.query<{id:string;kind:string;active:boolean;merged_into_id:string|null}>(`SELECT o.id,o.kind,o.active,o.merged_into_id FROM cohamy_crm.organizations o WHERE (${ps.sql}) AND o.id=$${ps.params.length+1} FOR SHARE OF o`,[...ps.params,d.organizationId])).rows[0];if(!org||!org.active||org.merged_into_id||!['DEALER','CUSTOMER'].includes(org.kind))throw new CrmError('SAMPLE_PARTNER_INVALID',409);
  const warehouse=(await sql.query<{id:string}>("SELECT w.id FROM cohamy_crm.warehouses w JOIN cohamy_crm.organizations o ON o.id=w.organization_id WHERE w.id=$1 AND w.active AND o.active AND o.kind='COHAMY' FOR SHARE OF w",[d.warehouseId])).rows[0];if(!warehouse)throw new CrmError('SAMPLE_WAREHOUSE_INVALID',409);
  const products=(await sql.query<{id:string}>('SELECT id FROM cohamy_crm.products WHERE id=ANY($1::uuid[]) AND active AND stock_unit<>\'\'',[d.lines.map(l=>l.productId)])).rows;if(products.length!==d.lines.length)throw new CrmError('SAMPLE_PRODUCT_INVALID',409);
  const id=randomUUID(),code=`MAU-${vietnamBusinessDate(new Date())}-${id.slice(0,8).toUpperCase()}`;await sql.query('INSERT INTO cohamy_crm.sample_issues(id,code,organization_id,warehouse_id,recipient_name,recipient_phone,purpose,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,code,d.organizationId,d.warehouseId,d.recipientName,d.recipientPhone,d.purpose,user.id]);for(const line of d.lines)await sql.query('INSERT INTO cohamy_crm.sample_issue_lines(id,issue_id,product_id,quantity) VALUES($1,$2,$3,$4)',[randomUUID(),id,line.productId,line.quantity]);const result={id,code,status:'REQUESTED',version:1};await event(sql,user,id,'CREATED',{organizationId:d.organizationId,warehouseId:d.warehouseId,recipientName:d.recipientName,lines:d.lines},d.reason,d.idempotencyKey,h,result);await audit(sql,user.id,'sample.created',id,{after:{...result,organizationId:d.organizationId,warehouseId:d.warehouseId,lines:d.lines},reason:d.reason});return result;
 });
}

const issueSchema=z.object({id:z.uuid(),version:z.number().int().positive(),minimumShelfLifeDays:z.number().int().min(0).max(3650).default(0),reason,idempotencyKey:key}).strict();
type StockRow={warehouse_id:string;location_id:string;product_id:string;lot_id:string;on_hand:string;reserved:string;location_code:string;lot_code:string;expires_on:string|null;sku:string;product_name:string;stock_unit:string};
export async function issueSample(user:Principal,input:unknown){
 writer(user,['ADMIN','MANAGER','WAREHOUSE']);const d=parse(issueSchema,input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const head=await sampleAccess(sql,user,d.id,true),cached=await prior(sql,user,d.idempotencyKey,h);if(cached)return cached;if(head.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(head.status!=='REQUESTED')throw new CrmError('SAMPLE_NOT_REQUESTED',409);
  const lines=(await sql.query<{id:string;product_id:string;quantity:string}>('SELECT id,product_id,quantity::text FROM cohamy_crm.sample_issue_lines WHERE issue_id=$1 ORDER BY product_id,id',[head.id])).rows,prepared:{lineId:string;row:StockRow;quantity:bigint}[]=[];
  for(const line of lines){let remaining=fixed(line.quantity);const stock=(await sql.query<StockRow>(`SELECT b.*,l.code AS location_code,t.code AS lot_code,t.expires_on,p.sku,p.name AS product_name,p.stock_unit FROM cohamy_crm.inventory_balances b JOIN cohamy_crm.warehouse_locations l ON l.id=b.location_id JOIN cohamy_crm.inventory_lots t ON t.id=b.lot_id JOIN cohamy_crm.products p ON p.id=b.product_id WHERE b.warehouse_id=$1 AND b.product_id=$2 AND l.active AND l.kind='PICK' AND t.status='AVAILABLE' AND (t.expires_on IS NULL OR t.expires_on>=CURRENT_DATE+$3::integer) AND b.on_hand>b.reserved ORDER BY t.expires_on NULLS LAST,t.created_at,t.id,l.id FOR UPDATE OF b`,[head.warehouse_id,line.product_id,d.minimumShelfLifeDays])).rows;for(const row of stock){if(remaining<=0n)break;const available=fixed(row.on_hand)-fixed(row.reserved),take=available<remaining?available:remaining;if(take>0n){prepared.push({lineId:line.id,row,quantity:take});remaining-=take;}}if(remaining>0n)throw new CrmError('SAMPLE_STOCK_INSUFFICIENT',409);}
  const documentId=randomUUID(),documentCode=`KHO-ISS-${vietnamBusinessDate(new Date())}-${documentId.slice(0,8).toUpperCase()}`;await sql.query("INSERT INTO cohamy_crm.inventory_documents(id,code,kind,organization_id,reference_type,reference_id,actor_id,reason,idempotency_key,request_hash) VALUES($1,$2,'ISSUE',$3,'sample-issue',$4,$5,$6,$7,$8)",[documentId,documentCode,head.organization_id,head.id,user.id,d.reason,d.idempotencyKey,h]);const allocations=[] as {lineId:string;locationCode:string;lotCode:string;quantity:string;movementId:string}[];
  for(const item of prepared){const next=fixed(item.row.on_hand)-item.quantity,movementId=randomUUID();if(next<fixed(item.row.reserved))throw new CrmError('SAMPLE_STOCK_INSUFFICIENT',409);await sql.query('UPDATE cohamy_crm.inventory_balances SET on_hand=$1,version=version+1,updated_at=now() WHERE warehouse_id=$2 AND location_id=$3 AND product_id=$4 AND lot_id=$5',[fixedText(next),item.row.warehouse_id,item.row.location_id,item.row.product_id,item.row.lot_id]);await sql.query('INSERT INTO cohamy_crm.inventory_movements(id,document_id,warehouse_id,location_id,product_id,lot_id,quantity,balance_after,unit_snapshot,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)',[movementId,documentId,item.row.warehouse_id,item.row.location_id,item.row.product_id,item.row.lot_id,fixedText(-item.quantity),fixedText(next),JSON.stringify({productId:item.row.product_id,sku:item.row.sku,name:item.row.product_name,stockUnit:item.row.stock_unit}),user.id]);await sql.query('INSERT INTO cohamy_crm.sample_allocations(id,line_id,warehouse_id,location_id,product_id,lot_id,quantity,movement_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),item.lineId,item.row.warehouse_id,item.row.location_id,item.row.product_id,item.row.lot_id,fixedText(item.quantity),movementId]);allocations.push({lineId:item.lineId,locationCode:item.row.location_code,lotCode:item.row.lot_code,quantity:fixedText(item.quantity),movementId});}
  const result={id:head.id,code:head.code,status:'SENT',version:head.version+1,inventoryDocumentId:documentId,inventoryDocumentCode:documentCode,allocations};await sql.query("UPDATE cohamy_crm.sample_issues SET status='SENT',inventory_document_id=$1,version=version+1,updated_at=now() WHERE id=$2",[documentId,head.id]);await sql.query('UPDATE cohamy_crm.inventory_documents SET result=$1::jsonb WHERE id=$2',[JSON.stringify(result),documentId]);await event(sql,user,head.id,'ISSUED',{minimumShelfLifeDays:d.minimumShelfLifeDays,allocations},d.reason,d.idempotencyKey,h,result);await audit(sql,user.id,'sample.issued',head.id,{before:{status:head.status,version:head.version},after:result,reason:d.reason});return result;
 });
}

const actionSchema=z.object({id:z.uuid(),version:z.number().int().positive(),action:z.enum(['RECEIVE','FEEDBACK','CONVERT','CLOSE']),feedback:z.string().trim().max(4000).default(''),outcome:z.enum(['INTERESTED','NOT_INTERESTED','FOLLOW_UP']).nullable().default(null),salesOrderId:z.uuid().nullable().default(null),reason,idempotencyKey:key}).strict();
export async function actSample(user:Principal,input:unknown){
 writer(user,['ADMIN','MANAGER','SALES']);const d=parse(actionSchema,input),h=digest(d);
 return(await database()).transaction(async sql=>{await assertCurrentPrincipal(sql,user);const head=await sampleAccess(sql,user,d.id,true),cached=await prior(sql,user,d.idempotencyKey,h);if(cached)return cached;if(head.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);let status:SampleStatus=head.status,salesOrderId:string|null=head.sales_order_id,receivedAt=head.received_at,feedback=head.feedback_text,outcome=head.feedback_outcome;
  if(d.action==='RECEIVE'){if(head.status!=='SENT')throw new CrmError('SAMPLE_NOT_SENT',409);status='RECEIVED';receivedAt=new Date().toISOString();}
  if(d.action==='FEEDBACK'){if(!['RECEIVED','FEEDBACK'].includes(head.status)||d.feedback.length<2||!d.outcome)throw new CrmError('SAMPLE_FEEDBACK_INVALID',409);status='FEEDBACK';feedback=d.feedback;outcome=d.outcome;}
  if(d.action==='CONVERT'){if(!['RECEIVED','FEEDBACK'].includes(head.status)||!d.salesOrderId)throw new CrmError('SAMPLE_CONVERSION_INVALID',409);const order=await salesOrderAccess(sql,user,d.salesOrderId);if(order.organization_id!==head.organization_id)throw new CrmError('SAMPLE_ORDER_MISMATCH',409);status='CONVERTED';salesOrderId=order.id;}
  if(d.action==='CLOSE'){if(['CONVERTED','CLOSED'].includes(head.status))throw new CrmError('SAMPLE_ALREADY_FINAL',409);status='CLOSED';}
  const result={id:head.id,code:head.code,status,version:head.version+1,salesOrderId};await sql.query('UPDATE cohamy_crm.sample_issues SET status=$1,sales_order_id=$2,received_at=$3,feedback_text=$4,feedback_outcome=$5,version=version+1,updated_at=now() WHERE id=$6',[status,salesOrderId,receivedAt,feedback,outcome,head.id]);await event(sql,user,head.id,d.action,{feedback:d.feedback,outcome:d.outcome,salesOrderId:d.salesOrderId},d.reason,d.idempotencyKey,h,result);await audit(sql,user.id,'sample.'+d.action.toLowerCase(),head.id,{before:{status:head.status,version:head.version},after:result,reason:d.reason});return result;
 });
}
