import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,type Sql} from './db';
import {audit,digest} from './auth';
import {can,CrmError,assertPermission} from './permissions';
import {getOrganization,listOrganizations,listCatalog} from './repository';
import {getOrder,listOrders,listTasks,getCatalogItem} from './work';
import type {Principal} from './types';

export const parse=<T>(schema:z.ZodType<T>,input:unknown):T=>{const result=schema.safeParse(input);if(!result.success)throw new CrmError('INVALID_FIELDS',400);return result.data;};
export async function entityAccess(user:Principal,type:string,id:string,sql?:Sql){
  if(type==='commercial-request')return (await import('./order-requests')).commercialRequestAccess(sql??await database(),user,id);
  if(type==='sales-order')return (await import('./sales-orders')).salesOrderAccess(sql??await database(),user,id);
  if(type==='visit')return (await import('./relationships')).getVisit(user,id,sql);
  if(type==='library')return (await import('./partner-library')).getLibraryItem(user,id,sql);
  if(type==='ticket')return (await import('./portal-services')).getTicket(user,id,sql);
  if(type==='partner')return getOrganization(user,id,sql);
  if(type==='order')return getOrder(user,id,sql);
  if(type==='product')return getCatalogItem(user,id);
  if(type==='account'&&id===user.id)return {id,name:user.displayName};
  throw new CrmError('NOT_FOUND',404);
}
const columns=z.enum(['name','code','phone','email','active','created_at']);
const prefsSchema=z.object({columns:z.array(columns).min(1).max(6).refine(v=>new Set(v).size===v.length).default(['name','code','phone','email','active']),columnWidths:z.partialRecord(columns,z.number().int().min(80).max(600)).default({}),quietStart:z.number().int().min(0).max(23).nullable().default(null),quietEnd:z.number().int().min(0).max(23).nullable().default(null),taskNotifications:z.boolean().default(true),notificationKinds:z.array(z.enum(['TASK','ONBOARDING','SUPPORT','SYSTEM'])).max(4).default(['TASK','ONBOARDING','SUPPORT','SYSTEM']),notificationChannels:z.array(z.literal('IN_APP')).max(1).default(['IN_APP']),version:z.number().int().min(0)}).strict().refine(v=>(v.quietStart===null&&v.quietEnd===null)||(v.quietStart!==null&&v.quietEnd!==null&&v.quietStart!==v.quietEnd));
export async function preferences(user:Principal){const r=(await(await database()).query<{value:Record<string,unknown>;version:number}>('SELECT value,version FROM cohamy_crm.workspace_preferences WHERE user_id=$1',[user.id])).rows[0];return parse(prefsSchema,{...(r?.value??{}),version:r?.version??0});}
export async function savePreferences(user:Principal,input:unknown){const {version,...value}=parse(prefsSchema,input);return(await database()).transaction(async tx=>{const result=version===0?await tx.query('INSERT INTO cohamy_crm.workspace_preferences(user_id,value) VALUES ($1,$2::jsonb) ON CONFLICT DO NOTHING RETURNING user_id',[user.id,JSON.stringify(value)]):await tx.query('UPDATE cohamy_crm.workspace_preferences SET value=$1::jsonb,version=version+1,updated_at=now() WHERE user_id=$2 AND version=$3 RETURNING user_id',[JSON.stringify(value),user.id,version]);if(!result.rows.length)throw new CrmError('VERSION_CONFLICT',409);return {version:version+1};});}
const draftSchema=z.object({key:z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/),entityType:z.enum(['partner','order','new-partner']),entityId:z.uuid().nullable(),version:z.number().int().min(0),value:z.object({name:z.string().max(200).optional(),phone:z.string().max(40).optional(),email:z.string().max(200).optional(),address:z.string().max(500).optional(),body:z.string().max(4000).optional(),title:z.string().max(240).optional()}).strict()}).strict();
export async function saveDraft(user:Principal,input:unknown){const d=parse(draftSchema,input);assertPermission(user,'partners.write');if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);if(d.entityType!=='new-partner'){if(!d.entityId)throw new CrmError('INVALID_FIELDS',400);await entityAccess(user,d.entityType,d.entityId);}else if(d.entityId)throw new CrmError('INVALID_FIELDS',400);
 const db=await database();const r=d.version===0?await db.query('INSERT INTO cohamy_crm.workspace_drafts(user_id,draft_key,entity_type,entity_id,value) VALUES ($1,$2,$3,$4,$5::jsonb) ON CONFLICT DO NOTHING RETURNING version',[user.id,d.key,d.entityType,d.entityId,JSON.stringify(d.value)]):await db.query('UPDATE cohamy_crm.workspace_drafts SET value=$1::jsonb,version=version+1,updated_at=now() WHERE user_id=$2 AND draft_key=$3 AND version=$4 AND entity_type=$5 AND entity_id IS NOT DISTINCT FROM $6::uuid RETURNING version',[JSON.stringify(d.value),user.id,d.key,d.version,d.entityType,d.entityId]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);return r.rows[0];}
export async function getDraft(user:Principal,key:string){assertPermission(user,'partners.write');const r=(await(await database()).query<{entity_type:string;entity_id:string|null;value:Record<string,string>;version:number}>('SELECT entity_type,entity_id,value,version FROM cohamy_crm.workspace_drafts WHERE user_id=$1 AND draft_key=$2',[user.id,key])).rows[0];if(r?.entity_id)await entityAccess(user,r.entity_type,r.entity_id);return r??null;}
const filterSchema=z.object({id:z.uuid().optional(),name:z.string().trim().min(2).max(80),resource:z.enum(['partners','orders','tasks']),value:z.object({tags:z.string().max(1200).refine(v=>!v||v.split(',').every(id=>z.uuid().safeParse(id).success)).optional(),q:z.string().max(120).optional(),status:z.enum(['PENDING_REVIEW','IN_PROGRESS','READY','REJECTED','CANCELLED']).optional(),kind:z.enum(['CUSTOMER','DEALER']).optional(),done:z.enum(['true','false','all']).optional(),overdue:z.literal('true').optional()}).strict(),shared:z.boolean().default(false),isDefault:z.boolean().default(false),version:z.number().int().min(0).default(0)}).strict();
function filterAccess(user:Principal,resource:string){assertPermission(user,resource==='partners'?'partners.read':resource==='orders'?'orders.read':'partners.write');if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}
export async function saveFilter(user:Principal,input:unknown){const d=parse(filterSchema,input);filterAccess(user,d.resource);if(d.shared&&!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);return(await database()).transaction(async tx=>{await tx.query('SELECT id FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id]);if(d.isDefault)await tx.query('UPDATE cohamy_crm.saved_filters SET is_default=false,version=version+1 WHERE user_id=$1 AND resource=$2 AND is_default AND id<>$3',[user.id,d.resource,d.id??randomUUID()]);const id=d.id??randomUUID();const r=d.version===0?await tx.query('INSERT INTO cohamy_crm.saved_filters(id,user_id,name,resource,value,shared,is_default) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7) RETURNING id',[id,user.id,d.name,d.resource,JSON.stringify(d.value),d.shared,d.isDefault]):await tx.query('UPDATE cohamy_crm.saved_filters SET name=$1,value=$2::jsonb,shared=$3,is_default=$4,version=version+1 WHERE id=$5 AND user_id=$6 AND version=$7 AND resource=$8 RETURNING id',[d.name,JSON.stringify(d.value),d.shared,d.isDefault,id,user.id,d.version,d.resource]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);return {id};});}
export async function listFilters(user:Principal,resource:string){filterAccess(user,resource);return(await(await database()).query<{id:string;user_id:string;name:string;value:Record<string,string>;version:number;shared:boolean;is_default:boolean}>('SELECT id,user_id,name,value,version,shared,is_default FROM cohamy_crm.saved_filters WHERE resource=$1 AND (user_id=$2 OR shared) ORDER BY is_default DESC,name LIMIT 100',[resource,user.id])).rows;}
export async function bookmark(user:Principal,input:unknown){const d=parse(z.object({entityType:z.enum(['partner','order','product']),entityId:z.uuid(),pinned:z.boolean().optional()}).strict(),input);await entityAccess(user,d.entityType,d.entityId);await(await database()).query('INSERT INTO cohamy_crm.workspace_bookmarks(user_id,entity_type,entity_id,pinned) VALUES ($1,$2,$3,COALESCE($4::boolean,false)) ON CONFLICT(user_id,entity_type,entity_id) DO UPDATE SET pinned=COALESCE($4::boolean,cohamy_crm.workspace_bookmarks.pinned),opened_at=now()',[user.id,d.entityType,d.entityId,d.pinned??null]);return {saved:true};}
export async function bookmarks(user:Principal){const rows=(await(await database()).query<{entity_type:string;entity_id:string;pinned:boolean;opened_at:string}>('SELECT entity_type,entity_id,pinned,opened_at FROM cohamy_crm.workspace_bookmarks WHERE user_id=$1 ORDER BY pinned DESC,opened_at DESC LIMIT 50',[user.id])).rows;const result=[];for(const row of rows){try{const entity=await entityAccess(user,row.entity_type,row.entity_id);result.push({...row,label:'name' in entity?entity.name:'code' in entity?entity.code:row.entity_id});}catch(e){if(!(e instanceof CrmError)||![403,404].includes(e.status))throw e;}}return result;}
export async function search(user:Principal,q:string,page=1){const term=q.trim().slice(0,120);if(!term)return {partners:[],products:[],orders:[],tasks:[],page};const [p,c,o,t]=await Promise.all([can(user,'partners.read')?listOrganizations(user,{q:term,page}):null,can(user,'catalog.read')?listCatalog(user,term):[],user.area==='crm'&&can(user,'orders.read')?listOrders(user,{q:term,page:String(page)}):null,user.area==='crm'&&can(user,'partners.write')?listTasks(user,{done:'all',q:term,page:String(page),pageSize:'20'}):[]]);return {partners:p?.items??[],products:c.slice((page-1)*20,page*20),orders:o?.items??[],tasks:t,page};}
export function notificationAvailableAt(pref:{quietStart:number|null;quietEnd:number|null},now=new Date()){
 if(pref.quietStart===null||pref.quietEnd===null)return now;
 const local=new Date(now.getTime()+7*3600000),hour=local.getUTCHours(),{quietStart:start,quietEnd:end}=pref;
 const quiet=start<end?hour>=start&&hour<end:hour>=start||hour<end;if(!quiet)return now;
 const nextDay=start>end&&hour>=start?1:0;
 return new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate()+nextDay,end)-7*3600000);
}
export async function enqueueNotification(tx:Sql,userId:string,eventKey:string,kind:string,type:string,id:string,message:string){
 const row=(await tx.query<{value:Record<string,unknown>;version:number}>('SELECT value,version FROM cohamy_crm.workspace_preferences WHERE user_id=$1',[userId])).rows[0];
 const pref=parse(prefsSchema,{...(row?.value??{}),version:row?.version??0}),mandatory=kind==='SECURITY';
 const group=kind==='TASK'?'TASK':kind==='ONBOARDING'?'ONBOARDING':kind==='SUPPORT'?'SUPPORT':'SYSTEM';
 if(!mandatory&&(!pref.notificationKinds.includes(group)||!pref.notificationChannels.includes('IN_APP')||kind==='TASK'&&!pref.taskNotifications))return;
 const available=mandatory?new Date():notificationAvailableAt(pref);
 await tx.query('INSERT INTO cohamy_crm.notifications(id,user_id,event_key,kind,entity_type,entity_id,message,available_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id,event_key) DO NOTHING',[randomUUID(),userId,eventKey,kind,type,id,message,available]);
}
export async function notifications(user:Principal,state='ALL'){const rows=(await(await database()).query<{id:string;entity_type:string;entity_id:string;message:string;read_at:string|null;created_at:string}>("SELECT id,entity_type,entity_id,message,read_at,created_at FROM cohamy_crm.notifications WHERE user_id=$1 AND available_at<=now() AND ($2='ALL' OR ($2='UNREAD' AND read_at IS NULL) OR ($2='READ' AND read_at IS NOT NULL)) ORDER BY created_at DESC,id LIMIT 100",[user.id,parse(z.enum(['ALL','UNREAD','READ']),state)])).rows;const result=[];for(const row of rows){try{await entityAccess(user,row.entity_type,row.entity_id);result.push(row);}catch(e){if(!(e instanceof CrmError)||![403,404].includes(e.status))throw e;}}return result;}
export async function readNotification(user:Principal,id:string){const row=(await notifications(user)).find(x=>x.id===id);if(!row)throw new CrmError('NOT_FOUND',404);await(await database()).query('UPDATE cohamy_crm.notifications SET read_at=now() WHERE id=$1 AND user_id=$2',[id,user.id]);return {read:true};}
export async function sessions(user:Principal,currentToken?:string){return(await(await database()).query<{id:string;created_at:string;expires_at:string;device_label:string;current:boolean}>('SELECT left(token_hash,16) AS id,created_at,expires_at,device_label,(token_hash=$2) AS current FROM cohamy_crm.sessions WHERE membership_id IN (SELECT id FROM cohamy_crm.memberships WHERE user_id=$1) AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC',[user.id,currentToken?digest(currentToken):null])).rows;}
export async function revokeSession(user:Principal,id:string){if(!/^[a-f0-9]{16}$/u.test(id))throw new CrmError('INVALID_FIELDS',400);await(await database()).transaction(async tx=>{await tx.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE left(token_hash,16)=$1 AND membership_id IN(SELECT id FROM cohamy_crm.memberships WHERE user_id=$2)',[id,user.id]);await audit(tx,user.id,'session.revoked',user.id);});return {revoked:true};}
export async function auditSearch(user:Principal,q:Record<string,string>){
 assertPermission(user,'accounts.manage');const page=Math.max(1,Math.min(10000,Number(q.page)||1)),term=(q.q??'').slice(0,120);
 const from=q.from?parse(z.iso.date(),q.from):null,to=q.to?parse(z.iso.date(),q.to):null,actor=q.actor?parse(z.uuid(),q.actor):null;
 if(from&&to&&from>to)throw new CrmError('INVALID_FIELDS',400);
 const rows=(await(await database()).query<{id:string;action:string;entity_id:string;created_at:string;actor_name:string|null;payload:unknown}>("SELECT a.id,a.action,a.entity_id,a.created_at,u.display_name AS actor_name,a.payload FROM cohamy_crm.audit_events a LEFT JOIN cohamy_crm.users u ON u.id=a.actor_id WHERE ($1='' OR a.action ILIKE $2 OR a.entity_id=$1 OR u.display_name ILIKE $2) AND ($4::date IS NULL OR a.created_at>=($4::date::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh')) AND ($5::date IS NULL OR a.created_at<(($5::date+1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh')) AND ($6::uuid IS NULL OR a.actor_id=$6) ORDER BY a.created_at DESC,a.id LIMIT 50 OFFSET $3",[term,'%'+term+'%',(page-1)*50,from,to,actor])).rows;
 const {redactAudit}=await import('./auth');return rows.map(row=>({...row,payload:redactAudit(row.payload)}));
}
export interface DocumentRecord{id:string;title:string;entity_type:string;entity_id:string;version_id:string;number:number;filename:string;mime:string;size:number;checksum:string;effective_at:string|null;expires_at:string|null;read_at:string|null}
export async function documents(user:Principal,type:string,id:string,q=''){await entityAccess(user,type,id);return(await(await database()).query<DocumentRecord&{current:boolean;latest:boolean}>(`SELECT d.id,d.title,d.entity_type,d.entity_id,v.id AS version_id,v.number,v.filename,v.mime,v.size,v.checksum,v.effective_at,v.expires_at,r.read_at,
 v.number=(SELECT max(x.number) FROM cohamy_crm.document_versions x WHERE x.document_id=d.id) AS latest,
 v.number=(SELECT max(x.number) FROM cohamy_crm.document_versions x WHERE x.document_id=d.id AND (x.effective_at IS NULL OR x.effective_at<=now()) AND (x.expires_at IS NULL OR x.expires_at>now())) AS current
 FROM cohamy_crm.private_documents d JOIN cohamy_crm.document_versions v ON v.document_id=d.id LEFT JOIN cohamy_crm.document_reads r ON r.version_id=v.id AND r.user_id=$4 WHERE d.entity_type=$1 AND d.entity_id=$2 AND (d.title ILIKE $3 OR v.filename ILIKE $3 OR v.mime ILIKE $3 OR v.checksum=$5) ORDER BY d.created_at DESC,v.number DESC LIMIT 100`,[type,id,'%'+q.slice(0,120)+'%',user.id,q.slice(0,120)])).rows;}
export async function uploadDocument(user:Principal,input:{entityType:string;entityId:string;title:string;filename:string;mime:string;content:Buffer;documentId?:string;effectiveAt?:string;expiresAt?:string}){if(input.entityType!=='ticket'||user.area==='crm'){assertPermission(user,'partners.write');if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}const d=parse(z.object({entityType:z.enum(['partner','order','ticket','library','visit']),entityId:z.uuid(),title:z.string().trim().min(2).max(200),filename:z.string().regex(/^[^/\\\r\n\x00]{1,180}$/),mime:z.enum(['application/pdf','image/png','image/jpeg']),content:z.instanceof(Buffer),documentId:z.uuid().optional(),effectiveAt:z.iso.datetime({offset:true}).optional(),expiresAt:z.iso.datetime({offset:true}).optional()}).strict(),input);if(d.content.length<1||d.content.length>8388608)throw new CrmError('FILE_SIZE_INVALID',413);const valid=d.mime==='application/pdf'?d.content.subarray(0,5).toString()==='%PDF-':d.mime==='image/png'?d.content.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):d.content[0]===255&&d.content[1]===216&&d.content[2]===255;if(!valid)throw new CrmError('FILE_TYPE_INVALID',400);if(d.expiresAt&&d.effectiveAt&&d.expiresAt<=d.effectiveAt)throw new CrmError('INVALID_FIELDS',400);
 return(await database()).transaction(async tx=>{await entityAccess(user,d.entityType,d.entityId,tx);const id=d.documentId??randomUUID();if(d.documentId){const doc=(await tx.query<{entity_type:string;entity_id:string}>('SELECT entity_type,entity_id FROM cohamy_crm.private_documents WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!doc||doc.entity_type!==d.entityType||doc.entity_id!==d.entityId)throw new CrmError('NOT_FOUND',404);}else await tx.query('INSERT INTO cohamy_crm.private_documents(id,entity_type,entity_id,title,created_by) VALUES ($1,$2,$3,$4,$5)',[id,d.entityType,d.entityId,d.title,user.id]);const number=Number((await tx.query<{number:number}>('SELECT COALESCE(max(number),0)+1 AS number FROM cohamy_crm.document_versions WHERE document_id=$1',[id])).rows[0].number);const versionId=randomUUID();await tx.query('INSERT INTO cohamy_crm.document_versions(id,document_id,number,filename,mime,size,checksum,content,effective_at,expires_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[versionId,id,number,d.filename,d.mime,d.content.length,digest(d.content.toString('base64')),d.content,d.effectiveAt??null,d.expiresAt??null,user.id]);await audit(tx,user.id,'document.uploaded',d.entityId,{documentId:id,version:number});return {id,versionId,number};});}
export async function downloadDocument(user:Principal,versionId:string){if(!z.uuid().safeParse(versionId).success)throw new CrmError('NOT_FOUND',404);const r=(await(await database()).query<{entity_type:string;entity_id:string;filename:string;mime:string;content:Uint8Array}>('SELECT d.entity_type,d.entity_id,v.filename,v.mime,v.content FROM cohamy_crm.document_versions v JOIN cohamy_crm.private_documents d ON d.id=v.document_id WHERE v.id=$1',[versionId])).rows[0];if(!r)throw new CrmError('NOT_FOUND',404);await entityAccess(user,r.entity_type,r.entity_id);return r;}
export async function acknowledgeDocument(user:Principal,id:string){await downloadDocument(user,id);await(await database()).query('INSERT INTO cohamy_crm.document_reads(version_id,user_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',[id,user.id]);return {acknowledged:true};}
