import 'server-only';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import bcrypt from 'bcryptjs';
import {database,type Sql} from './db';
import {audit,assertCurrentPrincipal} from './auth';
import {allPartners,assertPermission,CrmError} from './permissions';
import {getOrganization,partnerScope,assertWritableOrganization} from './repository';
import {roles,type Principal,type CatalogProduct} from './types';
import {orderStates,type OrderRecord,type EntityType,type StaffOption,type TaskRecord,type ActivityRecord} from './work-types';

function parse<T>(schema:z.ZodType<T>,input:unknown):T {const r=schema.safeParse(input);if(!r.success)throw new CrmError('INVALID_FIELDS',400);return r.data;}
function internal(user:Principal){if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);}
function manager(user:Principal){internal(user);if(!['ADMIN','MANAGER'].includes(user.role))throw new CrmError('FORBIDDEN',403);}
function editor(user:Principal){internal(user);if(!['ADMIN','MANAGER','SALES'].includes(user.role))throw new CrmError('FORBIDDEN',403);}
export function canManageWork(user:Principal){return user.area==='crm'&&['ADMIN','MANAGER','SALES'].includes(user.role);}
function orderScope(user:Principal){return allPartners(user)?{sql:'true',params:[] as unknown[]}:user.area==='crm'&&user.role==='SALES'?{sql:'o.assigned_to=$1',params:[user.membershipId] as unknown[]}:{sql:'false',params:[] as unknown[]};}
const orderSelect=`SELECT o.*,o.subtotal::text,u.display_name AS assignee_name,p.name AS organization_name FROM cohamy_crm.website_orders o LEFT JOIN cohamy_crm.memberships m ON m.id=o.assigned_to LEFT JOIN cohamy_crm.users u ON u.id=m.user_id LEFT JOIN cohamy_crm.organizations p ON p.id=o.organization_id`;
export async function getOrder(user:Principal,id:string,sql?:Sql){assertPermission(user,'orders.read');if(!z.uuid().safeParse(id).success)throw new CrmError('NOT_FOUND',404);const scope=orderScope(user);const row=(await (sql??await database()).query<OrderRecord>(`${orderSelect} WHERE (${scope.sql}) AND o.id=$${scope.params.length+1}`,[...scope.params,id])).rows[0];if(!row)throw new CrmError('NOT_FOUND',404);return row;}
export async function listOrders(user:Principal,query:Record<string,string>={}) {
 assertPermission(user,'orders.read');const scope=orderScope(user);const params=[...scope.params];const conditions=[scope.sql];
 const add=(value:unknown,condition:(p:string)=>string)=>{params.push(value);conditions.push(condition('$'+params.length));};
 if(query.q)add('%'+query.q.slice(0,120)+'%',p=>`(o.code ILIKE ${p} OR o.contact->>'fullName' ILIKE ${p} OR o.contact->>'phone' ILIKE ${p} OR o.contact->>'email' ILIKE ${p})`);
 if(query.status&&orderStates.includes(query.status as typeof orderStates[number]))add(query.status,p=>`o.status=${p}`);
 if(query.mine==='true')add(user.membershipId,p=>`o.assigned_to=${p}`);
 if(query.unassigned==='true')conditions.push('o.assigned_to IS NULL');
 for(const key of ['from','to'] as const)if(query[key]){const day=z.iso.date().safeParse(query[key]);if(!day.success)throw new CrmError('INVALID_FIELDS',400);add(day.data,p=>key==='from'?`o.created_at>=(${p}::date::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh')`:`o.created_at<((${p}::date+1)::timestamp AT TIME ZONE 'Asia/Ho_Chi_Minh')`);}
 const where=conditions.map(v=>'('+v+')').join(' AND '),db=await database();const total=Number((await db.query<{total:string}>(`SELECT count(*)::text AS total FROM cohamy_crm.website_orders o WHERE ${where}`,params)).rows[0].total);
 const page=Math.min(Math.max(1,Math.floor(Number(query.page)||1)),Math.max(1,Math.ceil(total/20)));params.push((page-1)*20);
 return {items:(await db.query<OrderRecord>(`${orderSelect} WHERE ${where} ORDER BY o.created_at DESC,o.id LIMIT 20 OFFSET $${params.length}`,params)).rows,total,page,pageSize:20};
}
export async function staffOptions(user:Principal,sql?:Sql):Promise<StaffOption[]> {
 internal(user);if(!['ADMIN','MANAGER'].includes(user.role))return [{id:user.membershipId,userId:user.id,name:user.displayName,role:user.role,organization_id:user.organizationId}];
 return (await(sql??await database()).query<StaffOption>(`SELECT m.id,u.id AS "userId",u.display_name AS name,m.role,m.organization_id FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.active AND u.active AND o.active AND o.kind='COHAMY' ORDER BY u.display_name`)).rows;
}
async function assertAssignee(sql:Sql,id:string,allowed:string[]){const row=(await sql.query<{role:string}>(`SELECT m.role FROM cohamy_crm.memberships m JOIN cohamy_crm.users u ON u.id=m.user_id JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.id=$1 AND m.active AND u.active AND o.active AND o.kind='COHAMY'`,[id])).rows[0];if(!row||!allowed.includes(row.role))throw new CrmError('INVALID_ASSIGNEE',400);}
export async function updateOrder(user:Principal,id:string,input:unknown){editor(user);const data=parse(z.object({version:z.number().int().positive(),status:z.enum(orderStates),reason:z.string().trim().max(1000).default(''),assignedTo:z.uuid().nullable().optional(),organizationId:z.uuid().nullable().optional()}).strict(),input);
 return (await database()).transaction(async tx=>{await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);await tx.query('SELECT id FROM cohamy_crm.website_orders WHERE id=$1 FOR UPDATE',[id]);const old=await getOrder(user,id,tx);if(old.version!==data.version)throw new CrmError('VERSION_CONFLICT',409);
 const transitions:Record<string,readonly string[]>={PENDING_REVIEW:['IN_PROGRESS','REJECTED','CANCELLED'],IN_PROGRESS:['PENDING_REVIEW','READY','REJECTED','CANCELLED'],READY:['IN_PROGRESS','CANCELLED'],REJECTED:['PENDING_REVIEW'],CANCELLED:['PENDING_REVIEW']};
 if(old.status!==data.status&&!transitions[old.status].includes(data.status))throw new CrmError('INVALID_TRANSITION',409);
 if(old.status!==data.status&&(['REJECTED','CANCELLED'].includes(data.status)||['REJECTED','CANCELLED'].includes(old.status))&&!data.reason)throw new CrmError('REASON_REQUIRED',400);
 if(['REJECTED','CANCELLED'].includes(old.status)&&data.status!==old.status)manager(user);
 let assigned=old.assigned_to,org=old.organization_id;
 if(data.assignedTo!==undefined&&data.assignedTo!==assigned){manager(user);if(data.assignedTo)await assertAssignee(tx,data.assignedTo,['ADMIN','MANAGER','SALES']);assigned=data.assignedTo;}
 if(data.organizationId!==undefined&&data.organizationId!==org){manager(user);if(data.organizationId){const p=await getOrganization(user,data.organizationId,tx);if(!p.active||!['CUSTOMER','DEALER'].includes(p.kind))throw new CrmError('INVALID_FIELDS',400);}org=data.organizationId;}
 await tx.query('UPDATE cohamy_crm.website_orders SET status=$1,assigned_to=$2,organization_id=$3,resolution_note=$4,version=version+1,updated_at=now() WHERE id=$5',[data.status,assigned,org,data.reason,id]);
 await audit(tx,user.id,'order.updated',id,{from:old.status,to:data.status,assignedTo:assigned,version:old.version+1});
 if(data.reason)await tx.query('INSERT INTO cohamy_crm.activities(id,entity_type,entity_id,actor_id,body) VALUES ($1,\'order\',$2,$3,$4)',[randomUUID(),id,user.id,data.reason]);return {id,version:old.version+1};});
}
async function entityAccess(user:Principal,type:EntityType,id:string,tx?:Sql){internal(user);if(type==='partner')await getOrganization(user,id,tx);else await getOrder(user,id,tx);}
export async function listActivities(user:Principal,type:EntityType,id:string){await entityAccess(user,type,id);const db=await database(),family=type==='partner'?await (await import('./partner-merge')).partnerFamily(db,id):[id];return (await db.query<ActivityRecord>('SELECT a.id,a.body,a.created_at,u.display_name AS actor_name FROM cohamy_crm.activities a JOIN cohamy_crm.users u ON u.id=a.actor_id WHERE entity_type=$1 AND entity_id=ANY($2::uuid[]) ORDER BY created_at DESC,id DESC LIMIT 100',[type,family])).rows;}
export async function addActivity(user:Principal,input:unknown){editor(user);const d=parse(z.object({entityType:z.enum(['partner','order']),entityId:z.uuid(),body:z.string().trim().min(1).max(4000),mentionedMembershipIds:z.array(z.uuid()).max(20).refine(ids=>new Set(ids).size===ids.length).default([])}).strict(),input);return(await database()).transaction(async tx=>{await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);await entityAccess(user,d.entityType,d.entityId,tx);if(d.entityType==='partner')await assertWritableOrganization(tx,user,d.entityId);const id=randomUUID();await tx.query('INSERT INTO cohamy_crm.activities(id,entity_type,entity_id,actor_id,body) VALUES ($1,$2,$3,$4,$5)',[id,d.entityType,d.entityId,user.id,d.body]);const {recordMentions}=await import('./care-automation');await recordMentions(tx,user,id,d.entityType,d.entityId,d.mentionedMembershipIds);await audit(tx,user.id,'activity.created',d.entityId,{activityId:id,mentionedMembershipIds:d.mentionedMembershipIds});return {id};});}
function taskScope(user:Principal){const os=orderScope(user),ps=partnerScope(user); // Both restricted scopes use this user's membership as $1.
 const unrestricted=allPartners(user);return {sql:unrestricted?'true':`t.assignee_id=$1 AND ((t.entity_type='partner' AND EXISTS(SELECT 1 FROM cohamy_crm.organizations o WHERE o.id=t.entity_id AND (${ps.sql}))) OR (t.entity_type='order' AND EXISTS(SELECT 1 FROM cohamy_crm.website_orders o WHERE o.id=t.entity_id AND (${os.sql}))))`,params:unrestricted?[]:[user.membershipId]};}
export async function listTasks(user:Principal,query:Record<string,string>={}){internal(user);const s=taskScope(user);const params:unknown[]=[...s.params];let where=`(${s.sql})`;
 if(query.done!=='all')where+=query.done==='true'?' AND t.done_at IS NOT NULL':' AND t.done_at IS NULL';
 if(query.overdue==='true')where+=' AND t.due_at<now() AND t.done_at IS NULL';
 if(query.today==='true')where+=" AND t.done_at IS NULL AND t.due_at>=now() AND t.due_at<((date_trunc('day',now() AT TIME ZONE 'Asia/Ho_Chi_Minh')+interval '1 day') AT TIME ZONE 'Asia/Ho_Chi_Minh')";
 if(query.entityId){if(!z.uuid().safeParse(query.entityId).success)throw new CrmError('INVALID_FIELDS',400);params.push(query.entityId);where+=` AND t.entity_id=$${params.length}`;}
 if(query.q){params.push('%'+query.q.trim().slice(0,120)+'%');where+=` AND (t.title ILIKE $${params.length} OR p.name ILIKE $${params.length} OR o.code ILIKE $${params.length})`;}
 const size=Math.max(1,Math.min(200,Math.floor(Number(query.pageSize)||200))),page=Math.max(1,Math.min(100000,Math.floor(Number(query.page)||1)));params.push(size,(page-1)*size);
 return(await(await database()).query<TaskRecord>(`SELECT t.*,u.display_name AS assignee_name,COALESCE(p.name,o.code) AS entity_label FROM cohamy_crm.tasks t JOIN cohamy_crm.memberships m ON m.id=t.assignee_id JOIN cohamy_crm.users u ON u.id=m.user_id LEFT JOIN cohamy_crm.organizations p ON t.entity_type='partner' AND p.id=t.entity_id LEFT JOIN cohamy_crm.website_orders o ON t.entity_type='order' AND o.id=t.entity_id WHERE ${where} ORDER BY t.done_at NULLS FIRST,t.due_at,t.id LIMIT $${params.length-1} OFFSET $${params.length}`,params)).rows;}
export async function createTaskInTransaction(user:Principal,input:unknown,tx:Sql){editor(user);const d=parse(z.object({entityType:z.enum(['partner','order']),entityId:z.uuid(),title:z.string().trim().min(2).max(240),assigneeId:z.uuid(),dueAt:z.iso.datetime({offset:true}),kind:z.enum(['GENERAL','FOLLOW_UP','SUPPORT','APPROVAL']).default('GENERAL')}).strict(),input);
 await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);
 await tx.query('SELECT id FROM cohamy_crm.memberships WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE',[[user.membershipId,d.assigneeId]]);
 await entityAccess(user,d.entityType,d.entityId,tx);if(d.entityType==='partner')await assertWritableOrganization(tx,user,d.entityId);if(d.assigneeId!==user.membershipId)manager(user);await assertAssignee(tx,d.assigneeId,['ADMIN','MANAGER','SALES']);
 const m=(await tx.query<{user_id:string;role:Principal['role'];organization_id:string}>('SELECT user_id,role,organization_id FROM cohamy_crm.memberships WHERE id=$1',[d.assigneeId])).rows[0];
 await entityAccess({...user,id:m.user_id,membershipId:d.assigneeId,role:m.role,organizationId:m.organization_id},d.entityType,d.entityId,tx);
 const id=randomUUID();await tx.query('INSERT INTO cohamy_crm.tasks(id,entity_type,entity_id,title,assignee_id,created_by,due_at,care_kind) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',[id,d.entityType,d.entityId,d.title,d.assigneeId,user.id,d.dueAt,d.kind]);await audit(tx,user.id,'task.created',d.entityId,{taskId:id});const {enqueueNotification}=await import('./workspace');const prefs=(await tx.query<{value:{taskNotifications?:boolean}}>('SELECT value FROM cohamy_crm.workspace_preferences WHERE user_id=$1',[m.user_id])).rows[0];if(prefs?.value.taskNotifications!==false)await enqueueNotification(tx,m.user_id,'task-created:'+id,'TASK',d.entityType,d.entityId,'Bạn được giao việc: '+d.title);return {id};}
export async function createTask(user:Principal,input:unknown){return(await database()).transaction(tx=>createTaskInTransaction(user,input,tx));}
export async function updateTask(user:Principal,id:string,input:unknown){editor(user);const d=parse(z.object({version:z.number().int().positive(),done:z.boolean()}).strict(),input);return(await database()).transaction(async tx=>{await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);const t=(await tx.query<TaskRecord>('SELECT * FROM cohamy_crm.tasks WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!t)throw new CrmError('NOT_FOUND',404);await entityAccess(user,t.entity_type,t.entity_id,tx);if(t.assignee_id!==user.membershipId)manager(user);if(t.version!==d.version)throw new CrmError('VERSION_CONFLICT',409);if(d.done){if((await tx.query('SELECT id FROM cohamy_crm.task_checklist WHERE task_id=$1 AND NOT done',[id])).rows.length)throw new CrmError('CHECKLIST_INCOMPLETE',409);if((await tx.query('SELECT p.id FROM cohamy_crm.task_dependencies x JOIN cohamy_crm.tasks p ON p.id=x.prerequisite_id WHERE x.task_id=$1 AND p.done_at IS NULL',[id])).rows.length)throw new CrmError('DEPENDENCY_INCOMPLETE',409);}else if((await tx.query('SELECT t.id FROM cohamy_crm.task_dependencies x JOIN cohamy_crm.tasks t ON t.id=x.task_id WHERE x.prerequisite_id=$1 AND t.done_at IS NOT NULL',[id])).rows.length)throw new CrmError('DEPENDENT_ALREADY_DONE',409);await tx.query('UPDATE cohamy_crm.tasks SET done_at=CASE WHEN $1 THEN now() ELSE NULL END,version=version+1 WHERE id=$2',[d.done,id]);const {notifyTaskWatchers}=await import('./care-automation');await notifyTaskWatchers(tx,t,d.done);await audit(tx,user.id,d.done?'task.completed':'task.reopened',t.entity_id,{taskId:id,before:{done:Boolean(t.done_at)},after:{done:d.done},reason:'Người phụ trách cập nhật tiến độ.'});return {id};});}
export async function assignments(user:Principal,type:'partner'|'warehouse',id:string){manager(user);const table=type==='partner'?'partner_assignments':'warehouse_assignments',column=type==='partner'?'organization_id':'warehouse_id';return(await(await database()).query<{membership_id:string}>(`SELECT membership_id FROM cohamy_crm.${table} WHERE ${column}=$1`,[id])).rows.map(r=>r.membership_id);}
export async function assignStaff(user:Principal,input:unknown){manager(user);const d=parse(z.object({type:z.enum(['partner','warehouse']),id:z.uuid(),membershipIds:z.array(z.uuid()).max(100)}).strict(),input);return(await database()).transaction(async tx=>{await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);if(d.type==='partner')await assertWritableOrganization(tx,user,d.id);else if(!(await tx.query('SELECT id FROM cohamy_crm.warehouses WHERE id=$1',[d.id])).rows.length)throw new CrmError('NOT_FOUND',404);for(const id of d.membershipIds)await assertAssignee(tx,id,d.type==='partner'?['SALES']:['WAREHOUSE']);const table=d.type==='partner'?'partner_assignments':'warehouse_assignments',column=d.type==='partner'?'organization_id':'warehouse_id';await tx.query(`DELETE FROM cohamy_crm.${table} WHERE ${column}=$1`,[d.id]);for(const id of new Set(d.membershipIds))await tx.query(`INSERT INTO cohamy_crm.${table}(membership_id,${column}) VALUES ($1,$2)`,[id,d.id]);await audit(tx,user.id,'assignment.updated',d.id,{type:d.type,membershipIds:d.membershipIds});return {id:d.id};});}
export async function changePassword(user:Principal,input:unknown){const d=parse(z.object({currentPassword:z.string().min(1).max(72),newPassword:z.string().min(12).max(72)}).strict(),input);const db=await database();return db.transaction(async tx=>{const r=(await tx.query<{password_hash:string}>('SELECT password_hash FROM cohamy_crm.users WHERE id=$1 FOR UPDATE',[user.id])).rows[0];if(!await bcrypt.compare(d.currentPassword,r.password_hash))throw new CrmError('INVALID_CREDENTIALS',400);await tx.query('UPDATE cohamy_crm.users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(d.newPassword,12),user.id]);await tx.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id IN (SELECT id FROM cohamy_crm.memberships WHERE user_id=$1)',[user.id]);await audit(tx,user.id,'account.password-changed',user.id);return {reauthenticate:true};});}
export async function manageAccount(user:Principal,id:string,input:unknown){
 assertPermission(user,'accounts.manage');
 const d=parse(z.object({action:z.enum(['revoke','password','role']),password:z.string().min(12).max(72).optional(),role:z.enum(roles).optional(),expectedVersion:z.number().int().positive().optional()}).strict(),input);
 if(id===user.membershipId)throw new CrmError('CANNOT_CHANGE_SELF',409);
 return(await database()).transaction(async tx=>{
  await tx.exec('LOCK TABLE cohamy_crm.task_dependencies IN SHARE ROW EXCLUSIVE MODE');await assertCurrentPrincipal(tx,user);
  const m=(await tx.query<{user_id:string;kind:string;role:string;version:number}>('SELECT m.user_id,m.role,m.version,o.kind FROM cohamy_crm.memberships m JOIN cohamy_crm.organizations o ON o.id=m.organization_id WHERE m.id=$1 FOR UPDATE OF m',[id])).rows[0];
  if(!m)throw new CrmError('NOT_FOUND',404);if(m.user_id===user.id)throw new CrmError('CANNOT_CHANGE_SELF',409);
  if(d.action==='password'){if(!d.password)throw new CrmError('INVALID_FIELDS',400);await tx.query('UPDATE cohamy_crm.users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(d.password,12),m.user_id]);}
  if(d.action==='role'){
   if(!d.role||m.kind!==(d.role.startsWith('DEALER_')?'DEALER':'COHAMY'))throw new CrmError('ROLE_ORGANIZATION_MISMATCH',400);
   if(d.expectedVersion===undefined)throw new CrmError('ROLE_PREVIEW_REQUIRED',409);
   if(m.version!==d.expectedVersion)throw new CrmError('VERSION_CONFLICT',409);
   await tx.query('UPDATE cohamy_crm.memberships SET role=$1,version=version+1 WHERE id=$2',[d.role,id]);
   await tx.query('DELETE FROM cohamy_crm.partner_assignments WHERE membership_id=$1',[id]);await tx.query('DELETE FROM cohamy_crm.warehouse_assignments WHERE membership_id=$1',[id]);
  }
  await tx.query('UPDATE cohamy_crm.sessions SET revoked_at=now() WHERE membership_id IN(SELECT id FROM cohamy_crm.memberships WHERE user_id=$1)',[m.user_id]);
  await audit(tx,user.id,'account.'+d.action,id,d.action==='role'?{before:{role:m.role,version:m.version},after:{role:d.role,version:m.version+1},reason:'Administrator applied reviewed role; previous assignments and sessions revoked.'}:{});return {id};
 });
}
export async function getCatalogItem(user:Principal,id:string){assertPermission(user,'catalog.read');if(!z.uuid().safeParse(id).success)throw new CrmError('NOT_FOUND',404);const p=(await(await database()).query<CatalogProduct>('SELECT *,retail_price::text FROM cohamy_crm.products WHERE id=$1',[id])).rows[0];if(!p||(user.area==='portal'&&!p.active))throw new CrmError('NOT_FOUND',404);return p;}
export async function updateCatalogItem(user:Principal,id:string,input:unknown){manager(user);const d=parse(z.object({version:z.number().int().positive(),sku:z.string().trim().min(2).max(80).regex(/^[A-Za-z0-9_-]+$/),name:z.string().trim().min(2).max(200),stockUnit:z.string().trim().max(40),unitsPerCase:z.number().int().min(1).max(100000).nullable(),active:z.boolean()}).strict(),input);return(await database()).transaction(async tx=>{await assertCurrentPrincipal(tx,user);const previous=(await tx.query<{stock_unit:string}>('SELECT stock_unit FROM cohamy_crm.products WHERE id=$1 FOR UPDATE',[id])).rows[0];if(previous&&previous.stock_unit!==d.stockUnit&&(await tx.query('SELECT code FROM cohamy_crm.commercial_units WHERE product_id=$1 AND active LIMIT 1',[id])).rows.length)throw new CrmError('UNIT_IN_USE',409);const r=await tx.query('UPDATE cohamy_crm.products SET sku=$1,name=$2,stock_unit=$3,units_per_case=$4,active=$5,version=version+1 WHERE id=$6 AND version=$7 RETURNING id',[d.sku,d.name,d.stockUnit,d.unitsPerCase,d.active,id,d.version]);if(!r.rows.length)throw new CrmError('VERSION_CONFLICT',409);await audit(tx,user.id,'catalog.updated',id,{version:d.version+1});return {id};});}
export async function entityAudit(user:Principal,type:EntityType,id:string){await entityAccess(user,type,id);return(await(await database()).query<{id:string;action:string;created_at:string;actor_name:string|null}>(`SELECT a.id,a.action,a.created_at,u.display_name AS actor_name FROM cohamy_crm.audit_events a LEFT JOIN cohamy_crm.users u ON u.id=a.actor_id WHERE a.entity_id=ANY($1::text[]) ORDER BY a.created_at DESC,a.id LIMIT 50`,[type==='partner'?await (await import('./partner-merge')).partnerFamily(await database(),id):[id]])).rows;}
export async function duplicatePartners(user:Principal,id:string){const original=await getOrganization(user,id);const {inputDuplicates}=await import('./partner-identifiers');return inputDuplicates(user,{phone:original.phone,email:original.email,businessId:original.business_id??'',excludeId:id});}
export async function workReport(user:Principal){internal(user);assertPermission(user,'reports.read');const scope=orderScope(user);const rows=await(await database()).query<{status:string;requests:string;subtotal:string}>(`SELECT status,count(*)::text AS requests,sum(subtotal)::text AS subtotal FROM cohamy_crm.website_orders o WHERE ${scope.sql} GROUP BY status ORDER BY status`,scope.params);return rows.rows;}
