const labels:Record<string,string>={active:'Sử dụng hồ sơ',stage:'Giai đoạn chăm sóc',role:'Vai trò',version:'Phiên bản',code:'Mã hồ sơ',name:'Tên hồ sơ',phone:'Điện thoại',email:'Email',address:'Địa chỉ',source:'Nguồn khách',segment:'Nhóm khách',contactName:'Người liên hệ',status:'Trạng thái',assignedTo:'Người phụ trách',organizationId:'Tổ chức',value:'Giá trị'};
const values:Record<string,string>={LEAD:'Tiềm năng',CONTACTED:'Đã liên hệ',ACTIVE:'Đang hoạt động',INACTIVE:'Ngừng chăm sóc',ADMIN:'Quản trị hệ thống',MANAGER:'Quản lý',SALES:'Sales',WAREHOUSE:'Thủ kho',ACCOUNTANT:'Kế toán',DEALER_OWNER:'Chủ đại lý',DEALER_STAFF:'Nhân viên đại lý',PENDING_REVIEW:'Chờ xét duyệt',IN_PROGRESS:'Đang xử lý',READY:'Đã chốt yêu cầu',REJECTED:'Từ chối',CANCELLED:'Đã hủy'};
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
function display(value:unknown):string{if(value===undefined||value===null||value==='')return 'Chưa ghi nhận';if(typeof value==='boolean')return value?'Có':'Không';if(typeof value==='string')return values[value]??value;if(Array.isArray(value))return value.map(display).join(', ');if(typeof value==='object')return Object.entries(record(value)).map(([key,v])=>(labels[key]??'Thuộc tính '+key)+': '+display(v)).join(' · ');return String(value);}
export function AuditChangeDetails({payload}:{payload:unknown}){
 const p=record(payload),before=p.before===undefined?{}:p.before&&typeof p.before==='object'?record(p.before):{value:p.before},after=p.after===undefined?{}:p.after&&typeof p.after==='object'?record(p.after):{value:p.after},keys=[...new Set([...Object.keys(before),...Object.keys(after)])];
 const reason=typeof p.reason==='string'?p.reason:null;
 return <details className="work-disclosure"><summary>Nội dung thay đổi và lý do</summary>{keys.length?<dl className="crm-readonly">{keys.map(key=><div key={key}><dt>{labels[key]??'Thuộc tính '+key}</dt><dd>Trước: {display(before[key])}<br/>Sau: {display(key in after?after[key]:before[key])}</dd></div>)}</dl>:<p>Sự kiện này chưa ghi chi tiết trước và sau.</p>}{reason&&<p>Lý do: {reason}</p>}<details className="work-disclosure"><summary>Dữ liệu kỹ thuật của sự kiện</summary><pre className="upgrade-audit-payload">{JSON.stringify(payload,null,2)}</pre></details></details>;
}
