import Link from 'next/link';
import {careSchedules,scheduleRuns,careRules,ruleRuns,slaPolicies,escalations,careKindLabels,taskWatchers} from '@/lib/crm/care-automation';
import {staffOptions} from '@/lib/crm/work';
import type {Principal} from '@/lib/crm/types';
import {ScheduleForm,RuleForm,SlaForm,HandoverForm} from './CareAutomationForms';
import {ActionButton} from './UpgradeForms';
const date=(value:string)=>new Date(value).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});
const frequencies={DAILY:'ngày',WEEKLY:'tuần',MONTHLY:'tháng'};
export async function AutomationPage({user}:{user:Principal}){const schedules=await careSchedules(user),staff=await staffOptions(user),manage=['ADMIN','MANAGER'].includes(user.role);return <><header className="portal-page-header"><div><h1>Lịch và quy tắc công việc</h1><p>Sinh việc theo giờ Việt Nam. Kết quả và lỗi được giữ cùng hồ sơ gốc.</p></div></header><section className="work-section"><h2>Lịch lặp của nhóm</h2>{!schedules.length&&<p className="work-help">Chưa có lịch trong phạm vi của bạn. Tạo lịch trên hồ sơ để giữ đúng ngữ cảnh.</p>}{schedules.map(s=><div id={'schedule-'+s.id} key={s.id} className="care-schedule-row"><h3>{s.title}</h3><p>{s.enabled?'Đang bật':'Tạm dừng'} · mỗi {s.every} {frequencies[s.frequency]} · {s.assignee_name} · {careKindLabels[s.care_kind]}</p><p>Lượt tiếp theo: {date(s.next_due_at)}{s.error_code?' · Cần kiểm tra quyền hoặc tình trạng hồ sơ trước khi bật lại.':''}</p><Link href={'/crm/'+(s.entity_type==='partner'?'partners':'orders')+'/'+s.entity_id}>Mở hồ sơ gốc</Link><details className="work-disclosure"><summary>Sửa lịch {s.title}</summary><ScheduleForm key={s.version} staff={staff} self={user.membershipId} schedule={s}/></details><details className="work-disclosure"><summary>Các lượt đã xử lý</summary><ScheduleHistory user={user} id={s.id}/></details></div>)}<p className="work-help">Tạo lịch ngay trên hồ sơ cần chăm sóc.</p><nav className="upgrade-actions" aria-label="Chọn hồ sơ tạo lịch"><Link href="/crm/customers">Mở khách hàng</Link><Link href="/crm/dealers">Mở đại lý</Link><Link href="/crm/orders">Mở yêu cầu</Link></nav></section>{manage&&<><Rules user={user} staff={staff}/><Sla user={user} staff={staff}/><section className="work-section"><h2>Bàn giao phụ trách</h2><p>Chuyển toàn bộ hồ sơ được giao, yêu cầu phụ trách và việc chưa xong giữa hai Sales. Xem danh sách trước khi xác nhận; dữ liệu thay đổi sẽ yêu cầu xem lại.</p><HandoverForm staff={staff}/></section></>}</>;}
async function ScheduleHistory({user,id}:{user:Principal;id:string}){const rows=await scheduleRuns(user,id);return rows.length?<ul className="work-task-list">{rows.map(r=><li key={r.id}><div><strong>{r.status==='SUCCEEDED'?'Đã tạo việc':'Chưa tạo: cần kiểm tra'}</strong><p>{date(r.scheduled_at)} · cấu hình bản {r.definition_version}</p></div>{r.task_id&&<Link href={'/crm/tasks/'+r.task_id}>Mở việc</Link>}</li>)}</ul>:<p>Chưa có lượt đến hạn được xử lý.</p>;}
async function Rules({user,staff}:{user:Principal;staff:Awaited<ReturnType<typeof staffOptions>>}){const rows=await careRules(user);return <section className="work-section"><h2>Việc tự tạo từ sự kiện</h2>{!rows.length&&<p>Chưa có quy tắc. Mẫu mới chỉ áp dụng cho sự kiện từ lúc bật.</p>}{rows.map(r=><details id={'rule-'+r.id} className="work-disclosure" key={r.id}><summary>{r.name} · {r.enabled?'Đang bật':'Tắt'}</summary><p>{r.event_action==='application.approved'?'Duyệt đối tác':'Tạo hồ sơ'} → {r.title} · {r.assignee_name}</p><RuleForm key={r.version} rule={r} staff={staff}/><RuleHistory user={user} id={r.id}/></details>)}<details className="work-disclosure"><summary>Tạo quy tắc</summary><RuleForm staff={staff}/></details></section>;}
async function RuleHistory({user,id}:{user:Principal;id:string}){const rows=await ruleRuns(user,id);return rows.length?<ul className="work-task-list">{rows.map((r,i)=><li key={i}><span>{date(r.created_at)} · {r.status==='SUCCEEDED'?'Đã tạo việc':'Chưa tạo: người hoặc hồ sơ không còn phù hợp'} · mẫu bản {r.rule_version}</span>{r.task_id&&<Link href={'/crm/tasks/'+r.task_id}>Mở việc</Link>}</li>)}</ul>:<p>Chưa có sự kiện đã xử lý.</p>;}
async function Sla({user,staff}:{user:Principal;staff:Awaited<ReturnType<typeof staffOptions>>}){const policies=await slaPolicies(user),events=await escalations(user);return <section className="work-section"><h2>Chuyển cấp việc chậm</h2>{!policies.length&&<p>Chưa bật chuyển cấp. Chọn loại việc, thời gian và người nhận phù hợp.</p>}{policies.map(p=><details className="work-disclosure" key={p.id}><summary>{p.name} · {p.enabled?'Đang bật':'Tắt'} · {p.recipient_name}</summary><SlaForm key={p.version} policy={p} staff={staff}/></details>)}<details className="work-disclosure"><summary>Tạo cấu hình chuyển cấp</summary><SlaForm staff={staff}/></details><h3>Lịch sử chuyển cấp</h3>{events.length?<ul className="work-task-list">{events.map((e,i)=><li key={i}><div><Link href={'/crm/tasks/'+e.task_id}>{e.title}</Link><p>{e.policy_name} · gửi đến {e.recipient_name} · {date(e.created_at)}</p><p>Mốc chuyển cấp: {date(e.deadline)}. Thông báo tuân theo tùy chọn của người nhận.</p></div></li>)}</ul>:<p>Chưa có việc được chuyển cấp.</p>}</section>;}
export async function RecurrencePanel({user,type,id}:{user:Principal;type:'partner'|'order';id:string}){return <section className="work-section"><h2>Lịch chăm sóc định kỳ</h2><details className="work-disclosure"><summary>Tạo lịch trên hồ sơ này</summary><ScheduleForm staff={await staffOptions(user)} self={user.membershipId} source={{type,id}}/></details><Link href="/crm/automation">Xem lịch và kết quả sinh việc</Link></section>;}
export async function WatchersPanel({user,id}:{user:Principal;id:string}){const rows=await taskWatchers(user,id),following=rows.some(r=>r.membership_id===user.membershipId);return <section className="work-section"><h2>Theo dõi công việc</h2><p>Nhận thông báo khi hoàn thành hoặc mở lại. Quyền xem hồ sơ được kiểm tra ở mỗi thông báo.</p><p>{rows.length?'Đang theo dõi: '+rows.map(r=>r.name).join(', '):'Chưa có người theo dõi.'}</p><ActionButton url="/api/crm/automation/follow" data={{taskId:id,follow:!following}} label={following?'Dừng theo dõi':'Theo dõi việc'} success={following?'Đã dừng theo dõi.':'Đã theo dõi công việc.'}/></section>;}
