import {consignmentOperations,consignmentOverview} from '@/lib/crm/consignment';
import {listInventory,listLocations} from '@/lib/crm/inventory';
import {listCatalog,listOrganizationOptions,listWarehouses} from '@/lib/crm/repository';
import type {Principal} from '@/lib/crm/types';
import {AgreementAcceptForm,AgreementForm,ReceiptForm,ReplenishmentDecisionForm,ReturnActionForm,ReturnRequestForm,SaleImportForm,SaleReportForm,SettlementActionForm,SettlementCreateForm,ShipmentForm,SuggestForm} from './ConsignmentForms';
export async function ConsignmentPage({user}:{user:Principal}){const manager=user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role),warehouseWriter=user.area==='crm'&&['ADMIN','MANAGER','WAREHOUSE'].includes(user.role),settlementWriter=user.area==='crm'&&['ADMIN','MANAGER','ACCOUNTANT'].includes(user.role),[data,ops,products,warehouses,locations,balances,organizations]=await Promise.all([consignmentOverview(user),consignmentOperations(user),listCatalog(user),listWarehouses(user),listLocations(user),user.area==='crm'?listInventory(user):Promise.resolve([]),manager?listOrganizationOptions(user):Promise.resolve([])]),returnLines=ops.returnLines as never[];
 return <><header className="portal-page-header"><div><h1>Ký gửi và đối soát</h1><p>Hàng ký gửi giữ owner Cohamy, tách khỏi hàng bán đứt và được đối chiếu theo lô.</p></div></header>
 {manager&&<section className="work-section"><h2>Thỏa thuận mới</h2><AgreementForm organizations={organizations} products={products.map(p=>({id:p.id,code:p.sku,name:p.name}))} warehouses={warehouses}/></section>}
 <section className="work-section"><h2>Thỏa thuận</h2>{data.agreements.map(a=><article className="work-card" key={a.id}><h3>{a.code} · {a.organization_name} · {a.status}</h3>{a.status==='PENDING_ACCEPTANCE'&&((user.area==='portal'&&user.role==='DEALER_OWNER')||manager)&&<AgreementAcceptForm agreement={a as never}/>} {a.status==='ACTIVE'&&<><details className="work-disclosure"><summary>Báo bán nhập tay</summary><SaleReportForm agreement={a as never} batches={data.batches as never} draftOwner={user.id}/></details><details className="work-disclosure"><summary>Báo bán từ Excel có preview</summary><SaleImportForm agreement={a as never}/></details><details className="work-disclosure"><summary>Đề nghị thu hồi/đổi</summary><ReturnRequestForm agreement={a as never} batches={data.batches as never}/></details><details className="work-disclosure"><summary>Gợi ý bổ sung</summary><SuggestForm agreement={a as never}/></details>{warehouseWriter&&<details className="work-disclosure"><summary>Xuất gửi thêm</summary><ShipmentForm agreement={a as never} balances={balances as never}/></details>}{settlementWriter&&<details className="work-disclosure"><summary>Tạo kỳ đối soát</summary><SettlementCreateForm agreement={a as never}/></details>}</>}</article>)}</section>
 <section className="work-section"><h2>Tồn ký gửi</h2>{data.batches.length?<div className="work-table-wrap" tabIndex={0}><table className="work-table"><thead><tr><th>SKU/lô</th><th>Kho giữ</th><th>Gửi</th><th>Nhận</th><th>Bán</th><th>Trả</th><th>Khả dụng</th></tr></thead><tbody>{data.batches.map(b=><tr key={b.id}><td>{b.sku}/{b.lot_code}</td><td>{b.warehouse_code}</td><td>{b.sent}</td><td>{b.received}</td><td>{b.sold}</td><td>{b.returned}</td><td>{b.available}</td></tr>)}</tbody></table></div>:<p>Chưa có lô ký gửi.</p>}</section>
 {user.area==='portal'&&<section className="work-section"><h2>Phiếu đang nhận</h2>{data.shipments.filter(s=>['IN_TRANSIT','PARTIAL'].includes(String(s.status))).map(s=><ReceiptForm key={String(s.id)} shipment={s as never} batches={data.batches as never}/>)}</section>}
 <section className="work-section"><h2>Đối soát</h2>{data.settlements.map(s=><article className="work-card" key={String(s.id)}><h3>{String(s.code)} · {String(s.status)}</h3><p>Tổng {String(s.gross_amount)} · đại lý {String(s.partner_amount)} · Cohamy {String(s.cohamy_amount)}</p>{!['LOCKED','ADJUSTMENT'].includes(String(s.status))&&<SettlementActionForm item={s as never}/>}</article>)}</section>
 <section className="work-section"><h2>Đề nghị bổ sung</h2>{data.replenishments.map(r=><article className="work-card" key={String(r.id)}><h3>{String(r.sku)} · {String(r.suggested)} · {String(r.status)}</h3><pre>{JSON.stringify(r.explanation,null,2)}</pre>{manager&&r.status==='REQUESTED'&&<ReplenishmentDecisionForm item={r as never}/>}</article>)}</section>
 <section className="work-section"><h2>Thu hồi và đổi hàng</h2>{data.returns.map(r=><article className="work-card" key={String(r.id)}><h3>{String(r.code)} · {String(r.status)}</h3><ReturnActionForm item={r as never} lines={returnLines} locations={locations} portal={user.area==='portal'}/></article>)}</section></>;
}
