import {financeOverview,receivableAging} from '@/lib/crm/finance';
import {listOrganizations} from '@/lib/crm/repository';
import type {Principal} from '@/lib/crm/types';
import {AllocationForm,BankImportForm,BankMatchForm,CashActionForm,CashCreateForm,CreditForm,DepositRefundForm,PaymentProofCreateForm,PaymentReviewForm,ReceivableAdjustForm,ReceivablePostForm,ReminderForm} from './FinanceForms';
type Overview=Awaited<ReturnType<typeof financeOverview>>;
function Header({title,description}:{title:string;description:string}){return <header className="portal-page-header"><div><h1>{title}</h1><p>{description}</p></div></header>;}
const money=(v:string)=>BigInt(v).toLocaleString('vi-VN')+' đ';
export async function FinancePage({user,mode}:{user:Principal;mode:string}){const data=await financeOverview(user) as Overview,internal=user.area==='crm'&&['ADMIN','MANAGER','ACCOUNTANT'].includes(user.role),manager=user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role),organizations=internal?(await listOrganizations(user,{page:1})).items.map(o=>({id:o.id,name:o.name})):[],aging=await receivableAging(user,new Date().toISOString().slice(0,10));
 return <><Header title={mode==='cash'?'Thu, chi và hoàn tiền':mode==='payments'?'Chứng từ thanh toán':'Hạn mức và công nợ'} description="Số dư lấy từ sổ nguồn và phân bổ đã xác nhận; chứng từ tải lên không tự ghi đã thu."/>
 {mode!=='cash'&&<><section className="work-section"><h2>Hạn mức</h2>{data.accounts.length?<div className="work-table-wrap" tabIndex={0}><table className="work-table"><thead><tr><th>Đối tác</th><th>Hạn mức</th><th>Đang dùng</th><th>Còn lại</th><th>Kỳ hạn</th><th>Trạng thái</th></tr></thead><tbody>{data.accounts.map(a=><tr key={a.organization_id}><td>{a.organization_name}</td><td>{money(a.limit_amount)}</td><td>{money(a.used_amount)}</td><td>{money((BigInt(a.limit_amount)-BigInt(a.used_amount)).toString())}</td><td>{a.terms_days} ngày</td><td>{a.enabled?'Đang mở':'Đang tắt'}</td></tr>)}</tbody></table></div>:<p>Chưa cấu hình hạn mức. Mua chịu vẫn bị khóa.</p>}{manager&&<details className="work-disclosure"><summary>Cấu hình hạn mức có phiên bản</summary><CreditForm organizations={organizations} accounts={data.accounts}/></details>}{internal&&<details className="work-disclosure"><summary>Ghi khoản phải thu từ đơn</summary><ReceivablePostForm/></details>}</section>
 <section className="work-section"><h2>Sổ phải thu</h2>{data.receivables.length?<>{data.receivables.map(r=><details className="work-disclosure" key={r.id}><summary>{r.code} · {r.organization_name} · còn {money(r.remaining_amount)} · {r.status}</summary><p>Nguồn {r.source_type}/{r.source_id} · đến hạn {r.due_on}</p>{internal&&<ReceivableAdjustForm receivable={r}/>} {internal&&BigInt(r.remaining_amount)>0n&&<ReminderForm receivable={r}/>}<h4>Lịch sử bất biến</h4><ul>{data.receivableEvents.filter(e=>String(e.receivable_id)===r.id).map(e=><li key={String(e.id)}>{String(e.action)} · {money(String(e.amount))} · {String(e.reason)}</li>)}</ul></details>)}</>:<p>Chưa có khoản phải thu đã ghi sổ.</p>}<h3>Tuổi nợ tại {aging.asOf}</h3>{aging.rows.length?<ul>{aging.rows.map((r,i)=><li key={i}>{r.organization_name} · {r.bucket} · {money(r.amount)}</li>)}</ul>:<p>Không có dư nợ tại ngày đối chiếu.</p>}<h3>Lịch sử nhắc</h3>{data.reminders.length?<ul>{data.reminders.map(r=><li key={String(r.id)}>{String(r.channel)} · {String(r.status)} · {new Date(String(r.scheduled_for)).toLocaleString('vi-VN')} {r.last_error?`· ${String(r.last_error)}`:''}</li>)}</ul>:<p>Chưa có lịch nhắc.</p>}</section>
 <section className="work-section"><h2>Thanh toán và ứng trước</h2><details className="work-disclosure"><summary>Tải ảnh/PDF và gửi chứng từ mới</summary><PaymentProofCreateForm organizations={organizations} portalOrganizationId={user.area==='portal'?user.organizationId:undefined}/></details>{data.payments.map(p=><article className="work-card" key={p.id}><h3>{p.code} · {p.organization_name} · {p.status}</h3><p>{p.kind} · {money(p.amount)} · đã phân bổ {money(p.allocated_amount)} · đã đề nghị hoàn {money(p.refunded_amount??'0')} · còn {money(p.available_amount??(BigInt(p.amount)-BigInt(p.allocated_amount)).toString())} · {p.reference}</p>{internal&&p.status==='PENDING'&&<PaymentReviewForm payment={p}/>} {internal&&p.status==='CONFIRMED'&&BigInt(p.available_amount??'0')>0n&&<AllocationForm payment={p} receivables={data.receivables}/>} {internal&&p.kind==='DEPOSIT'&&p.status==='CONFIRMED'&&BigInt(p.available_amount??'0')>0n&&<DepositRefundForm payment={p}/>}</article>)}</section>
 {internal&&<section className="work-section"><h2>Sao kê và ghép giao dịch</h2><details className="work-disclosure"><summary>Nhập dòng sao kê chống trùng</summary><BankImportForm/></details>{data.bankTransactions.map(b=><article className="work-card" key={String(b.id)}><h3>{String(b.bank_code)} · {String(b.external_id)} · {money(String(b.amount))}</h3><p>{String(b.counterparty)} · {String(b.reference)} · {b.payment_code?`đã ghép ${String(b.payment_code)}`:'chưa ghép'}</p><BankMatchForm transaction={b as never} payments={data.payments} manager={manager}/></article>)}</section>}</>}
 {mode==='cash'&&<section className="work-section"><h2>Đề nghị thu, chi và hoàn tiền</h2>{internal&&<details className="work-disclosure"><summary>Tạo đề nghị mới</summary><CashCreateForm organizations={organizations}/></details>}{data.cashRequests.map(c=><article className="work-card" key={String(c.id)}><h3>{String(c.code)} · {String(c.organization_name)} · {String(c.status)}</h3><p>{String(c.kind)} · {money(String(c.amount))} · nguồn {String(c.source_type)}/{String(c.source_id)}</p>{internal&&<CashActionForm request={c as never} currentUserId={user.id}/>}</article>)}</section>}
 </>;
}
