'use client';
import {Form} from './CommercialForms';
const str=(f:FormData,k:string)=>String(f.get(k)??''),iso=(v:string)=>v?new Date(v+':00+07:00').toISOString():null;
type Reservation={id:string;status:string;quantity:string;consumed:string;released:string;sku:string;lot_code:string;location_code:string};
type Line={id:string;planned:string;picked:string;packed:string;dispatched:string;delivered:string;sku:string;lot_code:string;location_code:string};
type Parcel={id:string;code:string;status:string};
type Delivery={id:string;code:string;status:string;version:number;lines:Line[];parcels:Parcel[]};
type Location={id:string;warehouse_code:string;code:string;name:string;kind?:string;active:boolean};
export function DeliveryCreateForm({orderId,reservations}:{orderId:string;reservations:Reservation[]}){return <Form endpoint="/api/crm/fulfillment/delivery-create" label="Lập đợt giao" payload={f=>({orderId,lines:[{reservationId:str(f,'reservationId'),quantity:str(f,'quantity')}],windowStart:iso(str(f,'windowStart')),windowEnd:iso(str(f,'windowEnd')),requirements:str(f,'requirements'),reason:str(f,'reason')})}><div className="work-fields"><label>Reservation<select name="reservationId" required><option value="">Chọn SKU/lô đã giữ</option>{reservations.filter(r=>['ACTIVE','PARTIAL'].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.sku} · {r.location_code}/{r.lot_code} · giữ {r.quantity}</option>)}</select></label><label>Số lượng đợt này<input name="quantity" required inputMode="decimal"/></label><label>Từ (giờ Việt Nam)<input name="windowStart" type="datetime-local"/></label><label>Đến (giờ Việt Nam)<input name="windowEnd" type="datetime-local"/></label><label>Yêu cầu nhận hàng<textarea name="requirements" maxLength={1000}/></label><label>Lý do lập đợt<input name="reason" required minLength={3}/></label></div></Form>;}
export function BackorderForm({orderId,products}:{orderId:string;products:{productId:string;sku:string}[]}){return <Form endpoint="/api/crm/fulfillment/backorder" label="Ghi hàng chờ bổ sung" payload={f=>({orderId,productId:str(f,'productId'),quantity:str(f,'quantity'),expectedOn:str(f,'expectedOn')||null,ownerMembershipId:null,reason:str(f,'reason')})}><div className="work-fields"><label>SKU thiếu<select name="productId" required>{products.map(p=><option key={p.productId} value={p.productId}>{p.sku}</option>)}</select></label><label>Lượng thiếu<input name="quantity" required inputMode="decimal"/></label><label>Ngày dự kiến<input name="expectedOn" type="date"/></label><label>Người/ghi chú xử lý<input name="reason" required minLength={3}/></label></div><p>Ngày dự kiến là thông tin theo dõi, không lấy tồn đã giữ cho đơn khác để cam kết.</p></Form>;}
export function PickForm({delivery}:{delivery:Delivery}){return <Form endpoint="/api/crm/fulfillment/pick" label="Xác nhận soạn" payload={f=>({id:delivery.id,version:delivery.version,lineId:str(f,'lineId'),quantity:str(f,'quantity'),scannerCode:str(f,'scannerCode'),manual:f.has('manual'),reason:str(f,'reason')})}><div className="work-fields"><label>Dòng soạn<select name="lineId" required>{delivery.lines.map(l=><option key={l.id} value={l.id}>{l.location_code} · {l.sku}/{l.lot_code} · {l.picked}/{l.planned}</option>)}</select></label><label>Mã quét SKU hoặc lô<input name="scannerCode" required/></label><label>Số lượng soạn<input name="quantity" required inputMode="decimal"/></label><label>Lý do / thiết bị<input name="reason" required minLength={3}/></label></div><label className="work-check"><input name="manual" type="checkbox"/>Nhập mã thủ công khi thiết bị không có camera</label></Form>;}
export function PackForm({delivery}:{delivery:Delivery}){return <Form endpoint="/api/crm/fulfillment/pack" label="Đóng kiện" payload={f=>({id:delivery.id,version:delivery.version,label:str(f,'label'),lines:[{lineId:str(f,'lineId'),quantity:str(f,'quantity')}],reason:str(f,'reason')})}><div className="work-fields"><label>Dòng đã soạn<select name="lineId" required>{delivery.lines.map(l=><option key={l.id} value={l.id}>{l.sku}/{l.lot_code} · đóng {l.packed}/{l.picked}</option>)}</select></label><label>Số lượng vào kiện<input name="quantity" required inputMode="decimal"/></label><label>Nhãn kiện<input name="label" required maxLength={200}/></label><label>Lý do đóng kiện<input name="reason" required minLength={3}/></label></div></Form>;}
export function TripForm({parcel}:{parcel:Parcel}){return <Form endpoint="/api/crm/fulfillment/trip-create" label="Gom vào chuyến mới" payload={f=>({parcelIds:[parcel.id],driverName:str(f,'driverName'),driverPhone:str(f,'driverPhone'),routeNote:str(f,'routeNote'),reason:str(f,'reason')})}><div className="work-fields"><label>Người giao<input name="driverName" required minLength={2}/></label><label>Điện thoại<input name="driverPhone" required minLength={5}/></label><label>Thứ tự / tuyến<input name="routeNote" maxLength={2000}/></label><label>Lý do lập chuyến<input name="reason" required minLength={3}/></label></div></Form>;}
export function DispatchTripForm({trip}:{trip:{id:string;version:number;code:string}}){return <Form endpoint="/api/crm/fulfillment/trip-dispatch" label="Xuất kho và khởi hành" payload={f=>({id:trip.id,version:trip.version,reason:str(f,'reason')})}><label>Lý do xuất chuyến {trip.code}<input name="reason" required minLength={3}/></label><p>Xuất chuyến tiêu thụ đúng reservation và đưa hàng ra khỏi tồn bán được.</p></Form>;}
export function FinishDeliveryForm({delivery}:{delivery:Delivery}){return <Form endpoint="/api/crm/fulfillment/delivery-finish" label="Ghi kết quả giao" payload={f=>({id:delivery.id,version:delivery.version,outcome:str(f,'outcome'),recipient:str(f,'recipient'),confirmation:str(f,'confirmation'),photoDocumentId:null,signatureDocumentId:null,resolution:str(f,'resolution')||null,nextAttemptAt:iso(str(f,'nextAttemptAt')),reason:str(f,'reason')})}><div className="work-fields"><label>Kết quả<select name="outcome"><option value="DELIVERED">Đã giao</option><option value="FAILED">Giao thất bại</option></select></label><label>Người nhận<input name="recipient" maxLength={120}/></label><label>Xác nhận POD<input name="confirmation" maxLength={1000}/></label><label>Xử lý khi thất bại<select name="resolution"><option value="">Không áp dụng</option><option value="RESCHEDULE">Hẹn lại</option><option value="RETURN">Hoàn hàng</option></select></label><label>Lần hẹn tiếp<input name="nextAttemptAt" type="datetime-local"/></label><label>Lý do / diễn giải<input name="reason" required minLength={3}/></label></div></Form>;}
export function CarrierManualForm({parcel}:{parcel:Parcel}){return <Form endpoint="/api/crm/fulfillment/carrier-manual" label="Ghi trạng thái vận đơn thủ công" payload={f=>({parcelId:parcel.id,status:str(f,'status'),trackingCode:str(f,'trackingCode')||null,reason:str(f,'reason')})}><div className="work-fields"><label>Trạng thái hãng<input name="status" required/></label><label>Mã vận đơn<input name="trackingCode"/></label><label>Lý do cập nhật thủ công<input name="reason" required minLength={3}/></label></div><p>Kết nối hãng chưa cấu hình vẫn giữ ở trạng thái tắt; cập nhật này được audit là thủ công.</p></Form>;}
export function ReturnRequestForm({orderId,lines}:{orderId:string;lines:Line[]}){return <Form endpoint="/api/crm/fulfillment/return-request" label="Gửi yêu cầu đổi trả" payload={f=>({orderId,lines:[{deliveryLineId:str(f,'lineId'),quantity:str(f,'quantity'),reason:str(f,'lineReason'),photoDocumentId:null}],reason:str(f,'reason')})}><div className="work-fields"><label>Dòng đã giao<select name="lineId" required>{lines.filter(l=>Number(l.delivered)>0).map(l=><option key={l.id} value={l.id}>{l.sku}/{l.lot_code} · đã giao {l.delivered}</option>)}</select></label><label>Số lượng trả<input name="quantity" required inputMode="decimal"/></label><label>Lý do dòng<input name="lineReason" required minLength={3}/></label><label>Lý do phiếu<input name="reason" required minLength={3}/></label></div></Form>;}
export function ReturnDecisionForm({item}:{item:{id:string;version:number}}){return <Form endpoint="/api/crm/fulfillment/return-decide" label="Quyết định yêu cầu trả" payload={f=>({id:item.id,version:item.version,action:str(f,'action'),reason:str(f,'reason')})}><div className="work-fields"><label>Quyết định<select name="action"><option value="APPROVE">Duyệt nhận hàng</option><option value="REJECT">Từ chối</option></select></label><label>Lý do<input name="reason" required minLength={3}/></label></div></Form>;}
export function ReturnReceiveForm({item,locations}:{item:{id:string;version:number;lines:{id:string;sku:string;lot_code:string;quantity:string}[]};locations:Location[]}){return <Form endpoint="/api/crm/fulfillment/return-receive" label="Ghi thực nhận và phân loại" payload={f=>({id:item.id,version:item.version,lines:[{requestLineId:str(f,'lineId'),quantity:str(f,'quantity'),disposition:str(f,'disposition'),locationId:str(f,'locationId'),reason:str(f,'lineReason')}],reason:str(f,'reason')})}><div className="work-fields"><label>Dòng trả<select name="lineId" required>{item.lines.map(l=><option key={l.id} value={l.id}>{l.sku}/{l.lot_code} · yêu cầu {l.quantity}</option>)}</select></label><label>Thực nhận<input name="quantity" required inputMode="decimal"/></label><label>Phân loại<select name="disposition"><option value="RESALE">Bán lại</option><option value="QUARANTINE">Cách ly</option><option value="DAMAGED">Hỏng</option></select></label><label>Vị trí đúng loại<select name="locationId" required>{locations.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.warehouse_code}/{l.code} · {l.kind??'PICK'}</option>)}</select></label><label>Lý do phân loại<input name="lineReason" required minLength={3}/></label><label>Lý do nhận phiếu<input name="reason" required minLength={3}/></label></div><p>Phân loại kho không tự tạo hoàn tiền.</p></Form>;}
