import {orderFulfillment} from '@/lib/crm/fulfillment';
import {listLocations,orderInventoryState} from '@/lib/crm/inventory';
import type {Principal} from '@/lib/crm/types';
import {BackorderForm,CarrierManualForm,DeliveryCreateForm,DispatchTripForm,FinishDeliveryForm,PackForm,PickForm,ReturnDecisionForm,ReturnReceiveForm,ReturnRequestForm,TripForm} from './FulfillmentForms';
type Line={id:string;planned:string;picked:string;packed:string;dispatched:string;delivered:string;sku:string;lot_code:string;location_code:string};
type Parcel={id:string;code:string;status:string};
type Delivery={id:string;code:string;status:string;version:number;window_start:string|null;window_end:string|null;timezone:string;requirements:string;next_attempt_at:string|null;lines:Line[];parcels:Parcel[];proof:Record<string,unknown>|null};
type Trip={id:string;code:string;status:string;version:number};
type Return={id:string;code:string;status:string;version:number;lines:{id:string;sku:string;lot_code:string;quantity:string}[]};
export async function FulfillmentPanel({user,orderId,products}:{user:Principal;orderId:string;products:{productId:string;sku:string}[]}){const [data,inventory,locations]=await Promise.all([orderFulfillment(user,orderId),orderInventoryState(user,orderId),listLocations(user)]),deliveries=data.deliveries as unknown as Delivery[],trips=data.trips as unknown as Trip[],returns=data.returns as unknown as Return[],writer=user.area==='crm'&&['ADMIN','MANAGER','WAREHOUSE'].includes(user.role),manager=user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role),allLines=deliveries.flatMap(d=>d.lines);
 return <section className="work-section"><h2>Soạn, giao và đổi trả</h2><p>Mỗi đợt giao dùng reservation cụ thể; tổng soạn, đóng kiện và giao không được vượt lượng đã giữ.</p>{writer&&inventory.active&&<details className="work-disclosure"><summary>Lập đợt giao mới</summary><DeliveryCreateForm orderId={orderId} reservations={inventory.rows}/></details>}{manager&&products.length>0&&<details className="work-disclosure"><summary>Ghi hàng chờ bổ sung</summary><BackorderForm orderId={orderId} products={products}/></details>}{data.backorders.length>0&&<ul>{(data.backorders as Record<string,unknown>[]).map((b,i)=><li key={i}>{String(b.sku)} · thiếu {String(b.quantity)} · dự kiến {String(b.expected_on??'chưa chốt')} · {String(b.status)}</li>)}</ul>}
 {deliveries.map(delivery=><article className="work-card" key={delivery.id}><h3>{delivery.code} · {delivery.status}</h3><p>{delivery.window_start?new Date(delivery.window_start).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa chốt khung giờ'}{delivery.window_end?' – '+new Date(delivery.window_end).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):''}<br/>{delivery.requirements||'Không có yêu cầu riêng'}</p><div className="work-table-wrap" tabIndex={0}><table className="work-table"><thead><tr><th>Dòng</th><th>Kế hoạch</th><th>Soạn</th><th>Đóng</th><th>Xuất</th><th>Giao</th></tr></thead><tbody>{delivery.lines.map(l=><tr key={l.id}><td>{l.location_code} · {l.sku}/{l.lot_code}</td><td>{l.planned}</td><td>{l.picked}</td><td>{l.packed}</td><td>{l.dispatched}</td><td>{l.delivered}</td></tr>)}</tbody></table></div>{writer&&['PLANNED','PICKING'].includes(delivery.status)&&<PickForm delivery={delivery}/>} {writer&&['PICKING','PACKED'].includes(delivery.status)&&<PackForm delivery={delivery}/>} {delivery.parcels.map(parcel=><details className="work-disclosure" key={parcel.id}><summary>{parcel.code} · {parcel.status}</summary>{writer&&parcel.status==='PACKED'&&<TripForm parcel={parcel}/>} {writer&&<CarrierManualForm parcel={parcel}/>}</details>)} {writer&&delivery.status==='IN_TRANSIT'&&<FinishDeliveryForm delivery={delivery}/>} {delivery.proof&&<p>POD: {String(delivery.proof.recipient)} · {new Date(String(delivery.proof.received_at)).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} · {String(delivery.proof.confirmation)}</p>}</article>)}
 {writer&&trips.map(trip=><details className="work-disclosure" key={trip.id}><summary>{trip.code} · {trip.status}</summary>{trip.status==='PLANNED'&&<DispatchTripForm trip={trip}/>}</details>)}
 {allLines.some(l=>Number(l.delivered)>0)&&<details className="work-disclosure"><summary>Yêu cầu đổi trả dòng đã giao</summary><ReturnRequestForm orderId={orderId} lines={allLines}/></details>}
 {returns.map(item=><article className="work-card" key={item.id}><h3>{item.code} · {item.status}</h3>{manager&&item.status==='REQUESTED'&&<ReturnDecisionForm item={item}/>} {writer&&item.status==='APPROVED'&&<ReturnReceiveForm item={item} locations={locations}/>}</article>)}
 </section>;
}
