'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {send} from './UpgradeForms';
import {roles,roleLabels,type Organization,type Role} from '@/lib/crm/types';
import type {FieldDefinition} from '@/lib/crm/governance';

const columnLabels:Record<string,string>={name:'Hồ sơ',code:'Mã',phone:'Điện thoại',email:'Email',active:'Trạng thái',created_at:'Tạo lúc'};
type Pref={columns:string[];columnWidths:Record<string,number>;version:number;quietStart:number|null;quietEnd:number|null;taskNotifications:boolean;notificationKinds:string[];notificationChannels:string[]};
export function AdvancedColumns({initial}:{initial:Pref}){
 const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const [order,setOrder]=useState([...initial.columns,...Object.keys(columnLabels).filter(k=>!initial.columns.includes(k))]),[visible,setVisible]=useState(initial.columns),[widths,setWidths]=useState(initial.columnWidths);
 const move=(index:number,offset:number)=>{const next=[...order];[next[index],next[index+offset]]=[next[index+offset],next[index]];setOrder(next);setSaved('');};
 return <details className="work-disclosure"><summary>Chọn cột hiển thị</summary><form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');try{await send('/api/crm/workspace/preferences',{...initial,columns:order.filter(k=>visible.includes(k)),columnWidths:widths});setSaved('Đã lưu cột, thứ tự và độ rộng.');router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <p>Độ rộng từ 80 đến 600 px. Bảng rộng được cuộn trong vùng danh sách.</p>
 {order.map((key,index)=><div className="upgrade-column-row" key={key}><label className="upgrade-inline"><input type="checkbox" checked={visible.includes(key)} onChange={e=>{setVisible(e.target.checked?[...visible,key]:visible.filter(k=>k!==key));setSaved('');}}/>{columnLabels[key]}</label><label>Độ rộng {columnLabels[key]}<input type="number" min={80} max={600} step={1} value={widths[key]??(key==='name'?240:150)} onChange={e=>{setWidths({...widths,[key]:Number(e.target.value)});setSaved('');}}/></label><div className="upgrade-actions"><button type="button" className="button button--secondary" disabled={index===0} aria-label={'Đưa '+columnLabels[key]+' lên'} onClick={()=>move(index,-1)}>Lên</button><button type="button" className="button button--secondary" disabled={index===order.length-1} aria-label={'Đưa '+columnLabels[key]+' xuống'} onClick={()=>move(index,1)}>Xuống</button></div></div>)}
 <button className="button button--primary" disabled={pending||!visible.length}>{pending?'Đang lưu…':'Lưu lựa chọn cột'}</button>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form></details>;
}

type SavedFilter={id:string;name:string;value:Record<string,string>;version:number;shared:boolean;is_default:boolean};
export function EditFilterForm({filter}:{filter:SavedFilter}){
 const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 return <form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');const f=new FormData(e.currentTarget);try{await send('/api/crm/workspace/filter',{id:filter.id,name:f.get('name'),resource:'partners',value:{...filter.value,q:String(f.get('q')??'')},version:filter.version,shared:f.get('shared')==='on',isDefault:f.get('isDefault')==='on'});setSaved('Đã lưu bộ lọc.');router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <label>Tên bộ lọc<input name="name" required minLength={2} maxLength={80} defaultValue={filter.name}/></label><label>Từ khóa bộ lọc<input name="q" maxLength={120} defaultValue={filter.value.q??''}/></label><label className="upgrade-inline"><input type="checkbox" name="isDefault" defaultChecked={filter.is_default}/>Mặc định khi mở danh sách chưa có lọc</label><label className="upgrade-inline"><input type="checkbox" name="shared" defaultChecked={filter.shared}/>Dùng chung (quản trị/quản lý)</label><button disabled={pending} className="button button--primary">{pending?'Đang lưu…':'Lưu sửa bộ lọc'}</button>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form>;
}

type Bulk={id:string;items:{id:string;name:string;version:number;before:Record<string,unknown>;after:Record<string,unknown>}[]};
export function BulkPartnerForm({items}:{items:Organization[]}){
 const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[selected,setSelected]=useState<string[]>([]),[action,setAction]=useState('STAGE'),[preview,setPreview]=useState<Bulk|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const names:Record<string,string>={LEAD:'Tiềm năng',CONTACTED:'Đã liên hệ',ACTIVE:'Đang hoạt động',INACTIVE:'Ngừng chăm sóc'};
 const describe=(value:Record<string,unknown>)=>Object.entries(value).map(([key,v])=>key==='active'?(v?'Hoạt động':'Ngừng dùng'):names[String(v)]??String(v)).join(' · ');
 return <details className="work-disclosure"><summary>Thao tác hàng loạt có preview</summary><form className="work-form" onChange={()=>{setPreview(null);setSaved('');}} onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');const f=new FormData(e.currentTarget);try{setPreview(await send('/api/crm/governance/bulk-preview',{ids:selected,action,reason:f.get('reason'),...(action==='STAGE'?{stage:f.get('stage')}:{})}));}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <fieldset className="upgrade-columns"><legend>Chọn hồ sơ trên trang này</legend>{items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{item.name}</label>)}</fieldset>
 <label>Thao tác<select aria-label="Thao tác hàng loạt" value={action} onChange={e=>setAction(e.target.value)}><option value="STAGE">Đổi giai đoạn chăm sóc</option><option value="DEACTIVATE">Ngừng dùng hồ sơ</option><option value="ACTIVATE">Mở lại hồ sơ</option></select></label>{action==='STAGE'&&<label>Giai đoạn mới<select aria-label="Giai đoạn mới" name="stage">{Object.entries(names).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
 <label>Lý do thao tác<textarea aria-label="Lý do thao tác" name="reason" required minLength={3} maxLength={500}/></label><button className="button button--secondary" disabled={pending||!selected.length}>{pending?'Đang kiểm tra…':'Xem tác động trước khi áp dụng'}</button>
 {preview&&<section><h3>Preview {preview.items.length} hồ sơ</h3><p>Có hiệu lực 10 phút. Nếu quyền hoặc phiên bản đổi, toàn bộ đợt bị chặn và không ghi một phần.</p><ul className="work-task-list">{preview.items.map(item=><li key={item.id}><div><strong>{item.name}</strong><p>{describe(item.before)} → {describe(item.after)}</p></div></li>)}</ul><button type="button" className="button button--primary" disabled={pending} onClick={async()=>{if(busy.current)return;busy.current=true;setPending(true);setError('');try{const r=await send('/api/crm/governance/bulk-confirm',{id:preview.id});if(r.errors.length){setError('Không áp dụng: '+r.errors.map((x:{id:string;error:string})=>(preview.items.find(i=>i.id===x.id)?.name??x.id)+' · '+x.error).join('; '));}else{setSaved('Đã áp dụng '+r.applied+' hồ sơ.');setPreview(null);router.refresh();}}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>{pending?'Đang áp dụng…':'Xác nhận áp dụng đợt này'}</button></section>}
 {error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form></details>;
}

export function NotificationPreferencesForm({initial}:{initial:Pref}){
 const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const labels:Record<string,string>={TASK:'Công việc',ONBOARDING:'Xét duyệt hồ sơ',SUPPORT:'Hỗ trợ',SYSTEM:'Thông tin hệ thống'};
 return <form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');const f=new FormData(e.currentTarget),kinds=f.getAll('kinds');try{await send('/api/crm/workspace/preferences',{...initial,notificationKinds:kinds,taskNotifications:kinds.includes('TASK'),notificationChannels:f.getAll('channels'),quietStart:f.get('quietStart')===''?null:Number(f.get('quietStart')),quietEnd:f.get('quietEnd')===''?null:Number(f.get('quietEnd'))});setSaved('Đã lưu tùy chọn thông báo.');router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <fieldset className="upgrade-columns"><legend>Loại thông báo</legend>{Object.entries(labels).map(([value,label])=><label key={value}><input name="kinds" type="checkbox" value={value} defaultChecked={initial.notificationKinds.includes(value)&&(value!=='TASK'||initial.taskNotifications)}/>{label}</label>)}</fieldset><label className="upgrade-inline"><input name="channels" type="checkbox" value="IN_APP" defaultChecked={initial.notificationChannels.includes('IN_APP')}/>Trong ứng dụng</label>
 <div className="work-fields">{(['quietStart','quietEnd'] as const).map(key=><label key={key}>{key==='quietStart'?'Giờ bắt đầu yên lặng':'Giờ kết thúc yên lặng'}<select aria-label={key==='quietStart'?'Giờ bắt đầu yên lặng':'Giờ kết thúc yên lặng'} name={key} defaultValue={initial[key]??''}><option value="">Không đặt giờ</option>{Array.from({length:24},(_,hour)=><option value={hour} key={hour}>{String(hour).padStart(2,'0')}:00</option>)}</select></label>)}</div><p>Giờ Việt Nam. Thông báo trong khoảng yên lặng được giữ đến giờ kết thúc. Thông báo bảo mật là bắt buộc và được hiển thị ngay.</p><button className="button button--primary" disabled={pending}>{pending?'Đang lưu…':'Lưu tùy chọn thông báo'}</button>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form>;
}

export function FieldDefinitionForm({definition}:{definition?:FieldDefinition}){
 const router=useRouter(),busy=useRef(false),[kind,setKind]=useState(definition?.kind??'TEXT'),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 return <form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');const f=new FormData(e.currentTarget);try{await send('/api/crm/governance/field-definition',{...(definition?{id:definition.id}:{}),version:definition?.version??0,key:f.get('key'),label:f.get('label'),kind,options:kind==='ENUM'?String(f.get('options')).split('\n').map(v=>v.trim()).filter(Boolean):[],required:f.get('required')==='on',readRoles:f.getAll('readRoles'),writeRoles:f.getAll('writeRoles'),active:f.get('active')==='on'});setSaved('Đã lưu phiên bản định nghĩa; giá trị cũ được giữ.');router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <div className="work-fields"><label>Mã trường<input name="key" aria-label="Mã trường" required pattern="[a-z][a-z0-9_]{1,39}" maxLength={40} aria-describedby={'field-code-hint-'+(definition?.id??'new')} onInvalid={e=>e.currentTarget.setCustomValidity('Mã phải có 2–40 ký tự, bắt đầu bằng chữ Latin thường (a–z); chỉ dùng chữ Latin thường, số và dấu gạch dưới.')} onInput={e=>e.currentTarget.setCustomValidity('')} readOnly={!!definition} defaultValue={definition?.field_key}/><span className="work-help" id={'field-code-hint-'+(definition?.id??'new')}>2–40 ký tự, bắt đầu bằng chữ Latin thường (a–z); chỉ chữ Latin thường, số và dấu gạch dưới. Ví dụ: muc_tieu_thang. Không dùng mã cho mật khẩu, OTP hoặc token.</span></label><label>Tên hiển thị<input name="label" required minLength={2} maxLength={120} defaultValue={definition?.label}/></label><label>Kiểu dữ liệu<select aria-label="Kiểu dữ liệu" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries({TEXT:'Văn bản',NUMBER:'Số chính xác',DATE:'Ngày',BOOLEAN:'Có / không',ENUM:'Danh sách lựa chọn'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
 {kind==='ENUM'&&<label>Các lựa chọn (mỗi dòng một mục)<textarea aria-label="Các lựa chọn" name="options" required maxLength={5000} defaultValue={definition?.options.join('\n')}/></label>}<label className="upgrade-inline"><input name="required" type="checkbox" defaultChecked={definition?.required}/>Bắt buộc khi lưu giá trị</label><label className="upgrade-inline"><input name="active" type="checkbox" defaultChecked={definition?.active??true}/>Đang sử dụng</label>
 {(['readRoles','writeRoles'] as const).map(key=><fieldset className="upgrade-columns" key={key}><legend>{key==='readRoles'?'Vai trò được đọc':'Vai trò được sửa (phải có quyền đọc và hồ sơ)'}</legend>{roles.map(role=><label key={role}><input name={key} type="checkbox" value={role} defaultChecked={definition?(key==='readRoles'?definition.read_roles:definition.write_roles).includes(role):(key==='readRoles'?['ADMIN','MANAGER','SALES','ACCOUNTANT']:['ADMIN','MANAGER','SALES']).includes(role)}/>{roleLabels[role]}</label>)}</fieldset>)}
 <button className="button button--primary" disabled={pending}>{pending?'Đang lưu…':'Lưu định nghĩa trường'}</button>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form>;
}
export function CustomValueForm({organizationId,definition,value,version}:{organizationId:string;definition:FieldDefinition;value:unknown;version:number}){
 const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 return <form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');const f=new FormData(e.currentTarget);try{await send('/api/crm/governance/custom-value',{organizationId,fieldId:definition.id,definitionVersion:definition.version,version,value:definition.kind==='BOOLEAN'?f.get('value')==='on':f.get('value')===''&&!definition.required?null:f.get('value')});setSaved('Đã lưu giá trị.');router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <label>{definition.label}{definition.required?' *':''}{definition.kind==='ENUM'?<select aria-label={definition.label} name="value" required={definition.required} defaultValue={String(value??'')}><option value="">Chưa chọn</option>{definition.options.map(v=><option value={v} key={v}>{v}</option>)}</select>:<input name="value" type={definition.kind==='BOOLEAN'?'checkbox':definition.kind==='DATE'?'date':'text'} inputMode={definition.kind==='NUMBER'?'decimal':undefined} required={definition.required&&definition.kind!=='BOOLEAN'} defaultValue={definition.kind==='BOOLEAN'?undefined:String(value??'')} defaultChecked={definition.kind==='BOOLEAN'?Boolean(value):undefined} maxLength={1000}/>}</label><button className="button button--secondary" disabled={pending}>{pending?'Đang lưu…':'Lưu '+definition.label}</button>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form>;
}

type RolePreview={membershipVersion:number;account:string;previousRole:Role;nextRole:Role;activeSessions:string;effect:string;permissions:{scope:string;permissions:{key:string;label:string}[]}};
export function RoleChangeForm({id,role}:{id:string;role:Role}){
 const router=useRouter(),busy=useRef(false),[selected,setSelected]=useState<Role>(role),[pending,setPending]=useState(false),[preview,setPreview]=useState<RolePreview|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState('');
 return <form className="work-form" onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');try{setPreview(await send('/api/crm/governance/role-preview',{id,role:selected}));}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>
 <label>Vai trò mới<select aria-label="Vai trò mới" value={selected} onChange={e=>{setSelected(e.target.value as Role);setPreview(null);setSaved('');}}>{roles.filter(r=>r.startsWith('DEALER_')===role.startsWith('DEALER_')).map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></label><button className="button button--secondary" disabled={pending}>{pending?'Đang kiểm tra…':'Xem quyền và người bị ảnh hưởng'}</button>
 {preview&&<div><h3>{preview.account}</h3><p>{roleLabels[preview.previousRole]} → {roleLabels[preview.nextRole]} · {preview.activeSessions} phiên bị thu hồi.</p><p>{preview.effect} Các phân công khách/kho cũ sẽ được xóa; cần phân công lại.</p><p>Phạm vi mới: {preview.permissions.scope}</p><ul>{preview.permissions.permissions.map(p=><li key={p.key}>{p.label}</li>)}</ul><button className="button button--primary" disabled={pending} type="button" onClick={async()=>{if(busy.current)return;busy.current=true;setPending(true);setError('');try{await send('/api/crm/work/account',{id,data:{action:'role',role:preview.nextRole,expectedVersion:preview.membershipVersion}});setSaved('Đã đổi quyền và thu hồi phiên.');setPreview(null);router.refresh();}catch(err){setError((err as Error).message);}finally{busy.current=false;setPending(false);}}}>{pending?'Đang áp dụng…':'Áp dụng quyền đã xem'}</button></div>}
 {error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status" className="form-success">{saved}</p>}</form>;
}
