import Link from 'next/link';
import {inventoryAlerts,inventoryOperations,listInventory,listLocations,lotTrace,previewStockCount} from '@/lib/crm/inventory';
import {listCatalog,listWarehouses} from '@/lib/crm/repository';
import type {Principal} from '@/lib/crm/types';
import {AlertRuleForm,ApproveCountForm,LocationForm,ReceiptForm,RecallForm,RecordCountForm,ReverseDocumentForm,StartCountForm,TransferForm,TransferReceiptForm} from './InventoryForms';
function Header({title,description}:{title:string;description:string}){return <header className="portal-page-header"><div><h1>{title}</h1><p>{description}</p></div></header>;}
type Balance=Awaited<ReturnType<typeof listInventory>>[number];
type CountRow={id:string;code:string;status:string;version:number;warehouse_code:string;snapshot:Record<string,unknown>};
type TransferRow={id:string;code:string;status:string;version:number;source_code:string;destination_code:string;snapshot:{lines:{quantity:string}[]}};
type DocumentRow={id:string;code:string;kind:string;status:string;reference_type:string;reference_id:string;reason:string};
export async function InventoryPage({user,id}:{user:Principal;id?:string}){
 const [balances,locations,operations,alerts,warehouses,products]=await Promise.all([listInventory(user),listLocations(user),inventoryOperations(user),inventoryAlerts(user),listWarehouses(user),listCatalog(user)]),manager=user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role),writer=user.area==='crm'&&['ADMIN','MANAGER','WAREHOUSE'].includes(user.role),counts=operations.counts as unknown as CountRow[],transfers=operations.transfers as unknown as TransferRow[],documents=operations.documents as unknown as DocumentRow[];
 if(id?.startsWith('lot-')){const lotId=id.slice(4),trace=await lotTrace(user,lotId);return <><Link className="work-back" href={'/'+user.area+'/inventory'}>← Sổ kho</Link><Header title="Truy vết lô" description="Chứng từ, vị trí, đơn và lượng gắn với lô được đọc từ ledger bất biến."/><section className="work-section"><h2>Movement</h2><TraceTable rows={trace.movements as Record<string,unknown>[]}/></section><section className="work-section"><h2>Reservation và đơn liên quan</h2><TraceTable rows={trace.reservations as Record<string,unknown>[]}/></section></>};
 if(id?.startsWith('count-')){const count=counts.find(row=>row.id===id.slice(6));if(!count)return <p role="status">Phiếu kiểm kê không còn trong phạm vi quyền.</p>;const preview=count.status==='PREVIEW'?await previewStockCount(user,count.id):null;return <><Link className="work-back" href={'/'+user.area+'/inventory'}>← Sổ kho</Link><Header title={count.code} description={`Kiểm kê kho ${count.warehouse_code} · ${count.status} · phiên bản ${count.version}`}/>{count.status==='COUNTING'&&writer&&<RecordCountForm count={count} balances={balances as Balance[]}/>} {preview&&<section className="work-section"><h2>Preview chênh lệch</h2><p>Chênh lệch được tính tại thời điểm đếm rồi áp vào tồn hiện tại, vì vậy movement phát sinh trong lúc đếm không bị mất.</p><TraceTable rows={preview.differences as unknown as Record<string,unknown>[]}/>{manager&&<ApproveCountForm count={count}/>}</section>}</>};
 if(id)return <p role="status">Không tìm thấy chứng từ kho trong phạm vi quyền.</p>;
 return <><Header title="Kho, lô và tồn khả dụng" description="Tồn lấy từ movement đã ghi sổ; giữ hàng, lô bị khóa và vị trí ngừng dùng được tách khỏi khả dụng."/>
  <section className="work-section"><h2>Tồn theo kho, vị trí và lô</h2>{balances.length?<div className="work-table-wrap" tabIndex={0} aria-label="Tồn kho theo lô"><table className="work-table"><thead><tr><th>Kho / vị trí</th><th>SKU / lô</th><th>Hạn dùng</th><th>Thực tế</th><th>Đã giữ</th><th>Khả dụng</th></tr></thead><tbody>{balances.map(b=><tr key={b.location_id+b.lot_id}><td>{b.warehouse_code}/{b.location_code}</td><td>{b.sku}<br/><Link href={'/'+user.area+'/inventory/lot-'+b.lot_id}>{b.lot_code}</Link> · {b.lot_status}</td><td>{b.expires_on??'Không khai báo'}</td><td>{b.on_hand}</td><td>{b.reserved}</td><td>{b.available}</td></tr>)}</tbody></table></div>:<p className="crm-status-note">Chưa có movement nhập kho. Hệ thống không suy diễn tồn từ danh mục hoặc đơn đã xác nhận.</p>}</section>
  <section className="work-section"><h2>Kho và vị trí</h2><div className="work-table-wrap" tabIndex={0}><table className="work-table"><thead><tr><th>Kho</th><th>Tổ chức</th><th>Vị trí hoạt động</th></tr></thead><tbody>{warehouses.map(w=><tr key={w.id}><td>{w.code} · {w.name}</td><td>{w.organization_name}</td><td>{locations.filter(l=>l.warehouse_id===w.id&&l.active).map(l=>l.code).join(', ')||'Chưa cấu hình'}</td></tr>)}</tbody></table></div>{manager&&<details className="work-disclosure"><summary>Thêm vị trí kho</summary><LocationForm warehouses={warehouses}/></details>}</section>
  {writer&&<section className="work-section"><h2>Ghi sổ kho</h2><details className="work-disclosure"><summary>Nhập hàng thực nhận theo lô</summary><ReceiptForm locations={locations} products={products}/></details><details className="work-disclosure"><summary>Xuất chuyển kho hai bước</summary><TransferForm locations={locations} balances={balances as Balance[]}/></details><details className="work-disclosure"><summary>Mở kiểm kê</summary><StartCountForm warehouses={warehouses}/></details>{manager&&<><details className="work-disclosure"><summary>Thiết lập cảnh báo</summary><AlertRuleForm warehouses={warehouses} products={products}/></details><details className="work-disclosure"><summary>Khóa và thu hồi lô</summary><RecallForm balances={balances as Balance[]}/></details></>}</section>}
  <section className="work-section"><h2>Cảnh báo cần xử lý</h2>{alerts.length?<TraceTable rows={alerts as Record<string,unknown>[]}/>:<p className="crm-status-note">Không có ngưỡng thiếu hoặc cận hạn đang kích hoạt.</p>}</section>
  <section className="work-section"><h2>Chuyển kho đang xử lý</h2>{transfers.length?<>{transfers.map(t=><article className="work-card" key={t.id}><h3>{t.code}</h3><p>{t.source_code} → {t.destination_code} · {t.status}</p>{writer&&['IN_TRANSIT','PARTIAL'].includes(t.status)&&<TransferReceiptForm transfer={t}/>}</article>)}</>:<p>Chưa có phiếu chuyển.</p>}</section>
  <section className="work-section"><h2>Kiểm kê</h2>{counts.length?<ul className="work-list">{counts.map(c=><li key={c.id}><Link href={'/'+user.area+'/inventory/count-'+c.id}>{c.code}</Link> · {c.warehouse_code} · {c.status}</li>)}</ul>:<p>Chưa có phiếu kiểm kê.</p>}</section>
  <section className="work-section"><h2>Chứng từ và đảo sổ</h2>{documents.length?<>{documents.map(d=><details className="work-disclosure" key={d.id}><summary>{d.code} · {d.kind} · {d.status}</summary><p>{d.reference_type}: {d.reference_id}<br/>{d.reason}</p>{manager&&d.status==='POSTED'&&<ReverseDocumentForm id={d.id}/>}</details>)}</>:<p>Chưa có chứng từ kho.</p>}</section>
  <section className="work-section"><h2>Thu hồi lô</h2>{operations.recalls.length?<TraceTable rows={operations.recalls as Record<string,unknown>[]}/>:<p>Chưa có đợt thu hồi.</p>}</section>
 </>;
}
function TraceTable({rows}:{rows:Record<string,unknown>[]}){if(!rows.length)return <p>Chưa có dữ liệu.</p>;const keys=Object.keys(rows[0]).filter(k=>!['snapshot','result'].includes(k));return <div className="work-table-wrap" tabIndex={0}><table className="work-table"><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{keys.map(k=><td key={k}>{format(row[k])}</td>)}</tr>)}</tbody></table></div>;}
function format(value:unknown){if(value===null||value===undefined)return '—';if(typeof value==='object')return JSON.stringify(value);return String(value);}
