import Link from 'next/link';
import {database} from '@/lib/crm/db';
import {CrmError} from '@/lib/crm/permissions';
import {commercialProducts,commercialPartners} from '@/lib/crm/commercial-read';
import {commercialRequestAccess,listCommercialRequests,commercialRequestVersions,commercialTimeline,type CommercialRequest} from '@/lib/crm/order-requests';
import {salesOrderAccess,listSalesOrders,salesOrderVersions} from '@/lib/crm/sales-orders';
import {readOrderPolicy} from '@/lib/crm/order-policy';
import {reorderPreview} from '@/lib/crm/order-previews';
import {quotationAccess,quotationVersions} from '@/lib/crm/quotations';
import {getOrder} from '@/lib/crm/work';
import {cart,addresses} from '@/lib/crm/portal-services';
import type {Principal} from '@/lib/crm/types';
import {RequestForm,RequestActionForm,SalesActionForm,DuplicateForm,ExcelRequestForm,OrderPolicyForm,CalculationView} from './OrderForms';
const commercialMoney=(v:string)=>new Intl.NumberFormat('vi-VN').format(BigInt(v))+' VND';
const date=(v:string)=>new Intl.DateTimeFormat('vi-VN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(v));
const requestLabels:Record<string,string>={DRAFT:'Bản nháp',PENDING_OWNER:'Chờ chủ đại lý duyệt',READY:'Sẵn sàng gửi',REJECTED:'Chủ đại lý đã từ chối',SUBMITTED:'Đã gửi đến Cohamy'};
const orderLabels:Record<string,string>={PENDING_APPROVAL:'Chờ Cohamy xác nhận',CONFIRMED:'Đã xác nhận',REJECTED:'Đã từ chối',CANCELLED:'Đã hủy'};
const deliveryLabels:Record<string,string>={NOT_STARTED:'Chưa giao',PARTIAL:'Giao một phần',DELIVERED:'Đã giao',RETURNED:'Đã trả'};
const paymentLabels:Record<string,string>={UNBILLED:'Chưa lập công nợ',UNPAID:'Chưa thanh toán',PARTIAL:'Thanh toán một phần',PAID:'Đã thanh toán',REFUNDED:'Đã hoàn tiền'};
const channelLabels:Record<string,string>={PORTAL:'Portal đại lý',PHONE:'Điện thoại',VISIT:'Lần thăm',OTHER:'Khác',WEBSITE:'Website',QUOTATION:'Báo giá',REORDER:'Đặt lại',EXCEL:'Excel'};
const eventLabels:Record<string,string>={SAVED:'Lưu bản nháp',PROPOSED:'Đề nghị',OWNER_APPROVED:'Chủ đại lý duyệt',OWNER_REJECTED:'Chủ đại lý từ chối',SUBMITTED:'Gửi đến Cohamy',CREATED:'Cohamy tiếp nhận đơn',APPROVED:'Duyệt ngoại lệ',REJECTED:'Từ chối ngoại lệ',CONFIRMED:'Xác nhận đơn'};
function Header({title,description}:{title:string;description:string}){return <header className="portal-page-header"><div><h1>{title}</h1><p>{description}</p></div></header>;}
function Search({q,label='Tìm yêu cầu hoặc đối tác'}:{q:string;label?:string}){return <form className="work-filters"><label>{label}<input name="q" maxLength={120} defaultValue={q}/></label><button className="button button--secondary">Tìm</button></form>;}
function writer(user:Principal){return user.area==='portal'?['DEALER_OWNER','DEALER_STAFF'].includes(user.role):['ADMIN','MANAGER','SALES'].includes(user.role);}
function canEdit(user:Principal,h:CommercialRequest){return writer(user)&&h.status!=='SUBMITTED'&&(user.area==='crm'||user.role==='DEALER_OWNER'||h.creator_id===user.id);}
async function partnerChoices(user:Principal,query='',include?:string){if(user.area==='portal')return [{id:user.organizationId,name:user.organizationName}];const rows=await commercialPartners(user,query);if(include&&!rows.some(r=>r.id===include)){const {getOrganization}=await import('@/lib/crm/repository'),o=await getOrganization(user,include);rows.unshift({id:o.id,code:o.code,name:o.name,pricingVersion:0,tierName:null});}return rows;}
async function Timeline({user,type,id,versions}:{user:Principal;type:'request'|'order';id:string;versions:{id:string;number:number}[]}){const events=await commercialTimeline(user,type,id);return <section className="work-section"><h2>Lịch sử theo phiên bản</h2>{events.length?<ul className="work-timeline">{events.map(e=><li key={e.id}><strong>{eventLabels[e.action]??'Thao tác đã lưu'} · Bản {versions.find(v=>v.id===e.source_version_id)?.number??'đã lưu'}</strong><p>{e.actor_name} · {date(e.created_at)}</p><p>{e.reason}</p></li>)}</ul>:<p>Chưa có thao tác.</p>}</section>;}
export async function RequestsPage({user,id,query}:{user:Principal;id?:string;query:Record<string,string>}){
 const root='/'+user.area+'/requests',w=writer(user),self=user.area==='portal'?user.organizationId:undefined;
 if(id==='policy'){const p=await readOrderPolicy(user);return <><Link className="work-back" href={root}>← Yêu cầu mua hàng</Link><Header title="Quy tắc duyệt và xác nhận đơn" description="Lưu từng phiên bản quy tắc; kích hoạt khi Cohamy đã xác nhận chính sách."/><section className="work-section"><h2>{p.current?'Quy tắc hiện tại · Bản '+p.current.number:'Chưa có quy tắc được xác nhận'}</h2><OrderPolicyForm current={p.current}/></section><section className="work-section"><h2>Lịch sử quy tắc</h2>{p.versions.length?<ul className="work-timeline">{p.versions.map(v=><li key={v.id}><strong>Bản {v.number} · {v.definition.enabled?'Kích hoạt':'Chưa kích hoạt'}</strong><p>{date(v.created_at)} · {v.reason}</p></li>)}</ul>:<p>Chưa có phiên bản.</p>}</section></>;}
 if(id==='new'||id==='excel'){
  if(!w)throw new CrmError('FORBIDDEN',403);const products=id==='new'?await commercialProducts(user):[],partners=await partnerChoices(user,query.q??'');
  let source:Parameters<typeof RequestForm>[0]['source'];let before:Awaited<ReturnType<typeof reorderPreview>>|null=null;
  if(id==='new'&&query.reorder){before=await reorderPreview(user,query.reorder);source={channel:'REORDER',id:before.sourceOrderId,basket:before.basket,delivery:before.delivery,note:before.note};}
  if(id==='new'&&query.quotation){const h=await quotationAccess(await database(),user,query.quotation),v=(await quotationVersions(user,h.id)).find(v=>v.id===h.accepted_version_id);if(!v)throw new CrmError('QUOTE_NOT_ACCEPTED',409);source={channel:'QUOTATION',id:h.id,basket:v.snapshot.basket,delivery:v.snapshot.delivery,note:v.snapshot.note};if(user.area==='crm'){const choices=await partnerChoices(user,'',h.organization_id);partners.splice(0,partners.length,...choices.filter(p=>p.id===h.organization_id));}}
  if(id==='new'&&query.website){if(user.area!=='crm')throw new CrmError('FORBIDDEN',403);const h=await getOrder(user,query.website);source={channel:'WEBSITE',id:h.id};const choices=await partnerChoices(user,'',h.organization_id??undefined);partners.splice(0,partners.length,...choices.filter(p=>p.id===h.organization_id));}
  let seed:Parameters<typeof RequestForm>[0]['initialBasket'];if(id==='new'&&self&&query.cart==='1'){const data=await cart(user);if(data.lines.length)seed={lines:data.lines.map(l=>({sku:l.sku,unitCode:'BASE',quantity:String(l.quantity)})),discountBasisPoints:0,creditTerms:false};}
  return <><Link className="work-back" href={root}>← Yêu cầu mua hàng</Link><Header title={id==='excel'?'Nhập yêu cầu từ Excel':source?.channel==='REORDER'?'Kiểm tra và đặt lại':'Tạo yêu cầu mua hàng'} description="Lưu bản nháp, kiểm tra giá và điều kiện, rồi đề nghị và gửi đến Cohamy."/>{!self&&!source&&<Search q={query.q??''} label="Tìm đối tác cho biểu mẫu"/>}{before&&<section className="work-section"><h2>Điều kiện đơn cũ và hiện tại</h2><p>Đơn cũ {before.sourceCode}: {commercialMoney(before.before.total)}. Giá hiện tại: {commercialMoney(before.after.total)}.</p><p>{before.changed?'Giá hoặc điều kiện đã thay đổi. Kiểm tra từng dòng bên dưới.':'Giá và điều kiện tính hiện tại trùng với bản cũ.'}</p><details className="work-disclosure"><summary>Dòng hàng và giá của đơn cũ</summary><CalculationView calculation={before.before}/></details><h3>Dòng hàng theo giá hiện tại</h3><CalculationView calculation={before.after}/><p>Khả năng giao hàng cần được kiểm tra khi giữ tồn; bản nháp chưa giữ hàng.</p></section>}<div className="work-section">{id==='excel'?<ExcelRequestForm self={self} partners={partners}/>:<RequestForm products={products} partners={partners} self={self} source={source} initialBasket={seed} addresses={self?await addresses(user):[]}/>}</div></>;
 }
 if(id){const head=await commercialRequestAccess(await database(),user,id),versions=await commercialRequestVersions(user,id),selected=versions.find(v=>v.id===query.v)??versions[0],latest=versions[0],s=selected.snapshot,editable=canEdit(user,head),[products,partners]=editable?await Promise.all([commercialProducts(user),partnerChoices(user,'',head.organization_id)]):[[],[]];const actions:string[]=[];if(selected.id===head.latest_version_id&&head.status!=='SUBMITTED'){if(editable&&head.creator_id===user.id&&head.status==='DRAFT')actions.push('PROPOSE');if(user.area==='portal'&&user.role==='DEALER_OWNER'&&head.status==='PENDING_OWNER')actions.push('OWNER_APPROVE','OWNER_REJECT');}
  return <><Link className="work-back" href={root}>← Yêu cầu mua hàng</Link><Header title={head.code+' · '+head.organization_name} description={requestLabels[head.status]+' · '+channelLabels[head.channel]}/><form className="work-filters"><label>Xem phiên bản<select name="v" defaultValue={selected.id}>{versions.map(v=><option key={v.id} value={v.id}>Bản {v.number}{v.id===head.latest_version_id?' · Hiện tại':''}{v.id===head.owner_approved_version_id?' · Chủ đại lý đã duyệt':''}</option>)}</select></label><button className="button button--secondary">Xem bản đã chọn</button></form><section className="work-section"><h2>Bản {selected.number} · {date(selected.created_at)}</h2><CalculationView calculation={s.calculation}/><dl className="work-facts"><dt>Giao hàng</dt><dd>{s.delivery.recipient} · {s.delivery.phone}<br/>{s.delivery.address}</dd><dt>Hạn giá giữ</dt><dd>{date(s.validUntil)} (giờ Việt Nam)</dd><dt>Nguồn giá</dt><dd>{s.priceBook.name} · Bản {s.priceBook.number}</dd><dt>Ghi chú</dt><dd>{s.note||'Không có'}</dd></dl>{head.status==='SUBMITTED'&&<p>Đề nghị đã gửi đến Cohamy. Mở danh sách đơn để theo dõi xác nhận, giao hàng và thanh toán.</p>}</section>{selected.id===head.latest_version_id&&head.status!=='SUBMITTED'&&<section className="work-section"><h2>Kiểm tra trước khi đề nghị</h2><DuplicateForm organizationId={head.organization_id} basket={s.basket} area={user.area}/></section>}{actions.length>0&&<section className="work-section"><h2>Thao tác với bản hiện tại</h2><RequestActionForm head={head} actions={actions} area={user.area}/></section>}{editable&&head.status==='READY'&&selected.id===head.latest_version_id&&<section className="work-section"><h2>Gửi đề nghị đã kiểm tra</h2><RequestActionForm head={head} actions={[]} submit area={user.area}/></section>}<Timeline user={user} type="request" id={id} versions={versions}/>{editable&&<section className="work-section"><details className="work-disclosure"><summary>Sửa và tính lại giá trong bản mới</summary><p>Sửa đề nghị sẽ bỏ quyết định duyệt cũ và yêu cầu duyệt lại đúng bản mới.</p><RequestForm key={latest.id} products={products} partners={partners} self={self} head={head} latest={latest} addresses={self?await addresses(user):[]}/></details></section>}</>;
 }
 const rows=await listCommercialRequests(user,query.q??'');return <><Header title="Yêu cầu mua hàng" description={self?'Nhân viên đề nghị, chủ đại lý duyệt, rồi gửi đến Cohamy.':'Tiếp nhận từ điện thoại, lần thăm, website hoặc báo giá; kiểm tra trước khi tạo đơn bán.'}/><nav className="commercial-actions" aria-label="Thao tác yêu cầu">{w&&<><Link className="button button--primary" href={root+'/new'}>Tạo yêu cầu</Link><Link className="button button--secondary" href={root+'/excel'}>Nhập Excel</Link></>}{!self&&['ADMIN','MANAGER'].includes(user.role)&&<Link href={root+'/policy'}>Quy tắc duyệt đơn</Link>}<Link href={'/'+user.area+'/'+(self?'orders':'sales')}>Đơn bán</Link></nav><Search q={query.q??''}/><section className="work-section">{rows.length?<ul className="work-task-list">{rows.map(r=><li key={r.id}><div><Link href={root+'/'+r.id}>{r.code} · {r.organization_name}</Link><p>{requestLabels[r.status]} · {channelLabels[r.channel]} · {date(r.updated_at)}</p></div></li>)}</ul>:<p>Chưa có yêu cầu phù hợp.</p>}</section></>;
}
export async function SalesOrdersPage({user,id,query}:{user:Principal;id?:string;query:Record<string,string>}){
 const root='/'+user.area+'/'+(user.area==='portal'?'orders':'sales');if(id){const head=await salesOrderAccess(await database(),user,id),versions=await salesOrderVersions(user,id),selected=versions.find(v=>v.id===query.v)??versions.find(v=>v.id===(head.confirmed_version_id??head.latest_version_id))!,s=selected.snapshot;const actions:string[]=[],decisions=user.area==='crm'?await commercialTimeline(user,'order',id):[],approved=decisions.some(e=>e.action==='APPROVED'&&e.source_version_id===selected.id);if('definition' in s.orderPolicy&&user.area==='crm'&&head.status==='PENDING_APPROVAL'&&selected.id===head.latest_version_id){if(s.orderPolicy.definition.approvalRoles.includes(user.role as 'ADMIN'|'MANAGER')&&selected.approval_required&&!approved&&(!(s.orderPolicy.definition.nonSelfApproval||s.quote.policy?.approval.nonSelfApproval)||![head.creator_id,s.request.creatorId,selected.actor_id].includes(user.id)))actions.push('APPROVE','REJECT');if((!selected.approval_required||approved)&&s.orderPolicy.definition.confirmationRoles.includes(user.role as 'ADMIN'|'MANAGER'|'SALES'))actions.push('CONFIRM');}
  return <><Link className="work-back" href={root}>← Đơn bán</Link><Header title={head.code+' · '+head.organization_name} description="Theo dõi xác nhận, giao hàng và thanh toán riêng theo bản đã lưu."/><dl className="work-facts commercial-summary"><dt>Đơn bán</dt><dd>{orderLabels[head.status]}</dd><dt>Giao hàng</dt><dd>{deliveryLabels[head.delivery_status]}</dd><dt>Thanh toán</dt><dd>{paymentLabels[head.payment_status]}</dd><dt>Đề nghị nguồn</dt><dd><Link href={'/'+user.area+'/requests/'+s.request.id}>{s.request.code}</Link> · {channelLabels[s.request.channel]}</dd></dl><form className="work-filters"><label>Xem bản đơn<select name="v" defaultValue={selected.id}>{versions.map(v=><option key={v.id} value={v.id}>Bản {v.number}{v.id===head.confirmed_version_id?' · Đã xác nhận':''}</option>)}</select></label><button className="button button--secondary">Xem bản đã chọn</button></form><section className="work-section"><h2>Bản {selected.number} · {date(selected.created_at)}</h2><CalculationView calculation={s.quote.calculation} approvalNotice={false}/><dl className="work-facts"><dt>Giao hàng</dt><dd>{s.quote.delivery.recipient} · {s.quote.delivery.phone}<br/>{s.quote.delivery.address}</dd><dt>Hạn giá giữ</dt><dd>{date(s.quote.validUntil)} (giờ Việt Nam)</dd><dt>Ghi chú</dt><dd>{s.quote.note||'Không có'}</dd><dt>Nguồn giá</dt><dd>{s.quote.priceBook.name} · Bản {s.quote.priceBook.number}</dd></dl></section>{actions.length>0&&<section className="work-section"><h2>Xử lý bản đang chờ</h2><SalesActionForm head={head} version={selected} actions={actions}/></section>}{user.area==='crm'&&head.status==='PENDING_APPROVAL'&&selected.approval_required&&!approved&&<p role="status">Bản này cần người có quyền khác duyệt ngoại lệ trước khi xác nhận.</p>}<Timeline user={user} type="order" id={id} versions={versions}/>{writer(user)&&head.confirmed_version_id&&<Link className="button button--secondary" href={'/'+user.area+'/requests/new?reorder='+head.id}>Kiểm tra giá và đặt lại</Link>}</>;
 }
 const rows=await listSalesOrders(user,query.q??'');return <><Header title={user.area==='portal'?'Đơn của tôi':'Đơn bán'} description="Đơn được tạo từ đề nghị đã gửi. Xác nhận đơn, giao hàng và thanh toán có tiến độ riêng."/><Link className="button button--primary" href={'/'+user.area+'/requests'}>Mở yêu cầu mua hàng</Link><Search q={query.q??''} label="Tìm đơn hoặc đối tác"/><section className="work-section">{rows.length?<ul className="work-task-list">{rows.map(o=><li key={o.id}><div><Link href={root+'/'+o.id}>{o.code} · {o.organization_name}</Link><p>{orderLabels[o.status]} · {deliveryLabels[o.delivery_status]} · {paymentLabels[o.payment_status]}</p></div></li>)}</ul>:<p>Chưa có đơn phù hợp.</p>}</section></>;
}
