import Link from 'next/link';
import {library,getLibraryItem,onboardingChecklist} from '@/lib/crm/partner-library';
import {dealerMembers} from '@/lib/crm/dealer-members';
import {listOrganizationOptions} from '@/lib/crm/repository';
import type {Principal} from '@/lib/crm/types';
import {DataForm,ActionButton} from './UpgradeForms';
import {DocumentsPanel} from './UpgradePages';
const categories:Record<string,string>={CATALOGUE:'Catalogue',IMAGE:'Hình ảnh',GUIDE:'Hướng dẫn',POLICY:'Chính sách'};
const statuses:Record<string,string>={DRAFT:'Bản nháp',PUBLISHED:'Đã công bố',WITHDRAWN:'Đã thu hồi'};
const localDate=(s:string)=>{const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export async function LibraryPage({user,id,query}:{user:Principal;id?:string;query:Record<string,string>}){const admin=user.area==='crm',root='/'+user.area+'/library';if(id){const item=await getLibraryItem(user,id),orgs=admin?(await listOrganizationOptions(user)).filter(o=>o.kind==='DEALER'):[];return <><Link className="work-back" href={root}>← Thư viện đối tác</Link><header className="portal-page-header"><div><h1>{item.title}</h1><p>{categories[item.category]} · {statuses[item.status]}{item.required_read?' · '+(item.read_confirmed?'Đã xác nhận phiên bản hiện hành':'Cần xác nhận đã đọc'):''}</p></div></header>{admin&&<section className="work-section"><h2>Phạm vi và thời gian công bố</h2><DataForm key={item.version} url="/api/crm/library/save" context={{id,version:item.version}} fields={[{name:'title',label:'Tên tài liệu',required:true,value:item.title},{name:'category',label:'Loại tài liệu',type:'select',value:item.category,options:Object.entries(categories).map(([value,label])=>({value,label}))},{name:'audience',label:'Vai trò được đọc',type:'select',value:item.audience,options:[{value:'ALL_DEALERS',label:'Chủ và nhân viên đại lý'},{value:'DEALER_OWNER',label:'Chỉ chủ đại lý'},{value:'DEALER_STAFF',label:'Chỉ nhân viên đại lý'}]},{name:'organizationId',label:'Đơn vị được đọc',type:'select',value:item.organization_id??'',options:[{value:'',label:'Mọi đại lý trong vai trò đã chọn'},...orgs.map(o=>({value:o.id,label:o.name}))]},{name:'requiredRead',label:'Yêu cầu xác nhận đã đọc',type:'checkbox',value:item.required_read},{name:'status',label:'Trạng thái công bố',type:'select',value:item.status,options:Object.entries(statuses).map(([value,label])=>({value,label}))},{name:'effectiveAt',label:'Hiệu lực từ',type:'datetime-local',required:true,value:localDate(item.effective_at)},{name:'expiresAt',label:'Hết hiệu lực (không bắt buộc)',type:'datetime-local',value:item.expires_at?localDate(item.expires_at):''}]} label="Lưu phạm vi và trạng thái"/><p>Tải tệp ở bên dưới trước khi công bố. Khi đổi phiên bản tệp, xác nhận đọc của phiên bản trước vẫn được giữ.</p></section>}<DocumentsPanel user={user} type="library" id={id}/></>;}
const rows=await library(user,query);return <><header className="portal-page-header"><div><h1>Thư viện đối tác</h1><p>Tài liệu, hình ảnh và chính sách được công bố cho tài khoản của bạn.</p></div></header><form className="table-toolbar"><label>Tên tài liệu<input name="q" defaultValue={query.q??''}/></label><label>Loại tài liệu<select aria-label="Loại tài liệu" name="category" defaultValue={query.category??'ALL'}><option value="ALL">Tất cả</option>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="button button--primary">Lọc tài liệu</button></form><section className="work-section">{rows.length?<ul className="work-task-list">{rows.map(item=><li key={item.id}><div><Link href={root+'/'+item.id}>{item.title}</Link><p>{categories[item.category]}{admin?' · '+statuses[item.status]:''}{item.required_read?' · '+(item.read_confirmed?'Đã xác nhận phiên bản hiện hành':'Cần xác nhận đã đọc'):''}</p></div></li>)}</ul>:<p>Chưa có tài liệu phù hợp trong phạm vi của bạn.</p>}</section>{admin&&<section className="work-section"><h2>Tạo tài liệu nháp</h2><DataForm url="/api/crm/library/save" context={{version:0,status:'DRAFT',audience:'ALL_DEALERS',effectiveAt:new Date().toISOString()}} fields={[{name:'title',label:'Tên tài liệu',required:true},{name:'category',label:'Loại tài liệu',type:'select',options:Object.entries(categories).map(([value,label])=>({value,label}))},{name:'requiredRead',label:'Yêu cầu xác nhận đã đọc',type:'checkbox'}]} label="Tạo tài liệu nháp"/><p>Sau khi tạo, mở tài liệu để tải tệp và chọn đối tượng được đọc.</p></section>}</>;}
export async function DealerMembersPage({user}:{user:Principal}){const rows=await dealerMembers(user);return <><header className="portal-page-header"><div><h1>Nhân viên đại lý</h1><p>Quản lý nhân viên trong {user.organizationName}. Khóa nhân viên sẽ kết thúc phiên đăng nhập của họ.</p></div><Link className="button button--primary" href="/portal/invitations">Mời nhân viên</Link></header><section className="work-section"><ul className="work-task-list">{rows.map(m=><li key={m.id}><div><strong>{m.name}</strong><p>{m.email} · {m.role==='DEALER_OWNER'?'Chủ đại lý':'Nhân viên đại lý'} · {m.active?'Đang hoạt động':'Đã khóa'}</p>{m.role==='DEALER_STAFF'&&<p>Được xem danh mục và thông tin vận hành của đơn vị; quyền này không bao gồm quản lý tài khoản hoặc công nợ.</p>}</div>{m.role==='DEALER_STAFF'&&<ActionButton url="/api/crm/portal/member" data={{id:m.id,version:m.version,active:!m.active,role:'DEALER_STAFF'}} label={m.active?'Khóa nhân viên':'Mở lại nhân viên'}/>}</li>)}</ul></section></>;}
export async function OnboardingChecklist({user}:{user:Principal}){const c=await onboardingChecklist(user);return <section className="work-section"><h2>Bắt đầu sử dụng</h2><ul className="work-task-list"><li><Link href="/portal/profile">Thông tin đơn vị</Link><span>{c.profileComplete?'Đã hoàn thiện':'Cần hoàn thiện'}</span></li><li><Link href="/portal/goods">Xem danh mục sản phẩm</Link><span>{c.catalogSeen?'Đã xem':'Chưa xem'}</span></li>{c.policies.map(p=><li key={p.id}><Link href={'/portal/library/'+p.id}>{p.title}</Link><span>{p.read?'Đã đọc phiên bản hiện hành':'Cần đọc và xác nhận'}</span></li>)}<li><Link href="/portal/requests">Yêu cầu mua đầu tiên</Link><span>{c.commercialRequestCreated?'Đã gửi đến Cohamy':'Chưa gửi'}</span></li></ul><p className="work-help">Lưu giỏ hoặc bản nháp chưa hoàn tất mục yêu cầu đầu tiên. Mục này hoàn tất khi có đề nghị đã gửi đến Cohamy.</p></section>;}
