'use client';
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import type {Organization} from '@/lib/crm/types';
import type {MergeManifest} from '@/lib/crm/partner-merge';

import {PartnerMergeDetails,mergeLabels as labels} from './PartnerMergeDetails';
const errors:Record<string,string>={MERGE_BUSY:'Đang có thao tác trên dữ liệu. Đợi thao tác đó kết thúc rồi thử lại.',VERSION_CONFLICT:'Dữ liệu hoặc liên kết vừa thay đổi. Xem lại preview mới trước khi xác nhận.',MERGE_INVALID_PAIR:'Chọn hai hồ sơ đang hoạt động cùng loại và chưa được gộp.',MERGE_MEMBERSHIP_CONFLICT:'Có người dùng cùng vai trò trong cả hai tổ chức. Cần xử lý tài khoản trùng trước khi gộp.',PREVIEW_EXPIRED:'Preview đã quá 10 phút. Tạo lại trước khi xác nhận.',MERGE_LIMIT:'Liên kết vượt giới hạn của lần gộp này. Cần xử lý bằng đợt migration riêng.',FORBIDDEN:'Quyền hiện tại không cho phép gộp hồ sơ.'};
const path=(o:Pick<Organization,'id'|'kind'>)=>'/crm/'+(o.kind==='DEALER'?'dealers':o.kind==='SUPPLIER'?'suppliers':'customers')+'/'+o.id;
export function PartnerMergeForm({source,targets}:{source:Organization;targets:Pick<Organization,'id'|'name'|'kind'|'code'>[]}) {
  const router=useRouter(),busy=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{id:string;manifest:MergeManifest}|null>(null),[saved,setSaved]=useState('');
  async function run(action:'preview'|'confirm',data:unknown){if(busy.current)return;busy.current=true;setPending(true);setError('');setSaved('');try{const response=await fetch('/api/crm/partners/merge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})}),result=await response.json();if(!response.ok){if(response.status===401){router.replace('/crm/login');return;}if(action==='confirm')setPreview(null);setError(errors[result.error]??'Chưa gộp được hồ sơ. Dữ liệu chưa được xác nhận thay đổi.');return;}if(action==='preview')setPreview(result);else{setPreview(null);setSaved('Đã gộp và kết thúc các phiên đại lý liên quan.');router.push(path({id:result.id,kind:source.kind}));router.refresh();}}catch{setError('Mất kết nối. Kiểm tra lịch sử gộp trước khi gửi lại xác nhận.');}finally{busy.current=false;setPending(false);}}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),choices=Object.fromEntries(Object.keys(labels).map(field=>[field,String(data.get(field))]));void run('preview',{sourceId:source.id,targetId:data.get('targetId'),reason:data.get('reason'),choices});}
  return <details className="work-disclosure"><summary>Gộp hồ sơ trùng có preview</summary><p>Hồ sơ này sẽ trở thành bản lịch sử. Chọn hồ sơ giữ lại và kiểm tra toàn bộ tác động trước khi xác nhận.</p><form onSubmit={submit} onChange={()=>{setPreview(null);setSaved('');}}><div className="crm-form-grid"><label>Hồ sơ giữ lại<select name="targetId" aria-label="Hồ sơ giữ lại" required><option value="">Chọn hồ sơ cùng loại</option>{targets.map(t=><option key={t.id} value={t.id}>{t.name} · {t.code}</option>)}</select></label><label>Lý do gộp<textarea name="reason" required minLength={3} maxLength={1000}/></label>{Object.entries(labels).map(([field,label])=><label key={field}>{label}<select name={field} aria-label={label} defaultValue="TARGET"><option value="TARGET">Giữ từ hồ sơ đích</option><option value="SOURCE">Lấy từ {source.name}</option></select></label>)}</div><button className="button button--secondary" disabled={pending}>{pending?'Đang xử lý…':'Xem tác động gộp'}</button></form>{error&&<p role="alert" className="form-status form-status--error">{error}</p>}{saved&&<p role="status">{saved}</p>}{preview&&<section className="work-section"><h3>Preview: {preview.manifest.source.name} → {preview.manifest.target.name}</h3><p>Hạn 10 phút. Mã hồ sơ đích giữ nguyên. Dữ liệu hoặc liên kết thay đổi sẽ chặn toàn bộ lần gộp.</p><PartnerMergeDetails manifest={preview.manifest}/><p>Hai tổ chức đại lý trở thành cùng một phạm vi truy cập: tài khoản chuyển sang hồ sơ đích, các Sales được giữ; {preview.manifest.sessionCount} phiên đang hoạt động sẽ kết thúc. Tài khoản đăng nhập lại để nhận phạm vi mới. Link mời của hồ sơ nguồn bị thu hồi.</p><p>Tác giả, file, lượt đọc và chứng từ lịch sử được giữ. Chứng từ sổ đã chốt giữ nguyên nguồn và số tiền; gộp không ghi kho, công nợ hoặc thanh toán.</p><Link href={path(preview.manifest.target)}>Xem hồ sơ đích</Link><button type="button" className="button button--primary" disabled={pending} onClick={()=>void run('confirm',{id:preview.id})}>{pending?'Đang xử lý…':'Xác nhận toàn bộ lần gộp'}</button></section>}</details>;
}
