import {staffOptions} from '@/lib/crm/work';
import Link from 'next/link';
import {can} from '@/lib/crm/permissions';
import {addresses,cart,listTickets,getTicket,ticketMessages} from '@/lib/crm/portal-services';
import type {Principal} from '@/lib/crm/types';
import {DataForm} from './UpgradeForms';
import {TicketForm,CartForm} from './PortalServiceForms';
import {DocumentsPanel} from './UpgradePages';
const labels:Record<string,string>={OPEN:'Mới tạo',IN_PROGRESS:'Đang xử lý',WAITING_PARTNER:'Chờ đại lý phản hồi',RESOLVED:'Đã giải quyết'};
export async function SupportPage({user,id,query}:{user:Principal;id?:string;query:Record<string,string>}){if(id==='new'&&user.area==='portal')return <><header className="portal-page-header"><div><h1>Tạo phiếu hỗ trợ</h1><p>Gửi nội dung trước, rồi thêm ảnh hoặc tài liệu vào phiếu đã lưu.</p></div></header><section className="work-section"><TicketForm/></section></>;if(id){const t=await getTicket(user,id),messages=await ticketMessages(user,id),staff=user.area==='crm'&&can(user,'partners.write')?await staffOptions(user):[];return <><Link className="work-back" href={'/'+user.area+'/support'}>← Phiếu hỗ trợ</Link><header className="portal-page-header"><div><h1>{t.title}</h1><p>{labels[t.status]}</p></div></header><section className="work-section"><h2>Trao đổi</h2><ul className="work-timeline">{messages.map(m=><li key={m.id}><strong>{m.actor_name}{m.internal?' · Nội bộ':''}</strong><time>{new Date(m.created_at).toLocaleString('vi-VN')}</time><p>{m.body}</p></li>)}</ul>{(user.area==='portal'||can(user,'partners.write'))&&<TicketForm id={id} internalAllowed={user.area==='crm'}/>}</section><DocumentsPanel user={user} type="ticket" id={id}/>{user.area==='crm'&&can(user,'partners.write')&&<section className="work-section"><h2>Tiến độ xử lý</h2><DataForm url="/api/crm/portal/ticket-update" context={{id,version:t.version}} fields={[{name:'status',label:'Trạng thái',type:'select',value:t.status,options:Object.entries(labels).map(([value,label])=>({value,label}))},{name:'assigneeId',label:'Người phụ trách hỗ trợ',type:'select',value:t.assigned_to??'',options:[{value:'',label:'Chưa phân công'},...staff.filter(s=>['ADMIN','MANAGER','SALES'].includes(s.role)).map(s=>({value:s.id,label:s.name}))]}]} label="Cập nhật tiến độ"/></section>}</>;}
 const rows=await listTickets(user,query),page=Math.max(1,Number(query.page)||1);return <><header className="portal-page-header"><div><h1>Phiếu hỗ trợ</h1><p>Theo dõi yêu cầu hỗ trợ và phản hồi của Cohamy.</p></div>{user.area==='portal'&&<Link className="button button--primary" href="/portal/support/new">Tạo phiếu hỗ trợ</Link>}</header><form className="table-toolbar"><label>Chủ đề<input name="q" defaultValue={query.q??''}/></label><label>Trạng thái<select name="status" defaultValue={query.status??'ALL'}><option value="ALL">Tất cả</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="button button--primary">Lọc phiếu</button></form><section className="work-section">{rows.length?<ul className="work-task-list">{rows.map(t=><li key={t.id}><div><Link href={'/'+user.area+'/support/'+t.id}>{t.title}</Link><p>{labels[t.status]} · {new Date(t.created_at).toLocaleString('vi-VN')}</p></div></li>)}</ul>:<p>Chưa có phiếu hỗ trợ phù hợp.</p>}<nav className="upgrade-actions" aria-label="Phân trang hỗ trợ">{page>1&&<Link href={'?'+new URLSearchParams({...query,page:String(page-1)})}>Trang trước</Link>}{rows.length===20&&<Link href={'?'+new URLSearchParams({...query,page:String(page+1)})}>Trang sau</Link>}</nav></section></>;}
export async function AddressesPage({user}:{user:Principal}){const rows=await addresses(user),fields=(r?:typeof rows[number])=>[{name:'label',label:'Chi nhánh / tên địa chỉ',required:true,value:r?.label},{name:'recipient',label:'Người nhận',required:true,value:r?.recipient},{name:'phone',label:'Điện thoại',required:true,value:r?.phone},{name:'address',label:'Địa chỉ đầy đủ',type:'textarea' as const,required:true,value:r?.address},{name:'isDefault',label:'Địa chỉ mặc định',type:'checkbox' as const,value:r?.is_default},{name:'active',label:'Đang sử dụng',type:'checkbox' as const,value:r?.active??true}];return <><header className="portal-page-header"><div><h1>Địa chỉ giao hàng</h1><p>Quản lý người nhận và địa chỉ của đại lý.</p></div></header><section className="work-section">{rows.map(r=><details className="work-disclosure" key={r.id}><summary>{r.label}{r.is_default?' · Mặc định':''}{!r.active?' · Ngừng dùng':''}</summary>{user.role==='DEALER_OWNER'?<DataForm url="/api/crm/portal/address" context={{id:r.id,version:r.version}} fields={fields(r)}/>:<p>{r.recipient} · {r.phone}<br/>{r.address}</p>}</details>)}{user.role==='DEALER_OWNER'&&<details className="work-disclosure"><summary>Thêm địa chỉ</summary><DataForm url="/api/crm/portal/address" context={{version:0}} fields={fields()}/></details>}</section></>;}
export async function CartPage({user}:{user:Principal}){const data=await cart(user);return <><header className="portal-page-header"><div><h1>Giỏ hàng nháp</h1><p>Lưu SKU, số lượng và đơn vị để tiếp tục trên thiết bị khác.</p></div></header><section className="work-section"><p>Giỏ này chưa gửi thành đơn. Bảng giá và điều kiện thương mại cần được cấu hình trước khi xác nhận đặt hàng.</p><CartForm key={data.version} initial={data}/></section><Link href="/portal/goods">Xem SKU và đơn vị trong danh mục</Link></>;}
