'use client';
import {Form} from './CommercialForms';
const str=(f:FormData,k:string)=>String(f.get(k)??'');
type Supplier={organization_id:string;name:string;contact_email:string;version:number;terms_days:number;payable_enabled:boolean;active:boolean};
type Product={id:string;sku:string;name:string};
type Request={id:string;code:string;status:string;version:number};
type Rfq={id:string;code:string;request_id:string;status:string};
type Quote={id:string;rfq_id:string;supplier_id:string;supplier_name:string;status:string;snapshot:{totalAmount:string}};
type Order={id:string;code:string;status:string;version:number;supplier_id:string;supplier_name:string;expected_on:string;late_reason:string};
type Line={id:string;request_id?:string;order_id?:string;sku:string;name?:string;quantity:string;unit_price?:string;received?:string;rejected?:string};
type Location={id:string;warehouse_code:string;code:string;active:boolean};
type Receipt={id:string;code:string;order_id:string};
type ReceiptLine={id:string;receipt_id:string;sku:string;rejected:string};
type Payable={id:string;code:string;supplier_id:string;remaining_amount:string;status:string};
type Payment={id:string;code:string;supplier_id:string;status:string;version:number};
export function SupplierCreateForm(){return <Form endpoint="/api/crm/procurement/supplier-create" label="Tạo nhà cung cấp" payload={f=>({code:str(f,'code'),name:str(f,'name'),phone:str(f,'phone'),email:str(f,'email'),address:str(f,'address'),businessId:str(f,'businessId'),contactName:str(f,'contactName'),termsDays:Number(str(f,'termsDays')),payableEnabled:f.has('payableEnabled'),reason:str(f,'reason')})}><div className="work-fields"><label>Mã<input name="code" required pattern="([A-Za-z0-9_]|-)+"/></label><label>Tên<input name="name" required minLength={2}/></label><label>Người liên hệ<input name="contactName"/></label><label>Điện thoại<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>Mã doanh nghiệp<input name="businessId"/></label><label>Địa chỉ<input name="address"/></label><label>Kỳ hạn ngày<input name="termsDays" type="number" min={0} defaultValue={0}/></label><label>Lý do mở hồ sơ<input name="reason" required minLength={3}/></label></div><label className="work-check"><input name="payableEnabled" type="checkbox"/>Cho phép ghi phải trả từ phiếu nhận đã duyệt</label></Form>;}
export function RequestForm({products}:{products:Product[]}){return <Form endpoint="/api/crm/procurement/request-create" label="Tạo đề nghị mua" payload={f=>({neededOn:str(f,'neededOn'),lines:[{productId:str(f,'productId'),quantity:str(f,'quantity'),note:str(f,'note')}],reason:str(f,'reason')})}><div className="work-fields"><label>Ngày cần<input name="neededOn" type="date" required/></label><label>SKU<select name="productId" required><option value="">Chọn SKU</option>{products.map(p=><option value={p.id} key={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Số lượng gốc<input name="quantity" inputMode="decimal" required/></label><label>Ghi chú dòng<input name="note"/></label><label>Lý do nhu cầu<input name="reason" required minLength={3}/></label></div></Form>;}
export function RequestDecisionForm({request}:{request:Request}){return <Form endpoint="/api/crm/procurement/request-decide" label="Ghi quyết định" payload={f=>({id:request.id,version:request.version,decision:str(f,'decision'),reason:str(f,'reason')})}><div className="work-fields"><label>Quyết định<select name="decision"><option value="APPROVE">Duyệt</option><option value="REJECT">Từ chối</option></select></label><label>Lý do<input name="reason" required minLength={3}/></label></div></Form>;}
export function RfqForm({request,suppliers}:{request:Request;suppliers:Supplier[]}){return <Form endpoint="/api/crm/procurement/rfq-create" label="Mở yêu cầu báo giá" payload={f=>({requestId:request.id,deadline:new Date(str(f,'deadline')).toISOString(),supplierIds:f.getAll('supplierIds').map(String),reason:str(f,'reason')})}><label>Hạn phản hồi<input name="deadline" type="datetime-local" required/></label><fieldset><legend>Nhà cung cấp nhận yêu cầu</legend>{suppliers.filter(s=>s.active).map(s=><label className="work-check" key={s.organization_id}><input type="checkbox" name="supplierIds" value={s.organization_id}/>{s.name}</label>)}</fieldset><label>Lý do / nội dung gửi<input name="reason" required minLength={3}/></label><p>Yêu cầu được lưu nội bộ theo phiên bản. Kênh ngoài chưa cấu hình sẽ không tự gửi.</p></Form>;}
export function RfqDispatchForm({rfq,suppliers}:{rfq:Rfq;suppliers:Supplier[]}){return <Form endpoint="/api/crm/procurement/rfq-dispatch" label="Ghi nhận / gửi RFQ" payload={f=>{const supplier=suppliers.find(s=>s.organization_id===str(f,'supplierId'))!,channel=str(f,'channel');return {rfqId:rfq.id,supplierId:supplier.organization_id,channel,recipient:channel==='EMAIL'?supplier.contact_email:supplier.organization_id,reason:str(f,'reason')}}}><div className="work-fields"><label>Nhà cung cấp<select name="supplierId" required>{suppliers.filter(s=>s.active).map(s=><option value={s.organization_id} key={s.organization_id}>{s.name}</option>)}</select></label><label>Kênh<select name="channel"><option value="INTERNAL">Chỉ ghi nhận nội bộ</option><option value="EMAIL">Gửi email Brevo đã cấu hình</option></select></label><label>Nội dung / lý do gửi<input name="reason" required minLength={3}/></label></div><p>Email chỉ gửi đến địa chỉ đã lưu trong hồ sơ nhà cung cấp và chỉ khi kênh Brevo được bật.</p></Form>;}
export function QuoteForm({rfq,suppliers,requestLines}:{rfq:Rfq;suppliers:Supplier[];requestLines:Line[]}){const lines=requestLines.filter(l=>l.request_id===rfq.request_id);return <Form endpoint="/api/crm/procurement/quote-add" label="Lưu phản hồi nhà cung cấp" payload={f=>({rfqId:rfq.id,supplierId:str(f,'supplierId'),lines:[{requestLineId:str(f,'requestLineId'),quantity:str(f,'quantity'),unitPrice:str(f,'unitPrice'),expectedOn:str(f,'expectedOn'),feeAmount:str(f,'feeAmount')}],terms:str(f,'terms'),validUntil:str(f,'validUntil'),reason:str(f,'reason')})}><div className="work-fields"><label>Nhà cung cấp<select name="supplierId" required>{suppliers.map(s=><option value={s.organization_id} key={s.organization_id}>{s.name}</option>)}</select></label><label>Dòng nhu cầu<select name="requestLineId" required>{lines.map(l=><option value={l.id} key={l.id}>{l.sku} · cần {l.quantity}</option>)}</select></label><label>Lượng chào<input name="quantity" required inputMode="decimal"/></label><label>Đơn giá VND / đơn vị gốc<input name="unitPrice" required inputMode="numeric"/></label><label>Phí dòng VND<input name="feeAmount" defaultValue="0" required inputMode="numeric"/></label><label>Ngày giao hẹn<input name="expectedOn" type="date" required/></label><label>Hiệu lực đến<input name="validUntil" type="date" required/></label><label>Điều kiện<textarea name="terms" required/></label><label>Lý do ghi nhận<input name="reason" required minLength={3}/></label></div></Form>;}
export function SelectQuoteForm({quote}:{quote:Quote}){return <Form endpoint="/api/crm/procurement/quote-select" label="Chọn và tạo đơn mua" payload={f=>({quoteId:quote.id,expectedOn:str(f,'expectedOn'),selectionReason:str(f,'selectionReason')})}><div className="work-fields"><label>Ngày giao cam kết<input name="expectedOn" type="date" required/></label><label>Lý do lựa chọn<input name="selectionReason" required minLength={3}/></label></div></Form>;}
export function OrderDecisionForm({order}:{order:Order}){return <Form endpoint="/api/crm/procurement/order-decide" label="Duyệt đơn mua" payload={f=>({id:order.id,version:order.version,decision:str(f,'decision'),reason:str(f,'reason')})}><div className="work-fields"><label>Quyết định<select name="decision"><option value="APPROVE">Duyệt</option><option value="CANCEL">Hủy</option></select></label><label>Lý do<input name="reason" required minLength={3}/></label></div></Form>;}
export function OrderAmendForm({order,lines}:{order:Order;lines:Line[]}){const choices=lines.filter(l=>l.order_id===order.id);return <Form endpoint="/api/crm/procurement/order-amend" label="Lưu phụ lục đơn mua" payload={f=>({id:order.id,version:order.version,expectedOn:str(f,'expectedOn'),lateReason:str(f,'lateReason'),lines:choices.map(l=>({lineId:l.id,quantity:str(f,'quantity-'+l.id),unitPrice:str(f,'unitPrice-'+l.id)})),reason:str(f,'reason')})}><p>Dòng đã nhận một phần không được sửa đơn giá; lượng mới không thể thấp hơn tổng đã nhận và đã từ chối.</p><div className="work-fields"><label>Ngày giao mới<input name="expectedOn" type="date" defaultValue={String(order.expected_on).slice(0,10)} required/></label><label>Nguyên nhân trễ / thay đổi<input name="lateReason" defaultValue={order.late_reason}/></label>{choices.map(l=><div className="commercial-row" key={l.id}><strong>{l.sku}</strong><label>Lượng đặt<input name={'quantity-'+l.id} defaultValue={l.quantity} required inputMode="decimal"/></label><label>Đơn giá<input name={'unitPrice-'+l.id} defaultValue={l.unit_price} required inputMode="numeric"/></label><small>Đã nhận {l.received??'0'} · từ chối {l.rejected??'0'}</small></div>)}<label>Lý do lập phụ lục<input name="reason" required minLength={3}/></label></div></Form>;}
export function ReceiptForm({order,lines,locations}:{order:Order;lines:Line[];locations:Location[]}){const choices=lines.filter(l=>l.order_id===order.id);return <Form endpoint="/api/crm/procurement/receipt" label="Ghi thực nhận" payload={f=>({orderId:order.id,orderVersion:order.version,receivedAt:new Date(str(f,'receivedAt')).toISOString(),lines:[{orderLineId:str(f,'orderLineId'),accepted:str(f,'accepted'),rejected:str(f,'rejected'),rejectionReason:str(f,'rejectionReason'),locationId:str(f,'locationId'),lotCode:str(f,'lotCode'),manufacturedOn:str(f,'manufacturedOn')||null,expiresOn:str(f,'expiresOn')||null}],reason:str(f,'reason')})}><div className="work-fields"><label>Thời điểm nhận<input name="receivedAt" type="datetime-local" required/></label><label>Dòng đơn mua<select name="orderLineId" required>{choices.map(l=><option value={l.id} key={l.id}>{l.sku} · đặt {l.quantity} · đã xử lý {Number(l.received??0)+Number(l.rejected??0)}</option>)}</select></label><label>Chấp nhận<input name="accepted" defaultValue="0" required inputMode="decimal"/></label><label>Từ chối<input name="rejected" defaultValue="0" required inputMode="decimal"/></label><label>Lý do từ chối<input name="rejectionReason"/></label><label>Vị trí nhập<select name="locationId" required>{locations.filter(l=>l.active).map(l=><option value={l.id} key={l.id}>{l.warehouse_code}/{l.code}</option>)}</select></label><label>Mã lô<input name="lotCode" required/></label><label>Ngày sản xuất<input name="manufacturedOn" type="date"/></label><label>Hạn dùng<input name="expiresOn" type="date"/></label><label>Lý do ghi nhận<input name="reason" required minLength={3}/></label></div></Form>;}
export function ClaimForm({line}:{line:ReceiptLine}){return <Form endpoint="/api/crm/procurement/claim-create" label="Mở khiếu nại" payload={f=>({receiptLineId:line.id,quantity:str(f,'quantity'),reason:str(f,'reason'),documentVersionId:str(f,'documentVersionId')||null})}><div className="work-fields"><label>Số lượng khiếu nại<input name="quantity" required inputMode="decimal" max={line.rejected}/></label><label>ID tài liệu minh chứng<input name="documentVersionId"/></label><label>Lý do<input name="reason" required minLength={3}/></label></div></Form>;}
export function PayableForm({receipt}:{receipt:Receipt}){return <Form endpoint="/api/crm/procurement/payable-post" label="Ghi phải trả" payload={f=>({receiptId:receipt.id,reason:str(f,'reason')})}><label>Lý do / chứng từ<input name="reason" required minLength={3}/></label></Form>;}
export function SupplierPaymentForm({suppliers}:{suppliers:Supplier[]}){return <Form endpoint="/api/crm/procurement/payment-create" label="Tạo đề nghị trả" payload={f=>({supplierId:str(f,'supplierId'),amount:str(f,'amount'),reason:str(f,'reason')})}><div className="work-fields"><label>Nhà cung cấp<select name="supplierId" required>{suppliers.map(s=><option value={s.organization_id} key={s.organization_id}>{s.name}</option>)}</select></label><label>Số tiền<input name="amount" required inputMode="numeric"/></label><label>Lý do<input name="reason" required minLength={3}/></label></div></Form>;}
export function SupplierPaymentActionForm({payment,payables}:{payment:Payment;payables:Payable[]}){const action=payment.status==='PENDING'?'APPROVE':payment.status==='APPROVED'?'EXECUTE':payment.status==='EXECUTED'?'REVERSE':'';if(!action)return null;const choices=payables.filter(p=>p.supplier_id===payment.supplier_id&&BigInt(p.remaining_amount)>0n);return <Form endpoint="/api/crm/procurement/payment-act" label={action} payload={f=>({id:payment.id,version:payment.version,action,allocations:action==='EXECUTE'?[{payableId:str(f,'payableId'),amount:str(f,'amount')}]:[],reason:str(f,'reason')})}>{action==='EXECUTE'&&<div className="work-fields"><label>Khoản phải trả<select name="payableId" required>{choices.map(p=><option value={p.id} key={p.id}>{p.code} · còn {p.remaining_amount}</option>)}</select></label><label>Số tiền phân bổ<input name="amount" required inputMode="numeric"/></label></div>}<label>Lý do<input name="reason" required minLength={3}/></label></Form>;}
