import {procurementOperations,procurementOverview,supplierPerformance} from '@/lib/crm/procurement';
import {listCatalog} from '@/lib/crm/repository';
import {listLocations} from '@/lib/crm/inventory';
import type {Principal} from '@/lib/crm/types';
import {ClaimForm,OrderAmendForm,OrderDecisionForm,PayableForm,QuoteForm,ReceiptForm,RequestDecisionForm,RequestForm,RfqDispatchForm,RfqForm,SelectQuoteForm,SupplierCreateForm,SupplierPaymentActionForm,SupplierPaymentForm} from './ProcurementForms';
function Header(){return <header className="portal-page-header"><div><h1>Mua hàng và nhà cung cấp</h1><p>Nhu cầu, báo giá, đơn mua, thực nhận, khiếu nại và phải trả liên kết theo chứng từ nguồn.</p></div></header>;}
export async function ProcurementPage({user}:{user:Principal}){const [data,ops,products,locations]=await Promise.all([procurementOverview(user),procurementOperations(user),listCatalog(user),listLocations(user)]),manager=['ADMIN','MANAGER'].includes(user.role),accounting=['ADMIN','MANAGER','ACCOUNTANT'].includes(user.role),performance=await supplierPerformance(user),requestLines=ops.requestLines as never[],quotes=ops.quotes as never[],orderLines=ops.orderLines as never[],receiptLines=ops.receiptLines as never[],dispatches=ops.dispatches as {id:string;rfq_id:string;supplier_name:string;channel:string;status:string}[],amendments=ops.amendments as {id:string;order_id:string;number:number;reason:string}[];
 return <><Header/><section className="work-section"><h2>Nhà cung cấp</h2>{data.suppliers.length?<ul>{data.suppliers.map(s=><li key={s.organization_id}>{s.name} · kỳ hạn {s.terms_days} ngày · {s.payable_enabled?'được ghi phải trả':'chưa mở ghi phải trả'}</li>)}</ul>:<p>Chưa có nhà cung cấp.</p>}{manager&&<details className="work-disclosure"><summary>Thêm nhà cung cấp</summary><SupplierCreateForm/></details>}</section>
 <section className="work-section"><h2>Đề nghị mua</h2><details className="work-disclosure"><summary>Tạo nhu cầu</summary><RequestForm products={products}/></details>{data.requests.map(r=><article className="work-card" key={String(r.id)}><h3>{String(r.code)} · {String(r.status)}</h3>{manager&&r.status==='REQUESTED'&&<RequestDecisionForm request={r as never}/>} {r.status==='APPROVED'&&<RfqForm request={r as never} suppliers={data.suppliers}/>}</article>)}</section>
 <section className="work-section"><h2>Yêu cầu và báo giá nhà cung cấp</h2>{data.rfqs.map(r=><article className="work-card" key={String(r.id)}><h3>{String(r.code)} · {String(r.status)}</h3>{r.status==='OPEN'&&<><details className="work-disclosure"><summary>Ghi nhận hoặc gửi bản RFQ</summary><RfqDispatchForm rfq={r as never} suppliers={data.suppliers}/></details><QuoteForm rfq={r as never} suppliers={data.suppliers} requestLines={requestLines}/></>} {dispatches.filter(d=>d.rfq_id===r.id).map(d=><p key={d.id}>Đã gửi/ghi nhận: {d.supplier_name} · {d.channel} · {d.status}</p>)} {quotes.filter((q:{rfq_id:string})=>q.rfq_id===r.id).map((q:{id:string;supplier_name:string;status:string;snapshot:{totalAmount:string}})=><details className="work-disclosure" key={q.id}><summary>{q.supplier_name} · {q.snapshot.totalAmount} VND · {q.status}</summary>{manager&&q.status==='RECEIVED'&&<SelectQuoteForm quote={q as never}/>}</details>)}</article>)}</section>
 <section className="work-section"><h2>Đơn mua và thực nhận</h2>{data.orders.map(o=><article className="work-card" key={String(o.id)}><h3>{String(o.code)} · {String(o.supplier_name)} · {String(o.status)}</h3><p>Hẹn {String(o.expected_on).slice(0,10)} · tổng snapshot {String(o.total_amount)} VND {o.late_reason?`· ${String(o.late_reason)}`:''}</p>{manager&&o.status==='PENDING_APPROVAL'&&<OrderDecisionForm order={o as never}/>} {manager&&['APPROVED','PARTIAL'].includes(String(o.status))&&<details className="work-disclosure"><summary>Lập phụ lục thay đổi có kiểm soát</summary><OrderAmendForm order={o as never} lines={orderLines}/></details>} {['APPROVED','PARTIAL'].includes(String(o.status))&&<ReceiptForm order={o as never} lines={orderLines} locations={locations}/>} {amendments.filter(a=>a.order_id===o.id).map(a=><p key={a.id}>Phụ lục {a.number} · {a.reason}</p>)}</article>)}</section>
 <section className="work-section"><h2>Phiếu nhận và khiếu nại</h2>{data.receipts.map(r=><details className="work-disclosure" key={String(r.id)}><summary>{String(r.code)} · {String(r.order_code)} · {String(r.status)}</summary>{accounting&&<PayableForm receipt={r as never}/>} {receiptLines.filter((l:{receipt_id:string;rejected:string})=>l.receipt_id===r.id&&Number(l.rejected)>0).map((l:{id:string;sku:string;rejected:string})=><ClaimForm key={l.id} line={l as never}/>)}</details>)}</section>
 <section className="work-section"><h2>Phải trả nhà cung cấp</h2>{data.payables.map(p=><p key={String(p.id)}>{String(p.code)} · {String(p.supplier_name)} · còn {String(p.remaining_amount)} VND · {String(p.status)}</p>)}{accounting&&<details className="work-disclosure"><summary>Tạo đề nghị thanh toán</summary><SupplierPaymentForm suppliers={data.suppliers}/></details>}{data.payments.map(p=><article className="work-card" key={String(p.id)}><h3>{String(p.code)} · {String(p.supplier_name)} · {String(p.status)}</h3>{accounting&&<SupplierPaymentActionForm payment={p as never} payables={data.payables as never}/>}</article>)}</section>
 <section className="work-section"><h2>Đánh giá từ chứng từ 365 ngày</h2>{performance.map(p=><p key={p.supplier_id}>{p.supplier_name} · {p.receipts} đợt nhận · đúng hạn {p.on_time} · nhận {p.accepted}, lỗi {p.rejected}</p>)}</section></>;
}
