"use client";
import { useRouter } from "next/navigation";
import { useRef, useState, useEffect, type FormEvent } from "react";
import Link from "next/link";
import { roleLabels, roles, type Organization, type OrganizationKind } from "@/lib/crm/types";
import { stages } from '@/lib/crm/work-types';
const errors:Record<string,string>={INVALID_FIELDS:"Kiểm tra mã, tên, email và các trường bắt buộc.",DUPLICATE_RECORD:"Mã hoặc email đã tồn tại. Dùng mã khác.",VERSION_CONFLICT:"Có người vừa cập nhật hồ sơ. Tải lại trang trước khi lưu.",FORBIDDEN:"Bạn không có quyền thực hiện thao tác này.",ROLE_ORGANIZATION_MISMATCH:"Vai trò nội bộ phải thuộc Cohamy; vai trò đại lý phải thuộc tổ chức đại lý.",INVALID_WAREHOUSE_OWNER:"Kho phải thuộc tổ chức Cohamy hoặc đại lý đang hoạt động."};
export function RecordForm({resource,kind,record,organizations=[]}:{resource:"partners"|"warehouses"|"accounts";kind?:OrganizationKind;record?:Organization;organizations?:Pick<Organization,"id"|"name"|"kind">[]}) {
  const router=useRouter();const busy=useRef(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");
  const [identifiers,setIdentifiers]=useState({phone:record?.phone??'',email:record?.email??'',businessId:record?.business_id??''});
  const [duplicates,setDuplicates]=useState<{id:string;name:string;code:string;kind:string;matches:string[]}[]>([]);
  const [duplicateState,setDuplicateState]=useState<'idle'|'checking'|'checked'|'error'>(Object.values(identifiers).some(v=>v.trim())?'checking':'idle');
  useEffect(()=>{if(resource!=='partners')return;if(!Object.values(identifiers).some(v=>v.trim()))return;
    const controller=new AbortController();let current=true;
    const timer=setTimeout(async()=>{try{const response=await fetch('/api/crm/partners/duplicates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...identifiers,...(record?{excludeId:record.id}:{})}),signal:controller.signal});if(!response.ok)throw new Error();const result=await response.json();if(current){setDuplicates(result.items);setDuplicateState('checked');}}catch{if(current&&!controller.signal.aborted)setDuplicateState('error');}},450);
    return()=>{current=false;clearTimeout(timer);controller.abort();};
  },[identifiers,resource,record]);
  async function submit(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setError("");
    const form=new FormData(event.currentTarget);const data=Object.fromEntries(form.entries());
    const input:Record<string,unknown>={...data};
    if(resource==="partners"){input.kind=record?.kind ?? kind;if(record){input.version=record.version;input.active=form.get("active")==="on";}}
    try {const response=await fetch(`/api/crm/${resource}${record?`/${record.id}`:""}`,{method:record?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const result=await response.json();if(!response.ok){if(response.status===401){router.replace("/crm/login");return;}setError(errors[result.error]||"Chưa lưu được dữ liệu. Kiểm tra kết nối rồi thử lại.");return;}
      const target=resource==="partners"?(kind==="CUSTOMER"||record?.kind==="CUSTOMER"?"customers":"dealers"):resource==="warehouses"?"inventory":"accounts";
      router.push(`/crm/${target}`);router.refresh();
    }catch{setError("Không kết nối được server. Dữ liệu chưa được xác nhận lưu.");}finally{busy.current=false;setPending(false);}
  }
  return <form className="crm-record-form form-card" onSubmit={submit} onChange={event=>{if(resource!=="partners"||!["phone","email","businessId"].includes((event.target instanceof HTMLInputElement?event.target.name:"")))return;const form=new FormData(event.currentTarget);const next={phone:String(form.get("phone")??""),email:String(form.get("email")??""),businessId:String(form.get("businessId")??"")};setIdentifiers(next);setDuplicates([]);setDuplicateState(Object.values(next).some(v=>v.trim())?"checking":"idle");}}><div className="crm-form-grid">
    {resource!=="accounts"&&<><div className="field"><label htmlFor="record-code">Mã</label><input id="record-code" name="code" required minLength={2} maxLength={40} pattern="([A-Za-z0-9_]|-)+" defaultValue={record?.code} /></div><div className="field"><label htmlFor="record-name">Tên {resource==="warehouses"?"kho":"hồ sơ"}</label><input id="record-name" name="name" required minLength={2} maxLength={200} defaultValue={record?.name}/></div></>}
    {resource==="partners"&&<><div className="field"><label htmlFor="record-business-id">Mã doanh nghiệp / mã số thuế</label><input id="record-business-id" name="businessId" maxLength={40} pattern="([A-Za-z0-9 ._]|-)*" defaultValue={record?.business_id}/></div><div className="field"><label htmlFor="record-phone">Điện thoại</label><input id="record-phone" name="phone" type="tel" maxLength={40} defaultValue={record?.phone}/></div><div className="field"><label htmlFor="record-email">Email</label><input id="record-email" name="email" type="email" defaultValue={record?.email}/></div><div className="field"><label htmlFor="record-address">Địa chỉ</label><textarea id="record-address" name="address" maxLength={500} defaultValue={record?.address}/></div>{record&&<label><input type="checkbox" name="active" defaultChecked={record.active}/> Đang hoạt động</label>}</>}
    {resource==="accounts"&&<><div className="field"><label htmlFor="account-name">Tên hiển thị</label><input id="account-name" name="displayName" required minLength={2} maxLength={120}/></div><div className="field"><label htmlFor="account-email">Email</label><input id="account-email" name="email" type="email" required/></div><div className="field"><label htmlFor="account-password">Mật khẩu ban đầu (12–72 ký tự)</label><input id="account-password" name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={72}/></div><div className="field"><label htmlFor="account-role">Vai trò</label><select id="account-role" name="role">{roles.map(role=><option key={role} value={role}>{roleLabels[role]}</option>)}</select></div></>}
    {resource!=="partners"&&<div className="field"><label htmlFor="record-org">Tổ chức sở hữu</label><select id="record-org" name="organizationId" required><option value="">Chọn tổ chức</option>{organizations.filter(org=>["COHAMY","DEALER"].includes(org.kind)).map(org=><option value={org.id} key={org.id}>{org.name} ({org.kind==="COHAMY"?"Cohamy":"Đại lý"})</option>)}</select></div>}
    {resource==="partners"&&<><div className="field"><label htmlFor="contact-name">Người liên hệ</label><input id="contact-name" name="contactName" maxLength={120} defaultValue={record?.contact_name}/></div><div className="field"><label htmlFor="partner-source">Nguồn khách</label><input id="partner-source" name="source" maxLength={120} placeholder="Website, giới thiệu, hội chợ…" defaultValue={record?.source}/></div><div className="field"><label htmlFor="partner-segment">Nhóm khách</label><input id="partner-segment" name="segment" maxLength={120} placeholder="Bán lẻ, siêu thị, quà tặng…" defaultValue={record?.segment}/></div><div className="field"><label htmlFor="partner-stage">Giai đoạn</label><select id="partner-stage" name="stage" defaultValue={record?.stage??"ACTIVE"}>{Object.entries(stages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div></>}
  </div>{resource==='partners'&&<div aria-live="polite">{duplicateState==='checking'&&<p>Đang kiểm tra thông tin trùng…</p>}{duplicateState==='error'&&<p role="alert">Chưa kiểm tra được thông tin trùng. Thử sửa lại trường liên hệ để kiểm tra.</p>}{duplicateState==='checked'&&duplicates.length>0&&<div className="crm-status-note"><strong>Có hồ sơ trùng thông tin đã nhập</strong><p>Kiểm tra các hồ sơ dưới đây trước khi lưu. Cảnh báo không tự gộp hoặc xóa hồ sơ.</p><ul>{duplicates.map(d=><li key={d.id}><Link href={'/crm/'+(d.kind==='DEALER'?'dealers':d.kind==='SUPPLIER'?'suppliers':'customers')+'/'+d.id}>{d.name} · {d.code}</Link> — {d.matches.map(m=>({phone:'điện thoại',email:'email',businessId:'mã doanh nghiệp'}[m])).join(', ')}</li>)}</ul></div>}</div>}{error&&<p className="form-status form-status--error" role="alert">{error}</p>}<div className="crm-form-actions"><button className="button button--primary" type="submit" disabled={pending}>{pending?"Đang lưu...":"Lưu dữ liệu"}</button><Link className="button button--secondary" href="/crm">Về trang chủ</Link></div></form>;
}
export function AccountToggle({id,active,self}:{id:string;active:boolean;self:boolean}) {
  const router=useRouter();const [pending,setPending]=useState(false);const [error,setError]=useState("");
  async function toggle(){setPending(true);setError("");try{const response=await fetch(`/api/crm/accounts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!active})});if(!response.ok)throw new Error();router.refresh();}catch{setError("Chưa đổi được trạng thái.");}finally{setPending(false);}}
  return <><button className="button button--secondary" disabled={pending||self} onClick={toggle}>{self?"Phiên của bạn":pending?"Đang xử lý...":active?"Khóa quyền truy cập":"Mở quyền truy cập"}</button>{error&&<p role="alert">{error}</p>}</>;
}
