import Link from 'next/link';
import {defaultReportFilters,operationalReports,reportSubscriptions} from '@/lib/crm/reports';
import type {Principal} from '@/lib/crm/types';
import {ReportSubscriptionForm} from './ReportForms';
const money=(v:string|null)=>v===null?'Chưa đủ giá vốn':BigInt(v).toLocaleString('vi-VN')+' đ';
const date=(v:string|null)=>v?new Date(v).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa có mốc';
const Empty=({children}:{children:React.ReactNode})=><p className="crm-status-note" role="status">{children}</p>;
export async function OperationalReportsPage({user,query}:{user:Principal;query:Record<string,string>}){const defaults=await defaultReportFilters(),filters={from:query.from??defaults.from,to:query.to??defaults.to,inactivityDays:Math.max(1,Math.min(730,Number(query.inactivityDays)||60)),...(query.organizationId?{organizationId:query.organizationId}:{}),...(query.sku?{sku:query.sku}: {})},[data,schedules]=await Promise.all([operationalReports(user,filters),reportSubscriptions(user)]);
 return <><header className="portal-page-header"><div><h1>Báo cáo vận hành</h1><p>Bán hàng, giao nhận, kho, tài chính và chất lượng được tách theo chứng từ nguồn và phạm vi quyền.</p></div></header><form className="table-toolbar" method="get"><label>Từ ngày<input name="from" type="date" required defaultValue={filters.from}/></label><label>Đến ngày<input name="to" type="date" required defaultValue={filters.to}/></label><label>Ngưỡng giảm hoạt động (ngày)<input name="inactivityDays" type="number" min={1} max={730} defaultValue={filters.inactivityDays}/></label><label>SKU chính xác<input name="sku" maxLength={80} defaultValue={filters.sku??''}/></label><button className="button button--primary">Áp dụng kỳ báo cáo</button></form>
 <details className="work-disclosure"><summary>Định nghĩa và nguồn số liệu</summary><dl className="crm-readonly">{Object.entries(data.definitions).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>
 <section className="work-section"><div className="work-section-title"><h2>Nguồn khách và chuyển đổi</h2><Link href="/crm/dealers">Mở hồ sơ đại lý →</Link></div>{data.sourceConversion.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Nguồn và chuyển đổi"><table className="data-table"><thead><tr><th>Nguồn</th><th>Hồ sơ</th><th>Có đơn xác nhận</th><th>Tỷ lệ</th></tr></thead><tbody>{data.sourceConversion.map(r=><tr key={r.source}><td>{r.source}</td><td>{r.partners}</td><td>{r.converted}</td><td>{r.rate===null?'Chưa có mẫu số':r.rate+'%'}</td></tr>)}</tbody></table></div>:<Empty>Chưa có hồ sơ tạo trong kỳ và phạm vi đã chọn.</Empty>}</section>
 <section className="work-section"><h2>Giai đoạn bán và lý do mất</h2>{data.stages.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Giai đoạn cơ hội"><table className="data-table"><thead><tr><th>Giai đoạn</th><th>Số cơ hội</th><th>Ngày trung bình ở giai đoạn</th><th>Lý do mất</th></tr></thead><tbody>{data.stages.map((r,i)=><tr key={r.stage+r.lost_reason+i}><td>{r.stage}</td><td>{r.records}</td><td>{r.average_days}</td><td>{r.lost_reason||'Không áp dụng'}</td></tr>)}</tbody></table></div>:<Empty>Chưa có cơ hội trong phạm vi báo cáo.</Empty>}</section>
 <section className="work-section"><h2>Đại lý mới hoặc giảm hoạt động</h2>{data.dealerActivity.length?<ul className="work-task-list">{data.dealerActivity.map(r=><li key={r.id}><div><Link href={'/crm/dealers/'+r.id}>{r.name}</Link><p>{r.region} · {r.activity_state==='NO_ORDERS'?'Chưa có đơn xác nhận':r.activity_state==='DECLINING'?'Giảm hoạt động':'Mới trong kỳ'} · đơn gần nhất {date(r.last_order_at)}</p></div></li>)}</ul>:<Empty>Không có đại lý mới hoặc giảm hoạt động theo ngưỡng.</Empty>}</section>
 <section className="work-section"><h2>Bán hàng và biên lợi nhuận theo chứng từ giao</h2>{!data.marginComplete&&<p className="crm-status-note">Một hoặc nhiều SKU thiếu giá vốn từ thực nhận nhà cung cấp; biên lợi nhuận được để trống cho đúng dữ liệu.</p>}{data.sales.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Bán hàng theo SKU đại lý vùng và sales"><table className="data-table"><thead><tr><th>SKU</th><th>Đại lý</th><th>Vùng</th><th>Sales</th><th>Lượng ròng</th><th>Trả</th><th>Tiền dòng giao</th><th>Giá vốn</th><th>Biên</th></tr></thead><tbody>{data.sales.map((r,i)=><tr key={r.sku+r.organization+r.sales+i}><td>{r.sku}</td><td>{r.organization}</td><td>{r.region}</td><td>{r.sales}</td><td>{r.quantity}</td><td>{r.returned}</td><td>{money(r.net)}</td><td>{money(r.cost)}</td><td>{money(r.margin)}</td></tr>)}</tbody></table></div>:<Empty>Chưa có lượng giao thực tế trong kỳ.</Empty>}</section>
 <section className="work-section"><h2>Tốc độ xử lý đơn</h2>{data.speed.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Tốc độ xử lý đơn"><table className="data-table"><thead><tr><th>Đơn</th><th>Chờ xác nhận</th><th>Chờ tạo giao</th><th>Soạn/đóng</th><th>Vận chuyển</th></tr></thead><tbody>{data.speed.map(r=><tr key={r.order_id}><td><Link href={'/crm/sales/'+r.order_id}>{r.code}</Link></td>{[r.approvalMinutes,r.stockMinutes,r.packingMinutes,r.deliveryMinutes].map((v,i)=><td key={i}>{v===null?'Đang chờ mốc':v+' phút'}</td>)}</tr>)}</tbody></table></div>:<Empty>Chưa có đơn trong kỳ.</Empty>}</section>
 <section className="work-section"><h2>Tồn lâu, cận hạn và vòng quay</h2>{data.inventory.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Tồn kho phân loại"><table className="data-table"><thead><tr><th>Kho/vị trí</th><th>SKU/lô</th><th>Thực</th><th>Giữ</th><th>Khả dụng</th><th>Ký gửi</th><th>Hạn dùng</th><th>Movement gần nhất</th></tr></thead><tbody>{data.inventory.map((r,i)=><tr key={r.warehouse+r.sku+r.lot_code+i}><td>{r.warehouse} · {r.location_kind}</td><td>{r.sku}/{r.lot_code}</td><td>{r.on_hand}</td><td>{r.reserved}</td><td>{r.available}</td><td>{r.consigned}</td><td>{r.expires_on??'Chưa ghi nhận'} · ngưỡng {r.near_expiry_days} ngày</td><td>{date(r.last_movement_at)} · chậm {r.slow_days} ngày</td></tr>)}</tbody></table></div>:<Empty>Chưa có số dư sổ kho trong phạm vi.</Empty>}</section>
 <section className="work-section"><h2>Đổi trả, giao thất bại và chất lượng</h2>{data.quality.length?<div className="crm-table-wrap" tabIndex={0} role="region" aria-label="Chất lượng giao nhận"><table className="data-table"><thead><tr><th>SKU/lô</th><th>Đã giao</th><th>Đã nhận trả</th><th>Chuyến thất bại</th><th>Nguyên nhân</th></tr></thead><tbody>{data.quality.map(r=><tr key={r.sku+r.lot_code}><td>{r.sku}/{r.lot_code}</td><td>{r.delivered}</td><td>{r.returned}</td><td>{r.failed_deliveries}</td><td>{r.reasons||'Chưa ghi nhận'}</td></tr>)}</tbody></table></div>:<Empty>Chưa có dữ liệu giao/đổi trả trong kỳ.</Empty>}</section>
 <section className="work-section"><h2>Tổng hợp định kỳ</h2><p className="work-help">Lịch giữ bộ lọc hiện tại. Worker kiểm tra quyền lại lúc chạy; cùng lịch/cùng kỳ chỉ tạo một kết quả.</p><ReportSubscriptionForm userId={user.id} email={user.email} filters={filters}/>{schedules.length>0&&<ul className="work-task-list">{schedules.map((s:Record<string,unknown>)=><li key={String(s.id)}><strong>{String(s.name)}</strong><span>{String(s.report_key)} · {String(s.frequency)} · {String(s.channel)} · lần tới {date(String(s.next_run_at))}</span></li>)}</ul>}</section></>;
}
