'use client';
import {useState,type FormEvent} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';

async function post(action:string,body:unknown){const response=await fetch('/api/crm/security/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(String(result.error??'FAILED'));return result;}
const errorText=(code:string)=>({INVALID_CREDENTIALS:'Mật khẩu hiện tại không đúng.',MFA_CODE_INVALID:'Mã xác thực không đúng hoặc đã dùng.',RESET_TOKEN_INVALID:'Liên kết đặt lại đã hết hạn hoặc đã dùng.',MFA_NOT_CONFIGURED:'Máy chủ chưa có khóa mã hóa MFA.',EMAIL_NOT_CONFIGURED:'Kênh email Brevo chưa được cấu hình.'}[code]??'Chưa hoàn tất được thao tác. Kiểm tra dữ liệu rồi thử lại.');
export function MfaControls({enabled,recoveryCodesRemaining}:{enabled:boolean;recoveryCodesRemaining:number}){const router=useRouter(),[setup,setSetup]=useState<{secret:string;otpauthUrl:string}|null>(null),[codes,setCodes]=useState<string[]>([]),[message,setMessage]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{const result=await post(action,Object.fromEntries(f));if(action==='mfa-begin')setSetup(result);else if(action==='mfa-confirm'){setCodes(result.recoveryCodes);setMessage('MFA đã bật. Lưu các mã khôi phục trước khi đăng nhập lại.');}else{router.replace('/crm/login');router.refresh();}}catch(err){setError(errorText(err instanceof Error?err.message:''));}}
 return <section className="work-section"><h2>Xác thực hai bước</h2><p className="work-help">{enabled?`Đang bật · còn ${recoveryCodesRemaining} mã khôi phục chưa dùng.`:'Chưa bật. Dùng ứng dụng TOTP tương thích và lưu mã khôi phục ở nơi riêng.'}</p>{!enabled&&!setup&&<form className="work-form" onSubmit={e=>submit(e,'mfa-begin')}><label>Mật khẩu hiện tại<input name="password" type="password" required maxLength={72} autoComplete="current-password"/></label><button className="button button--primary">Bắt đầu thiết lập MFA</button></form>}{setup&&!codes.length&&<form className="work-form" onSubmit={e=>submit(e,'mfa-confirm')}><p><strong>Khóa thiết lập:</strong> <code>{setup.secret}</code></p><details className="work-disclosure"><summary>URI cho ứng dụng xác thực</summary><code className="security-uri">{setup.otpauthUrl}</code></details><label>Mã 6 số hiện tại<input name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}"/></label><label>Xác nhận mật khẩu<input name="password" type="password" required maxLength={72} autoComplete="current-password"/></label><button className="button button--primary">Xác nhận và bật MFA</button></form>}{codes.length>0&&<div className="crm-status-note" role="status"><p>{message}</p><ul>{codes.map(code=><li key={code}><code>{code}</code></li>)}</ul></div>}{enabled&&<details className="work-disclosure"><summary>Tắt MFA</summary><form className="work-form" onSubmit={e=>submit(e,'mfa-disable')}><label>Mật khẩu hiện tại<input name="password" type="password" required autoComplete="current-password"/></label><label>Mã xác thực hoặc khôi phục<input name="code" required autoComplete="one-time-code"/></label><button className="button button--secondary">Tắt và kết thúc mọi phiên</button></form></details>}{error&&<p className="work-error" role="alert">{error}</p>}</section>;}

export function ForgotPasswordForm(){const [message,setMessage]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');try{await post('forgot',{email:new FormData(e.currentTarget).get('email')});setMessage('Nếu email thuộc tài khoản đang hoạt động, Cohamy đã gửi liên kết có hiệu lực 30 phút.');}catch(err){setError(errorText(err instanceof Error?err.message:''));}}return <form className="auth-form" onSubmit={submit}><div className="field"><label htmlFor="reset-email">Email đăng nhập</label><input id="reset-email" name="email" type="email" required autoComplete="email"/></div><button className="button button--primary">Gửi liên kết đặt lại</button>{message&&<p className="form-status" role="status">{message}</p>}{error&&<p className="form-status form-status--error" role="alert">{error}</p>}</form>;}
export function ResetPasswordForm(){const query=useSearchParams(),router=useRouter(),[needsMfa,setNeedsMfa]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await post('reset',{token:query.get('token')??'',newPassword:f.get('newPassword'),...(needsMfa?{secondFactor:f.get('secondFactor')}: {})});router.replace('/crm/login?reset=1');}catch(err){const code=err instanceof Error?err.message:'';if(code==='MFA_REQUIRED'){setNeedsMfa(true);setError('Tài khoản này có MFA. Nhập mã để hoàn tất đặt lại.');}else setError(errorText(code));}}return <form className="auth-form" onSubmit={submit}><div className="field"><label htmlFor="new-password">Mật khẩu mới</label><input id="new-password" name="newPassword" type="password" minLength={12} maxLength={72} required autoComplete="new-password"/></div>{needsMfa&&<div className="field"><label htmlFor="reset-mfa">Mã MFA hoặc khôi phục</label><input id="reset-mfa" name="secondFactor" required autoComplete="one-time-code"/></div>}<button className="button button--primary">Đặt lại mật khẩu</button>{error&&<p className="form-status form-status--error" role="alert">{error}</p>}</form>;}
