import {PartnerMergeDetails} from './PartnerMergeDetails';
import {PartnerMergeForm} from './PartnerMergeForm';
import {mergeHistory,mergeTargets} from '@/lib/crm/partner-merge';
import {getOrganization} from '@/lib/crm/repository';
import {RecurrencePanel} from './CareAutomationPages';
import {mentionCandidates} from '@/lib/crm/care-automation';
import {CareReportPanel} from './RelationshipPages';
import {DraftNoteForm,RecordActions} from './WorkspaceControls';
import {getDraft} from '@/lib/crm/workspace';
import {DocumentsPanel} from './UpgradePages';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {assignments,canManageWork,getOrder,listActivities,listOrders,listTasks,staffOptions,duplicatePartners,entityAudit,getCatalogItem,workReport} from '@/lib/crm/work';
import {CrmError} from '@/lib/crm/permissions';
import {orderLabels,type EntityType,type OrderRecord,type TaskRecord} from '@/lib/crm/work-types';
import type {Principal} from '@/lib/crm/types';
import {AssignmentForm,OrderEditor,TaskForm,TaskToggle,CatalogForm} from './WorkForms';
import type {OrderState} from '@/lib/crm/work-types';
export const formatDate=(date:string)=>new Date(date).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'});
export const money=(value:string)=>BigInt(value).toLocaleString('vi-VN')+' đ';
export function WorkHeader({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <header className="work-page-heading"><div><h1>{title}</h1><p>{description}</p></div>{action}</header>;}
export function OrderTable({orders}:{orders:OrderRecord[]}){return orders.length?<><ul className="work-orders-mobile">{orders.map(o=><li key={o.id}><Link href={"/crm/orders/"+o.id}>{o.contact.fullName}</Link><div><span className={"work-status status-"+o.status}>{orderLabels[o.status]}</span><strong>{money(o.subtotal)}</strong></div><p>{o.code}</p><p>{formatDate(o.created_at)} · {o.assignee_name??"Chưa phân công"}</p></li>)}</ul><div className="crm-table-wrap work-orders-desktop" role="region" aria-label="Danh sách yêu cầu đặt hàng" tabIndex={0}><table className="data-table"><thead><tr><th>Yêu cầu / thời gian</th><th>Khách hàng</th><th>Trạng thái</th><th>Phụ trách</th><th className="work-number">Tổng hàng</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><Link className="table-primary" href={'/crm/orders/'+o.id}>{o.code}</Link><small>{formatDate(o.created_at)}</small></td><td><strong>{o.contact.fullName}</strong><small>{o.contact.phone}</small></td><td><span className={'work-status status-'+o.status}>{orderLabels[o.status]}</span></td><td>{o.assignee_name??<span className="work-unassigned">Chưa phân công</span>}</td><td className="work-number">{money(o.subtotal)}</td></tr>)}</tbody></table></div></>:<div className="work-empty"><h2>Chưa có yêu cầu phù hợp</h2><p>Yêu cầu từ website sẽ xuất hiện tại đây theo phạm vi được giao. Hãy thử bỏ bộ lọc nếu đang tìm một yêu cầu cũ.</p><Link href="/crm/orders">Bỏ bộ lọc</Link></div>;}
function ContactFacts({order}:{order:OrderRecord}){return <dl className="work-facts"><dt>Họ tên</dt><dd>{order.contact.fullName}</dd><dt>Điện thoại</dt><dd><a href={'tel:'+order.contact.phone.replace(/[^+0-9]/g,'')}>{order.contact.phone}</a></dd><dt>Email</dt><dd><a href={'mailto:'+order.contact.email}>{order.contact.email}</a></dd><dt>Giao đến</dt><dd>{[order.contact.address,order.contact.ward,order.contact.district,order.contact.city].filter(Boolean).join(', ')}</dd><dt>Lời nhắn</dt><dd className="work-prewrap">{order.contact.note||'Khách chưa để lại lời nhắn.'}</dd><dt>Thanh toán mong muốn</dt><dd>{{bank:'Chuyển khoản',cod:'Khi nhận hàng',momo:'MoMo'}[order.payment_requested]??order.payment_requested}</dd></dl>;}
export async function OrdersPage({user,id,query}:{user:Principal;id?:string;query:Record<string,string>}){
 if(id){const order=await getOrder(user,id).catch(e=>{if(e instanceof CrmError&&e.status===404)notFound();throw e;});const staff=await staffOptions(user);return <><Link className="work-back" href="/crm/orders">← Yêu cầu đặt hàng</Link><WorkHeader title={order.code} description={'Nhận lúc '+formatDate(order.created_at)} action={<span className={'work-status status-'+order.status}>{orderLabels[order.status]}</span>}/><div className="work-contact-strip"><span>{order.contact.fullName}</span><a className="button button--secondary" href={"tel:"+order.contact.phone.replace(/[^+0-9]/g,"")}>Gọi {order.contact.phone}</a><details className="work-disclosure work-contact-details"><summary>Địa chỉ, lời nhắn và thông tin khách</summary><ContactFacts order={order}/></details></div><div className="work-detail-grid"><div><section className="work-section"><h2>Sản phẩm yêu cầu</h2><ul className="work-lines-mobile">{order.lines.map(l=><li key={l.websiteId}><strong>{l.name}</strong><p>{l.quantity} × {money(l.unitPrice)}</p><span>{money(l.lineTotal)}</span></li>)}</ul><div className="crm-table-wrap work-lines-desktop" role="region" tabIndex={0} aria-label="Sản phẩm trong yêu cầu"><table className="data-table"><thead><tr><th>Sản phẩm</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{order.lines.map(l=><tr key={l.websiteId}><td>{l.name}</td><td>{l.quantity}</td><td>{money(l.unitPrice)}</td><td>{money(l.lineTotal)}</td></tr>)}</tbody></table></div><p className="work-total">Tổng tiền hàng <strong>{money(order.subtotal)}</strong></p><p className="work-help">Chưa thanh toán · Phí giao hàng cần xác nhận.</p></section><section className="work-section"><h2>Xử lý yêu cầu</h2>{canManageWork(user)?<OrderEditor order={order} staff={staff} manage={['ADMIN','MANAGER'].includes(user.role)}/>:<p>Bạn có quyền xem. Người phụ trách xử lý: {order.assignee_name??'chưa phân công'}.</p>}</section><RecordActions type="order" id={id}/><DocumentsPanel user={user} type="order" id={id}/><EntityWork user={user} type="order" id={id}/></div><aside className="work-detail-aside"><section className="work-section"><h2>Thông tin khách</h2><ContactFacts order={order}/></section><section className="work-section"><h2>Bước tiếp theo</h2><p>Liên hệ xác nhận sản phẩm, địa chỉ và phí giao. Ghi lại kết quả trao đổi, rồi cập nhật trạng thái yêu cầu.</p><p className="work-help">Giao hàng và ghi công nợ sẽ được mở sau khi chính sách vận hành được chốt.</p></section></aside></div></>;}
 const result=await listOrders(user,query);const href=(p:number)=>'/crm/orders?'+new URLSearchParams({...query,page:String(p)});return <><WorkHeader title="Yêu cầu đặt hàng" description="Tiếp nhận, phân công và theo dõi trao đổi với khách."/><nav className="work-tabs" aria-label="Lọc nhanh yêu cầu">{[['','Tất cả'],['PENDING_REVIEW','Mới nhận'],['IN_PROGRESS','Đang tư vấn'],['READY','Đã chốt']].map(([s,label])=><Link key={s} className={(query.status??'')===s?'active':''} href={'/crm/orders?'+new URLSearchParams({...query,status:s,page:'1'})}>{label}</Link>)}</nav><form className="work-filter" method="get"><label className="work-search">Tìm yêu cầu<input name="q" defaultValue={query.q} placeholder="Mã yêu cầu, tên, số điện thoại, email"/></label><label>Từ ngày<input type="date" name="from" defaultValue={query.from}/></label><label>Đến ngày<input type="date" name="to" defaultValue={query.to}/></label><label>Trạng thái<select name="status" defaultValue={query.status??''}><option value="">Tất cả</option>{Object.entries(orderLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Phân công<select name="mine" defaultValue={query.mine??''}><option value="">Trong phạm vi quyền</option><option value="true">Giao cho tôi</option></select></label><button className="button button--primary">Lọc yêu cầu</button><Link className="work-reset" href="/crm/orders">Xóa lọc</Link></form><section className="work-section work-section--table"><div className="work-section-title"><h2>{result.total} yêu cầu</h2><span>Giờ Việt Nam · Tiền hàng chưa gồm phí giao</span></div><OrderTable orders={result.items}/><footer className="table-footer"><span>Trang {result.page} / {Math.max(1,Math.ceil(result.total/20))}</span><nav aria-label="Phân trang yêu cầu">{result.page>1&&<Link href={href(result.page-1)}>Trang trước</Link>}{result.page*20<result.total&&<Link href={href(result.page+1)}>Trang sau</Link>}</nav></footer></section></>;
}
export function TaskList({tasks}:{tasks:TaskRecord[]}){return tasks.length?<ul className="work-task-list">{tasks.map(t=><li key={t.id}><div><Link href={t.entity_type==='order'?'/crm/orders/'+t.entity_id:'/crm/partners/'+t.entity_id}>{t.title}</Link><p>{t.entity_label} · {t.assignee_name}</p><span className={t.done_at?'work-success':'work-help'}>{t.done_at?'Đã hoàn thành':'Hẹn '+formatDate(t.due_at)}</span></div><TaskToggle id={t.id} version={t.version} done={Boolean(t.done_at)}/></li>)}</ul>:<div className="work-empty"><h2>Không có việc trong danh sách này</h2><p>Tạo việc từ chi tiết khách hàng hoặc yêu cầu đặt hàng để luôn giữ đúng ngữ cảnh.</p><Link href="/crm/orders">Mở yêu cầu đặt hàng</Link></div>;}
export async function TasksPage({user,query}:{user:Principal;query:Record<string,string>}){const tasks=await listTasks(user,query);return <><WorkHeader title="Việc cần làm" description="Theo dõi lịch hẹn và các bước chăm sóc tiếp theo. Theo giờ Việt Nam; mỗi trang tối đa 200 việc theo hạn hoàn thành."/><nav className="work-tabs" aria-label="Lọc công việc"><Link className={!query.done&&!query.overdue?'active':''} href="/crm/tasks">Chưa xong</Link><Link className={query.overdue?'active':''} href="/crm/tasks?overdue=true">Quá hạn</Link><Link className={query.done==='true'?'active':''} href="/crm/tasks?done=true">Đã hoàn thành</Link><Link className={query.today?'active':''} href="/crm/tasks?today=true">Còn hạn hôm nay</Link></nav><section className="work-section"><TaskList tasks={tasks}/><nav className="upgrade-actions" aria-label="Phân trang công việc">{Number(query.page)>1&&<Link href={'?'+new URLSearchParams({...query,page:String(Number(query.page)-1)})}>Trang trước</Link>}{tasks.length===200&&<Link href={'?'+new URLSearchParams({...query,page:String((Number(query.page)||1)+1)})}>Trang sau</Link>}</nav></section></>;}
export async function EntityWork({user,type,id}:{user:Principal;type:EntityType;id:string}){if(user.area!=='crm')return null;const activities=await listActivities(user,type,id);const staff=await staffOptions(user);const edit=canManageWork(user);const tasks=edit?await listTasks(user,{entityId:id}):[];return <><section className="work-section"><h2>Lịch sử chăm sóc</h2>{edit&&<DraftNoteForm type={type} id={id} initial={await getDraft(user,'note-'+id)} mentions={await mentionCandidates(user,type,id)}/>}<ol className="work-timeline">{activities.length?activities.map(a=><li key={a.id}><strong>{a.actor_name}</strong><time>{formatDate(a.created_at)}</time><p>{a.body}</p></li>):<li><p>Chưa có ghi chú. Ghi lại kết quả liên hệ đầu tiên để cả nhóm theo dõi.</p></li>}</ol></section>{edit&&<section className="work-section"><h2>Việc tiếp theo</h2>{tasks.length?<TaskList tasks={tasks}/>:<p className="work-help">Chưa có việc tiếp theo cho hồ sơ này. Thêm việc và hạn hoàn thành ngay bên dưới.</p>}<details className="work-disclosure"><summary>Tạo việc và đặt hạn</summary><TaskForm type={type} id={id} staff={staff} self={user.membershipId}/></details></section>}{edit&&<RecurrencePanel user={user} type={type} id={id}/>} {type==='partner'&&['ADMIN','MANAGER'].includes(user.role)&&<section className="work-section"><h2>Phân công chăm sóc</h2><AssignmentForm type="partner" id={id} staff={staff} selected={await assignments(user,'partner',id)}/></section>}<AuditHistory user={user} type={type} id={id}/></>;}
export async function WarehouseAssignment({user,id}:{user:Principal;id:string}){if(!['ADMIN','MANAGER'].includes(user.role))return null;return <details className="work-disclosure"><summary>Phân công thủ kho</summary><AssignmentForm type="warehouse" id={id} staff={await staffOptions(user)} selected={await assignments(user,'warehouse',id)}/></details>;}
export async function PartnerDuplicates({user,id}:{user:Principal;id:string}){const duplicates=await duplicatePartners(user,id);return duplicates.length?<div className="crm-status-note"><strong>Có hồ sơ trùng thông tin liên hệ</strong><p>Kiểm tra trước khi chăm sóc; hệ thống chưa tự gộp hồ sơ.</p>{duplicates.map(d=><Link style={{display:'block'}} key={d.id} href={'/crm/'+(d.kind==='DEALER'?'dealers':'customers')+'/'+d.id}>{d.name}</Link>)}</div>:null;}
export async function AuditHistory({user,type,id}:{user:Principal;type:EntityType;id:string}){const rows=await entityAudit(user,type,id);const labels:Record<string,string>={'order.updated':'Cập nhật yêu cầu','partner.created':'Tạo hồ sơ','partner.updated':'Sửa hồ sơ','assignment.updated':'Đổi phân công','activity.created':'Thêm ghi chú','task.created':'Tạo việc cần làm','task.completed':'Hoàn thành việc','task.reopened':'Mở lại việc','website.order-received':'Nhận yêu cầu website'};return <details className="work-disclosure work-section"><summary>Nhật ký thay đổi · 50 sự kiện gần nhất</summary><ol className="work-timeline">{rows.map(r=><li key={r.id}><strong>{labels[r.action]??r.action}</strong><time>{formatDate(r.created_at)}</time><p>{r.actor_name??'Hệ thống'}</p></li>)}</ol></details>;}
export async function CatalogDetail({user,id}:{user:Principal;id:string}){const p=await getCatalogItem(user,id);return <><Link className="work-back" href={'/'+user.area+'/goods'}>← Danh mục hàng hóa</Link><WorkHeader title={p.name} description={'SKU '+p.sku+' · '+p.weight_label}/><section className="work-section"><h2>Thông tin thương mại</h2>{['ADMIN','MANAGER'].includes(user.role)?<CatalogForm product={p}/>:<dl className="work-facts"><dt>Đơn vị cơ sở</dt><dd>{p.stock_unit||'Chưa khai báo'}</dd><dt>Quy đổi thùng</dt><dd>{p.units_per_case??'Chưa khai báo'}</dd></dl>}</section></>;}
export async function ReportsPage({user}:{user:Principal}){const rows=await workReport(user);return <><WorkHeader title="Báo cáo tiếp nhận" description="Tổng hợp toàn bộ yêu cầu website theo trạng thái hiện tại trong phạm vi quyền."/><CareReportPanel user={user}/><section className="work-section"><h2>Tình hình xử lý yêu cầu</h2><p className="work-help">Tổng tiền hàng là giá trị yêu cầu, chưa phải doanh thu hoặc công nợ. Báo cáo tồn kho và tài chính chưa mở.</p><div className="crm-table-wrap" role="region" tabIndex={0} aria-label="Báo cáo trạng thái yêu cầu"><table className="data-table"><thead><tr><th>Trạng thái</th><th>Số yêu cầu</th><th>Tổng tiền hàng yêu cầu</th></tr></thead><tbody>{rows.map(r=><tr key={r.status}><td><Link href={'/crm/orders?status='+r.status}>{orderLabels[r.status as OrderState]}</Link></td><td>{r.requests}</td><td>{money(r.subtotal)}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="crm-status-note">Chưa nhận yêu cầu website nào.</p>}</section></>;}

export async function PartnerMergePanel({user,id}:{user:Principal;id:string}) {const record=await getOrganization(user,id),history=await mergeHistory(user,id);const managed=user.area==='crm'&&['ADMIN','MANAGER'].includes(user.role);return <>{managed&&!record.merged_into_id&&record.active&&<PartnerMergeForm source={record} targets={await mergeTargets(user,record)}/>}<section className="work-section"><h2>Lịch sử gộp hồ sơ</h2>{history.length?<ul className="work-timeline">{history.map(h=><li key={h.id}><strong>{h.actor_name}</strong><time>{new Date(h.created_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</time><p>{h.reason}</p>{h.manifest&&h.choices&&<details className="work-disclosure"><summary>Xem lựa chọn và tác động đã lưu</summary><PartnerMergeDetails manifest={h.manifest} choices={h.choices} historical/></details>}<Link href={'/crm/'+(record.kind==='DEALER'?'dealers':record.kind==='SUPPLIER'?'suppliers':'customers')+'/'+(h.target_id===id?h.source_id:h.target_id)}>Xem hồ sơ {h.target_id===id?'nguồn lịch sử':'giữ lại'}</Link></li>)}</ul>:<p>Chưa gộp hồ sơ.</p>}</section></>;}
