'use client';
import {useRef,useState,type FormEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import {orderLabels,orderStates,type EntityType,type OrderRecord,type StaffOption} from '@/lib/crm/work-types';
import {roles,roleLabels,type CatalogProduct} from '@/lib/crm/types';
const messages:Record<string,string>={VERSION_CONFLICT:'Hồ sơ vừa được cập nhật. Tải lại trang để xem bản mới trước khi lưu.',REASON_REQUIRED:'Nhập lý do thay đổi trạng thái.',INVALID_TRANSITION:'Chuyển trạng thái chưa phù hợp. Vui lòng kiểm tra lại.',INVALID_ASSIGNEE:'Người phụ trách chưa có quyền phù hợp.',NOT_FOUND:'Hồ sơ hoặc người được giao không thuộc phạm vi truy cập.',INVALID_FIELDS:'Kiểm tra lại thông tin bắt buộc và độ dài dữ liệu.',FORBIDDEN:'Bạn chưa có quyền thực hiện thao tác này.',INVALID_CREDENTIALS:'Mật khẩu hiện tại không đúng.',ROLE_ORGANIZATION_MISMATCH:'Vai trò không phù hợp với tổ chức của tài khoản.',CANNOT_CHANGE_SELF:'Dùng hồ sơ cá nhân để quản lý tài khoản của bạn.'};
export function WorkForm({action,children,payload,success='Đã lưu thay đổi.',label='Lưu thay đổi',reauth=false}:{action:string;children?:ReactNode;payload:(f:FormData)=>unknown;success?:string;label?:string;reauth?:boolean}) {
 const router=useRouter(),busy=useRef(false);const[pending,setPending]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setMessage('');setError('');const form=e.currentTarget;
 try {const response=await fetch('/api/crm/work/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(new FormData(form)))});const result=await response.json();if(!response.ok){if(response.status===401){router.refresh();return;}setError(messages[result.error]??'Chưa lưu được. Kiểm tra kết nối rồi thử lại.');return;}if(reauth){router.replace('/crm/login');router.refresh();return;}setMessage(success);if(action==='activity'||action==='task')form.reset();router.refresh();}catch{setError('Không kết nối được. Nội dung vẫn giữ để bạn thử lại.');}finally{busy.current=false;setPending(false);}}
 return <form className="work-form" onSubmit={submit}>{children}<div className="work-form-footer"><button className="button button--primary" disabled={pending}>{pending?'Đang lưu…':label}</button>{message&&<p className="work-success" role="status">{message}</p>}</div>{error&&<p className="work-error" role="alert">{error}</p>}</form>;
}
export function OrderEditor({order,staff,manage}:{order:OrderRecord;staff:StaffOption[];manage:boolean}){return <WorkForm action="order" payload={f=>({id:order.id,data:{version:order.version,status:f.get('status'),reason:f.get('reason'),...(manage?{assignedTo:f.get('assignedTo')||null}:{})}})}><div className="work-fields"><label>Trạng thái<select name="status" defaultValue={order.status}>{orderStates.map(s=><option key={s} value={s}>{orderLabels[s]}</option>)}</select></label>{manage&&<label>Người phụ trách<select name="assignedTo" defaultValue={order.assigned_to??''}><option value="">Chưa phân công</option>{staff.filter(s=>['ADMIN','MANAGER','SALES'].includes(s.role)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label className="work-wide">Ghi chú xử lý / lý do<textarea name="reason" maxLength={1000} rows={3} placeholder="Kết quả trao đổi với khách, lý do hủy hoặc mở lại…"/></label></div><p className="work-help">Đã chốt yêu cầu nghĩa là đã thống nhất với khách. Xuất kho và ghi công nợ chưa được mở.</p></WorkForm>;}
export function ActivityForm({type,id}:{type:EntityType;id:string}){return <WorkForm action="activity" label="Thêm ghi chú" success="Đã thêm vào lịch sử chăm sóc." payload={f=>({entityType:type,entityId:id,body:f.get('body')})}><label>Nội dung trao đổi<textarea name="body" required maxLength={4000} rows={3} placeholder="Khách quan tâm gì? Đã trao đổi và cần tiếp tục việc gì?"/></label></WorkForm>;}
export function TaskForm({type,id,staff,self}:{type:EntityType;id:string;staff:StaffOption[];self:string}){return <WorkForm action="task" label="Tạo việc cần làm" payload={f=>({entityType:type,entityId:id,title:f.get('title'),assigneeId:f.get('assigneeId'),dueAt:new Date(String(f.get('dueAt'))).toISOString()})}><label>Việc cần làm<input name="title" required minLength={2} maxLength={240} placeholder="Ví dụ: gọi lại xác nhận số lượng"/></label><div className="work-fields"><label>Hẹn hoàn thành<input name="dueAt" type="datetime-local" required/></label><label>Giao cho<select name="assigneeId" defaultValue={self}>{staff.filter(s=>['ADMIN','MANAGER','SALES'].includes(s.role)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><p className="work-help">Người được giao cần có quyền xem hồ sơ này. Thời gian theo thiết bị của bạn.</p></WorkForm>;}
export function TaskToggle({id,version,done}:{id:string;version:number;done:boolean}){return <WorkForm action="task-update" label={done?'Mở lại':'Hoàn thành'} payload={()=>({id,data:{version,done:!done}})}/>;}
export function AssignmentForm({type,id,staff,selected}:{type:'partner'|'warehouse';id:string;staff:StaffOption[];selected:string[]}){const options=staff.filter(s=>s.role===(type==='partner'?'SALES':'WAREHOUSE'));return <WorkForm action="assignment" label="Lưu phân công" payload={f=>({type,id,membershipIds:f.getAll('members')})}><fieldset><legend>{type==='partner'?'Sales phụ trách hồ sơ':'Nhân viên được xem kho'}</legend>{options.length?options.map(s=><label className="work-check" key={s.id}><input type="checkbox" name="members" value={s.id} defaultChecked={selected.includes(s.id)}/>{s.name}</label>):<p>Chưa có tài khoản đúng vai trò. Cấp tài khoản trước khi phân công.</p>}</fieldset></WorkForm>;}
export function PasswordForm(){return <WorkForm action="password" label="Đổi mật khẩu và đăng nhập lại" reauth payload={f=>({currentPassword:f.get('currentPassword'),newPassword:f.get('newPassword')})}><label>Mật khẩu hiện tại<input type="password" name="currentPassword" required autoComplete="current-password" maxLength={72}/></label><label>Mật khẩu mới<input type="password" name="newPassword" required minLength={12} maxLength={72} autoComplete="new-password"/></label><p className="work-help">Tối thiểu 12 ký tự. Sau khi đổi, các phiên đăng nhập của bạn sẽ kết thúc.</p></WorkForm>;}
export function CatalogForm({product}:{product:CatalogProduct}){return <WorkForm action="catalog" label="Lưu thông tin hàng hóa" payload={f=>({id:product.id,data:{version:product.version,sku:f.get('sku'),name:f.get('name'),stockUnit:f.get('stockUnit'),unitsPerCase:f.get('unitsPerCase')?Number(f.get('unitsPerCase')):null,active:f.get('active')==='on'}})}><div className="work-fields"><label>SKU chính thức<input name="sku" required pattern="([A-Za-z0-9_]|-)+" maxLength={80} defaultValue={product.sku}/></label><label>Tên trong CRM<input name="name" required minLength={2} maxLength={200} defaultValue={product.name}/></label><label>Đơn vị cơ sở<input name="stockUnit" maxLength={40} placeholder="Gói, hộp…" defaultValue={product.stock_unit}/></label><label>Số đơn vị cơ sở / thùng<input name="unitsPerCase" type="number" min={1} max={100000} step={1} defaultValue={product.units_per_case??''}/></label></div><label className="work-check"><input type="checkbox" name="active" defaultChecked={product.active}/>Hiển thị trong danh mục đại lý</label><p className="work-help">Đơn vị và quy đổi do người quản lý nhập theo thực tế. Tên, giá và hình trên website hiện được quản lý riêng; thay đổi này chưa tác động website hoặc tạo tồn kho.</p></WorkForm>;}
export function AccountTools({id,role,self}:{id:string;role:string;self:boolean}){if(self)return <p>Đổi mật khẩu của bạn tại Hồ sơ cá nhân.</p>;return <div className="work-account-tools"><WorkForm action="account" label="Thu hồi mọi phiên" payload={()=>({id,data:{action:'revoke'}})}/><WorkForm action="account" label="Đổi vai trò" payload={f=>({id,data:{action:'role',role:f.get('role')}})}><label>Vai trò<select name="role" defaultValue={role}>{roles.filter(r=>r.startsWith('DEALER_')===role.startsWith('DEALER_')).map(r=><option value={r} key={r}>{roleLabels[r]}</option>)}</select></label><p className="work-help">Đổi vai trò thu hồi phiên và xóa phân công khách/kho cũ. Phân công lại sau khi đổi.</p></WorkForm><WorkForm action="account" label="Đặt lại mật khẩu" payload={f=>({id,data:{action:'password',password:f.get('password')}})}><label>Mật khẩu mới (12–72 ký tự)<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label></WorkForm></div>;}
